### ISSUE TITLE
Using gitgutter_realtime results in error

### ISSUE THREAD

**Issue by frewsxcv** [airblade/vim-gitgutter#101]
Just upgraded to the latest gitgutter. Noticed I was getting this error while in gvim everytime I moved (though not in vim):

```
Error detected while processing function GitGutter..<SNR>16_run_diff:
line   13:
E484: Can't open file /tmp/vajLswy/9
Press ENTER or type command to continue
```

I did a git-bisect and traced the issue back to [this commit](https://github.com/airblade/vim-gitgutter/commit/6e1e1dfe094da7e54caa1d5b7825ef8fe264bed4). Interestingly, it's trying to open `9`, but only `8` exists in that `tmp` directory. This is always the case. The (filename - 1) exists in the tmp directory, but not the filename itself. As I expected, if I turn off realtime, the plugin works flawlessly

[Here's](https://github.com/frewsxcv/config/blob/master/config/vimrc) my vimrc. I'm running Ubuntu 13.04 with Fish shell

**Comment by airblade** [comment]
@frewsxcv vim-gitgutter now supports the fish shell (0ca15c8).
