### ISSUE TITLE
<SNR>116_run_diff error

### ISSUE THREAD

**Issue by sunaku** [airblade/vim-gitgutter#106]
Hello, I get the following error every few seconds (even when not doing anything):

```
Error detected while processing function GitGutter..<SNR>116_run_diff:
line   13:
E484: Can't open file /tmp/vqLwd5h/18
Press ENTER or type command to continue
```

This only started happening after upgrading this plugin in the last few days.

Thanks for your consideration. :sweat_smile:

**Comment by geraldus** [comment]
> If I put set shell=/bin/bash in my vimrc the error goes away
Helped for me as well! Thank you! BTW I've switched to fish right now.
@airblade can you support fish shell as well? (:

**Comment by airblade** [comment]
@geraldus See #228.

**Comment by hlecuanda** [comment]
Wow! I didn't realise this issue refused to die after a year and change... in fact, i was surprised to see my own comment way back at the beginning of the thread... i even thought.. "hey that guy's avatar looks just like my own.... and on top of it; writes about the issue like he's full of himself... hey, wait.... vim temp files, yeah, i remember having something to do with them back in the day.... haha

sorry about the babble... i was just amazed by my sudden perception of the passage of time...

**Comment by airblade** [comment]
@geraldus vim-gitgutter now supports the fish shell (0ca15c8).
