### ISSUE TITLE
Jumping between changes with 2 open windows of the same file

### ISSUE THREAD

**Issue by golergka** [airblade/vim-gitgutter#163]
1. open a file that is under git version control
2. `:vsplit` and jump to the new window
3. switch to the new window
4. change two lines not adjacent to each other
5. `:wa`
6. press `[c`

Expected: jump to the changed hunk in the current window
Actual: jump to the changed hunk in the first window

**Comment by zeroepoch** [comment]
I'm observing this problem as well with vim-gitgutter 339f8ba0 from May 8th 2015.  In my case I have a nerd tree split open on the left and two different files open in the right two splits.  When I use [c or ]c to jump between changes it follows the lines of the last file I opened (or did :e).  It happens on vim 7.2 from RHEL 6.5 but not on vim 7.4 from F20.

**Comment by airblade** [comment]
I'll be able to look at this once I'm back from holiday.

Are you saying it worked as expected before the commit you mentioned, or is that just the one you happened to observe the problem with?

**Comment by zeroepoch** [comment]
I came across the problem with the hash mentioned just today and noticed
someone else already reported I think the same problem. I'm not sure if it
worked before or not but it does appear to be working in newer vim
releases. I'm not sure if it makes sense to fix it for older releases I
more just wanted to confirm the issue.

**Comment by airblade** [comment]
@zeroepoch Thanks for the comments.

I'll only look into this further if the problem occurs on Vim 7.4+.
