### ISSUE TITLE
Signs very hard to read with solarized and vim-gitgutter

### ISSUE THREAD

**Issue by andrewferrier** [airblade/vim-gitgutter#164]
I use both vim-solarized (https://github.com/altercation/vim-colors-solarized) and vim-gitgutter together. It appears that a change was made between commits 0ca3f7e and 7908def of vim-gitgutter that is causing the signs in the left-hand column to be much harder to read. Previously they showed up on dark grey, but they now show up on top of a light grey like the rest of the margin. I don't think vim-colors-solarized has changed in some time, although I don't know if this is incorrect behavior on the part of the colorscheme or vim-gitgutter. Please let me know if there's any info I can add to help diagnosis.

**Comment by positron** [comment]
I couldn't get any of the above to work. I went into solarized directly (`~/.vim/bundle/vim-colors-solarized/colors/solarized.vim`) and changed the `SignColumn` from

    exe "hi! SignColumn"     .s:fmt_none   .s:fg_base0

to

    exe "hi! SignColumn"     .s:fmt_none   .s:fg_base01 .s:bg_base02

which is the same as the number column.

**Comment by bguest** [comment]
Don't know if will help anyone, but I'm using iterm2... the key for me was
```
set background=dark
highlight clear SignColumn
```
In that order... didn't need anything else.

**Comment by sagarjauhari** [comment]
This is a prevailing proboem with Solarized. Can you re-open this issue please?

**Comment by airblade** [comment]
@sagarjauhari My opinion is that the plugin is correctly using the sign column's background colour as the background colour for its signs.

Solarized-dark sets a grey background which has a low contrast with this plugin's default foreground colours for its signs.  vim-gitgutter's default colours are, well, just defaults.  If you don't like the visual combination of your preferred colour scheme and this plugin's colours, you have two options: modify the colour scheme or configure this plugin's colours.

I don't see any point in adjusting this plugin's default colours to match one colour scheme: inevitably the new defaults would look bad in another.

As it happens I use solarized-dark too.  My vimrc has the same snippet as @bguest:

```viml
colorscheme solarized
set background=dark
highlight clear SignColumn
```

I think Solarized has chosen a poor colour for the sign column, and that the real solution is for Solarized to change it.

**Comment by sagarjauhari** [comment]
@airblade makes sense to me. I have added to my .vimrc file too.

![screen shot 2015-02-09 at 9 13 24 pm](https://cloud.githubusercontent.com/assets/1958807/6109414/a8e5a076-b0a0-11e4-9124-74d0e969e57a.png)

And, thanks for writing this plugin!

**Comment by ahaarnos** [comment]
I used @andrewwutw's solution above in my `~/.vimrc.after` (I'm using Janus) to fix my issue (sign column looked correct, but the signs themselves still has an odd grey background).

```
highlight clear SignColumn
call gitgutter#highlight#define_highlights()
```

I should note, I am not using solarized as my colorscheme.

**Comment by airblade** [comment]
FYI as of 07d7c9d vim-gitgutter overrides the sign column's highlight by default to make it easier on the eye.  You no longer need `highlight clear SignColumn` in your vimrc.

**Comment by andrewwutw** [comment]
@airblade Good, now vim-gitgutter + solarized colorscheme without `highlight clear SignColumn` work fine. :smile:

**Comment by sagarjauhari** [comment]
:heart:

**Comment by atomaka** [comment]
Thanks!

**Comment by vigilancer** [comment]
gvim 8.0.1207, macos, solarized theme
Similar thing was happening to me.
I had augroup to reload vimrc on changes. Simple ':source' did break some stuff.
One of them was sign column colors. It became white as in original question. `highlight clear SignColumn` only reverted it's background, but signs was staying white (both `vim-signature` and `vim-gitgutter`).
As already mentioned above one need to press some buttons inside of plugins. For `gitgutter` it's `#define_highlights`.

```
augroup myvimrc
    au!
    au BufWritePost .vimrc so $MYVIMRC
    " fixes sign column colors (at least for solarized theme)
    au BufWritePost .vimrc hi clear SignColumn
    " fixes sign colors for gitgutter
    au BufWritePost .vimrc call gitgutter#highlight#define_highlights()
augroup END
```
