### ISSUE TITLE
Issue accessing tmp when shell is set to fish

### ISSUE THREAD

**Issue by zovt** [airblade/vim-gitgutter#195]
Hi, I'm using the fish shell on my linux installation. However, having this set as my default breaks the realtime mode. The is the same as the ones created many times before such as [this](https://github.com/airblade/vim-gitgutter/issues/101). Is there any known fix aside from changing the default shell inside of my .vimrc? 

EDIT: Apparently changing the shell isn't as big of a deal as I thought. I'll still leave this open though as it should be noted that fish breaks gitgutter.

**Comment by airblade** [comment]
vim-gitgutter now supports the fish shell (0ca15c8).
