### ISSUE TITLE
Errors when trying to open a saved session

### ISSUE THREAD

**Issue by ahmedelgabri** [airblade/vim-gitgutter#196]
Whenever I try to open a saved session I get these errors, this only happens with sessions.
![screen shot 2014-09-18 at 1 24 30 pm](https://cloud.githubusercontent.com/assets/63876/4317709/3c1d95a8-3f16-11e4-88b7-2ec3100e1277.png)
Any idea how to fix this? I don't have an customization in my `.vimrc` for gitgutter, just downloaded it & using the default settings.

**Comment by airblade** [comment]
Do you use Pathogen to load your plugins?

**Comment by ahmedelgabri** [comment]
I was using Vundle but I changed to vim-plug now.

**Comment by airblade** [comment]
OK, thanks.  I was asking because I just noticed Vim's default behaviour when restoring a session [prevents Pathogen from loading all plugins](https://github.com/tpope/vim-pathogen/commit/f45c82a760bba467e18de18a1e20a33569a05f05), causing the error you saw.
