### ISSUE TITLE
Not working with vim in fish(oh-my-fish)

### ISSUE THREAD

**Issue by Fity** [airblade/vim-gitgutter#213]
OS: Mac OSX 10.10.1
Terminator: iTerm2
VIM: 7.4.488
These are the error messages:

> ".vimrc" 261L, 7922C
> Error detected while processing function gitgutter#process_buffer..gitgutter#diff#run_diff..gitgutter#utility#system:
> line   10:
> E484: Can't open file /var/folders/wz/wrdxjdzj27762sj614ky9jbr0000gn/T/vcBMlWT/1
> '''

**Comment by airblade** [comment]
vim-gitgutter now supports the fish shell (0ca15c8).
