### ISSUE TITLE
Non-posix terminal and gitgutter causes crash

### ISSUE THREAD

**Issue by tusj** [airblade/vim-gitgutter#221]
I am using a non-posix compliant terminal, called fish as default terminal. In order for vim to operate nicely, I have this little snippet to help:
```
		if &shell =~# 'fish$'
			set shell=bash\ --login
		endif
```
I did have an issue with that where the environment was reset, so I changed the switch from ```--login``` to ```-i``` to make it interactive, which seemed to fix it. However, that made vim crash whenever I tried to do anything, as well as the shell vim was started from. I found out the root of the problem to be a system call where gitgutter is opening a temporary file.

It is not a common use case for a non-posix terminal as the default terminal. However, I thought I should mention it as a potential problem, as the effect was that both vim and the shell crashed -- not especially pretty.

I will provide more info if wanted.

**Comment by airblade** [comment]
Thanks for reporting this.

As far as I know vim itself isn't fish-compatible – it only works with POSIX shells – so your snippet setting the `shell` option to bash is a good idea.  However one would expect an interactive shell to hang vim every time it tries to make an external system call.  Things should work if you use `set shell=bash`.

**Comment by airblade** [comment]
vim-gitgutter now supports the fish shell (0ca15c8).
