### ISSUE TITLE
Possible to write file without triggering a refresh?

### ISSUE THREAD

**Issue by davidpdrsn** [airblade/vim-gitgutter#224]
When I'm running tests I automatically write the file first. This means I have to wait the (tiny) amount of it takes for the plugin to refresh the signs. I'm wondering if there there is some way to save without refreshing.

I've tried disabling before the write and then enabling afterwards, but then I never get to look at my test output because it just immediately jumps back into Vim once the shell command finishes.

**Comment by airblade** [comment]
I presume you're working in terminal vim and running tests with some kind of mapping which saves-and-runs-the-tests (maybe [this](https://github.com/davidpdrsn/dotfiles/blob/ae6cdd00502afa5550c77630fe2d983fef4e5650/vim/vimrc.symlink#L446))?

You could cancel vim-gitgutter's `BufWritePost` autocommand in your vimrc (or perhaps it would need to go in `after/` to be executed after the plugin is loaded).  Then you could just let the `CursorHold(I)` autocommands take care of refreshing the signs.

Ideally you'd be able to chain a refresh onto your test runner mapping but I don't know how to do that while keeping the test output until you're ready.  It may be possible but I've never tried to do that before and haven't looked into it ;)

**Comment by davidpdrsn** [comment]
Alright thanks for the inspiration! I'll look into it.
