### ISSUE TITLE
Make GitGutterRevertHunk mapping repeatable

### ISSUE THREAD

**Issue by wellle** [airblade/vim-gitgutter#225]
Sometimes I move through the hunks with `]c` and `[c` (`GitGutter{Next,Prev}Hunk`) and revert a hunk with `\hr` (`GitGutterRevertHunk`). Moving through different hunks I wish I could repeat the revert with `.`. So I would type
```
]c\hr]c.]c.]c.
```
to revert four hunks interactively. Currently I have to type
```
]c\hr]c\hr]c\hr]c\hr
```
instead.

Could you try to make reverting repeatable? Possibly by using [vim-repeat](https://github.com/tpope/vim-repeat). It would probably also make sense to make `GitGutterStageHunk` repeatable, but I personally don't use it.

Thanks!

**Comment by airblade** [comment]
Thanks for the good idea.  It's in 6b8e908.

**Comment by wellle** [comment]
Works like a charm, thanks!
