### ISSUE TITLE
GitGutter not showing previous changes to file in OSX 10.10

### ISSUE THREAD

**Issue by mr6volt** [airblade/vim-gitgutter#227]
I have gitgutter working perfectly on Ubuntu 10.04. 

However, for OSX 10.10, it doesn't show the gutter, and doesn't show any of the committed changes that have been previously made to a file.

If i make a change to the file and save it, the gutter will show up, and everything behaves as if it's the very first change that has ever been made to a file. (I verified that the file has previous commits by looking at my commit history elsewhere)

If i close vi, and reopen the file, gitgutter doesn't see that anything has ever changed.

Here is GitGutterDebug output:
-----------------------------------------
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 23 2015 20:29:56)
MacOS X (unix) version
Included patches: 1-488

git version 2.2.2

updatetime=1
shell=/bin/zsh
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=

-----------------------------------------

![screen shot 2015-01-24 at 5 10 44 pm](https://cloud.githubusercontent.com/assets/2038189/5889435/f774a0aa-a3eb-11e4-8be6-703ce963db0f.png)

I am using ZSH with oh-my-zsh.

Current OSX version is 10.10.1
Git version 2.2.2
Vim 7.4.488
zsh 5.0.5

my very messy vimrc file:
-----------------------------------------
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
Plugin 'user/L9', {'name': 'newL9'}
"
Plugin 'Chiel92/vim-autoformat'
Plugin 'scrooloose/nerdcommenter'
Plugin 'Valloric/YouCompleteMe'
Plugin 'bling/vim-airline'
Plugin 'kien/ctrlp.vim'
Plugin 'mbbill/undotree'
Plugin 'majutsushi/tagbar'
Plugin 'airblade/vim-gitgutter'
Plugin 'bling/vim-bufferline'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
set omnifunc=syntaxcomplete#Complete
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
set laststatus=2
let g:airline_theme = 'bubblegum'
" let g:airline#extensions#tabline#enabled = 1
nmap U :UndotreeToggle<CR>
set undodir=~/.undodir/
set undofile
set undolevels=10000
set backspace=indent,eol,start
colorscheme slate
set number
set mouse=a
set clipboard=unnamed
" set term=builtin_ansi
syntax on
" filetype plugin indent on
Bundle 'wakatime/vim-wakatime'
let g:ycm_semantic_triggers = {
  \ 'c' : ['->', '.'],
  \ 'objc' : ['->', '.'],
  \ 'ocaml' : ['.', '#'],
  \ 'cpp,objcpp' : ['->', '.', '::'],
  \ 'perl' : ['->'],
  \ 'php' : ['->', '::'],
  \ 'cs,css,haskell,java,javascript,d,vim,ruby' : ['.'],
  \ 'python,perl6,scala,vb,elixir,go' : ['.'],
  \ 'lua' : ['.', ':'],
  \ 'erlang' : [':'],
  \ }
iabbrev </ </<C-X><C-O>
highlight clear SignColumn
highlight GitGutterAdd ctermfg=green
highlight GitGutterChange ctermfg=yellow
highlight GitGutterDelete ctermfg=red
highlight GitGutterChangeDelete ctermfg=yellow

-----------------------------------------

Thanks for any help you can provide!

**Comment by airblade** [comment]
Thanks for all the detail.  Please could you clarify this?

> [it] doesn't show any of the committed changes that have been previously made to a file.

The plugin won't show you previously committed changes; it's a wrapper around `git-diff` so it'll show you what `git-diff` shows you, i.e. the difference between the working tree and the index.

I notice your `updatetime` is `1`ms.  While in theory that should be fine, in practice I'm not sure vim can keep up with that.  Please could you try setting it to `100`ms or even `500`ms?  (I have mine set to `750`ms).

You're not setting `updatetime` in your vimrc so one of your plugins must be doing that.  `:verbose set updatetime` will tell you where it's being set.

**Comment by airblade** [comment]
Any updates?

**Comment by mr6volt** [comment]
Sorry, yeah. It's working exactly the way you said.

I honestly thought it was examining the git repo and showing a diff of previous commits or something... which would be EXTREMELY useful if i need to reference previous code.

Thanks!

**Comment by airblade** [comment]
You could try playing with `g:gitgutter_diff_args` to diff against different revisions.  Perhaps you could set up a little VimL function which lets you specify how many commits back you want to go (`n`) and sets the base of your diff to `HEAD^n`.  Or similar.
