### ISSUE TITLE
Mksession VIM Sessions cause errors

### ISSUE THREAD

**Issue by brettins** [airblade/vim-gitgutter#230]
I get many of the following errors when loading a mksession session that was made previous to installing gitgutter - I have to hit enter for a long time to be able to load my files. Any mksession made after gitgutter is installed is fine, so this issue doesn't affect me anymore.

"style.css" 2856L, 66354C
E117: Unknown function: gitgutter#diff#run_diff
E15: Invalid expression: gitgutter#diff#run_diff(a:realtime || gitgutter#utility#has_unsaved_changes(), 1, 0)
line    9:
E121: Undefined variable: diff
E116: Invalid arguments for function gitgutter#diff#parse_diff(diff))
E116: Invalid arguments for function gitgutter#hunk#set_hunks
line   10:
E117: Unknown function: gitgutter#diff#process_hunks
E15: Invalid expression: gitgutter#diff#process_hunks(gitgutter#hunk#hunks())
line   12:
E121: Undefined variable: modified_lines
E116: Invalid arguments for function len(modified_lines) > g:gitgutter_max_signs
E15: Invalid expression: len(modified_lines) > g:gitgutter_max_signs
line   19:
E121: Undefined variable: modified_lines

**Comment by airblade** [comment]
Do you use Pathogen to load your plugins?

**Comment by brettins** [comment]
Yep, pathogen.

**Comment by airblade** [comment]
In that case the problem is Vim's session restoration preventing Pathogen from loading your plugins.  From Pathogen's [README](https://github.com/tpope/vim-pathogen/commit/f45c82a760bba467e18de18a1e20a33569a05f05):

> Why don't my plugins load when I use Vim sessions?
> Vim sessions default to capturing all global options, which includes the 'runtimepath' that pathogen.vim manipulates. This can cause other problems too, so I recommend turning that behavior off:
> 
> `set sessionoptions-=options`

I use Pathogen too and this configuration change fixed the problem for me.
