### ISSUE TITLE
can't see the gutter

### ISSUE THREAD

**Issue by ngarto** [airblade/vim-gitgutter#231]
Hello,
I can't seem to get git gutter working,
I am on Vim 7.4.52 , git 1.9.1 on Ubuntu 14.04
I had it working at one point but it stopped and I can't seem to figure out why.

:GitGutterEnable has no effect and doesn't pop in the gutter. 

I'm not sure if it's related but whenever I lose/regain focus to the vim terminal I see this at the bottom of the screen:"Press ENTER or type command to continue"

Here is my .vimRC:

```
set nocompatible              " be iMproved
filetype off                  " required!

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
" required!
Plugin 'gmarik/Vundle.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'altercation/vim-colors-solarized'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
set background=dark
"colorscheme default
let g:solarized_termcolors=1
colorscheme solarized
highlight clear SignColumn
```

**Comment by airblade** [comment]
Hmm, what does `:GitGutterDebug` give you?  If you go into the directory where Vundle has installed vim-gitgutter, does `git log` show you're running the latest code?

**Comment by ngarto** [comment]
```

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org

git version 1.9.1

updatetime=2000
shell=/bin/bash
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

git log does show that I am up to date with master on vim-gitgutter

**Comment by airblade** [comment]
Looks ok.

You could try adding `echo a:cmd` just above [this line](https://github.com/airblade/vim-gitgutter/blob/061258e04476c0f9f653a969e640bf03b3659594/autoload/gitgutter/utility.vim#L110) to see what vim-gitgutter is executing, then run that command manually (with `:!`) and you'll be able to see easily whether it succeeds or fails.

**Comment by ngarto** [comment]
That seems to succeed, it outputs a new line I just added
```
@@ -1,0 +2 @@ test
```

**Comment by airblade** [comment]
Good to know.  The next most likely problem is the `grep` output: is it colourful?  If so you can try this:

```viml
let g:gitgutter_escape_grep = 1
```

– or even just change [this line](https://github.com/airblade/vim-gitgutter/blob/061258e04476c0f9f653a969e640bf03b3659594/autoload/gitgutter/diff.vim#L1) to cut out `grep` altogether, as follows:

```viml
let s:grep_available = 0
```

**Comment by ngarto** [comment]
let s:grep_available = 0 worked!
It turns out this line in my .bashrc broke it somehow
the culprit was this line in my bashrc:
```
export GREP_OPTIONS='--color=always'
```
Removing that line resolved the issue.
Thanks!

**Comment by airblade** [comment]
This should work: `export GREP_OPTIONS='--color=auto'` (from #153).

Glad it's all working for you now!

**Comment by airblade** [comment]
I added a note to the README in f6d5b82.

**Comment by airblade** [comment]
A better idea is to tell grep not to use colours: 1fae335.
