### ISSUE TITLE
Realtime diffs say entire file has changed if EOL differs between index and working tree, ignoring EOL conversion

### ISSUE THREAD

**Issue by elyscape** [airblade/vim-gitgutter#232]
When using vim-gitgutter on a system/repo that has CRLF conversion enabled (i.e. `core.autocrlf` is `true` or `input`), realtime diffs that run when the file hasn't been written to disk show every line as having been modified.  This is due to the fact that `git diff` does not perform EOL conversion on stdin, and `git show` never performs EOL conversion.  A workaround is to set `g:gitgutter_diff_args` to `'--ignore-space-at-eol'`, but this has the side effect of also making it not identify lines that have extra whitespace added at the end.  A better solution would be for vim-gitgutter to write the buffer to a temporary file and run `git diff --no-index blobfile tempbufferfile`.

**Comment by airblade** [comment]
Cross-referencing #187.
