### ISSUE TITLE
Settings for sign column width

### ISSUE THREAD

**Issue by letalvoj** [airblade/vim-gitgutter#241]
Hi, 

I find distracting, that the default sign column width is two even if all the signs are of width one. Could the settings be exposed? Or could just somebody point me to the part of the code which creates the column?

Thanks
V.

**Comment by airblade** [comment]
You can't change the width of the sign column: Vim fixes it to two characters.  From `:h sign-intro`:

> When signs are defined for a file, Vim will automatically add a column of two
characters to display them in.

**Comment by letalvoj** [comment]
Thanks for such a quick response and also sorry for my dumb question. :)

V.L.

**Comment by airblade** [comment]
I had no idea the sign column was fixed width until I built this plugin :)

**Comment by gabrielflorit** [comment]
FYI https://github.com/neovim/neovim/issues/990
