### ISSUE TITLE
gitgutter error message

### ISSUE THREAD

**Issue by sivaswami** [airblade/vim-gitgutter#247]
Error detected while processing function gitgutter#highlight#define_signs..gitgutter#highlight#define_sign_text:
line    4:
E239: Invalid sign text: ?~@?

**Comment by airblade** [comment]
Sounds like #229.

Please could you try typing an overline with `^K'-` (control-K apostrophe minus, without any spaces) and let me know whether your vim displays it.

**Comment by sivaswami** [comment]
^K'-
E78: Unknown Mark

**Comment by sivaswami** [comment]
In insert mode Yes I am able to see the "-"
when I entered this in my vimrc, the issue went away
let g:gitgutter_sign_removed_first_line = "^_"

**Comment by airblade** [comment]
If you can see the overbar/overline with `^K-` in insert mode then I'm not sure why Vim throws E239 when loading up vim-gitgutter.

Anyway, 339f8ba handles this situation so you can remove that line from your vimrc.
