### ISSUE TITLE
Enhancement: Show all lines that changed in past x days or since commit y

### ISSUE THREAD

**Issue by xanderdunn** [airblade/vim-gitgutter#248]
gitgutter is life changing!  Thanks so much for this gem!

Often times I know that a bug was introduced within the past x days, or some time after a specific commit.  

It would be super duper amazing if it were possible to show in the gutter every line that has changed across a time range or commit range.  Do you think gitgutter could run `git diff` for multiple commits and then aggregate the changes to be displayed?

Thanks a lot!

**Comment by airblade** [comment]
Currently the plugin runs its diffs in two ways:

- "realtime", i.e. when the buffer has unsaved modifications: it writes the buffer to a temporary file, [writes the file as it is in the index to a temporary file](https://github.com/airblade/vim-gitgutter/blob/339f8ba079ed7d465ca442c9032b36bc56c21f61/autoload/gitgutter/diff.vim#L24), and diffs the two;
- when the buffer is saved: it does a ["normal" git-diff](https://github.com/airblade/vim-gitgutter/blob/339f8ba079ed7d465ca442c9032b36bc56c21f61/autoload/gitgutter/diff.vim#L48).

To change the basis of the diffs you'd need to state them explicitly in both those diff methods.

The docs for `git-rev-parse` explain all the ways to specify revisions.

(Unfortunately I don't have time to work on this myself at the moment.)

**Comment by xanderdunn** [comment]
@airblade Thanks very much.  This is helpful.  I'll probably give this a go sometime.

**Comment by airblade** [comment]
I'll close this for now but please do send a pull request if you get it working.  Thanks!
