### ISSUE TITLE
Showing cached changes

### ISSUE THREAD

**Issue by albfan** [airblade/vim-gitgutter#249]
Sometimes is useful to show what you have already staged, to unstage, modify or improve.

Adding this to ~/.vimrc is enough. See `-M` allow to detect renames showing real changes, nor successions of delete/add files

``` viml
let g:gitgutter_cached_enabled=0
function! GitGutterToggleCached()
  if g:gitgutter_cached_enabled 
    let g:gitgutter_diff_args=g:gitgutter_diff_args_old
  else
    let g:gitgutter_diff_args_old=g:gitgutter_diff_args
    let g:gitgutter_diff_args=g:gitgutter_diff_args." -M --cached"
  endif
  let g:gitgutter_cached_enabled=!g:gitgutter_cached_enabled
  GitGutterAll
endfunction

function! GitGutterIsCached()
  echo (g:gitgutter_cached_enabled ? "Enabled" : "Disabled")
endfunction

command! GitGutterIsCached :call GitGutterIsCached()
nnoremap <silent> <Leader>hc :call GitGutterToggleCached()<CR>
```

The missing enhancements are to show different symbols when cached is active:

```viml
call s:set('g:gitgutter_sign_added_cached',                'A')
call s:set('g:gitgutter_sign_modified_cached',             'M')
call s:set('g:gitgutter_sign_removed_cached',              'R')
call s:set('g:gitgutter_sign_removed_first_line_cached',   '^')
call s:set('g:gitgutter_sign_modified_removed_cached',    'MR')
```

I didn't create a PR, because I don't know where to put all these stuff. If you find it useful just let me know

**Comment by airblade** [comment]
Thanks!  I'll be able to look at this properly when I return from holiday.

P.S.  Sorry to be brief; sent from my phone.

**Comment by somini** [comment]
Yes, this almost works, changing the symbols is must, otherwise I get confused which mode is on.
To change the symbols at runtime, just run
`call gitgutter#highlight#define_signs()`
after [changing it](https://github.com/airblade/vim-gitgutter/issues/254#issuecomment-121214943).

**Comment by albfan** [comment]
Great @somini! I would try to provide a PR based on that.

**Comment by airblade** [comment]
@albfan Thanks!  I'd be happy to merge a pull request with this stuff.

The functions can probably go in [autoload/gitgutter.vim](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter.vim), and the command and map in [plugin/gitgutter.vim](https://github.com/airblade/vim-gitgutter/blob/master/plugin/gitgutter.vim).
