### ISSUE TITLE
Gitgutter fails to load when a session is opened.

### ISSUE THREAD

**Issue by kriox26** [airblade/vim-gitgutter#250]
When I open a single file with no session, gitgutter works as expected. But when I try to open a session, the following error appears: 
```
Error detected while processing function gitgutter#process_buffer:
line    8:
E117: Unknown function: gitgutter#diff#run_diff
"ai.rb" 82L, 1829C
E117: Unknown function: gitgutter#diff#run_diff
E15: Invalid expression: gitgutter#diff#run_diff(a:realtime || gitgutter#utility#has_unsaved_changes(), 1)
line    9:
E121: Undefined variable: diff
E116: Invalid arguments for function gitgutter#diff#parse_diff(diff))
E116: Invalid arguments for function gitgutter#hunk#set_hunks
line   10:
E117: Unknown function: gitgutter#diff#process_hunks
E15: Invalid expression: gitgutter#diff#process_hunks(gitgutter#hunk#hunks())
line   12:
E121: Undefined variable: modified_lines
E116: Invalid arguments for function len(modified_lines) > g:gitgutter_max_signs
E15: Invalid expression: len(modified_lines) > g:gitgutter_max_signs
line   19:
E121: Undefined variable: modified_lines
E116: Invalid arguments for function gitgutter#sign#update_signs
```
This message is almost the same as the [#230](https://github.com/airblade/vim-gitgutter/issues/230) issue, i also have Pathogen installed, but even after setting `set sessionoptions-=options`(which is the solution to that issue) in my vimrc the error continues to appear.
EDIT: add a few lines to the error message

**Comment by airblade** [comment]
I'll be able to investigate this when I get back from holiday...

**Comment by kriox26** [comment]
I was having trouble with some others plugins so i decided to remove vim and recompile it with different flags. Now vim-gitgutter is working great, closing issue, sorry for the inconvenience!!
