### ISSUE TITLE
vim-gitgutter causing error messages when using help system

### ISSUE THREAD

**Issue by komidore64** [airblade/vim-gitgutter#251]
I've notice that Vim spits out some warnings and error messages when using the help system. I'm fairly certain it is caused by vim-gitgutter because I have disabled all of my plugins except for vundle and vim-gitgutter and the problem persists.

```
$ vim
:help autocmd
```

results in:
```
"autocmd.txt.gz" [readonly][noeol] 80L, 15988C
W10: Warning: Changing a readonly file
Press ENTER or type command to continue

[presses enter; continues to read help docs]
```
Once I am done reading, `:q` which spits out another message:

```
E37: No write since last change (add ! to override)
```

I have to `:q!` to get out of help. These warnings/errors are only displayed the first time I run `:help <something>`.

Also: Interestingly, opening a new instance of Vim, then running only `:help` displays neither of the above mentioned warnings/errors.

---

Attachments:
- version of [Vim](https://gist.github.com/komidore64/4b3d55d33417b8a40cda) that I'm using on Centos6
- [verbose output](https://gist.github.com/komidore64/5b7e8057e278a991954b) from running the following:
```
$ vim -V9vim.log
:help autocmd
[enter]
:qa!
```

Please let me know if there's any other information I can get to you. Thanks!

**Comment by airblade** [comment]
Sorry for the slow reply – I was away on holiday.

I don't know why vim-gitgutter would attempt to change the file.  In fact I didn't think vim-gitgutter would run at all on help files but I suppose it is doing so.

Does adding this to your vimrc help?

```viml
autocmd BufEnter * if &ft == 'help' | let g:gitgutter_enabled = 0 | endif
autocmd BufEnter * if &ft != 'help' | let g:gitgutter_enabled = 1 | endif
```

On a different tack, does Centos6 have a less ancient version of Vim available?

**Comment by airblade** [comment]
I just saw this [comment](https://github.com/airblade/vim-gitgutter/commit/e098491906c4e6d8a2a4d10ab60b91570eb81113#commitcomment-11340034) which sounds very related.

**Comment by airblade** [comment]
Please try 2e98692.

**Comment by komidore64** [comment]
> does Centos6 have a less ancient version of Vim available?

Haha, it certainly is ancient isn't it! Unless I build Vim from source, or pull RPMs from repositories other than Centos and EPEL, I believe that's the newest that Centos6 is going to get.

I pulled down 2e98692 into my Vim environment, but the problem still seems to persist. I also tried adding your code snippet to to my vimrc. That also didn't help.

For what it's worth, this problem does not occur in a newer Vim that I have on a Fedora 20 machine (no warning/error messages).

@airblade, I realize the Vim I am using in Centos6 is quite old. I'm willing to accept "Versions of Vim older than X are not fully supported" if that's what you'd prefer to do. It's tough maintaining full backwards compatibility :smile:. Thank you for the response and for trying to fix this issue!

**Comment by airblade** [comment]
Hmm, well I have no idea why vim-gitgutter is still trying to modify help files.

Since the problem doesn't manifest in a newer Vim, and it's not such a big problem, I can't summon the energy to pursue it any further ;)

**Comment by sitaramc** [comment]
I can see this on vim 7.4.x, but see the latest comment I added [here](https://github.com/airblade/vim-gitgutter/commit/e098491906c4e6d8a2a4d10ab60b91570eb81113#commitcomment-12662440).  (TLDR: works on pristine vimrc, doesn't work on mine, could not figure out precisely what the conflict was, gave up.)

**Comment by airblade** [comment]
@komidore64 @sitaramc Out of curiosity, what are your `&cpoptions`?

**Comment by sitaramc** [comment]
On 08/13/2015 12:44 PM, Andy Stewart wrote:
> @komidore64 <https://github.com/komidore64> @sitaramc <https://github.com/sitaramc> Out of curiosity, what are your |&cpoptions|?

cpoptions=aABceFs

Looks like the default; it's the same before and after ":set cpoptions&"

regards
sitaram

**Comment by komidore64** [comment]
```
:set cpoptions?
  cpoptions=aABceFs
```
