### ISSUE TITLE
Show staged, but uncommited changes

### ISSUE THREAD

**Issue by somini** [airblade/vim-gitgutter#252]
Is it possible to show hunks that have been staged, but not yet commited?
Basically, the output of `git diff --cached`
I read the documentation but I couldn't find any option regarding this?

**Comment by airblade** [comment]
This should do it: `let g:gitgutter_diff_args='cached'`.

**Comment by airblade** [comment]
See also #249.

**Comment by somini** [comment]
Great, thanks! That other issue solves half my "problem".

What I was really looking for was to keep it all in a single gutter. Meaning staged changes would show up in a different colour, for example.
Maybe it needs to run git 2 times, so it would slow things down considerably. How easy is to add extra symbols?

**Comment by airblade** [comment]
To get both sets of changes you'd have to do everything twice which would slow things down.  I have found that people are quite sensitive to any lag this plugin causes.

You'd need to add a second set of signs, and keep track of a second set of hunks, and so on.  I suppose in principle it's straightforward, though fiddly.

It's not something I'm going to spend any time on but I'd be happy to try to help with any questions.
