### ISSUE TITLE
Configured g:gitgutter_sign_ values aren't taken into account if defined in .vim/after/plugin/gitgutter.vim

### ISSUE THREAD

**Issue by CaptainQuirk** [airblade/vim-gitgutter#254]
Hi there,

Thanks for you work ! Added to fugitive, your plugin makes working with git a real pleasure.

However, I'm trying to split my vimrc file by relying on certain built-in behaviors of vim. I've put my git-gutter configuration in the file mentioned above (Not in the right directory for now, but at least you get the content of the file [here](https://github.com/CaptainQuirk/.vim/blob/master/plugin/gitgutter.vim))
My custom function works, as my mappings. Eager and realtime are working as expected.
But the signs are the default ones ...

Any ideas ?

**Comment by airblade** [comment]
Sorry for the slow reply – I was away on holiday.

Try adding this to your 'after' file, below where you set your new signs:

```viml
call gitgutter#highlight#define_signs()
```

**Comment by airblade** [comment]
@CaptainQuirk Did you get this working?

**Comment by airblade** [comment]
I'm assuming everything's fine now.  Please tell me if your signs still aren't being configured properly.
