### ISSUE TITLE
Disruptive error message

### ISSUE THREAD

**Issue by dpo** [airblade/vim-gitgutter#259]
The documentation says that gitgutter automatically turns itself off when the max number of signs has been reached. That's true, but it also outputs the error message `exceeded maximum number of signs`, which is distracting and disruptive. How do I turn the error message off?

**Comment by benwoodward** [comment]
+1!

**Comment by airblade** [comment]
Sorry for taking so long to get back to you.

Is the problem that you have to press enter to acknowledge the message, or simply that the message is there at all?

**Comment by al3xandru** [comment]
@airblade mostly the fact that it's breaking the flow. the message could be added to the messages list or anything that wouldn't interrupt

**Comment by erlandsona** [comment]
+1! To answer more specifically for @airblade I wouldn't mind if it was just a message but having to hit enter every time I see it get's very distracting. How can I turn off that particular error message?

**Comment by al3xandru** [comment]
The line triggering the message is https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter.vim#L27. I cannot tell though why `gitgutter#utility#warn` leads to the press enter part. I tried calling directly this function and it doesn't lead to that behavior.

**Comment by noscripter** [comment]
This is quite annoying, every time I save the file, this message pops up in the status line.

**Comment by airblade** [comment]
What does `:echo &cmdheight` give you?  For me setting `cmdheight` to `2` makes the press-enter prompts go away.  I also seem to find MacVim behaves differently from system Vim (OS X 10.11.2) in this regards.

However even without the prompts it's still annoying to have the warning flash up all the time.  I think just showing it once per editing session would be enough.  Would you agree?

**Comment by al3xandru** [comment]
Considering it's a configurable option, a simple logged warn would be enough IMO.

**Comment by al3xandru** [comment]
If someone knows how to disable this please post it here... it's been killing me lately :-(.

**Comment by airblade** [comment]
Please upgrade to 3a810a9 and let me know if it helps.

**Comment by al3xandru** [comment]
thanks @airblade. I'm trying it today and report back.

**Comment by al3xandru** [comment]
I can confirm that I haven't seen that messages since upgrading. again, many thanks @airblade !
