### ISSUE TITLE
How to make GitGutter{Prev,Next}Hunk to wrap around?

### ISSUE THREAD

**Issue by claudiodangelis** [airblade/vim-gitgutter#260]
Is it possible to make these two commands wrap around on reaching the beginning/ending of the file?

Thanks!

**Comment by airblade** [comment]
There was a discussion on a similar topic in #236.

I suppose I could add a configuration setting which would allow/prevent those commands wrapping.

Just need a bit of spare time...!

**Comment by claudiodangelis** [comment]
Awesome, thank you.

**Comment by airblade** [comment]
I don't want to build this into the plugin: it's big enough already.  You can achieve what you want with this in your vimrc:

```viml
function! PrevHunkWrap(count)
  for i in range(1, a:count)
    let line = line('.')
    silent GitGutterPrevHunk
    if line('.') == line
      normal G
      silent GitGutterPrevHunk
    endif
  endfor
endfunction

function! NextHunkWrap(count)
  for i in range(1, a:count)
    let line = line('.')
    silent GitGutterNextHunk
    if line('.') == line
      normal 1G
      silent GitGutterNextHunk
    endif
  endfor
endfunction

command -count=1 Phw call PrevHunkWrap(<count>)
command -count=1 Nhw call NextHunkWrap(<count>)
```
