### ISSUE TITLE
GREP_OPTIONS="-n" breaks gitgutter

### ISSUE THREAD

**Issue by jcppkkk** [airblade/vim-gitgutter#263]
Hi,

vim-gitgutter does not show file changes in vim screen, here is related information.

$ git status
```
On branch dev
Your branch is up-to-date with 'origin/dev'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   README.md

no changes added to commit (use "git add" and/or "git commit -a")
```
vim README.md (vim-gitgutter does not show changes, neither the vim-airline)

![image](https://cloud.githubusercontent.com/assets/84070/9433668/aa65ff10-4a68-11e5-9b38-a6e37b0d892a.png)
![image](https://cloud.githubusercontent.com/assets/84070/9433696/d73b41ee-4a68-11e5-9da8-bffba7994131.png)

GitGutterDebug
```
:GitGutterDebug
  1                                                                      
  2 VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)   
  3 Included patches: 1-52                                               
  4 Modified by pkg-vim-maintainers@lists.alioth.debian.org              
  5                                                                      
  6 git version 2.5.0                                                    
  7                                                                      
  8 updatetime=4000                                                      
  9 shell=/bin/bash                                                      
 10 shellcmdflag=-c                                                      
 11 shellpipe=2>&1| tee                                                  
 12 shellquote=                                                          
 13 shellredir=>%s 2>&1                                                  
 14 shellslash [n/a]                                                     
 15 shelltemp=1                                                          
 16 shelltype [n/a]                                                      
 17 shellxescape=                                                        
 18 shellxquote=                                                         
```

However, the git command in vim shows correct status
```
:!git status
On branch dev
Your branch is up-to-date with 'origin/dev'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   README.md

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by airblade** [comment]
Is your vim-gitgutter installation up to date?

I assume `echo has('signs')` returns `1`?  It should do.

Your `updatetime` is `4000`ms so you the plugin will wait 4 seconds after you stop typing before updating the signs for any unsaved changes.  I prefer something closer to `500`ms or `750`ms.

However with saved changes, as you have here, the signs should show immediately.  What do you get if you add `echom output` immediately below [this line](https://github.com/airblade/vim-gitgutter/blob/0e66fc915c5c7d8f18eb62f69230393465812fc3/autoload/gitgutter/utility.vim#L118)?

**Comment by jcppkkk** [comment]
> I assume echo has('signs') returns 1? It should do.

Yes

> What do you get if you add echom output immediately below this line?

I found it may be related to my gitconfig, because when i use ```sudo vim file``` it works.

with ```sudo vim file``` it shows
```docker^@@@ -7 +7 @@^@```

with ```vim file``` (the problem case) it shows
```README.md^@5:@@ -10,0 +11 @@ Config file^@```

And my ~/.gitconfig is as below
```
[user]
        name = Jethro Yu
        email = comet.jc@gmail.com
[core]
        editor = vim
        autocrlf = input
        whitespace = cr-at-eol
        pager = less -+F
[color]
        branch = auto
        diff = auto
        interactive = auto
        status = auto
        ui = true
[alias]
        co = checkout
        ci = commit --verbose
        st = status
        br = branch
        last = log -1 HEAD
        unstage = reset HEAD --
        gr = "log --all --graph --pretty=format:'%Cred%h%Creset%x09%C(yellow) %d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit  --date=relative"
        last = !git --no-pager gr -20
        d = difftool
[merge]
        tool = meld
[branch]
        autosetuprebase = always
[push]
        default = current
[credential]
        helper = cache --timeout=86400
[rerere]
        enabled = true
```

**Comment by airblade** [comment]
I wonder what that `5:` is in the problem case's output.  The `^@`s are new lines.

If you move your gitconfig out of the way temporarily, does vim-gitgutter start working?

I can't think why `sudo` would make a difference.

**Comment by jcppkkk** [comment]
@airblade  I found it by add ```echo a:cmd``` and trace how the command runs
```cd /home/ubuntu/trunk/dotfiles/vim/bundle/vim-gitgutter/autoload/gitgutter && (git ls-files --error-unmatch utility.vim && (git diff --no-ext-diff --no-color -U0  -- utility.vim | grep --color=never -e '^@@ ' || exit 0))```

The "5:" turns outs is mine grep system variable enables line number:
```
export GREP_OPTIONS="-n"
```

After remove "-n" options the gitgutter works. 

I suggest to do these fixes:
1. overwrite GREP_OPTIONS inside command: ```GREP_OPTIONS=""```
2. escape potential alias of grep (ref #235): ```\grep  -e '^@@ '```

Result as following command
```cd /home/ubuntu/trunk/dotfiles/vim/bundle/vim-gitgutter/autoload/gitgutter && (git ls-files --error-unmatch utility.vim && (git diff --no-ext-diff --no-color -U0  -- utility.vim | GREP_OPTIONS="" \grep  -e '^@@ ' || exit 0))```

**Comment by airblade** [comment]
Glad you found the problem.

GREP_OPTIONS is deprecated so I don't think specifying it is the best solution.  I'm not sure what would be better though.

**Comment by jcppkkk** [comment]
How about this? not specifying but unset it ```cd /home/ubuntu/trunk/dotfiles/vim/bundle/vim-gitgutter/autoload/gitgutter && (git ls-files --error-unmatch utility.vim && (git diff --no-ext-diff --no-color -U0  -- utility.vim | (unset GREP_OPTIONS && grep  -e '^@@ ') || exit 0))```

**Comment by airblade** [comment]
The [`grep` documentation](http://www.gnu.org/software/grep/manual/html_node/Environment-Variables.html) says:

> GREP_OPTIONS
> This variable specifies default options to be placed in front of any explicit options. As this causes problems when writing portable scripts, this feature will be removed in a future release of grep, and grep warns if it is used. Please use an alias or script instead.

I suggest you replace your `GREP_OPTIONS` with `alias grep='grep -n'`.

vim-gitgutter knows how to [escape a `grep` alias](https://github.com/airblade/vim-gitgutter#whether-or-not-to-escape-grep): set `let g:gitgutter_escape_grep=1`.

After that, everything will work for you.
