### ISSUE TITLE
An issue with gettabvar()

### ISSUE THREAD

**Issue by szw** [airblade/vim-gitgutter#266]
Hi! I really like gitgutter and appreciate your good work :). Recently there was [an issue](https://github.com/vim/vim/issues/394) I raised in Vim that made `gettabvar()` called after `:only` to return an empty string for the first time. The subsequent calls provided correct results. The issue seems to be fixed in the newest Vim but surprisingly it's still present with vim-gitgutter. 

Here's how to reproduce:

1. Open Vim with gitgutter
2. `:let t:foo = "bar"`
3. `:help`
4. `<C-w>j` (go back to the No Name buffer from help window)
5. `:only`
6. `:echo gettabvar(1, "foo")` you will get the empty string
7. Repeat the command from 6 - now you will see `"bar"` string

Thanks in advance for looking at this. I have no idea whether it's still a Vim issue and why it's present when vim-gitgutter is enabled.

My setup is a console Vim on OSX:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 14 2015 09:16:22)
MacOS X (unix) version
Included patches: 1-865
Compiled by Homebrew
Huge version without GUI. 
```

I'm using Vundle and my most recent vimrc is [here](https://github.com/szw/dotfiles/blob/master/vimrc).

All the best!

s.

**Comment by airblade** [comment]
Hi Szymon!

Presumably vim-gitgutter is following a code path which somehow sidesteps the fix made for the original issue, though I'm not familiar enough with vim's internals to know what's going on.

The only place I use `gettabvar()` is [here](https://github.com/airblade/vim-gitgutter/blob/1067294cdc379be1deb56074a093b49a8303308f/plugin/gitgutter.vim#L170-L178):

``viml
    autocmd BufEnter,BufWritePost,FileChangedShellPost *
          \  if gettabvar(tabpagenr(), 'gitgutter_didtabenter') |
          \   call settabvar(tabpagenr(), 'gitgutter_didtabenter', 0) |
          \ else |
          \   call gitgutter#process_buffer(bufnr(''), 0) |
          \ endif
    autocmd TabEnter *
          \  call settabvar(tabpagenr(), 'gitgutter_didtabenter', 1) |
          \ call gitgutter#all()
```

I think vim-gitgutter is showing that the issue you identified in vim hasn't been entirely resolved.

Presumably vim-gitgutter still works as expected for you?

**Comment by airblade** [comment]
This is what happens when you switch tabs:

1. Vim fires a `TabEnter` event.  vim-gitgutter updates the signs in every window of the new tab.
2. Vim fires a `BufEnter` event for the buffer you arrive in on the new tab.  We don't want vim-gitgutter to update the buffer's signs all over again because we only just updated them in step 1.

The plugin uses a tab variable to achieve this.

Perhaps the problem is still present because we read the tab variable in `BufEnter` and [`firstwin`](https://github.com/vim/vim/commit/7e47d1ac6a9ae0e5a7167aa34ff651a9c39c1641#diff-de9ab8906fef668ed8042046e0a1eb02R12295) isn't initialised by then.

**Comment by airblade** [comment]
As far as I can tell:

- `firstwin` is set to `NULL` in [`leave_tabpage()`](https://github.com/vim/vim/blob/b4ff518d95aa57c2f8c0568c915035bef849581b/src/window.c#L3921).
- `firstwin` is set to `tp->tp_firstwin` in [`enter_tabpage()`](https://github.com/vim/vim/blob/b4ff518d95aa57c2f8c0568c915035bef849581b/src/window.c#L3943).
- But just after that there's an interesting comment:

```c
     /* We would like doing the TabEnter event first, but we don't have a
     * valid current window yet, which may break some commands.
     * This triggers autocommands, thus may make "tp" invalid. */
     win_enter_ext(tp->tp_curwin, FALSE, TRUE,
			      trigger_enter_autocmds, trigger_leave_autocmds);
```

Maybe `BufEnter` is fired before `firstwin` is set.  I don't really know ;)

**Comment by airblade** [comment]
Whatever the explanation, I'm confident this isn't a vim-gitgutter problem.
