### ISSUE TITLE
Git Gutter does not update the signs after committing changes 

### ISSUE THREAD

**Issue by ruiafonsopereira** [airblade/vim-gitgutter#267]
After committing and pushed my changes to the server, the signs are not updated until I close and re-open the file. Wouldn't it be nice if the changes were updated in [real time](https://github.com/airblade/vim-gitgutter#when-are-the-signs-updated)? Did I miss some configuration when reading the readme file?

*Note: I use tmux and I committed the changes while vim was opened in a different split window. Not sure if this changes a thing.*

**Comment by airblade** [comment]
The changes should be updated in realtime while you're in Vim.  If your focus is elsewhere, such as a different tmux split, Vim isn't "active".

Unfortunately terminal Vim doesn't emit the `FocusGained` event so once you move your focus back to Vim you'll have to do something to let vim-gitgutter know it needs to update, e.g. save the file or run `:GitGutter`.

**Comment by ruiafonsopereira** [comment]
Thanks for the explanation.

Neither saving the file nor running ``:GitGutter`` forced vim-gitgutter 
to update.

**Comment by airblade** [comment]
What does `:GitGutterDebug` say?

**Comment by ruiafonsopereira** [comment]
Looks like that saving the file does the trick after all. I thought that 
committing the changes was enough, but it's also required to push them 
to the remote origin.

If this is the expected behaviour, you can go ahead and close this issue.
Thanks.

**Comment by airblade** [comment]
I agree it is suboptimal that if you stage or commit some changes outside vim, there's isn't a way (that I know of) to nudge vim to tell it something has happened.  There is the `FileChangedShellPost` autocommand but that is only fired when the files actually change, which doesn't happen when staging or commiting.

**Comment by hk0i** [comment]
Not to poke a dead issue here, but saving or running `:GitGutter` doesn't work for me. Using nvim + tmux in iTerm 2 (OS X)

`git status` shows no changes on those files.

my `:GitGutterDebug` output:

```

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5

git version 2.24.2 (Apple Git-127)

grep (BSD grep) 2.5.1-FreeBSD
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]	[-e pattern] [-f file] [--binary-files=value] [--color=when]	[--context[=num]] [--directories=action] [--label] [--line-buffered]	[--null] [pattern] [file ...]

updatetime=1000
shell=/bin/zsh
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

**Comment by hk0i** [comment]
I just tried installing [Terminus](https://github.com/wincent/terminus) so we'll see if that resolves the issue (restarted vim and it looks okay so far)

**Comment by airblade** [comment]
@hk0i If `git status` doesn't show any changes, `git diff` will be empty so there's nothing for gitgutter to show.  Or have I misunderstood your situation?

**Comment by mihaigalos** [comment]
I tried a `:Git status` using [vim-fugitive](https://github.com/tpope/vim-fugitive) to force-update the status.
That updated gitgutter.
