### ISSUE TITLE
Sourcing a file breaks the plugin styles

### ISSUE THREAD

**Issue by Joe5** [airblade/vim-gitgutter#268]
In my .vimrc I have an auto command that automatically sources my .vimrc when I save it. This breaks styling of the plugin.

Before save:
![ok](https://cloud.githubusercontent.com/assets/6758999/10067744/25ce10a4-629f-11e5-9436-17a12cfbaca5.png)
After save:
![broken](https://cloud.githubusercontent.com/assets/6758999/10067748/2a872d06-629f-11e5-92b5-e61e117c9054.png)

**Comment by airblade** [comment]
I imagine your .vimrc resets syntax highlighting and things like that.

After re-sourcing your .vimrc, does this help? :- 

```viml
call gitgutter#highlight#define_sign_column_highlight()
call gitgutter#highlight#define_highlights()
```

**Comment by Joe5** [comment]
Yes, in my .vimrc I have few settings changing syntax and theme. I've commented all of them out and the problem disappeared. Then I enabled them one by one and found that the problem was with `colorscheme` command. I am using custom theme but I've found that it was also broken when using official theme (`desert`).

Calling the functions you have mentioned fixed the problem regardless of this setting.

**Comment by airblade** [comment]
Good to hear you tracked down the cause.  However vim-gitgutter has a [`ColorScheme` autocommand](https://github.com/airblade/vim-gitgutter/blob/1067294cdc379be1deb56074a093b49a8303308f/plugin/gitgutter.vim#L186) which should call those functions automatically, so I'm puzzled it didn't work.  I'll see if I can figure out the problem there.

**Comment by airblade** [comment]
Hmm, I can't reproduce the problem.  Are you using the latest version of this plugin?  What version of vim are you on?

**Comment by Joe5** [comment]
My Vim is 7.4 (2013 Aug 10) on Ubuntu 15.04. I am using pathogen and git submodules to install all plugins so it should be the latest version but I don't know how to check it. Anyway I've checked source of your plugin and I have that autocommand there but it's not working as it should be. As a temporary workaround I have modified autocommand resourcing my .vimrc to include those functions. It's an ugly "hack" but it works.

**Comment by airblade** [comment]
It seems either the autocommand isn't firing or it is firing but not having the desired effect.  To determine which, please could you run this in vim? :- 

```viml
autocmd ColorScheme * echom "hello"
```

Then change the colorscheme.  Do you see `hello` in the messages (`:messages`)?

**Comment by airblade** [comment]
I don't think it's relevant but patch [7.4.109](https://github.com/vim/vim/commit/b95186fd36bae9716181bfdd203fb27f410e3c4f), which your vim doesn't have, affects the `ColorScheme` autocommand.

**Comment by Joe5** [comment]
Nope, colorscheme auto command does not fire.

**Comment by airblade** [comment]
That's the problem.  If your vim doesn't fire the colorscheme auto command when you change the colorscheme, there's no way for vim-gitgutter to know it should update the highlights.

**Comment by Joe5** [comment]
Yep, thank you for your help.

**Comment by BrowncoatShadow** [comment]
For anyone else who comes across this issue in the future; I worked around this by [manually executing the ColorScheme event](http://vimdoc.sourceforge.net/htmldoc/autocmd.html#autocmd-execute).

It would look something like this in your vimrc:

```vim
colorscheme solarized
set background=dark
do ColorScheme
```

The event execution needs to be *after* you set the colorscheme and background. This manually triggers the event when you source your vimrc file, so that vim-gitgutter can automatically call the functions needed to set the proper highlights.

I think this is a little cleaner than manually calling the individual functions, and should be future-proof for any changes vim-gitgutter makes that are related to the event.

**Comment by airblade** [comment]
@BrowncoatShadow Thank you, that's helpful.
