### ISSUE TITLE
Changes in subfolders starting with upper case aren't tracked

### ISSUE THREAD

**Issue by MarkusAmshove** [airblade/vim-gitgutter#269]
Hi airblade,

first of all thanks for your great plugin, it really makes working with git and vim super easy!

Today I stumbled upon a bug that I think depends on subfolder (I'm on Windows btw).

I have the following repository layout:

.git\
Tests\SubfolderFile.txt
RootLevelFile.txt

If I modify the RootLevelFile.txt I get all symbols that I would expect.

However, if I modify the file in the subfolder (Tests\SubfolderFile.txt) and I save it I won't get any symbols.

I'm also using fugitive for the git commands an the statusbar and it won't recognize the changes either.

If my subfolder's name is all lowercase, everything works as expected.

Is there some way to fix this issue?

**Comment by airblade** [comment]
Since fugitive has the same problem, it sounds like this is to do with Windows' case sensitivity rather than any specific thing that fugitive or vim-gitgutter is doing.

I know vim-gitgutter doesn't change the case of any filenames it works with.

Does [this](http://stackoverflow.com/questions/2528589/git-windows-case-sensitive-file-names-not-handled-properly) help?

**Comment by MarkusAmshove** [comment]
Hm, I now think it's more of a (g)vim or NERDTree problem.

If I'm in the directory of my repository vim shows the path as:

C:\Path\To\My\Repository   (it contains the uppercase characters)

however, if I then switch (through NERDTree or \:e) to the subdirectory containing an uppercase letter
e.g. \:e Tests/MyTest.txt
it gets translated to tests, so the path vim shows is 
C:\Path\To\My\Repository\tests

If I cd into the Tests directory via cmd or powershell and then launch vim right from that directory, everyhting (including gitgutter ofcourse) works perfectly.

What also works is if I'm in the file and the git status isn't showing, I can type \:cd ../Tests (go one directory up, change to Tests uppercase) and then git will work.

That's some weird thing :-)

You can close it if you want, because I don't think it is anything realted to gitgutter.

Do you have any further hint as where I could go to? (NERDTree, Vim, ...)

**Comment by airblade** [comment]
If I understand you correctly, it sounds like without NERDTree everything else works.

So I would search NERDTree's issues for case sensitivity and/or open an issue there.
