### ISSUE TITLE
Doc TOC needs to be updated.

### ISSUE THREAD

**Issue by sanscore** [airblade/vim-gitgutter#270]
The TOC  of vim-gitgutter's help document needs to be updated. Fairly simple issue to fix.

https://github.com/airblade/vim-gitgutter/blob/master/doc/gitgutter.txt#L17

Should be:
```
5. CUSTOMISATION...|GitGutterCustomisation|
6. FAQ....
```

**Comment by airblade** [comment]
Thanks for letting me know.  It's fixed in dcaa7ea.
