### ISSUE TITLE
GitGutterChangeDeleteLine doesn't default to DiffChange

### ISSUE THREAD

**Issue by JacobLeach** [airblade/vim-gitgutter#272]
The docs say: 

`GitGutterChangeDeleteLine " default: links to GitGutterChangeLineDefault, i.e. DiffChange`

 but `GitGutterChangeLineDefault` doesn't seem to exist and a change/delete line does not get highlighted by default. 

Adding:  

`highlight link GitGutterChangeDeleteLine DiffChange` 

to my vimrc made a change/delete line highlight. 

Not sure if the default behavior was intended or if I am just understanding the docs incorrectly.

**Comment by airblade** [comment]
Thanks for pointing this out.  I think this change (b18e23c) should fix it – please can you try it and let me know?

**Comment by JacobLeach** [comment]
@airblade It is fixed. Thanks!
