### ISSUE TITLE
Error if file name contains equals sign

### ISSUE THREAD

**Issue by JakobR** [airblade/vim-gitgutter#273]
I encountered this when editing templates for [vim-template](https://github.com/aperezdc/vim-template). The *.java template is named `=template=.java`, for example. I believe the `=` sign in the name breaks something in gitgutter:

Automatically after `updatetime`:
![screen shot 2015-10-13 at 09 03 30](https://cloud.githubusercontent.com/assets/1545558/10448001/d9358c8c-7189-11e5-817b-a5b8f3a25a36.png)

When saving manually:
![screen shot 2015-10-13 at 09 03 43](https://cloud.githubusercontent.com/assets/1545558/10448003/dd0409ce-7189-11e5-9eb2-6007521105d2.png)

(Is there a way to copy the error messages so I can paste the text instead of a screenshot?)

**Comment by airblade** [comment]
I agree, I think the `=` in the filename is tripping up vim-gitgutter.  I'll come up with a fix.

I don't know a good way to copy the error messages.  It might be possible to yank `v:errmsg` into the system clipboard...but a screenshot is certainly easier ;)

**Comment by airblade** [comment]
This should be fixed by a30ee7f.  Please can you try it and let me know?

**Comment by JakobR** [comment]
Wow, that was fast!

Yes, it seems to work now. Thank you!
