### ISSUE TITLE
gitgutter overwriting all other plugin signs (YCM, signify, syntastic)

### ISSUE THREAD

**Issue by vsilv** [airblade/vim-gitgutter#276]
I have the strange behavior that gitgutter is overwriting all other plugins. Maybe it is something system-specific, but I updated to the recent versions of all plugins. Do you know how I can find the problem?

**Comment by airblade** [comment]
It shouldn't ever overwrite signs it didn't place itself.

You could try inspecting the content of the `other_signs` list at the end of [this function](https://github.com/airblade/vim-gitgutter/blob/a30ee7f23e93c827b4857d337f04c1ddf3c0c16e/autoload/gitgutter/sign.vim#L70-L102) to see if vim-gitgutter is correctly identifying other plugins' signs.

**Comment by airblade** [comment]
Any more information?

**Comment by airblade** [comment]
Closing this because there hasn't been any further information and I can't reproduce the problem.
