### ISSUE TITLE
Placeholder for clean state?

### ISSUE THREAD

**Issue by pdawczak** [airblade/vim-gitgutter#277]
Hi,

First of all - thank you for great plugin! Great work. 

This is something that is slightly disturbing. If I open a _clean_ file, that is up to date and there are no signs allocated yet, once a change is introduced, it _re-draws_ whole interface allocating new column (near numbers):

<img width="33" alt="2015-10-30_1547" src="https://cloud.githubusercontent.com/assets/601110/10850442/a35f5d9e-7f1d-11e5-88a7-82b4b9c66071.png">
<img width="46" alt="2015-10-30_1548" src="https://cloud.githubusercontent.com/assets/601110/10850446/a6fafe04-7f1d-11e5-9ae1-92be33d60f02.png">

How about something like (near [here](https://github.com/airblade/vim-gitgutter/blob/master/plugin/gitgutter.vim#L40)):

```
call s:set('g:gitgutter_sign_clean',                ' ')
```

_(with proper implementation of it ;))_

That could keep the _clean_ state with place for signs allocated, that once the change is introduced, there is no effect of redrawing the whole _interface_.

Thank you!

**Comment by airblade** [comment]
Try this: `let g:gitgutter_sign_column_always = 1`.

> By default the sign column will appear when there are signs to show and disappear when there aren't. If you would always like the sign column to be there, add `let g:gitgutter_sign_column_always = 1` to your ~/.vimrc.

From the [README](https://github.com/airblade/vim-gitgutter#sign-column).

**Comment by pdawczak** [comment]
Hey! Thanks for your quick response! I've tried this before, but it didn't work. I've tried this one more time and this time was as expected! (Quite possible my error with first attempt)

Again - Thank you!
