### ISSUE TITLE
Allow ranges for GitGutterStage

### ISSUE THREAD

**Issue by rnestler** [airblade/vim-gitgutter#279]
I would like to be able to use GitGutterStageHunk with a range. This would enable to select the lines I want to stage in visual mode:
![git_gutter_stage](https://cloud.githubusercontent.com/assets/1435346/10940501/f73525ba-8306-11e5-88a2-1f254a8ef9e1.png)
Then I would type `:GitGutterStageHunk`

Currently I get `E481: No range allowed`

**Comment by airblade** [comment]
Sounds feasible.  I'll do it when I get some time.

**Comment by rnestler** [comment]
If you can point me in the right direction I could give it a try. I've never really done anything with vim-script and would like to learn it.

**Comment by airblade** [comment]
The first step is to modify the `GitGutterStageHunk` command to accept an optional range and pass it to the function it calls.  See `:h command-range`.

Then the function `gitgutter#stage_hunk()` needs to accept an optional range and pass it to `gitgutter#diff#generate_diff_for_hunk()`.

The tricky part will be amending the diff that last function generates.  Probably the easiest approach is to let it generate a diff for the whole hunk, as it does now, and then just keep the part corresponding to the range.  You'll have to update line numbers in the patch header appropriately.

**Comment by deepflame** [comment]
That would be awesome guys. +1

**Comment by gibbycu** [comment]
+1.  This is the first thing my fingers tried.

**Comment by airblade** [comment]
I've got the code to handle the example in your screenshot.  It's also easy to handle staging part of a hunk of only-modified lines.

However it gets trickier with modified and added lines.  Consider this buffer:

```
  a
  b
  c
  d
```

You insert a line (`x`) between the first and second lines, and modify the original second and third lines:

```
  a
  x
  bb
  cc
  d
```

This corresponds to a diff of:

```diff
- b
- c
+ x
+ bb
+ cc
```

Note there's no way to tell from the diff which line was added (`x`) and which lines were modified (`bb`, `cc`).

Vim-gitgutter will render this as:

```
  a
~ x
~ bb
+ cc
  d
```

If you choose the first two lines (`x`, `bb`) for staging, you probably want to stage the reverse of:

```diff
- b
+ x
+ bb
```

But there is no way to know for git or vim-gitgutter to know which of the three `+` lines in the diff was simply added and which were the result of modifying lines.

As a result the code I have produces this:

```diff
- b
- c
+ x
+ bb
```

But that includes the `c` line which you didn't want.

So then I looked at the selection another way: stage all but the last line (`cc`).  We could then get a diff of:

```diff
- b
+ x
+ bb
```

Which is what we want.  But this falls down if the added line (`x`) comes at the end of the hunk:

```
  a
~ bb
~ cc
+ x
  d
```

The diff is:

```diff
- b
- c
+ bb
+ cc
+ x
```

If we again want to stage the first two lines of the hunk (`bb`, `cc`), our revised algorithm fails while our original algorithm succeeds.

Can anyone think of a way to resolve this?

**Comment by somini** [comment]
I think you'll need to compare the diffs with the line contents,and include the signs too.
Other than considering the full hunk, there's not enough information. Git interactive add does that too, as I recall. 
Either that or forbid mixed signs hunks.

**Comment by airblade** [comment]
@somini I didn't understand the first part:

> I think you'll need to compare the diffs with the line contents,and include the signs too.

Please could you eloborate?

**Comment by somini** [comment]
Sorry, I was on mobile.

On your second example, if the user wants to stage all but the last line.
That corresponds with two lines `bb` and `cc`, so you process the hunk so that only the lines that add those line contents are added. Since they are both "modified" lines, take the same number of lines from the "deleted" side.
If you want to stage the last two lines, with mixed signals.
That corresponds to two lines `cc` and `x`, one "modified" and one "added". So take those two and only the last from the "deleted" side.

**Comment by somini** [comment]
Hmm, that also breaks down on the first example. I was reading it wrong.
After some googling, the only solution I found was let the user manually edit the patch, but that's too fiddly.

When I want to stage parts of a hunk, I save the file, change the hunk to the result I want to stage, stage the hunk, then undo until I saved the file the first time.

**Comment by airblade** [comment]
How about this:

- When the user selects part of a hunk which can be staged unambiguously, the plugin does it.
- When the user selects part of a hunk which cannot be staged unambiguously:
  - the plugin opens the hunk diff in a temporary buffer;
  - the user edits the patch and types `:w` to stage it or `:q` to cancel;
  - the plugin closes the temporary buffer and stages the amended patch.

This way we get the best of both worlds.

**Comment by somini** [comment]
Yup, that's what git does, and so do most other frontends like magit. Seems like it's the only sane way to do it.

**Comment by supercrabtree** [comment]
+1 this would be amazing :)

**Comment by victorkristof** [comment]
Hi, any status on this issue? That would truly be super nice :)

**Comment by airblade** [comment]
No progress – it's never quite at the top of my to-do list...

**Comment by aureooms** [comment]
I did not quite get the issue with implementing this. For example, what would be difficult with staging a single line that is part of a bigger hunk.

**Comment by airblade** [comment]
@aureooms There's no particular issue.

**Comment by sheluchin** [comment]
This would be useful.  vim-fugitive recently added the ability to [stage partial hunks](https://github.com/tpope/vim-fugitive/blob/02c26619c4d42d874216943eb9ad69cff371a109/doc/fugitive.txt#L235-L238) in its diff window.  Maybe tpope's implementation can be a source of inspiration here, or maybe some people will use it as a workaround. FWIW, I prefer a combination of both vim-gitgutter and vim-fugitive.

**Comment by airblade** [comment]
You can stage part of an additions-only hunk now.

For other kinds of hunk – lines removed, and lines added and removed – I envisage previewing the hunk, removing lines from the preview which you don't want to stage, then using the stage command in the preview window.

**Comment by airblade** [comment]
Now you can stage part of any hunk:

- preview the hunk (e.g. `\hp` or `:GitGutterPreviewHunk`)
- move to the preview window (`:wincmd P`)
- delete the lines you don't want to stage
- stage it (e.g. `\hs` or `:GitGutterStageHunk`).

I'm going to close this issue now – please open a new one if you encounter any bugs.
