### ISSUE TITLE
Got a lot of lines `Line indented incorrectly`

### ISSUE THREAD

**Issue by timhtheos** [airblade/vim-gitgutter#281]
I have not changed anything into the file, but I get

```
Line indented incorrectly; expected at least XX spaces, found X
```

![](https://www.evernote.com/l/AoyxA4ypYtZEiIfcmDsAVctRh9NPwGSbACcB/image.png)

Any idea why is this happening?

Thanks.

**Comment by airblade** [comment]
That message isn't coming from vim-gitgutter.  Also your `S>` signs aren't coming from vim-gitgutter unless you've configured those as your gitgutter signs.

Have you started using some kind of linter?  Maybe for PHP?  Perhaps via Syntastic?

**Comment by timhtheos** [comment]
@airblade Yeah, I'm using both syntastic and phpcs in my git pre-commit hook.  I'll try to isolate the problem.  Thanks for the direction.
