### ISSUE TITLE
Is this amount of lag normal?

### ISSUE THREAD

**Issue by her** [airblade/vim-gitgutter#283]
hey all 🙂

[![https://gyazo.com/db47153927d9aa94792f92bec0dc05cf](https://i.gyazo.com/db47153927d9aa94792f92bec0dc05cf.gif)](https://gyazo.com/db47153927d9aa94792f92bec0dc05cf)

I've tried using

`let g:gitgutter_realtime = 0
let g:gitgutter_eager = 0`

but this hasn't made any difference...

`set updatetime=1000` 

has made some difference, but I'm still getting a bit of lag(as you can see in the above gif) so is this amount of lag normal? is it possible to get gigutter running faster(instaneous)?

Currently using terminal vim version 7.4.922
on commit 51d9af

Thanks everyone love this plugin❣️

**Comment by airblade** [comment]
The lag is governed by `updatetime` so I suggest you reduce your `updatetime` to `500` or `250` or `100`.  You won't need to turn off `gitgutter_realtime` or `gitgutter_eager`.

`updatetime` is the amount of time vim waits after you stop typing before it fires the `CursorHold` or `CursorHoldI` autocommand events, which in turn trigger vim-gitgutter.  The lower your `updatetime` the faster vim-gitgutter will feel.

The other thing to bear in mind is that you might have other plugins triggering on `CursorHold` and `CursorHoldI`.  You can find out with:

```viml
:au CursorHold,CursorHoldI *
```

**Comment by her** [comment]
Okay nice! Thanks. I'll try this and let you know how it works. 

I guess I can do some of my own testing but j may as well just ask ya while I'm here, and I hope that's okay 😄

I have YouCompleteMe running, is updatetime a global setting in vim? Is this what you mean by it could effect other plugins? Off this line of thinking then would it be possible to only tweak the updatetime for gitgutter?

Anyway thank you so much for responding. I'll absolutely report back how this effects everything 😊

**Comment by airblade** [comment]
Yes, `updatetime` is a global setting; you can't have a different value for each plugin.  See `:help updatetime` for more info.

Figuring out the best value is a bit trial-and-error.  Just keeping reducing it until things start to go wrong ;)  100ms will feel instantaneous so there's probably no point going lower than that.

**Comment by her** [comment]
That's amazing! You've got me really excited about updatetime now lol

What's your own personal sweet spot setting for updatetime? 🍬⏱

**Comment by airblade** [comment]
I've had my `updatetime` at `750` for quite a while, but I set that when I was using an old version of Vim which had a bug causing visual glitches when the `updatetime` was too low.

However that bug was fixed in [Vim 7.4.427](https://github.com/vim/vim/releases/tag/v7.4.427) and I have since upgraded my Vim.  Our conversation has just prompted me to reduce `updatetime` to `100`.  I haven't given it much of a workout yet but so far it seems good – and it feels pretty much instantaneous.

**Comment by her** [comment]
hey @airblade 

so! I went ahead and set 'updatetime=100' but i'm getting some of the little glitches you wrote about in your doc 

[![https://gyazo.com/2b51ab68f1d2f9f8bf2d15666d9c55d0](https://i.gyazo.com/2b51ab68f1d2f9f8bf2d15666d9c55d0.gif)](https://gyazo.com/2b51ab68f1d2f9f8bf2d15666d9c55d0)

I'm going to of course play around with adjusting 'updatetime` further like you suggested but you're right that at `100` it's really buttery and smooth(though if `1000` is the fastest it can go that's also okay too!) 

maybe you have any suggested tricks to fix this little glitch? 

Thanks again for all the help  😊

**Comment by airblade** [comment]
That's great news!  Glad it's all so smooth :)
