### ISSUE TITLE
Add folding

### ISSUE THREAD

**Issue by albfan** [airblade/vim-gitgutter#286]
although `:GitGutterNextHunk` is handy, folding would be really nice, and stick to our beloved unified diff format.

Moreover, basic implementation exits

https://github.com/mhinz/vim-signify/commit/8c5ad74a7b0c292b4d3b545263dfdf0af0e90499

as usual, is based on a redir and parse from `sign place`. Man! when would it be a complete vim API available?

**Comment by airblade** [comment]
That's a nice idea.  I'll get to it when I have a spare moment...

**Comment by albfan** [comment]
I'm currently working on it

**Comment by albfan** [comment]
Here you can see `<Leader>hf` working

https://github.com/albfan/vim-signify/commit/cc91ae92e9240557e7ffb07c4b1b3716c58d789b

**Comment by ayushajain** [comment]
does anyone have a working branch of this yet?

**Comment by albfan** [comment]
Expect one PR on next couple of days.

**Comment by albfan** [comment]
Cool! Have to give it a try!
