### ISSUE TITLE
Make compatible with vim-signature

### ISSUE THREAD

**Issue by hallzy** [airblade/vim-gitgutter#289]
I have a plugin called vim-signature which displays the location of marks, but they show in the same column as the diff markers for this. it would be nice to have these two plugins compatible so that if both are used, they use different columns.

I am not too familiar with the left margin columns though so I am not sure if this is actually possible.

If this is not of interest to anyone, that is fine, but I would like to at least add it to my own setup, so if someone knows that it is possible to add another column in that left margin, it would be nice to know :)

**Comment by airblade** [comment]
I agree, it would be nice.  Unfortunately it's not possible: vim provides only one sign column and allows only one sign per line.  So it's not possible to run two plugins which both use the sign column without them treading on each other's toes.

**Comment by hallzy** [comment]
Okay thanks for the update anyways :)

I would also like to add something. I was looking around to see if anyone else came across this problem. It turns out that vim-signature actually has a support feature for gitgutter and signify.

See this commit I just made to my [.vimrc](https://github.com/hallzy/dotfiles/commit/c1361e53f99f74a1db0e40be3dd8ca389a41de83). That flag makes it so that the mark letter overwrites the gitgutter sign, but the mark letter inherits the colour... so if the mark is coloured red, we know it was on a line where the delete sign would be.

See the screenshots below:

This is with only changes, and no marks
![without marks](https://cloud.githubusercontent.com/assets/5404143/11644349/14103982-9d00-11e5-963e-1db76ff8b1cd.png)

This is with changes and marks (The same changes as above). Note that the mark on an added line is a dark green, while an unchanged line is a bright green.

![with marks](https://cloud.githubusercontent.com/assets/5404143/11644364/374f4b9a-9d00-11e5-9be4-2521bc73f629.png)

It is not exactly what I was hoping for, but it works so I can't complain. Just thought I would leave this here in case you or anyone else comes across it.

**Comment by airblade** [comment]
Good to know, thanks.
