### ISSUE TITLE
How do you update updatetime?

### ISSUE THREAD

**Issue by lanceh1412** [airblade/vim-gitgutter#290]
Hi, I wanted to change this updatetime value to 250ms as suggested but haven't got a clue how to do that. Have only just started using vim and it is a bit of a mystery to me. Thanks for any help.

**Comment by airblade** [comment]
Type `:set updatetime=250` or `:set ut=250` inside Vim, or add `set updatetime=250` (without the colon) to your vimrc configuration file.

**Comment by lanceh1412** [comment]
Thanks for the swift response.
