### ISSUE TITLE
Unknown sign: GitGutterDummy

### ISSUE THREAD

**Issue by igormoreno** [airblade/vim-gitgutter#294]
I'm getting the following error:

Error detected while processing function gitgutter#all..gitgutter#process_buffer..gitgutter#sign#update_signs..gitgutter#sign#add_dummy_sign:
E155: Unknown sign: GitGutterDummy

**Comment by airblade** [comment]
I've never seen this before.

E155 means the sign we are trying to place (GitGutterDummy) has been undefined.  The plugin doesn't undefine signs so I wonder if some other plugin you're using is undefining signs...

**Comment by dgrabla** [comment]
I'm getting also this same error. vim 7.4 with a bunch of plugins. What would you need to be able to debug or come up with a workaround?

**Comment by airblade** [comment]
Can you grep all your plugins for `sign undefine`?

**Comment by dgrabla** [comment]
It doesn't look like that's the issue

```
[~/.vim/bundle]> grep -nr 'sign undefine' .                                                                                                           
[~/.vim/bundle]>

[~/.vim/bundle]> grep -nr 'sign unplace' .                                                                                                            
./vim-gitgutter/test/helper.vim:6:  sign unplace *
./vim-gitgutter/autoload/gitgutter/sign.vim:59:    execute "sign unplace" s:dummy_sign_id "buffer=" . bufnr
./vim-gitgutter/autoload/gitgutter/sign.vim:95:          execute "sign unplace" gitgutter_signs[line_number].id
./vim-gitgutter/autoload/gitgutter/sign.vim:133:    execute "sign unplace * buffer=" . bufnr
./vim-gitgutter/autoload/gitgutter/sign.vim:139:      execute "sign unplace" id
./ctrlp.vim/autoload/ctrlp.vim:1179:			exe 'sign unplace' key 'buffer='.s:bufnr
./ctrlp.vim/autoload/ctrlp.vim:1771:		exe 'sign unplace' key 'buffer='.s:bufnr
./vim-signature/autoload/signature/sign.vim:171:  silent! execute 'sign unplace ' . l:id
./vim-signature/autoload/signature/sign.vim:192:    silent! execute 'sign unplace 666 buffer=' . bufnr('%')

```
                      `

**Comment by airblade** [comment]
Hmm, I don't understand how `sign unplace` could cause an E155 error.

I don't think vim-gitgutter on its own would cause the E155; I think it must be arising from (the interaction with) another plugin.

Are you able to give me steps to reproduce the problem?  I haven't been able to reproduce it here.

**Comment by dgrabla** [comment]
I updated and clean all packages installed with NeoBundle: Now it all works perfectly. Thanks!

**Comment by airblade** [comment]
Good news!
