### ISSUE TITLE
Please add to readme - how to install without Pathogen and Vundle

### ISSUE THREAD

**Issue by vitaly-zdanevich** [airblade/vim-gitgutter#299]

**Comment by tomswartz07** [comment]
What method are you trying to use?

If you don't use any plugin manager, you can simply copy the files to their matching folders in your ~/.vim path, creating them if necessary.

The most basic method would be as follows:
```
git clone ...
cp -r * ~/.vim/.
```

**Comment by vitaly-zdanevich** [comment]
Today I first tried to install plugin to vi, I already installed Pathogen and all good but newcomers may not understands for what they need plugin manager if they want only install one plugin. I think that you can write few lines in readme about that.

**Comment by airblade** [comment]
Done in 90c558b.
