### ISSUE TITLE
neovim async

### ISSUE THREAD

**Issue by nhooyr** [airblade/vim-gitgutter#300]
It'd be really nice to have neovim integration. I find that my cursor flashes when its updating. It'd be a major performance boost, and I mean **MAJOR** performance boost.

**Comment by airblade** [comment]
I'm working on this...

**Comment by airblade** [comment]
Please could you try the `nvim` branch and let me know if it works for you?

**Comment by nhooyr** [comment]
Will do. At school right now so I'll give you an update at lunch.

**Comment by nhooyr** [comment]
@airblade looks good, i'll report any bugs.

**Comment by airblade** [comment]
Thanks for letting me know.  This is now in master (as of 18b7836).

**Comment by amadeus** [comment]
Any plans to add async support for Vim 8? I believe the APIs in Vim 7.4 on the latest patches are pretty stable and usable at this point?

**Comment by airblade** [comment]
@amadeus It's the next big feature on my list (#326).
