### ISSUE TITLE
Slow Startup in Neovim

### ISSUE THREAD

**Issue by hew** [airblade/vim-gitgutter#301]
I was having some noticeably slow startup times with my Neovim build (0.1.1) and through trail and error I was able to track the problem down to vim-gitgutter. 

I apologize as I don't know Vim/Neovim all that well, and don't have any logs. My approach to testing was to install my plugins one-by-one until I was able to pinpoint the cause of the lag. The plugin in question was vim-gitgutter.

I'm just posting this in case anyone is having a similar problem.

**Comment by airblade** [comment]
Please could you profile your neovim's startup time, as described [here](https://github.com/airblade/vim-gitgutter/wiki/How-to-profile-vim-gitgutter)?

**Comment by daenney** [comment]
I have the same problem, whenever I open, switch modes or write a file that's in a directory vim-gutter causes at least a second of slow down. Disabling the plugin returns vim to its usually snappy self when dealing with these files.

I gisted the `gitgutter.log` here: https://gist.github.com/daenney/4bcd9ebecfe0637f56ab

**Comment by airblade** [comment]
Thanks for the log.  The key line is [this one](https://gist.github.com/daenney/4bcd9ebecfe0637f56ab#file-gitgutter-log-L1605);

```
    3              3.763088     silent let output = (a:0 == 0) ? system(a:cmd) : system(a:cmd, a:1)
```

It's telling us Vim is taking over a second to execute the builtin `system()` function.  Which is surprising...

**Comment by airblade** [comment]
What does `:GitGutterDebug` give you?

**Comment by daenney** [comment]
```
NVIM 0.1.1 (compiled Dec 20 2015 22:55:38)
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/build/config -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/src -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/build/src/nvim/auto -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/build/include

git version 2.7.0

updatetime=4000
shell=/usr/local/bin/fish
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

**Comment by daenney** [comment]
Quick q, does the `#system` thing cause it to spawn a (sub)shell?

**Comment by airblade** [comment]
Probably, I'm not sure.

BTW you can set your `updatetime` to something like `250` for snappy realtime updating (once the `system()` slowness is resolved)...

**Comment by daenney** [comment]
Alright, I tried disabling the few things I thought might be related to my shell initialisation but that doesn't seem to have any noticeable effect.

```

NVIM 0.1.1 (compiled Dec 20 2015 22:55:38)
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/build/config -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/src -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/build/src/nvim/auto -I/tmp/neovim20151220-37487-xntgdw/neovim-0.1.1/build/include

git version 2.7.0

updatetime=250
shell=/usr/local/bin/fish
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

**Comment by daenney** [comment]
I tried a `:echo system('ls')`, that's pretty slow too so it might have to do with something in our local environment and not the plugin. It just happens to use `system` which causes the issue.

**Comment by airblade** [comment]
I just installed neovim 0.1.1 and vim-gitgutter seems to work normally.  There's no 1s delay each time the plugin runs.

Oddly, though, it doesn't do anything when I set `shell` to fish.  It's supposed to work with fish...

**Comment by daenney** [comment]
I grabbed https://github.com/nathan-hoad/differ for now which uses Neovim's async job control. I'm not entirely sure what's going on just yet but I'll dig into it.

**Comment by airblade** [comment]
I've started working on this.

**Comment by airblade** [comment]
Please could you try the `nvim` branch and let me know if it works for you?

**Comment by daenney** [comment]
This seems to have stopped the plugin for working at all for me. `git diff` reports differences but even when I explicitly `:GitGutterEnable` I don't see anything when writing a file I just changed.

**Comment by airblade** [comment]
I forgot you use fish.  Can you quickly try setting your shell to bash?

vim-gitgutter supports fish but the neovim job hard-codes bash at the moment...

**Comment by daenney** [comment]
Ah check. Yap, that seems to work!

**Comment by airblade** [comment]
Thanks for letting me know.  This is now in master (as of 18b7836).

**Comment by daenney** [comment]
What's merged on master doesn't seem to work with fish though.

**Comment by airblade** [comment]
I tested it with fish as follows and it works for me:

```sh
$ nvim --cmd "set shell=/usr/local/bin/fish" somefile.txt
```

I have fish v2.2.0.

**Comment by airblade** [comment]
Alternatively, if you don't need vim's shell to be fish, you could add `set shell=/bin/bash` to your vimrc.

**Comment by daenney** [comment]
Mmm curious. I'll take a look at what's happening in my environment. Thanks!
