### ISSUE TITLE
files opened from command line are 'changed' by default

### ISSUE THREAD

**Issue by SukumarMehta** [airblade/vim-gitgutter#302]
Loading vim-gitgutter (verified) causes vim to think that whatever file you loaded has been changed. 
i.e.
`bash$ vim file.txt`
in vim - after no change
`:q`
shows error:
`E37: No write since last change (add ! to override)`

it forces you to use 
`:q!`

This is only the case for the base file - if i load another file while in vim this doesn't happen

**Comment by airblade** [comment]
I can't reproduce this.  Are you using the latest commit?  Is `file.txt` tracked by git or not?  What does `:GitGutterDebug` produce?

**Comment by SukumarMehta** [comment]
So I don't have http access directly to the host - so I used a tarball from the master branch (pretty recently - not sure how to find the last commit in this scenario)

Sorry - not sure about your `file.txt` question - there is no file.txt in any git project i'm working on - 
But - this issue happens regardless of the file i open at vim startup - meaning regardless of being a git-tracked file

here's the :GitGutterDebug output

```
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Feb  4 2012 09:50:29)
Included patches: 1-108
Compiled by 'http://www.opensuse.org/'

git version 2.7.0

updatetime=1
shell=/bin/bash
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape [n/a]
shellxquote=
```

**Comment by airblade** [comment]
I'm not sure how to find the last commit from a tarball either.

The `file.txt` was just a placeholder for whatever file you're editing, not a specific file.  Sorry, I should have written something like `<FILE>`.

Anyway, I'm not sure the plugin will work properly with Vim 7.2.  That's seriously old.  I recommend upgrading if you can.

Also, an `updatetime` of 1ms will probably cause problems: it's probably too fast for anything hooked into `CursorMoved(I)` to finish in time.  I have `updatetime` set to 100ms and that works well for me.

**Comment by SukumarMehta** [comment]
Upgrading to vim 7.4 Fixed the problem - thanks!

I'll look into changing updatetime
