### ISSUE TITLE
process_buffer exits ctrl-x mode

### ISSUE THREAD

**Issue by taylor-peterson** [airblade/vim-gitgutter#305]
The autocommand that calls gitgutter#process_buffer(bufnr(''), 1) when the CursorHoldI event is triggered exits the ctrl-x sub-mode. If updatetime is set to the recommended value, this makes it very difficult to use completion.

Repro-Steps:
1. enable vim-gitgutter
2. :set updatetime=1000 (to better see what's going on)
3. :set showmode
4. Enter insert mode -> status line displays that you are in insert mode
5. Hit ctrl-x ->status line displays that you are in ctrl-x mode
6. updatetime later, CursorHoldI is triggered, calling process_buffer and you are dropped out of ctrl-x mode back into insert mode

Desired Behavior:
You remain in ctrl-x mode after the process_buffer call.

**Comment by airblade** [comment]
I have never noticed this before.  I don't know how to detect the i_CTRL-X submode so I have asked on [vim_use](https://groups.google.com/d/topic/vim_use/EsISt5b-tnM/discussion).

**Comment by TKr** [comment]
Same issue

**Comment by airblade** [comment]
No reply on vim_use so I have asked on [vim_dev](https://groups.google.com/d/msg/vim_dev/f6dei3rD86s/5N1N8jbZAAAJ).

**Comment by airblade** [comment]
This is a vim problem: I can reproduce it without vim-gitgutter.

1. Start vim with:

    `vim -u NONE --cmd 'set updatetime=1000' --cmd 'set showmode' --cmd 'autocmd CursorHoldI * 1'`
2. Type `i` to enter insert mode.
3. Type `CTRL-x` to enter the insertion completion submode.
4. Expected: vim stays in insertion completion submode.  Actual: after 1 second the mode changes back to insert mode.

I'll leave this issue open for now and wait to see what happens on vim_dev.

**Comment by airblade** [comment]
This is fixed in [Vim 7.4.1758](https://github.com/vim/vim/releases/tag/v7.4.1758).
