### ISSUE TITLE
Why aren't any signs showing at all?

### ISSUE THREAD

**Issue by hholst80** [airblade/vim-gitgutter#308]
This section in the readme should be expanded to answer the question if the plugin works at all in Windows and if so how it can be made to work.

**Comment by airblade** [comment]
Is it not working for you?

**Comment by hholst80** [comment]
No the signs are not showing up at all. I tried to set shell to the bash.exe included in GIT. 

1. Copy GIT installation from C:\Program Files (x86)\Git to C:\GIT
2. Set shell=C:\GIT\bin\bash.exe
3. Set shellopts=-c
4. Run !ls and verify that it works.
5. Run GitGutter by opening a file in a GIT repository. Does not work.

Transscript of error (translated by hand from Swedish vim output):

gitgutter#process_buffer..gitgutter#diff#run_diff..gitgutter#utility#system: 
line 10:
E484: Cannot open file C:/Users/hholst/AppData/Local/Temp/VIo17ED.tmp

**Comment by hholst80** [comment]
I don't know if the problem is cmd.exe not being POSIX or not. The help about setting shell=/bin/bash seems like a very UNIX specific advice though.

**Comment by airblade** [comment]
Thanks for the extra information.  E484 means that Vim is failing to run the plugin's shell commands via `system()`.  Vim jumps through various hoops to try to run external commands on different platforms, but still gets it wrong sometimes.

Does it work without steps 2 and 3?

Does `:system("git --status")` work?

What's the value of `shell` before you set it?

What does `:GitGutterDebug` produce?

**Comment by hholst80** [comment]
~~~~
set shell?
shell=C:\windows\system32\cmd.exe
~~~~

~~~~
C:\Users\hholst>git --status
Unknown option: --status
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

C:\Users\hholst>
~~~~


~~~~

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 10 2013 14:38:33)
MS-Windows 32-bitars GUI-version med OLE-stöd
Kompilerad av mool@tororo

git version 1.9.0.msysgit.0

updatetime=4000
shell=C:\windows\system32\cmd.exe
shellcmdflag=/c
shellpipe=>%s 2>&1
shellquote=
shellredir=>%s 2>&1
shellslash=0
shelltemp=1
shelltype [n/a]
shellxescape="&|<>()@^
shellxquote=(
~~~~

**Comment by airblade** [comment]
What does your `shellopts=-c` do?

The `--status` was a type.  Please can you try this in Vim: `:system("git status")`?

**Comment by hholst80** [comment]
E492: Not an editor command: system("git status")

^^ translated from Swedish so might not match 1:1 with the English error message.

-c is an argument to bash to execute the arguments in the new shell. I guess it is used much like /c is used in cmd.exe

~~~~
C:\Users\hholst\vimfiles\bundle\vim-gitgutter>git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   doc/gitgutter.txt

no changes added to commit (use "git add" and/or "git commit -a")

C:\Users\hholst\vimfiles\bundle\vim-gitgutter>
~~~~

**Comment by airblade** [comment]
Sorry again, I meant `:echo system("git status")`.  I'm trying to establish the point where the external commands stop working.

**Comment by hholst80** [comment]
That works. After a `:cd ~/vimfiles/bundle/vim-gitgutter` that gives the same result as above.

**Comment by airblade** [comment]
OK, and you still get the E484 error?

By the way, once we have fixed whatever is wrong, I suggest setting your `updatetime` to `250` or similar.

**Comment by hholst80** [comment]
Yes with cmd.exe as shell I get nothing, and with `shell=bash.exe` (and `shellcmdopts=-c`) I get the same E484.

**Comment by hholst80** [comment]
I can reproduce the "nothing happens" with bash by setting:
~~~~
set shell=bash
set shellcmdflag=-c
set shellxquote=\"
~~~~
`C:\Program Files (x86)\Git\bin\` is part of my %PATH%.

**Comment by airblade** [comment]
There are two problems: the lower level E484 which means can't talk to the shell; and the lack of signs.

I think it's best to leave the `shell` and related options to Vim's defaults; they ought to work and in fact you don't get E484 when using them.  In other words your Vim can talk to the shell with its defaults.

So that leaves the higher level problem of no signs.  To debug this, please could you:

- Add `echom diff` immediately after [line 22](https://github.com/airblade/vim-gitgutter/blob/8b046bd5211d12629504cbd336e1ba350ebea54a/autoload/gitgutter.vim#L22).
- Add `echom `diff failed` immediately after [line 27](https://github.com/airblade/vim-gitgutter/blob/8b046bd5211d12629504cbd336e1ba350ebea54a/autoload/gitgutter.vim#L27).

You can inspect the output with `:messages`.  These two lines will tell you whether the plugin is getting a diff back from the shell or whether the diff is failing.

Let me know and we'll take it from there...

I noticed there are more recent version of both Vim for Windows ([gvim74-1024.exe](http://www.vim.org/download.php)) and git for Windows ([v2.7.1(2)](https://git-for-windows.github.io)).  I don't know if you feel like upgrading to see if that helps...

**Comment by hholst80** [comment]
~~~~
Error was detected when processing function gitgutter#process_buffer:
line 15:
E121: Undefined variable: diff
E15: Invalid expression: diff failed
~~~~

I'll try and get a newer version of gvim for windows!

**Comment by airblade** [comment]
15 lines into the `process_buffer` function is a weird place to fail that way.  It's inside the `catch` block where `echom 'diff failed'` should just output a string; there's no reference to a `diff` variable.  Please could you check the line?

**Comment by hholst80** [comment]
Upgrading to the suggested version of vim above solved the problem. I only had to add a custom grep command
~~~~
let g:gitgutter_grep_command = 'grep -e'
~~~~
because `--colors=never` isn't supported in the grep.exe bundled with git 1.9. If I upgrade also GIT that might be fixed. I'll try.

**Comment by hholst80** [comment]
I typed exactly as you wrote, 
~~~~
Add `echom diff` immediately after line 22.
~~~~
should it be something else?

**Comment by airblade** [comment]
> I typed exactly as you wrote...

I believe you; the thing is the line number in the error message is the 15th line of the function but the file's line number I mentioned, line 22, is the 8th line of the function.  Which makes me wonder whether you're using the latest version of vim-gitgutter?

**Comment by airblade** [comment]
Regarding the grep command: great!  Making progress...

**Comment by hholst80** [comment]
I realized that I might have an old version. Git submodules are a bit complicated for me still... I'll make sure I have the latest version of GitGutter installed and try with the old Vim version I have on Windows back home. To be continued... :-)

**Comment by hholst80** [comment]
This is really embarrassing, but after making sure I had the latest version of GitGutter I could not reproduce the problem with markers not being visible. Thanks for helping me look into this in detail @airblade ! The version was not too old (I just installed this a few days ago). 

One thing I will look into is having "grep.exe" not in %PATH% because that seems to be bad practice (There is a big fat warning displayed by the Git installer about putting all the GNU utils in the path as they might conflict with the existing Windows `find` and `sort` tools.)

**Comment by airblade** [comment]
Glad to hear the problem has gone away :)

The plugin will work fine if grep isn't available.  It uses grep to filter git's diffs for the hunk headers, but if grep is unavailable it'll just do it in vimscript instead.

**Comment by desnudopenguino** [comment]
I've run into this issue on my openbsd box. It isn't even showing the gutter beside my numbers anymore.  I checked the things in the Readme as well to make sure it isn't one of those issues. I even removed all other plugins to make sure that it isn't one of those either. Any thoughts?

**Comment by airblade** [comment]
@desnudopenguino Is gitgutter listed in `:scriptnames`?  What does `:GitGutterDebug` produce?  What version of Vim are you running?  Are you using the latest revision of gitgutter?

**Comment by desnudopenguino** [comment]
It appears in the list of :scriptnames:
`.vim/bundle/git-gutter/plugin/gitgutter.vim
.vim/bundle/git-gutter/autoload/gitgutter/highlight.vim
.vim/bundle/git-gutter/autoload/gitgutter/gitgutter.vim
.vim/bundle/git-gutter/autoload/gitgutter/gitgutter/utility.vim
.vim/bundle/git-gutter/autoload/gitgutter/gitgutter/diff.vim
.vim/bundle/git-gutter/autoload/gitgutter/gitgutter/hunk.vim
.vim/bundle/git-gutter/autoload/gitgutter/gitgutter/sign.vim`

I'm using vim version vim version 7.4 and the latest version of gitgutter.

It was working before, but just recently stopped. I am always tweaking my vimrc, along with other dotfiles, and am constantly reloading them, so I don't remember the exact date/time/change that caused the issue, but I had gitgutter working in the past with a similar .vimrc to the one I have now.

**Comment by desnudopenguino** [comment]
It appears in :scriptnames.  
:GitGutterDebug shows the following:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  8 2015 09:49:20)
Included patches: 1-769                           
Compiled by naddy@amd64.ports.openbsd.org

git version 2.4.6                                 

updatetime=4000                                   
shell=/usr/local/bin/bash
shellcmdflag=-c                                   
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]                                   
shellxescape=
shellxquote=

I have vim version 7.4 and the latest version of gitgutter.

I had gitgutter working in the past, but at some point in the past month it stopped working. I was pretty busy and didn't notice until recently when I was tweaking my dotfiles.

**Comment by airblade** [comment]
This might be due to grep; The plugin changed how it calls grep slightly...

**Comment by desnudopenguino** [comment]
Ah. any thoughts/tests/work-arounds you might suggest?

**Comment by airblade** [comment]
We need `grep` not to produce colourful output.  Before these [commits](https://github.com/airblade/vim-gitgutter/compare/4510e9b...e884a0e) the plugin tried to detect whether grep would produce colours, and switch it off, but since then it's up to the user.

The plugin defaults to `grep --color=never -e`; if your version of grep doesn't support the color flag you'll need to set `g:gitgutter_grep_command` appropriately.

**Comment by desnudopenguino** [comment]
cool. that. fixed it. Added the line below to my .vimrc. 
`let g:gitgutter_grep_command='grep -e'`

Thanks!

**Comment by airblade** [comment]
@desnudopenguino Good news.  I've added a note about this to the README (0af9f2a).

**Comment by airblade** [comment]
@hholst80 Is everything working for you now?

**Comment by Meelo** [comment]
Hmm, the gitgutter seems to stop marking lines if the source file is big enough. In my case the source file has 2500+ lines of code and jumping to git changes no longer work.

gitgutter_debug:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 18 2015 06:18:50)                 
Included patches: 1-963                                                            
Modified by pkg-vim-maintainers@lists.alioth.debian.org                            
                                                                                   
git version 2.7.0                                                                  
                                                                                   
shell=/bin/bash                                                                    
shellcmdflag=-c                                                                    
shellpipe=2>&1| tee                                                                
shellquote=                                                                        
shellredir=>%s 2>&1                                                                
shellslash [n/a]                                                                   
shelltemp=1                                                                        
shelltype [n/a]                                                                    
shellxescape=                                                                      
shellxquote=                                                                       
```
