### ISSUE TITLE
Diff against last commit (instead of staging area)

### ISSUE THREAD

**Issue by IngoHeimbach** [airblade/vim-gitgutter#309]
I've tried to add the following option to my `.vimrc`:

```vim
let g:gitgutter_diff_args = 'HEAD'
```

As a result, vim-gutter shows the git diff against the last commit independently from any changes that have already been added to the staging area. That works nicely when saving a file but unfortunately the sign column disappears while typing in insert mode so the realtime support is broken with the additional diff argument. After a short search I found the following section in the plugin code:

```vim
let cmd .= 'git -c "diff.autorefreshindex=0" diff --no-ext-diff --no-color -U0 '.g:gitgutter_diff_args.' -- '
if a:realtime
  let cmd .= blob_file.' '.buff_file
else
  let cmd .= gitgutter#utility#shellescape(gitgutter#utility#filename())
endif
``` 

So in realtime mode, two files are used to create the diff and according to the git diff help page, no commit reference (`HEAD`) can be passed to the command in that case. As a result, the command execution fails and no signs are shown in realtime mode.
Would it be possible to add support for a diff against the last commit?

**Comment by airblade** [comment]
Do you get what you want if you change [this line](https://github.com/airblade/vim-gitgutter/blob/8b046bd5211d12629504cbd336e1ba350ebea54a/autoload/gitgutter/diff.vim#L66):

```viml
let blob_name = ':'.gitgutter#utility#shellescape(gitgutter#utility#file_relative_to_repo_root())
```

– to this:

```viml
let blob_name = 'HEAD:'.gitgutter#utility#shellescape(gitgutter#utility#file_relative_to_repo_root())
```

**Comment by IngoHeimbach** [comment]
Thanks a lot, I just replaced the line and it works perfectly. :)

**Comment by airblade** [comment]
Ausgezeichnet.  I'll add a new config option for specifying which revision to diff against.

**Comment by IngoHeimbach** [comment]
Great, thanks!

**Comment by sanscore** [comment]
To expand on this request, it would be nice for GitGutter to have the ability show diffs against arbitrary commits; not just HEAD.

For my current use case, I want to review entire files that have been modified on a remote branch. I could use 'git difftool', but that adds too much distraction, vim automatically folds unchanged areas, git gives the files from the repository rather than then getting the current file from the working director, etc.

I expect that is the intent behind the change described in @airblade 's previous comment, but I haven't seen the change yet so I figured I should add my two-cents.

**Comment by IngoHeimbach** [comment]
I've tested the new option
```vim
let g:gitgutter_diff_base = 'HEAD'
```
and it works well on file save. But when typing, the sign column disappears if the real time mode is enabled.

**Comment by airblade** [comment]
That's odd: it works for me.  And 75eee3e only does what we tried manually.

Please could you upgrade to the latest version, do `:let g:gitgutter_log=1`, make the error occur, then post the contents of `gitgutter.log` in your vim-gitgutter directory?  Then we can see the exact commands that fail.

**Comment by IngoHeimbach** [comment]
Today, I did some tests and even tried the commits from `git reflog` but now it is working as expected. If the problem occurs again, I will do some more testing...

**Comment by airblade** [comment]
Thanks for letting me know.

**Comment by pkalever** [comment]
Thumbs up to the Idea!

**Comment by pkalever** [comment]
Not sure if this is broken on latest master.
I don't think "let g:gitgutter_diff_base = 'HEAD'" is working, at least for me.

using VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  8 2016 14:13:25)
