### ISSUE TITLE
omni complete exits abnormal under NeoVim

### ISSUE THREAD

**Issue by lvht** [airblade/vim-gitgutter#310]
If I edit some file under git, and use omnifunc to open a completion list, NeoVim will automatically use the first item and exit the completion if and only if the item has an info attribute which will let vim open an preview window to display.

I think this commit 18b7836168ae9956abebaa6046980b16687dfb7f is the bad boy. 

By the way, this problem will disappear if I add `let g:gitgutter_eager = 0` to my vim config.

---
How to reappear?

```
function OmniDemo(findstart, base)
       if a:findstart > 0
              return 0
       endif
       return [{'word':'word1', 'info':'info1'},{'word':'word2', 'info':'info2'}]
endfunction
set omnifunc=OmniDemo
```
Edit any file under git, use ctrl_x ctrl_o to complete, and you will only get the word1.

**Comment by airblade** [comment]
Hmm, #305 also relates to completion.  I wonder if they are related.

**Comment by chemzqm** [comment]
I just figured it out, neovim would trigger `BufEnter` for the preview window,  and it would has some problem with the function `gitgutter#process_buffer`, I got a simple work around, change the line 172 at `plugin/gitgutter.vim` to
```
\ elseif !empty(bufname(expand('abuf')))|
```
so that the function process_buffer won't be called when enter the preview window.

**Comment by Shougo** [comment]
This is neovim bug?  If so, you should create new issue in neovim.

**Comment by Shougo** [comment]
I think it is not neovim/Vim bug.  It is feature.
Because, to create preview window, Vim/neovim creates new preview window buffer `[preview]`.  BufEnter is occurred.
vim-gitgutter should ignore BufEnter in the preview window.

**Comment by chemzqm** [comment]
@Shougo you're right, both vim and neovim triggered the BufEnter event, but neovim can't works with function `gitgutter#process_buffer`. The buffer trigger BufEnter is not the preview buffer, but the current buffer, and I found we can check `pumvisible` to avoid the function call.
