### ISSUE TITLE
Need command to select entire hunk for a vim operation

### ISSUE THREAD

**Issue by mnebuerquo** [airblade/vim-gitgutter#312]
For my changes to a legacy codebase, I would like to make any hunks I commit match a set of rules for things like whitespace, even if the surrounding code does not follow these rules.

What I want to do is select a hunk before I stage it, and run some cleanups on it, such as replace leading spaces with tabs, remove trailing whitespace, etc. There might even be some other formatting changes to this code, given specific rules I can code into vim.

I might even want to put these into a `autocmd BufWritePre`.

What I'd like to be able to do is bind a key to select next hunk, or select all hunks. Then do something with that selection (yank, indent, clean whitespace, etc.) as if I had used visual mode to select the lines where the gutter shows a symbol.

This might look like the other bindings, as in this completely hypothetical example:
```
nmap ]v <Plug>GitGutterSelectNextHunk
nmap [v <Plug>GitGutterSelectPrevHunk
nmap ]a <Plug>GitGutterSelectAllHunks
```
The documentation in the README.mkd doesn't suggest this is available currently. My guess is that this should be feasible, since the gitgutter has marked or highlighted the lines already, and updates every so often. I just want to be able to bind a keystroke to select those lines.

Thanks!

**Comment by airblade** [comment]
Sorry for the delay; I've been out of action for a couple of weeks.

I like this idea and I'll try to get to it soon – lots of catching up to do though...

**Comment by corence** [comment]
+1 for this idea.

For me, the most prominent use-case is to clear trailing whitespace from all modified lines.

I don't think Vim will do non-contiguous Visual selections though, so I'm not clear how GitGutterSelectAllHunks would work.

Possibly it might be implemented using a new symbol argument for `:s` like this:
```
:~s/\s*$//
```
or making a new command similar to `:g` or `:%`
```
:GitGutterDoSomethingOnAllModifiedLines/normal $gElD
```

but I don't know what's possible in Vim hacking.

**Comment by airblade** [comment]
There is a hunk text object as of e48824c.

@mnebuerquo You can write a function that cleans up your code, map an operator to that function, then use it with the text object.  For example:

```viml
function! s:CleanUp(type)   
  let [first, last] = [line("'["), line("']")]
  for lnum in range(first, last)
    let line = getline(lnum)

    " clean up the text, e.g.:
    let line = substitute(line, '\s\+$', '', '')

    call setline(lnum, line)
  endfor
endfunction

nmap <silent> <Leader>x :set opfunc=<SID>CleanUp<CR>g@

```

Then place your cursor in a hunk and type `\xic` (assuming a leader of `\`).

Alternatively you could place your cursor in a hunk, type `vic` to select it, then `:CleanUp()`.

As @corence says, Vim doesn't support non-contiguous selections.  However you could write a command like @corence's last example:

```viml
function! GlobalChangedLines(ex_cmd)
  for hunk in GitGutterGetHunks()
    for lnum in range(hunk[2], hunk[2]+hunk[3]-1)
      let cursor = getcurpos()
      silent! execute lnum.a:ex_cmd
      call setpos('.', cursor)
    endfor
  endfor
endfunction

command -nargs=1 Glines call GlobalChangedLines(<q-args>)
```

You would call it like this: `:Glines s/\s\+$//`.
