### ISSUE TITLE
GitGutterStageHunk silent fail

### ISSUE THREAD

**Issue by hholst80** [airblade/vim-gitgutter#313]
I have one repo where GitGutterStageHunk works on one file, but on another it does not work. It seems to execute but does nothing. How can I debug this?

**Comment by a-x-** [comment]
:+1: 
`GitGutterStageHunk` not work for me at all :(

**Comment by airblade** [comment]
When it stops working, can you still jump between hunks, including the one you want to stage, with `[c` and `]c`?

Are you running the latest version of this code?

You could debug this by adding `echom diff_for_hunk` after [this line](https://github.com/airblade/vim-gitgutter/blob/0af9f2a3ab029054d279f69364351e95e107008a/autoload/gitgutter.vim#L193).

**Comment by a-x-** [comment]
> When it stops working, can you still jump between hunks
yep

**Comment by a-x-** [comment]
debug:
```
diff --git images/blocks-deskpad/sizes/sizes.bemhtml.js images/blocks-deskpad/sizes/sizes.bemhtml.js^@index f7e7418..e1f6630 100644^@--- images/blocks-deskpad
/sizes/sizes.bemhtml.js^@+++ images/blocks-deskpad/sizes/sizes.bemhtml.js^@@@ -1,0 +2 @@ block('sizes')(^@+^@
```

**Comment by a-x-** [comment]
also, i have `git config diff.noprefix true`

**Comment by airblade** [comment]
When you say switching to false isn't a solution, do you mean (a) it solves the problem but you don't want to do it for other reasons, or (b) it doesn't solve the problem?  I'm guessing (b)...

If you apply the debug output by hand, does it work?  I.e. save the debug output to a file (replacing the `^@` with new lines), then do `git apply --cached --unidiff-zero - <PATCH FILE>`.

**Comment by a-x-** [comment]
b) and yeah, i don't want do it at all.

**Comment by airblade** [comment]
Next time the hunk-staging fails, please could you save the debug output to a file (replacing the `^@` with new lines), then do `git apply --cached --unidiff-zero - <PATCH FILE>` and let me know what happens?

**Comment by airblade** [comment]
I've added logging in 4bed1da so next time the staging fails, please do `:let g:gitgutter_log=1`, try to stage the hunk, then post the `gitgutter.log` file from where vim-gitgutter is installed.

In the meantime, it's been about 6 weeks and I haven't heard anything further, so I'm going to assume the problem's gone away.  Please let me know if not.

**Comment by tarmo** [comment]
Hi, I also had a problem with hunk staging not working and also happen to have `diff.noprefix=true`. I found it could be fixed in vim-gitgutter like this:

```diff
--- autoload/gitgutter/diff.vim
+++ autoload/gitgutter/diff.vim
@@ -94,7 +94,7 @@ function! gitgutter#diff#run_diff(realtime, preserve_full_diff)
   if s:c_flag
     let cmd .= ' -c "diff.autorefreshindex=0"'
   endif
-  let cmd .= ' diff --no-ext-diff --no-color -U0 '.g:gitgutter_diff_args.' '
+  let cmd .= ' diff --src-prefix=a/ --dst-prefix=b/ --no-ext-diff --no-color -U0 '.g:gitgutter_diff_args.' '

   if a:realtime
     let cmd .= ' -- '.blob_file.' '.buff_file
```

**Comment by airblade** [comment]
@tarmo Thanks for that.  You could get the same effect with:

```viml
let g:gitgutter_diff_args = '--src-prefix=a/ --dst-prefix=b/'
```

And then you wouldn't need to patch the code.

**Comment by airblade** [comment]
I've just pushed 80375e6 which tells git to use prefixes.  Hopefully that fixes this problem.

**Comment by tarmo** [comment]
@airblade Thank you
