### ISSUE TITLE
GitGutter does not work

### ISSUE THREAD

**Issue by bangn** [airblade/vim-gitgutter#316]
I am using VIM 7.4 with MacVim.
I have gone through this issue and follow your debugging instructions.
Everything seems right when using your suggested commands in https://github.com/airblade/vim-gitgutter/issues/6 , however somehow GitGutter does not work in my machine.
FYI: I used Mac OS El Capital, Vim 7.4.

Running `:call GitGutter()` will give following error `Unknown function: GitGutter()`

**Comment by airblade** [comment]
What does `:GitGutterDebug` give you?

**Comment by bangn** [comment]
```

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 16 2015 23:42:56)
MacOS X (unix) version
Included patches: 1-936

git version 2.5.1

grep (BSD grep) 2.5.1-FreeBSD
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]	[-e pattern] [-f file] [--binary-files=value] [--color=when]	[--context[=num]] [--directories=action] [--label] [--line-buffered]	[--null] [pattern] [file ...]

updatetime=4000
shell=/bin/zsh
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

**Comment by airblade** [comment]
Thanks for that.

I've just re-read your original question; to run vim-gitgutter manually you need `:GitGutter`, not `:call GitGutter()`.  `GitGutter` is a command not a function.

Also if you want the plugin to run in realtime you should reduce your `updatetime` to, say, `200`.

**Comment by bangn** [comment]
Yeah, when I ran `:GitGutter` it did not show any error. However, it still does not work though.
I ended up using `vim-signify` instead
ANW, thank you for your time
