### ISSUE TITLE
Add option to disable async diff

### ISSUE THREAD

**Issue by HerringtonDarkholme** [airblade/vim-gitgutter#318]
I use gitgutter and [tsuquyomi](https://github.com/Quramy/tsuquyomi) in neovim.
However, tsuquyomi usually [hangs on save](https://github.com/Quramy/tsuquyomi/issues/60).
 After investigation, I found gitgutter's job control and tsuquyomi's vimproc will conflict.

Using `git bisect`, the first "bad" commit seems to be 18b7836168ae9956abebaa6046980b16687dfb7f, where gitgutter is updated to add async functionalilty. The minimal setup can be found [here](https://github.com/Quramy/tsuquyomi/issues/60).

I have not dig deeper in it. But a quick fix will be adding an option to disable async diff, I think.
Would be happy if you can take a consideration for this, thank you.

**Comment by airblade** [comment]
I'm happy to add an option to disable async diffs.

However I believe vim-gitgutter uses neovim's async feature correctly so the cause of the problem would be elsewhere – perhaps neovim's async doesn't work properly with multiple plugins trying to use it, or with vimproc.  I don't know.
