### ISSUE TITLE
Refresh on focus broken by commit 18b783 for NeoVim

### ISSUE THREAD

**Issue by hoschi** [airblade/vim-gitgutter#320]
After updating the gutter doesn't update anymore when nvim receives focus. BUT only when I loaded my CtrlSpace session. When I open a file via nvim args, it works. I file this issue not in CtrlSpace because GitGutter works fine, till commit 18b783 and other async plugins like NeoMake also work fine with CtrlSpace. `GitGutterAll` also stopped working and don't refresh all buffers anymore when called, I  hope this helps.

**Comment by airblade** [comment]
Thanks for letting me know.

- What commit of CtrlSpace are you at?
- Do you have any specific CtrlSpace configuration or do you use the defaults?
- What version of nvim are you on?

**Comment by hoschi** [comment]
* git gutter commit: e884a0e
* CtrlSpace commit: f7987e4
* nvim version: 0.1.2-398-g8f22031

CtrlSpace config:
```
"--------------------
"ctrl space
"--------------------
hi CtrlSpaceSelected term=reverse ctermfg=187  ctermbg=23  cterm=bold
hi CtrlSpaceNormal   term=NONE    ctermfg=244  ctermbg=232 cterm=NONE
hi CtrlSpaceFound    ctermfg=220  ctermbg=NONE cterm=bold

let g:CtrlSpaceSetDefaultMapping = 0
let g:CtrlSpaceDefaultMappingKey = "<Tab>"
let g:CtrlSpaceSaveWorkspaceOnExit = 1
let g:CtrlSpaceSaveWorkspaceOnSwitch = 0
let g:CtrlSpaceIgnoredFiles = '\v(tmp|temp|work|vendors)[\/]'
if executable("ag")
	let g:CtrlSpaceGlobCommand = 'ag -l --nocolor -g ""'
endif
map <Tab> :CtrlSpace<cr>
```

```
" git gutter
let g:gitgutter_sign_column_always = 1

autocmd FocusGained * call gitgutter#all()

nmap <silent> ]h :<C-U>execute v:count1 . "GitGutterNextHunk"<CR>
nmap <silent> [h :<C-U>execute v:count1 . "GitGutterPrevHunk"<CR>

let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '~'
let g:gitgutter_sign_removed = '—'
let g:gitgutter_sign_removed_first_line = '—'
let g:gitgutter_sign_modified_removed = '≁'

let g:gitgutter_override_sign_column_highlight = 0

hi GitGutterAdd				guifg=#e9e9e9 guibg=#006c02 guisp=NONE ctermfg=2 ctermbg=NONE
hi GitGutterChange			guifg=#000000 guibg=#cbcd04 guisp=NONE ctermfg=3 ctermbg=NONE
hi GitGutterDelete			guifg=#e9e9e9 guibg=#9b0e05 guisp=NONE ctermfg=1 ctermbg=NONE
hi GitGutterChangeDelete	guifg=#000000 guibg=#c16f00 guisp=NONE ctermfg=3 ctermbg=NONE
```

I just see that the focus update is by me:
`autocmd FocusGained * call gitgutter#all()`
So it should be just the problem that `GitGutterAll` doesn't work, as mentioned in my first comment.

**Comment by hoschi** [comment]
I tested master (78d83c7) of git gutter again, changing two buffers instead of just one. Only the focused one gets updated! So it has nothing to do with session loading or CtrlSpace. Its just `GitGutterAll` doesn't refresh all buffers.

**Comment by airblade** [comment]
You shouldn't need `autocmd FocusGained * call gitgutter#all()` in your vimrc: the plugin [sets that up already](https://github.com/airblade/vim-gitgutter/blob/78d83c7056e1973ed4cbf9b5b3f09263a3dbf968/plugin/gitgutter.vim#L179).

So this problem manifests with only vim-gitgutter?

**Comment by hoschi** [comment]
You are right, I removed my `autocmd` line and it still works as before. This means, on e884a0e all buffers gutters are refreshed, on master only the focused buffer is refreshed.

**Comment by airblade** [comment]
OK, I'll check it out.

In the meantime, if you want to run the latest version, you could change [this line](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/diff.vim#L123) to `if 0` to make the diffing synchronous.

**Comment by hoschi** [comment]
Thanks for digging into this :)

**Comment by airblade** [comment]
I can't reproduce this.  I'm on nvim 0.1.3 and vim-gitgutter 103acc7, with only vim-gitgutter installed.  Here's what I'm doing:

1. Open NeoVim with `nvim`.
2. Open a file with unstaged changes via `:e somefile`.
3. Split the window and open another file with unstaged changes via `:e othefile`.
4. Open a new terminal and stage both files.
5. Focus NeoVim.
  - Expected: signs in both buffers are updated.
  - Actual: as expected.

**Comment by airblade** [comment]
@hoschi Any updates?

**Comment by hoschi** [comment]
Sorry for the silence, I haven't had time to check this again. Its not easy for me to update neovim. 

Your test scenario looks valid for me. Feel free to close the issue till I checked if I can reproduce this on my machine.

**Comment by airblade** [comment]
Ok, let me know if you still have this problem and I'll reopen.  Thanks!
