### ISSUE TITLE
Neovim: gitgutter breaks when a flag is added to `&shell`

### ISSUE THREAD

**Issue by gwerbin** [airblade/vim-gitgutter#321]
In order to get my `.zprofile` to run in the Neovim terminal, I have this line in my `nvim/init.vim` file:

```
let &shell='"/usr/local/bin/zsh" -l'
```

Gitgutter _really_ doesn't like it when I do this. If the plugin is loaded, any time I enter a normal-mode command in a file being tracked by Git I get this error:
```
Error detected while processing function gitgutter#process_buffer[8]..gitgutter#diff#run_diff:
line   75:
E902: ""/usr/local/bin/zsh" -l" is not an executable
```

The output from `:GitGutterDebug` seems okay:
```
NVIM 0.1.4-dev
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160415-59562-1w6hc5b/build/config -I/tmp/neovim20160415-59562-1w6hc5b/src -I/tmp/neovim20160415-59562-1w6hc5b/deps-build/usr/include -I/tmp/neovim20160415-59562-1w6hc5b/deps-build/usr/include -I/tmp/neovim20160415-59562-1w6hc5b/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160415-59562-1w6hc5b/deps-build/usr/include -I/tmp/neovim20160415-59562-1w6hc5b/deps-build/usr/include -I/tmp/neovim20160415-59562-1w6hc5b/deps-build/usr/include -I/tmp/neovim20160415-59562-1w6hc5b/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160415-59562-1w6hc5b/build/src/nvim/auto -I/tmp/neovim20160415-59562-1w6hc5b/build/include

git version 2.8.1

grep (BSD grep) 2.5.1-FreeBSD
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]	[-e pattern] [-f file] [--binary-files=value] [--color=when]	[--context[=num]] [--directories=action] [--label] [--line-buffered]	[--null] [pattern] [file ...]

updatetime=1
shell="/usr/local/bin/zsh" -l
shellcmdflag=-c
shellpipe=| tee
shellquote=
shellredir=>
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

I suspect this is some finicky quoting issue. But this setting works seamlessly with other plugins, including kassio/neoterm, and it follows the recommendation of the Neovim docs (options.txt, E91).

**Comment by gwerbin** [comment]
It looks like the issue lies [here](https://github.com/airblade/vim-gitgutter/blob/28353bd0609ae7b8c7e01c70dce31700d8c6e654/autoload/gitgutter/diff.vim#L128):
```
    let job_id = jobstart([&shell, '-c', cmd], {
          \ 'on_stdout': function('gitgutter#handle_diff_job'),
          \ 'on_stderr': function('gitgutter#handle_diff_job'),
          \ 'on_exit':   function('gitgutter#handle_diff_job')
          \ })
```

The Neovim docs recommend the following construction:
```
jobstart({cmd}[, {opts}])				{Nvim} *jobstart()*
		Spawns {cmd} as a job.  If {cmd} is a |List|, it will be run
		directly.  If {cmd} is a |string|, it will be roughly 
		equivalent to
			:call jobstart(split(&shell) + split(&shellcmdflag) + ['{cmd}'])
		NOTE: read |shell-unquoting| before constructing any lists 
		with 'shell' or 'shellcmdflag' options.  The above call is 
		only written to show the idea, one needs to perform unquoting 
		and do split taking quotes into account.
```

So `jobstart([split(&shell), '-c', cmd], ...` might be enough of a fix.

**Comment by airblade** [comment]
Closed by 530bf68...103acc7.

**Comment by airblade** [comment]
neovim/neovim#3999 sounds like this issue.

**Comment by gwerbin** [comment]
Indeed, it's the same issue.  By the way, I discovered that this is the incorrect way to add flags in Neovim anyway:  you're supposed to set `&shellcmdflag`,  which handles word splitting better. The quoted-path method is really only for when you have spaces in the path itself.

**Comment by airblade** [comment]
I know from bitter experience that trying to modify the way vim interacts with the shell can be a real pain and I suppose neovim has inherited some of that.

At one stage I tried to document it in [vim-system-escape](/airblade/vim-system-escape) but I gave up after a while.

Incidentally I got the `jobstart([&shell, '-c', cmd], {})` format from [|job-control-usage|](https://neovim.io/doc/user/job_control.html#job-control-usage).

I'm not sure how to dig into this further.  The patch you sent worked for me and I'm still baffled by the problem people ran into in #324, especially as the plugin stopped working only partly, not entirely.  Let me know if you can think of any way I can help!
