### ISSUE TITLE
More targets than List items on Neovim

### ISSUE THREAD

**Issue by ezuk** [airblade/vim-gitgutter#323]
Using nvim 0.1.4.

```
:GitGutterEnable
Error detected while processing function gitgutter#utility#git_supports_command_line_config_override:
line    1:
E688: More targets than List items
Error detected while processing function gitgutter#enable[2]..gitgutter#all:
line    4:
E171: Missing :endif
Press ENTER or type command to continue
```

Not quite sure what to make of it, but it's borked :) Any ideas?

**Comment by airblade** [comment]
That's from the most recent commit (cc77f32).

What does `git --version` give you?

**Comment by ezuk** [comment]
```
 $ git --version                                                                                                                           (/home/ezuk)(12:08)
git version 2.4.2
```

Sorry for the much-delayed response, I've been traveling. Thank you for looking into this!

**Comment by airblade** [comment]
No worries, thanks for the reply.

I still have no idea why you got an error.  Does this execute successfully?

```viml
:let [major, minor, patch; _] = split(matchstr(system('git --version'), '[0-9.]\+'), '\.')
```

**Comment by ezuk** [comment]
Nope! Gives "more targets than list items"

FWIW, I use Fish as my shell, Ubuntu 14.04.

**Comment by airblade** [comment]
It may well be.  What do you get with the following?

```viml
:echo system('git --version')
:echo matchstr(system('git --version'), '[0-9.]\+')
```

**Comment by ezuk** [comment]
```
:echo system('git --version')

^[Ptmux;^[^[]50;CursorShape=1^G^[\git version 2.4.2                                                                                                                                                            
                                                                                                                                                                                                               
Press ENTER or type command to continue

:echo matchstr(system('git --version'), '[0-9.]\+')
50
```

So we no longer get the error, but it's matching than 50 rather than 2.4.2.

**Comment by airblade** [comment]
OK, so the problem is tmux wrapping the output of `system()` with useless junk.  I can fix the regex in this case to pull out the git version number...but the plugin makes quite a few system calls and I don't plan to adjust them to compensate for tmux.

I don't use tmux so I'm not familiar with its settings, but is there a way to tell it not to wrap the stuff it sends back to vim from `system()`?

**Comment by ezuk** [comment]
I fixed it! Fix was to remove the following from `config.fish`:

```
echo -en "\ePtmux;\e\e]50;CursorShape=1\007\e\\"
```

I also removed something to that effect from my .vimrc. Thank you for your help!
