### ISSUE TITLE
Signs disappear upon saving in neovim

### ISSUE THREAD

**Issue by tlarrieu** [airblade/vim-gitgutter#324]
Observed behavior : 
- when I save a buffer, the signs disappear and I can't navigate hunks
- when I make a modifications, signs are back (until I save the buffer)
- switching focus between splits has no effect whatsoever

This commit appears to be the culprit : 103acc7a2337c52389ad1e4b4653f5dcaaff45dc (found with git bisect)

---

My setup is as follows :

```
$ git show HEAD -s
commit 035ea9260c40bac6fee8db013522353d019dbe8d
Author: Andy Stewart <boss@airbladesoftware.com>
Date:   Thu Apr 21 15:57:07 2016 +0100

    Add section on extensions to README.
```

```
$ nvim --version
NVIM v0.1.4-179-ga7a0bf5
Build type: Dev
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/yaourt-tmp-tlarrieu/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-tlarrieu/aur-neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/yaourt-tmp-tlarrieu/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-tlarrieu/aur-neovim-git/src/neovim-git/build/include
Compiled by tlarrieu@tlarrieu-pc

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by bugeats** [comment]
I've got the same. `NVIM v0.1.4-179-ga7a0bf5`.

**Comment by airblade** [comment]
That commit changed the way async jobs are handed to neovim.  That the realtime diffs work but not the "non-realtime" ones suggests neovim's "internal black magic" (quoting @gwerbin's commit message) is getting confused by the non-realtime command.

That surprises me because the non-realtime command is simpler than the realtime one.

What does `:GitGutterDebug` give you?

It would also help to know what diff, if any, you're getting back asynchronously.  Please could you add `:echom a:diff` as the first line of [this function](https://github.com/airblade/vim-gitgutter/blob/035ea9260c40bac6fee8db013522353d019dbe8d/autoload/gitgutter.vim#L58) and post the result?

@gwerbin Any change here will affect you – would you like to join in?

**Comment by airblade** [comment]
BTW I can't reproduce this with nvim 0.1.4-dev (2671b9f).  My `&shell` inside neovim is `/bin/bash`.

**Comment by gwerbin** [comment]
Dark arts, indeed.  If anything, my change ought to make the two jobs "more similar",  since they are now both called  by constructing a string.

What is your `&shell` option set to? What OS are you running and what shell do you use?

**Comment by martin-svk** [comment]
I also have the issue. Just found out that the shell from which I run `nvim` is influencing it.
When running `nvim` from `zsh` it is not working, but from `bash` it is working.

**Comment by yyadavalli** [comment]
I'm having the same issue with `NVIM 0.1.3` and `zsh`
OS: Arch Linux

**Comment by adambiggs** [comment]
Same issue here. `:GitGutterDebug` info:

```
NVIM v0.1.4-195-g3d7a6e4
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160422-34133-8041af/build/config -I/tmp/neovim-20160422-34133-8041af/src -I/tmp/neovim-20160422-34133-8041af/deps-build/usr/include -I/tmp/neovim-20160422-34133-8041af/deps-build/usr/include -I/tmp/neovim-20160422-34133-8041af/deps-build/usr/include/luajit-2.0 -I/tmp/neovim-20160422-34133-8041af/deps-build/usr/include -I/tmp/neovim-20160422-34133-8041af/deps-build/usr/include -I/tmp/neovim-20160422-34133-8041af/deps-build/usr/include -I/tmp/neovim-20160422-34133-8041af/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160422-34133-8041af/build/src/nvim/auto -I/tmp/neovim-20160422-34133-8041af/build/include

git version 2.8.1

grep (BSD grep) 2.5.1-FreeBSD
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]	[-e pattern] [-f file] [--binary-files=value] [--color=when]	[--context[=num]] [--directories=action] [--label] [--line-buffered]	[--null] [pattern] [file ...]

updatetime=750
shell=/bin/zsh
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

**Comment by airblade** [comment]
So the common factor seems to be zsh.  Strangely I can't reproduce the problem using neovim on zsh, where inside neovim my `&shell` is `/bin/zsh`.

However since the modified `jobstart()` invocation was clearly causing problems I have reverted the change until we can figure out what the problem is and how to solve it for everyone.

**Comment by airblade** [comment]
I'd be grateful if someone who had this problem could post their diff, as described [above](#issuecomment-213287161).  Thanks!

**Comment by yyadavalli** [comment]
Here is a diff, but this is after the above commit, I can revert back and post again if needed.
```
@@ -13,0 +14,3 @@ libraryDependencies ++= Seq(^@^@
```

**Comment by gwerbin** [comment]
I'll take a closer look at this tomorrow, but it's odd because I'm using Zsh without a problem.

Fwiw this was the original issue i was trying to solve, maybe someone else has insight until I have a chance to dig into what I did: vim-gitgutter/issues/321

**Comment by airblade** [comment]
@yyadavalli Yes, please go back to the version that didn't work for you and post again.  I'd like to see whether the plugin is able to get as far as running the diff.  Thanks!

**Comment by tlarrieu** [comment]
> So the common factor seems to be zsh

`&shell` *does not seem* to be an issue (since I'm using `/bin/bash`), but the shell from which nvim is run **might** be (I use `/usr/bin/fish`).


---

`:GitGutterDebug` :

```
NVIM v0.1.4-179-ga7a0bf5
Build type: Dev
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/yaourt-tmp-tlarrieu/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-tlarrieu/aur-neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/yaourt-tmp-tlarrieu/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-tlarrieu/aur-neovim-git/src/neovim-git/build/include

git version 2.8.0

grep (GNU grep) 2.24
```

---

`:echom a:diff` :


after opening the file :

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"autoload/gitgutter.vim" 255L, 6892C
@@ -58,0 +59 @@ function! gitgutter#handle_diff(diff)
```

making a modification adds this :

```
@@ -58,0 +59,2 @@ function! gitgutter#handle_diff(diff)
```

and finally after saving :

```
@@ -58,0 +59,2 @@ function! gitgutter#handle_diff(diff)
"autoload/gitgutter.vim" 256L, 6893C written
```

So there *seem* to be a diff (and no error) as far as I can tell

**Comment by yyadavalli** [comment]
Oddly, it stopped working completely when I reverted to `d282c33`

So I started digging around, here is the job command
```
Initial startup
/bin/zsh -c cd project && (git ls-files --error-unmatch plugins.sbt && (git -c "diff.autorefreshindex=0" diff --no-ext-diff --no-color -U0 -- plugins.sbt | grep --color=never -e '^@@ ' || exit 0))

Just after buffer load
/bin/zsh -c cd project && (git ls-files --error-unmatch plugins.sbt && (git show :project/plugins.sbt > /tmp/yyadavalli/nvimyozJIl/2.sbt && git -c "diff.autorefreshindex=0" diff --no-ext-diff --no-color -U0 -- /tmp/yyadavalli/nvimyozJIl/2.sbt /tmp/yyadavalli/nvimyozJIl/3.sbt | grep --color=never -e '^@@ ' || exit 0))
```
The call `gitgutter#utility#pending_job(job_id)` always returns `0` (may be it should) and I get `async` returned back and a call to `gitgutter#handle_diff(diff)` never happens

**Comment by airblade** [comment]
I'm assuming that 5ed00d1 fixed the problem for everyone...please let me know if not.

I just added simple logging in 4bed1da so if things stop working again, please:

- add `let g:gitgutter_log=1` to your vimrc;
- reproduce the problem;
- post the `gitgutter.log` file from vim-gitgutter's installation directory.

**Comment by airblade** [comment]
@tlarrieu @yyadavalli  That all looks ok to me.  I'm not sure what the problem is but maybe the extra logging would reveal something.  Anyway, hopefully it's all working for you now.
