### ISSUE TITLE
Disable vim-gitgutter when editting file is not in a repository

### ISSUE THREAD

**Issue by mrleolink** [airblade/vim-gitgutter#325]
Title says it all.
Also i think my problem is same as #304 , but since that one looks like the OP doesn't care anymore so I create this issue to elaborate it more.

This one is really annoying.
I set line highlighting always on. If my current repository is a repository, and if I vi a file outside of that repository, vim-gitgutter still runs and treats the file as a new file in the repository (highlight all the lines and add + sign in every single line).

**Comment by airblade** [comment]
The plugin always changes to a file's directory before running so it shouldn't be treating the "outside" file as a new file in the repository.

Is your "outside" file in a repository of its own?

What version of vim-gitgutter are you on?

**Comment by mrleolink** [comment]
Version: newest one, I just installed it today

> Is your "outside" file in a repository of its own?

I dont think so, I was standing in a repo, then I tried to edit my .vimrc, then it happened...

**Comment by mrleolink** [comment]
Oh sorry, it wasn't .vimrc but another file which names "[dot]zshrc".

Also I tried with some files, it only happened on files which have prefix is "[dot]".
Do you think it's because of the special characters like "[" and "]"

**Comment by airblade** [comment]
It may well be...let me investigate.

**Comment by mrleolink** [comment]
Thank you!

**Comment by airblade** [comment]
Please see the commit message for an explanation of the bug.

Oh, and let me know if it solves your problem ;)

**Comment by mrleolink** [comment]
woah, it was fast!!!
Confirmed, you are awesome man ;)
