### ISSUE TITLE
Please use release system

### ISSUE THREAD

**Issue by shibumi** [airblade/vim-gitgutter#327]
Hello,
I am Arch Linux Maintainer in the AUR (Arch Linux User Repository). I would like to package vim-gitgutter. Could you please use the release system and tag 'stable releases' this way?
This would be awesome! If you do this there is maybe a good chance that vim-gitgutter will be pulled in to the official Arch Linux repositories.

best regards

Chris

**Comment by airblade** [comment]
Do you mean GitHub's release system?  Do you need tags to be in a specific format?

**Comment by shibumi** [comment]
Hello, thanks for you reply!
Yes I need it in a specific format. Avoid chars like "-". Use a simple format system like for example:

1.0.0 

first number Main-version, second number little patches like more features third number bugfixes..

**Comment by beanaroo** [comment]
would a `-git` package not be sufficient? You could make use of the `pkgver()`[ function](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver.28.29_function). Seeing as gitgutter doesn't have tags, revision counting works:

    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"

**Comment by shibumi** [comment]
@beanaroo 
This would work for AUR, yes. And there is a git package already.. But there are persons who don't like to pull the latest HEAD. And if some maintainer want to package it for an official repository we would need stable releases. :-)

**Comment by airblade** [comment]
I never know which of my commits are going to be "stable".

**Comment by shibumi** [comment]
don't worry. Just take the last one that is workable. Don't use a commit where even starting wouldn't work ^^

**Comment by hgiesel** [comment]
I'm going to add that in order to use this plugin with [kana's vim-flavor](https://github.com/kana/vim-flavor) it also needs a release tag.

**Comment by reinerh** [comment]
I would also like to ask you to create releases. Packaging a release where the developer knows that this version is currently not totally broken is better than if package maintainers would have to decide on their own which development snapshot they should pick.

**Comment by airblade** [comment]
I'm afraid this just isn't a priority for me.

**Comment by shibumi** [comment]
sad
