### ISSUE TITLE
Error thrown when saving to a network path on Windows

### ISSUE THREAD

**Issue by kflu** [airblade/vim-gitgutter#328]
Sorry I can't reopen #61, but I'm still seeing this with the latest master branch (5ed00d1bd386e19f5bf2996fedd4021760e99591). 

More specifically, on opening a Windows network share file (`\\share\folder\file.txt`), it prompts the error

```
Error detected while processing function GitGutter..<SNR>60_is_active..<SNR>60_is_in_a_git_repo:
line 2:
E484: Can't open file C:\Users\ljani\AppData\Local\Temp\VIoEE6D.tmp
```

And it gets periodically popped up every few seconds.

**Comment by airblade** [comment]
Does it help if you change the start of [this line](https://github.com/airblade/vim-gitgutter/blob/4bed1da6486f26324f97307e0f20574af0f549ea/autoload/gitgutter/utility.vim#L152) from `'cd '` to `'cd /d '`?

**Comment by kflu** [comment]
No, still given me the error. But I just realized the error message might be slightly different than what was given in #61. Here's the one I'm seeing:

![untitled](https://cloud.githubusercontent.com/assets/1031978/14837085/4cff6f04-0bca-11e6-971a-6b7f04e71caf.png)

**Comment by airblade** [comment]
That error message means that Windows wasn't able to execute the external command for some reason, presumably the network share path.

I'm not familiar with Windows or network shares so I don't know how to adjust for the different path.

You could upgrade to the latest vim-gitgutter, do `:let g:gitgutter_log=1`, then reproduce the error.  If you look in the vim-gitgutter directory you'll see a `gitgutter.log`...please could you post the contents here?  That will show the exact command that is failing.

**Comment by kflu** [comment]
Thanks for looking into this @airblade here you go:

```
function gitgutter#process_buffer[8]..gitgutter#diff#run_diff[90]..gitgutter#utility#system[1]:
cd "\\share\public\Files\UserFiles\kfl" && (git ls-files --error-unmatch Clean-HostsCert.ps1 && (git -c "diff.autorefreshindex=0" diff --no-ext-diff --no-color -U0   -- Clean-HostsCert.ps1))

function gitgutter#process_buffer[8]..gitgutter#diff#run_diff[13]..gitgutter#utility#file_relative_to_repo_root[3]..gitgutter#utility#system[1]:
cd "\\share\public\Files\UserFiles\kfl" && git rev-parse --show-prefix
```

My repro step was to edit a file on the share in vim with this command:

    :e \\share\public\Files\UserFiles\kfl\Clean-HostsCert.ps1

**Comment by airblade** [comment]
If you run these commands on the command line, what do you get?

```
cd "\\share\public\Files\UserFiles\kfl" && (git ls-files --error-unmatch Clean-HostsCert.ps1 && (git -c "diff.autorefreshindex=0" diff --no-ext-diff --no-color -U0   -- Clean-HostsCert.ps1))
```

```
cd "\\share\public\Files\UserFiles\kfl" && git rev-parse --show-prefix
```

**Comment by kflu** [comment]
That just went through fine. And it seems that I shouldn't be using the quotes around the path - `cd \\share\public\Files\UserFiles\kfl`.

But after executing the two commands, access a share file like `\\share\public\Files\UserFiles\kfl\some_file.txt` still gives me the error.

**Comment by airblade** [comment]
I don't know how to fix this.  Sorry.

**Comment by kflu** [comment]
Is it possible to try and catch (swallow) them in vim. I don't care gitgutter not to work at those locations. I just don't want an error to pop up every 3 seconds.

**Comment by haliphax** [comment]
I agree with @kflu - it would be awesome to have a gitgutter setting that would allow us to disable gitgutter warnings for this particular problem.

**Comment by Snaptags** [comment]
Would it break anything if you wrapped the line causing the error in try..catch?
![trycatch](https://cloud.githubusercontent.com/assets/1249745/21496992/a8f60106-cc22-11e6-8035-4be1efdb9e29.png)
This does work for me by not showing the error on network shares for files NOT under git version control. If I copy a git project to the share, git-gutter does not indicate modifications at all. But as it does not work **without** the try..catch either, we don't really lose anything :-)

**Comment by airblade** [comment]
I have just rejigged the path handling (5bfe5b9) – please could you update and try again?

**Comment by Snaptags** [comment]
On UNC paths (e.g. \\server-42\dir\file.txt) I still get the same error message as posted by kflu ...
If I assign a drive letter then opening and saving of the file does work.

**Comment by airblade** [comment]
@Snaptags Please could you post the contents of the command which fails?  And the caller references too (the previous line in the log)?  With `let g:gitgutter_log=1` you'll find the commands in a logfile in your gitgutter directory.

**Comment by Snaptags** [comment]
```
0.000028 function gitgutter#init_buffer[4]..gitgutter#utility#set_repo_path[22]..gitgutter#utility#system[1]:

0.000028 cd "\\server-42\tmp\dir" && git ls-files --error-unmatch --full-name test.txt
```

plus vim shows the errors from kflus screen shot. If I confirm them using <enter> the file is opened. I can then edit it and save it without any further errors.

**Comment by airblade** [comment]
@Snaptags Does applying this change help?

```diff
diff --git a/autoload/gitgutter/utility.vim b/autoload/gitgutter/utility.vim
index 6885489..b783408 100644
--- a/autoload/gitgutter/utility.vim
+++ b/autoload/gitgutter/utility.vim
@@ -138,7 +138,7 @@ function! s:set_path(bufnr, path)
 endfunction

 function! gitgutter#utility#cd_cmd(bufnr, cmd) abort
-  return 'cd '.s:dir(a:bufnr).' && '.a:cmd
+  return 'pushd '.s:dir(a:bufnr).' && '.a:cmd
 endfunction

 function! s:use_known_shell() abort
```

If not, does `:!cd "\\server-42\tmp\dir"` work?

**Comment by Snaptags** [comment]
After applying the patch everything is working perfectly!

P.S. `:!cd "\\server-42\tmp\dir"` results in:
C:\WINDOWS\system32\cmd.exe /c (cd ^"\\server-42\tmp\dir^")
"\\server-42\tmp\dir"
CMD does not support UNC-paths as current directory.
shell returned 1

**Comment by airblade** [comment]
@Snaptags That's good news.  Please could you try out this new patch?

```diff
diff --git a/autoload/gitgutter/utility.vim b/autoload/gitgutter/utility.vim
index 6885489..3f4cb22 100644
--- a/autoload/gitgutter/utility.vim
+++ b/autoload/gitgutter/utility.vim
@@ -138,7 +138,12 @@ function! s:set_path(bufnr, path)
 endfunction

 function! gitgutter#utility#cd_cmd(bufnr, cmd) abort
-  return 'cd '.s:dir(a:bufnr).' && '.a:cmd
+  let cd = s:unc_path(a:bufnr) ? 'pushd' : 'cd'
+  return cd.' '.s:dir(a:bufnr).' && '.a:cmd
+endfunction
+
+function! s:unc_path(bufnr)
+  return s:abs_path(a:bufnr, 0) =~ '^\\\\'
 endfunction

 function! s:use_known_shell() abort
```

**Comment by Snaptags** [comment]
The result is the same, working fine.
