### ISSUE TITLE
GitGutterGetHunkSummary() returns wrong stats for inactive buffers

### ISSUE THREAD

**Issue by xzfc** [airblade/vim-gitgutter#331]
Steps to reproduce:

1. exec `:set statusline=%{join(GitGutterGetHunkSummary())}` to see hunk summary in the statusline.
2. Split-open a few files with different hunk summary; also split-open a `:help` window.
3. Jump over windows (e.g., `CTRL-W h`, `CTRL-W j`, ...).
4. As result, an incorrect hunk summaries shown in inactive windows' statuslines.

The root cause is the `s:summary` variable at [hunk.vim:2], which is script-variable, but it should be buffer-variable.

[hunk.vim:2]: https://github.com/airblade/vim-gitgutter/blob/65e3ff89941e1294a44549848eeed6fa962e374e/autoload/gitgutter/hunk.vim#L2

**Comment by airblade** [comment]
What revision of the plugin are you using?  I'm wondering whether this is an async problem; can you reproduce the problem after doing `let g:gitgutter_async = 0`?

**Comment by xzfc** [comment]
I'm using latest master, 65e3ff89941e1294a44549848eeed6fa962e374e. It is reproducible with `let g:gitgutter_async = 0`.

**Comment by airblade** [comment]
I've just tried this and I see the problem.  I'll try to find time to fix it soon.

**Comment by airblade** [comment]
I've updated the code in the [hunks](https://github.com/airblade/vim-gitgutter/compare/hunks) branch.  However it doesn't solve the problem for me.

I'm not actually sure when Vim updates a window's statusline so I've asked on [vim_use](https://groups.google.com/d/topic/vim_use/nw8HwyVmncg/discussion).
