### ISSUE TITLE
GitGutter stopped working

### ISSUE THREAD

**Issue by pmcRTR** [airblade/vim-gitgutter#332]
GitGutter used to work for me and now no longer does - no symbols appear any more when I make changes to a Git version controlled file.  I've tried manually doing <code>:GitGutterDisable</code>, <code>:GitGutterEnable</code> etc. - no joy.

I've added no plugins or new settings to my .vimrc at all between it working and not working.  The only thing I do is compile Vim and Git regularly so that I'm always running the latest versions.  I'm not exactly sure when it stopped working, sorry :(

Here is the output of <code>:GitGutterDebug</code>

<code>VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  2 2016 16:25:30) Included patches: 1-1816 Compiled by root@pmcUbuntu</code>
<code>
git version 2.8.2
grep (GNU grep) 2.24 Copyright © 2016 Free Software Foundation, Inc. (further output elided)
</code>

<code>updatetime=4000</code>
<code>shell=/bin/bash</code>
<code>shellcmdflag=-c</code>
<code>shellpipe=2>&1| tee</code>
<code>shellquote=</code>
<code>shellredir=>%s 2>&1</code>
<code>shellslash [n/a]</code>
<code>shelltemp=1</code>
<code>shelltype [n/a]</code>
<code>shellxescape=</code>
<code>shellxquote=</code>

**Comment by airblade** [comment]
What revision of the plugin are you using?

Please could you do `let g:gitgutter_log = 1` then try to make the signs appear with a `:w` or by making a change to the buffer and waiting 4s (your `updatetime`)?  You'll then find a `gitgutter.log` and `channel.log` in your vim-gitgutter directory – please could you post their contents?

**Comment by tokoyami** [comment]
Hello, I'm experiencing the same ever since the patch enabling async updates for vim (e607a997cef29923e5847fc434f3d115fcad8e23 I'd guess). My symptoms are 10+ zombie shell processes spawned as children of vim and no signs showing up (no hunks available either). This behavior stopped when I disabled the async updates with `let g:gitgutter_async = 0`.

A zombie process seems to spawn every time a change is made and `updatetime` time passes. I guess that's when gitgutter starts the check.

My `:GitGutterDebug`:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  2 2016 09:11:39)
Included patches: 1-1816
Compiled by plamen@midori

git version 2.8.2

grep (GNU grep) 2.16

updatetime=2000
shell=/usr/bin/zsh
shellcmdflag=-c
shellpipe= > /dev/null 2>&1 | tee 
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```
Logs: [gist link](https://gist.github.com/tokoyami/43184891e79efb43dff0abc73488a112)

**Comment by airblade** [comment]
This is due to [Vim 7.4.1810](https://github.com/vim/vim/commit/715d285d79a1d97928dd717278e25e6de45d1496) which changed the way Vim reports the end of a job's stdout.

I've got an alternative approach working, using a `close_cb` handler, but Vim keeps segfaulting...

**Comment by pmcRTR** [comment]
Sounds like you know what the issue is but just in case it helps / confirms here are my .log files as requested.

gitgutter.log:

<pre><code>==== start log session ====

  0.000046 function gitgutter#process_buffer[8]..gitgutter#diff#run_diff[13]..gitgutter#utility#file_relative_to_repo_root[3]..gitgutter#utility#system[1]:
  0.000046 cd /home/pmc/dotfiles && git rev-parse --show-prefix

  0.065681 function gitgutter#process_buffer[8]..gitgutter#diff#run_diff[74]..gitgutter#async#execute[25]:
  0.065681 [vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 1 open, 'process': 4344}] cd /home/pmc/dotfiles && (git ls-files --error-unmatch vimrc && (git show :vimrc > /tmp/vpP1lZA/3 && git -c "diff.autorefreshindex=0" diff --no-ext-diff --no-color -U0   -- /tmp/vpP1lZA/3 /tmp/vpP1lZA/4 | grep --color=never -e '^@@ ' || exit 0))

  0.106938 function gitgutter#async#handle_diff_job_vim[1]:
  0.106938 channel: channel 1 open, line: vimrc

  0.166680 function gitgutter#async#handle_diff_job_vim[1]:
  0.166680 channel: channel 1 open, line: @@ -15,0 +16 @@ Plugin 'gmarik/Vundle.vim' </code></pre>

channel.log:

<pre><code>==== start log session ====
  0.065185 : Starting job: /bin/bash  -c  cd /home/pmc/dotfiles && (git ls-files --error-unmatch vimrc && (git show :vimrc > /tmp/vpP1lZA/3 && git -c "diff.autorefreshindex=0" diff --no-ext-diff --no-color -U0   -- /tmp/vpP1lZA/3 /tmp/vpP1lZA/4 | grep --color=never -e '^@@ ' || exit 0))
  0.065275 on 1: Created channel
  0.066321 : looking for messages on channels
  0.106352 RECV on 1: 'vimrc
'
  0.107069 on 1: Invoking channel callback gitgutter#async#handle_diff_job_vim
  0.166829 RECV on 1: '@@ -15,0 +16 @@ Plugin 'gmarik/Vundle.vim'
'
  0.166857 : looking for messages on channels
  0.166876 on 1: Invoking channel callback gitgutter#async#handle_diff_job_vim
  0.167322 ERR on 1: channel_select_check(): Cannot read from channel
  0.167351 on 1: Closing channel
  0.167376 : looking for messages on channels </code></pre>

**Comment by airblade** [comment]
I've turned off async for vim (db6a253) for the time being, which will get vim-gitgutter working for you again.

I have updated the code to work with the change in Vim 7.4.1810 (see the [async](https://github.com/airblade/vim-gitgutter/compare/async) branch) but Vim segfaults.  There's a [discussion on vim_dev about this](https://groups.google.com/d/topic/vim_dev/n0jeRog4DI0/discussion).

**Comment by airblade** [comment]
@tokoyami 

> My symptoms are 10+ zombie shell processes spawned as children of vim

What shell command did you run to see the zombie processes?

**Comment by tokoyami** [comment]
@airblade Just regular htop with tree view enabled. They were all with state Z. It was probably because they were waiting for a 'wait' call by the parent to close. They didn't stay dangling after I quit vim.

**Comment by airblade** [comment]
@tokoyami Thanks, that's really helpful.
