### ISSUE TITLE
Automatically collapsing folds

### ISSUE THREAD

**Issue by renstrom** [airblade/vim-gitgutter#334]
This commit https://github.com/airblade/vim-gitgutter/commit/27f99c4a4dbbaa3f7c34a9fda5eda6904d05e383 causes folds to automatically collapse expanded folds.

How to reproduce:

**vimrc**

```vim
" Plugins {{{1
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
call plug#begin()
" airblade/vim-gitgutter {{{2
Plug 'airblade/vim-gitgutter'
let g:gitgutter_map_keys = 0

call plug#end()
" vim: set foldenable foldmethod=marker foldlevel=0:
```

Now open up `vimrc` with `vim -N -u vimrc vimrc` and expand a fold, after a moment (1-3s) it will collapse again.

Vim version: 7.4.1817

**Comment by airblade** [comment]
Oops, I should have read the docs:

>  After applying the autocommands the modelines are processed, so that their settings overrule the settings from autocommands, like what happens when editing a file. This is skipped when the `<nomodeline>` argument is present. You probably want to use `<nomodeline>` for events that are not used when loading a buffer, such as `User`.

Sorry about that!
