### ISSUE TITLE
Makes gvim use 100% CPU

### ISSUE THREAD

**Issue by yannick1974** [airblade/vim-gitgutter#336]
Hi,

I'm using vim version 7.4.1829 with Debian testing. Since commit [72d100](https://github.com/airblade/vim-gitgutter/commit/72d100) (found bisecting) if I run gvim (either GTK2 or GTK3) version gvim get stuck at 100% CPU and sort of freeze. I've no problem using vim in console.

I've tested with a clean configuration and only vim-plugged and vim-gitgutter as plugins.

If you have any idea on how to debug the problem, I can try it.

Cheers,

Yannick

**Comment by airblade** [comment]
I presume everything's fine with `let g:gitgutter_async=0`?

The 100% CPU is almost certainly due to a Vim bug.  I expect if you do `let g:gitgutter_log=1`, use the plugin a little, and look at `gitgutter.log` and `channel.log` in your vim-gitgutter directory, you'll see that the close callback isn't being called (or similar).

Would you be able to post an excerpt from those log files?

**Comment by yannick1974** [comment]
Setting async to 0 makes the problem disappear.

If (without the async flag and with logging enables) open a CHANGELOG.md in a git repository:

channel.log is full of:

 26.202932 ERR on 0: messageFromNetbeans(): Cannot read from channel, will close it soon

and gitgutter.log contains:

==== start log session ====

  0.000011 function gitgutter#process_buffer[8]..gitgutter#diff#run_diff[74]..gitgutter#async#execute[28]:
  0.000011 [vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 0 open, 'process': 24109}, buffer: 1] cd . && (git ls-files --error-unmatch CHANGELOG.md && (git -c "diff.autorefreshindex=0" diff --no-ext-diff --no-color -U0   -- CHANGELOG.md | grep --color=never -e '^@@ ' || exit 0))

**Comment by airblade** [comment]
Thanks.

Is everything ok in terminal vim (instead of gvim)?

**Comment by yannick1974** [comment]
Yes, I have no problem in terminal.

**Comment by airblade** [comment]
MacVim is similar at the moment: the async stuff works in the terminal but not in the GUI.  I suspect Vim's async implementation doesn't work with GUIs yet.

**Comment by airblade** [comment]
Does `:echo has('gui-running')` return `1` in gvim?

**Comment by yannick1974** [comment]
Yes.

**Comment by yannick1974** [comment]
Unless I made an error bisecting, the problem occurs since [v7.4.1826](https://github.com/vim/vim/commit/cf7ff70ca73218d618e7c00ab785bcf5f9120a94).

**Comment by luisdavim** [comment]
This seams to be similar to #335 but on that one the problem occurs in terminal, I did not tested any GUI version of vim.

**Comment by airblade** [comment]
Fixed in 882073f by having graphical vims run diffs synchronously.
