### ISSUE TITLE
Commit ba6e1048 breaks plugin on OpenBSD

### ISSUE THREAD

**Issue by xguerin** [airblade/vim-gitgutter#340]
Hello there , 

Commit:  ba6e1048482d46adc0cfbd74929ad5d357c045f9 enforces /bin/bash as the default shell. However, /bin/bash is not available on OpenBSD. Bash is installed through ports and accessible at /usr/local/bin/bash.

I already set my shell variable to cope with that situation. Could gitgutter avoid overwriting the shell variable if it is already set to a bash ?

Thx,

**Comment by airblade** [comment]
I didn't know bash wasn't even installed on OpenBSD.

An alternative solution might be to use `/bin/sh` – what does that point to on OpenBSD?

**Comment by xguerin** [comment]
:) yes, the default shell is pdksh. /bin/sh exists.

**Comment by airblade** [comment]
Ok, thanks.

Would you mind modifying your local copy of vim-gitgutter so it uses `/bin/sh` instead of `/bin/bash`, and let me know if everything still works?  You'll need to do it in [utility.vim](https://github.com/airblade/vim-gitgutter/blob/b3979e7736b8c0fa0223a1e0e8dfdc79252c5a26/autoload/gitgutter/utility.vim#L189) and [async.vim](https://github.com/airblade/vim-gitgutter/blob/b3979e7736b8c0fa0223a1e0e8dfdc79252c5a26/autoload/gitgutter/async.vim#L52) (also line 21 if you're using neovim).

**Comment by xguerin** [comment]
Sure. There is another problem with grep now, 28353bd0609ae7b8c7e01c70dce31700d8c6e654 seems to add "--color=never" which is only available in GNU grep.

**Comment by airblade** [comment]
`--color=never` is also available in (Free)BSD grep.

Anyway, see [Use a custom grep command](https://github.com/airblade/vim-gitgutter#use-a-custom-grep-command):

```viml
let g:gitgutter_grep_command='grep -e'
```

**Comment by xguerin** [comment]
Ok, amending my PR.

**Comment by airblade** [comment]
The argument against using `/bin/sh` is you don't know which shell you're going to get so you don't know how to escape file paths properly.

**Comment by xguerin** [comment]
Wouldn't it be simpler to assume `/bin/bash` and allow the user to override it like what exists for `grep` ?

**Comment by svanharmelen** [comment]
This also seems to make NeoVim crash... When you open a terminal inside NeoVim (`:term`) and then close it again, NeoVim crashes. I'm afraid I don't have more details but when deleting this single commit the problem goes away...

**Comment by jan0sch** [comment]
On my FreeBSD box everything seems to work ok, if I change `/bin/bash` to `/bin/sh` for vim.
