### ISSUE TITLE
Commit ba6e1048 breaks `:term` usage within NeoVim

### ISSUE THREAD

**Issue by svanharmelen** [airblade/vim-gitgutter#344]
In addition to issue #340 commit ba6e1048 also seems to make NeoVim crash when using a terminal split... When you open a terminal inside NeoVim (:term) and then close it again, NeoVim crashes about a second later.

I'm afraid I don't have more details but when deleting this commit the problem goes away and all is good again.

**Comment by airblade** [comment]
How strange.  I have no idea why setting `&shell` would cause a segmentation fault.  Do you think it's worth opening an issue on the NeoVim repo?

**Comment by airblade** [comment]
BTW what OS are you on?  If you replace every `/bin/bash` in the plugin with `/bin/sh` does the problem go away?

**Comment by svanharmelen** [comment]
I'm on OSX 10.11.5 But I just updated to use the latest code (where `/bin/bash` is updated to `/bin/sh`) and this also seems to fix the crashes 😀 

So we can close this one as well I guess... Thx!
