### ISSUE TITLE
Feature request: Print number of removed lines in sign column

### ISSUE THREAD

**Issue by smkent** [airblade/vim-gitgutter#345]
This is one feature [vim-signify](https://github.com/mhinz/vim-signify) has that vim-gitgutter doesn't. vim-signify will show the number of deleted lines in the sign column (ex. "!3" for 3 deleted lines, up to "99" for 99 deleted lines). It would be great if vim-gitgutter had this feature as well.

**Comment by airblade** [comment]
I can see the utility but I find the numbers and different markers distracting.  For me a single, consistent sign is easier to process at a glance.

If I want to know how many lines were deleted in a hunk, I jump to the hunk and use `<leader>hp` to preview its diff.

I know this comes down to personal aesthetics but I'm going to keep it the way it is.  Sorry.

**Comment by smkent** [comment]
What if this was added as an optional feature that is disabled by default?

**Comment by airblade** [comment]
I don't have the time or the inclination to write the code, write the tests, and then maintain and support them.
