### ISSUE TITLE
Cursor jumps after revert command

### ISSUE THREAD

**Issue by yevhen-m** [airblade/vim-gitgutter#346]
Hey, 
when I do "revert", my cursor is centered. This happens due to the `silent edit` command.
I don't like these jumps, is it possible to somehow get rid of them?

**Comment by airblade** [comment]
Now you mention it, I agree it's jarring.

(Note to self: this happens when the file is taller than the window and the cursor line can be positioned in the middle of the window.)

**Comment by yevhen-m** [comment]
Thanks a lot.
