### ISSUE TITLE
MacVim GUI async sometimes doesn't display signs

### ISSUE THREAD

**Issue by airblade** [airblade/vim-gitgutter#349]
This seems to happen when one opens a file which already has some unstaged changes.

It doesn't occur in terminal MacVim, only GUI MacVim.

It's intermittent.  The problem presumably lies with GUI MacVim's channel implementation.

**Comment by mssalvatore** [comment]
I'm actually seeing this behavior in the terminal with:
MacVim 7.4
vim 7.4
nvim 0.1.5-dev

GUI MacVim seems work most consistently for me, while all terminal vims are hit-or-miss.

**Comment by airblade** [comment]
I haven't seen this since upgrade Vim/MacVim to v8.  @mssalvatore Have you?

**Comment by mssalvatore** [comment]
I just upgraded to v8, so I'll have to let you know in a few days.

**Comment by airblade** [comment]
I haven't seen this for over a month so I'm going to assume it's fixed.  Let me know if you still have problems.
