### ISSUE TITLE
Error detected while processing function gitgutter#async#handle_diff_job_vim_close[8]

### ISSUE THREAD

**Issue by 7KVZw8C** [airblade/vim-gitgutter#351]
Why i'am getting this error, and what does it mean?

```
Error detected while processing function gitgutter#async#handle_diff_job_vim_close[8]..gitgutter#handle_diff[15]..gitgutter#sign#update_signs[1]..gitgutter#sign#find_curr
ent_signs:
line    7:
E158: Invalid buffer name: 
line    6:
E121: Undefined variable: signs
E121: Undefined variable: signs
```

i'am using vundle, all plugins are up to date
echo has('signs') return 1

**Comment by airblade** [comment]
I've never seen that before.

The stacktrace indicates that the job callback wasn't able to [get the current buffer's number](https://github.com/airblade/vim-gitgutter/blob/c8fa0b33496464de1da9047f9e21a05ba4ce98f2/autoload/gitgutter/async.vim#L121).

In turn this relies on the buffer number already being set so logically it was either set to a bad value or it wasn't set at all.  I can't think how either could occur.

If this happens again, please could you `:set g:gitgutter_log=1`, reproduce the problem, then post the `gitgutter.log` and `channel.log` in vim-gitgutter's installation directory?

**Comment by 7KVZw8C** [comment]
i start disabled my plugins one by one to see with which gitgutter conflict, and i find out that it was this one https://github.com/arnaud-lb/vim-php-namespace and it only occur when i hit <leader>u or <leader>e as they say in the docs, the plugin itself is just 140 line of code, i don't write vim script so i can't tel what cause the conflict. to reproduct this error:

1. install the plugin https://github.com/arnaud-lb/vim-php-namespace with gitgutter
2. in a php project generate ctags so you can use the given plugin
3. try to extend or use a class the key mapping as the plugin say in the docs
4. errors while start to appear every 4 seconds

**Comment by airblade** [comment]
I suspect the problem is related to how the vim-php-namespace plugin jumps around between buffers and the preview window when you activate it.

I have never used php so I don't know how to try it out.  Please could you show me a gist with a php file(s) I can copy and paste to see the problem for myself?

**Comment by Nomad145** [comment]
Hi, @airblade.  I've been having the same issue for a while now.  I'm also using `vim-php-namespace` plugin.  If you still need a test environment, I can help get you one if you're still interested in this bug.

In the meantime, I think it's worth noting that the issue doesn't happen all the time.  It seems to happen less if I'm trying to include a namespace from a local folder than from a vendor folder.  If I have a lot of buffers open and I can't restart Vim, I just use `:GitGutterSignsToggle` and it seems to suppress the error for the time being.

**Comment by airblade** [comment]
@Nomad145 Thanks for the offer.  I can't tackle this bug until I can reproduce the problem, and I can't do that because I have no idea how to set up PHP.

Please could you or @7KVZw8C give me a minimal set of steps I can copy and paste to reproduce the problem?

Thanks.

**Comment by Nomad145** [comment]
Alright.  I have a simple test case that is failing for me consistently.

```
git clone https://github.com/myclabs/php-enum.git
cd php-enum/src
```

For this example, we need to generate Ctags.  Here's a link to a gist containing my ctags file.  https://gist.github.com/Nomad145/0aaa0c6db0bd4514f7e2b04024094160

Paste the following into `TestEnum.php`:

```
<?php

class TestEnum extends Enum
{
}
```

With the cursor over `Enum` in Vim (`gg2j$`), execute `:call IPhpInsertUse()`.

If you have any issues with anything, let me know.  Hopefully this is all you need to reproduce.  Thanks for your help!

**Comment by ysolis** [comment]
I have exactly the same problem, with Python programs (no PHP related) i open 4 buffers and the problem happens if I try to close the 4 buffers with a `:bufdo bw` command. If I close the four buffers manually with `:bw` four times, the problem don't happens.

**Comment by airblade** [comment]
Thanks @Nomad145 and @ysolis.

I think I have fixed this...please could you try out branch [issue-351](https://github.com/airblade/vim-gitgutter/tree/issue-351) and let me know?

**Comment by Nomad145** [comment]
Works for the test case I wrote up.  I'll continue using it and report any problems I find.  Thanks for getting a fix out for this so soon.

**Comment by ysolis** [comment]
corrected in my case with the same scenario with the branch indicated

**Comment by airblade** [comment]
Thanks for the feedback.  The fix is now in master at 373ad73.

**Comment by Nomad145** [comment]
Just wanted to stop in and say thanks @airblade for your work on this.  It's much appreciated.

**Comment by airblade** [comment]
Thanks @Nomad145!

**Comment by tnguyen14** [comment]
Hi, I'm seeing a similar error, but I don't use `vim-php-namespace`:

```
Error detected while processing function gitgutter#async#handle_diff_job_nvim:
line    1:
E121: Undefined variable: self
```

How should I debug this issue further?

**Comment by airblade** [comment]
@tnguyen14 Are you using the latest version of gitgutter?  What version of nvim are you using?

**Comment by tnguyen14** [comment]
@airblade I'm on nvim version `0.2.0-dev`. I use vim-plug, and I did `PlugUpdate` a few times. Apparently that did not pull down the latest version of gitgutter. I had to `cd` into the `~/.vim/plugged/vim-gitgutter` directory directly and pull down the latest version of master. This seems to make the error go away now.

**Comment by airblade** [comment]
@tnguyen14 Glad to hear the error has gone away.

**Comment by jvortmann** [comment]
After the same error above, I've got the error below when trying to update the plugins using VimPlug under Neovim 0.2.

![screen shot 2017-05-08 at 3 15 51 pm](https://cloud.githubusercontent.com/assets/57185/25818638/a3f3557c-3401-11e7-9521-442bc367ccfc.png)

What @tnguyen14 suggested worked: I removed the plugin folder and reinstalled it successfully.

**Comment by airblade** [comment]
@jvortmann Weird, I don't know why you would get "refusing to merge unrelated histories".  Anyway, thanks for letting everyone know.

**Comment by ram535ii** [comment]
Just in case it helps anyone else, doing what @tnguyen14 suggested and manually `cd` into `~/.vim/plugged/vim-gitgutter` and just doing `git pull` fixed it for me as well.
