### ISSUE TITLE
Vim startup is slow

### ISSUE THREAD

**Issue by bronzovik** [airblade/vim-gitgutter#353]
Hi,

my vim startup is really slow when using gitgutter. It is pretty much instant if I disable the plugin.
The file I'm trying t open is a 35 lines python code file.

OSX version 7.4.1817, latest plugin.

Any advice how can I debug the issue?

Cheers,
A.

**Comment by airblade** [comment]
It should be instant so something's gone awry.

The first step is to [profile it](https://github.com/airblade/vim-gitgutter/wiki/How-to-profile-vim-gitgutter).  We can go from there.

**Comment by bronzovik** [comment]
1. Upgraded to version 7.4.1952 via brew update
2. Wiped out ~/.vim/bundle
3. re-installed all bundles (NeoBundle).

it won't work at all if you skip 2 & 3

The load is instant.
