### ISSUE TITLE
Error in opening files with VIM and plugin

### ISSUE THREAD

**Issue by hugohy** [airblade/vim-gitgutter#356]
When I open vim to edit a file (like any xPP file or even .vimrc file), there is this error message:
My .vimrc has 138 lines, the last one is empty, I can't figure out 
```
"~/.vimrc" 138L, 4290C
Error detected while processing function gitgutter#utility#git_supports_command_
line_config_override..gitgutter#utility#git_version:
line    1:
E484: Can't open file /tmp/v1ry8BY/0
```

Although saving changes on those files are ok, similar error message is shown:
```
Error detected while processing function gitgutter#utility#git_supports_command_
line_config_override..gitgutter#utility#git_version:
line    1:
E484: Can't open file /tmp/vcbGLRP/1
```
What could that be?
Using
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52

**Comment by airblade** [comment]
Please can you do `:let g:gitgutter_log=1`, use vim until you see the error, then post the `gitgutter.log` in the directory where vim-gitgutter is installed?

Also what does `:GitGutterDebug` say?

**Comment by hugohy** [comment]
:GitGutterDebug says:
Error detected while processing function gitgutter#utility#git_supports_command_line_config_override..gitgutter#utility#git_version:
line    1:
E484: Can't open file /tmp/vw4gH4Y/0

Then it opens a (?)buffer(?) (text saved in attached file):
[out.txt](https://github.com/airblade/vim-gitgutter/files/350346/out.txt)

I couldn't find any gitgutter.log on ~/.vim/bundle/vim-gitgutter
Searching deeper on my home directory

**Comment by airblade** [comment]
Are you running the latest version of vim-gitgutter?

What does `:echo system("git --version")` produce?

**Comment by hugohy** [comment]
Yes I downloaded from Git repositories yesterday.
IDK why on work computer these steps didn't work at all. It couldn't run the last command either. Tomorrow, I'll try to reinstall it.

I tried on my personal computer and everything went smoothly. git version1.9.1 is the version on my own computer.
:GitGutterDebug output:
[out.txt](https://github.com/airblade/vim-gitgutter/files/351129/out.txt)

**Comment by hugohy** [comment]
Sorry, my bad, it worked fine here at work after deleting whole folder and reinstalling. I am trying to put dotfiles on github, there were missing few steps (maybe still missing) in scripts.

Closing issue...
