### ISSUE TITLE
Error on neovim+termux

### ISSUE THREAD

**Issue by frivoal** [airblade/vim-gitgutter#360]
Everything works fine in other environments, but on termux+neovim, I repeatedly get the following error
```
Error detected while processing function gitgutter#utility#git_supports_command_line_config_overri
de:
line    1:
E688: More targets than List items
```

**Comment by airblade** [comment]
Does the solution in #323 help?

**Comment by airblade** [comment]
Any progress with this?

**Comment by frivoal** [comment]
Sorry for the slow follow up, I got side tracked. I am not entirely sure which part of #323 is supposed to help, but running 
`:let [major, minor, patch; _] = split(matchstr(system('git --version'), '[0-9.]\+'), '\.')`
as suggested runs without errors. Both
`:!git --version` and `:echo system('git --version')`
give `git version 2.10.0`, which looks legit.
`:echo matchstr(system('git --version'), '[0-9.]\+')` gives `2.10.0`, so no problem there.

So the problem is coming from somewhere else. I am not at all familiar with vim plugins internal. Any idea how to debug this and let you know what fails?

**Comment by frivoal** [comment]
Ok, I tested some more, and if I run the following commands while not opening a file that is version-controlled by git, I get the results above.

However, if I am editing a file that is version-controlled by git, `:!git --version` gives me
`Cannot execute /bin/sh

shell return -1`

No idea what's causing that.

**Comment by frivoal** [comment]
I cannot see anything in my startup scripts that would cause this, but just in case it is indeed there and I'm just not seeing it, they are here: https://github.com/frivoal/dotfiles

**Comment by airblade** [comment]
Sorry, I should have been more specific.  I was wondering whether you had some shell or terminal configuration which interfered invisibly with the output of commands (e.g. [this](https://github.com/airblade/vim-gitgutter/issues/323#issuecomment-215436286)).  I looked at your dotfiles but couldn't see anything, though I'm not familiar with termux.

Do you get the problems if you don't use termux?

What does `:GitGutterDebug` produce?

What OS are you on?

**Comment by frivoal** [comment]
> I looked at your dotfiles and saw this which appears to change the shape of your cursor.

That only has an effect when I'm on my linux box, using the ["Terminal"](https://en.wikipedia.org/wiki/Terminal_(Xfce)) terminal emulator from Xfce. That's not the environment I'm having issues with.


> Do you get the problems if you don't use termux?
> What OS are you on?

The OS under which I'm having issues is android, on my phone. I cannot not use termux, since termux is the thing that adds an linux-like environment to Android.

**Comment by frivoal** [comment]
> What does :GitGutterDebug produce?

NVIM 0.1.6-dev
Build type: MinSizeRel
Compilation: /home/fornwall/.termux-build/_lib/toolchain-arm-ndk12-api21-gcc4.9-v1/bin/arm-linux-androideabi-gcc -specs=/home/fornwall/dc/termux.spec -march=armv7-a -mfpu=neon -mfloat-abi=softfp -Os -I/data/data/com.termux/files/usr/include -isystem /data/data/com.termux/files/usr/include/libandroid-support -Wconversion -Os -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/fornwall/.termux-build/neovim/build/config -I/home/fornwall/.termux-build/neovim/src/src -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include -I/home/fornwall/.termux-build/neovim/build/src/nvim/auto -I/home/fornwall/.termux-build/neovim/build/include






updatetime=4000
shell=/bin/sh
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=

**Comment by airblade** [comment]
Your [comment above](https://github.com/airblade/vim-gitgutter/issues/360#issuecomment-247202098) is interesting.

When this plugin runs a diff, it sets the `shell` option to `/bin/sh` (and a couple of related options) for the duration of the command, then sets them back to their original values.

However the diff is erroring out, which probably leads to those options not being restored.  This would explain why the command in your comment works before you edit a git-tracked file and not after.

I found termux/termux-app#104 which seems to say that under Termux `/bin/sh` doesn't exist.  Instead the path is `/system/bin/sh`.  Is this the case on your installation?  If so, please could you update [this line](https://github.com/airblade/vim-gitgutter/blob/373ad7337b973af149276d67694c543b8cadee6a/autoload/gitgutter/utility.vim#L190) accordingly and let me know if it solves the problem?

If not, please could you open a fresh vim (without editing any file), and tell me what `:echo &shell` gives?

**Comment by frivoal** [comment]
> under Termux /bin/sh doesn't exist. Instead the path is /system/bin/sh. Is this the case on your installation? 

There is indeed a `/system/bin/sh` and no `/bin/sh`.

There's also one in `/data/data/com.termux/files/usr/bin/sh`, which is a symlink to `/data/data/com.termux/files/usr/bin/dash`. Not entirely sure which is for what, but I suppose that `/system/bin/sh` is what you'd normally expect to find in `/bin/sh`, while the other one is what you'd normally find in `usr/bin/sh`. For what it's worth, `which sh` points me to `/data/data/com.termux/files/usr/bin/sh`.

> If so, please could you update this line accordingly and let me know if it solves the problem?

I've updated it to `/system/bin/sh` That alone doesn't solve it, as I then get a different-but-similar error, but if I also update [this line](https://github.com/airblade/vim-gitgutter/blob/373ad7337b973af149276d67694c543b8cadee6a/autoload/gitgutter/async.vim#L27) and [that one](https://github.com/airblade/vim-gitgutter/blob/373ad7337b973af149276d67694c543b8cadee6a/autoload/gitgutter/async.vim#L58) then it does work.

Should I just use that as a local fix, or can you make some upstream change that will do the right thing regardless of where `sh` lives?

**Comment by airblade** [comment]
Thanks for the feedback.

Please pull the latest commit (402257f) and add `let g:gitgutter_sh="/system/bin/sh"` to your vimrc.  Everything should then work properly.

**Comment by airblade** [comment]
Hmm, I wonder if that's the best solution.  Is `sh` on your path?  If so, the plugin could just call `sh` everywhere instead of using an absolute path...

**Comment by Neo-Oli** [comment]
> the plugin could just call sh 

`let g:gitgutter_sh="sh"` does indeed work on termux+neovim (I had the same error in the same environment) and is preferable, because `/system/bin/sh` is the system sh in android, but termux normally uses a different one (`$PREFIX/bin/sh` which would be `/data/data/com.termux/files/usr/bin/sh`). Using `/system/bin/sh` from termux is not really supported.

**Comment by airblade** [comment]
Thanks @Neo-Oli.  I've updated the code to just use `sh`.  Hopefully this works for everybody.
