### ISSUE TITLE
GitGutter errors after 'C' tab close in CtrlSpace plugin

### ISSUE THREAD

**Issue by unclechu** [airblade/vim-gitgutter#361]
NeoVim (also I can reproduce it in old Vim).
![selection_207](https://cloud.githubusercontent.com/assets/799353/17104077/54d2a4e4-5292-11e6-9844-62c2082c1900.png)
When I open CtrlSpace panel and close current tab by `C` key, then I get this error every time when I switch between tabs or buffers.

**Comment by unclechu** [comment]
But if I close every by buffer by `c` key and then press `lc` to close tab, it won't get any errors.

**Comment by unclechu** [comment]
It also happens when I just reload again my workspace by `CtrlSpace`.

**Comment by airblade** [comment]
The error message in your screenshot points to [this line](https://github.com/airblade/vim-gitgutter/blob/26c6b549f287b8ae348eda083e7c77f79f4de28b/autoload/gitgutter/sign.vim#L76):

```viml
redir => signs
```

I don't understand how that could throw an E121 error.

Which version of vim-gitgutter are you using?  I.e. which commit is yours at?

**Comment by airblade** [comment]
I wonder if this is related to #351.

**Comment by unclechu** [comment]
@airblade I can reproduce it with latest version (updated today). I can't see any release tags in this repo to say which version is latest for this moment.

**Comment by airblade** [comment]
I think I have fixed this...please could you try out branch [issue-351](https://github.com/airblade/vim-gitgutter/tree/issue-351) and let me know?

**Comment by airblade** [comment]
I think this is fixed so I'm closing the issue now.  Please let me know if there's still a problem and I'll reopen it.

**Comment by unclechu** [comment]
@airblade  sorry about delay, I confirm that I can't reproduce this bug after last update. Thanks a lot!
