### ISSUE TITLE
Version of GitGutterNextHunk that goes through all files

### ISSUE THREAD

**Issue by mkollaro** [airblade/vim-gitgutter#362]
I would like to have a command that would go trough ALL the hunks in the project, not just the current file.  Is this already somehow possible?

**Comment by airblade** [comment]
It's not built in but you could write a VimL function to wrap `GitGutterNextHunk` and go to the next buffer's next hunk when there are no more hunks in the current buffer.

**Comment by airblade** [comment]
I've added a [section to the README](https://github.com/airblade/vim-gitgutter#cycle-through-hunks-in-all-buffers) explaining how to do this.

You'll need commit 8576f00 for it to work.

**Comment by shmup** [comment]
I think that is a good idea, and I think it's best if you map @airblade's suggestion to a capital `C`, such as:

```
nmap <silent> ]C :call NextHunkAllBuffers()<CR>
nmap <silent> [C :call PrevHunkAllBuffers()<CR>
```

This way you can still get the (sometimes preferred, if not usually) `[c` and `]c` local buffer only behavior

**Comment by shmup** [comment]
Ok this would be a lot more useful if you could `[C` and `]C` (cycle) through all of the hunks/changes in the repo, regardless of if the buffer is already open. 

I need this, and I'll work on it

**Comment by KevinLeigh** [comment]
Hey @shmup! 

This is very late, but found a temporary solution that works quite well, while trying to find a way to cycle through all git changes/hunks across all edited files, please see below ->

1) Set vim as default git editor in your terminal env file (i.e .zshenv)
```
export VISUAL=vim
export EDITOR="$VISUAL"
```
2) Source your terminal env file (for me the file will be ~/.zshenv)
```
source ~/.zshenv // <-- change this to your terminal env file
```

3) Add alias to ~/.gitconfig
```
[alias]
  edit = !$EDITOR $(git status --short | awk '$1 ~ /^M|A|U/ {print $2}')
```

4) Add config from comment to your .vimrc -> https://github.com/airblade/vim-gitgutter/issues/362#issuecomment-434713641

5) Inside your repo directory where you made multiple changes to different files, you can now run command
```
git edit
```

This will open all the files that you edited inside your repo in vim buffers, and then you can use `[C` and `]C`  to cycle through all the changes/hunks

Hope this helps!
