### ISSUE TITLE
GitGutter doesn't work

### ISSUE THREAD

**Issue by occia** [airblade/vim-gitgutter#363]
Hi,I use Vundle to install the GitGutter,use this command in my .vimrc.
`Plugin 'airblade/vim-gitgutter'`
And then I input PluginInstall,and everything seems OK.
But when I modify a local file like a.txt,no effects at all.The airline appears +0 ~0 -0,but it never changes,always be 0.And then I tried to input :call GitGutter(),it shows Unknown function: GitGutter.Is there something I missed?Can I use Vundle to install gitgutter?I can't find the vundle part tutorial in README.Any help is appreciated and thanks anyway!
![image](https://cloud.githubusercontent.com/assets/14798217/17202682/45ef7b22-54cd-11e6-82c6-cbb7b30de9ef.png)

**Comment by airblade** [comment]
Does `:GitGutter` work?  (It's a command not a function.)

You can install vim-gitgutter any way you like, including Vundle.  However I don't know whether Vundle is working properly for you.

In Vim, `:scriptnames` will tell you which plugin files are loaded.  Do you see any `vim-gitgutter` files listed?

**Comment by occia** [comment]
![image](https://cloud.githubusercontent.com/assets/14798217/17729412/b18967fc-6496-11e6-82af-77f8ffcc5f02.png)
Oh,it has been listed.But I still can't let it work.For example , I use vim a.txt , and input sth,and :w .Then the gutter appear,with no sign.And the airline's status bar '+0 ~0 -0' never changes.
![image](https://cloud.githubusercontent.com/assets/14798217/17729474/ff27cab2-6496-11e6-811a-e6ba941cbf46.png)
![image](https://cloud.githubusercontent.com/assets/14798217/17729557/5977177a-6497-11e6-90ee-d0f4fcbf9296.png)

**Comment by airblade** [comment]
What does `:!git status a.txt` print?

**Comment by occia** [comment]
![image](https://cloud.githubusercontent.com/assets/14798217/17730148/10a72906-649a-11e6-9f1f-3f2694ec5fa4.png)

**Comment by airblade** [comment]
vim-gitgutter works with git repositories.  Your file `a.txt` isn't in a git repository so there's nothing for vim-gitgutter to do.  It's behaving correctly.

**Comment by occia** [comment]
Okay,sorry to bother you a lot.I think it is using in arbitrary file before.Sorry...
