### ISSUE TITLE
Force gitgutter refresh

### ISSUE THREAD

**Issue by amigrave** [airblade/vim-gitgutter#364]
Hi,

I'd like to force gitgutter refresh when I press <kbd>Ctrl+L</kbd>, so basically I'd like to:

```vim
nnoremap <C-l> :GitGutterRefresh<CR><C-l>
```

Of course there's no `GitGutterRefresh` command so I wonder if there's a way to force the refresh ?

**Comment by airblade** [comment]
The `GitGutter` command will refresh the current buffer and `GitGutterAll` will refresh all visible buffers.

**Comment by amigrave** [comment]
Oh right ! Sorry for not spotting the obvious. Thanks !
