### ISSUE TITLE
modify diff hunk size?

### ISSUE THREAD

**Issue by joe-lawrence** [airblade/vim-gitgutter#366]
I might have missed this in the docs somewhere, but is there anyway to change the size of the current hunk?   The use-case here would be staging/reverting parts of a hunk instead of the entire hunk... kind of like git gui's "single line" feature or git add --patch's "split hunk" feature.

**Comment by airblade** [comment]
I'd like this too.   I haven't found time to implement it yet but I plan to.

There's a discussion at #279 so I'll close this issue as a duplicate.
