### ISSUE TITLE
Preview hunk

### ISSUE THREAD

**Issue by timhtheos** [airblade/vim-gitgutter#369]
Hi, I have been using this plugin for almost a year already, but now, I'm curious as to how to preview hunk changes with <Leader>hp but closes the buffer of the changes when the input pointer leaves the changed hunk.

Yep, I can press <Leader>hp, just fine, but is there a way to show and hide it as the pointer enter and leaves the changed hunk/lines?

Thanks. :)

**Comment by airblade** [comment]
Does this do what you want?

```viml
au CursorMoved * if empty(gitgutter#hunk#current_hunk()) |
      \   pclose |
      \ else |
      \   call gitgutter#preview_hunk() |
      \ endif
```

**Comment by timhtheos** [comment]
Hi @airblade ,

Thanks.  It returns an error:

```
Error detected while processing CursorMoved Auto commands for "*":
E117: Unknown function: gitgutter#hunk#current_hunk
```

I suspect, it has to do with:
```
empty(gitgutter#hunk#current_hunk()) 
```

Do you have any idea?  Thank you very much.

**Comment by airblade** [comment]
That error implies the plugin wasn't loaded.  How about this instead?

```viml
au CursorMoved * |
      \ if exists('*gitgutter#utility#is_active') && gitgutter#utility#is_active() |
      \   if empty(gitgutter#hunk#current_hunk()) |
      \     pclose |
      \   else |
      \     call gitgutter#preview_hunk() |
      \   endif |
      \ endif
```

**Comment by timhtheos** [comment]
Hi @airblade ,

At the start of vim, I get:
```
E749: empty buffer
```
to which I tried to resolve, by adding condition(s) such as
```
bufname("%") == ""
```
to no avail.

But after initial launch, where there is a buffer already, I don't get the preview_hunk buffer, instead, I just get a single line buffer at the bottom where the current line where cursor is, is echo'ed.

![](https://www.evernote.com/l/AmIrlbQMOqtPppjmFf6-p7fsF9bB_GR7FNAB/image.png)

Thanks.

**Comment by airblade** [comment]
Oops, my mistake: the `|` on the first line wasn't being treated as a line continuation character.  Sorry about that.

Try this:

```viml
au CursorMoved * if exists('*gitgutter#utility#is_active') && gitgutter#utility#is_active() |
      \   if empty(gitgutter#hunk#current_hunk()) |
      \     pclose |
      \   else |
      \     call gitgutter#preview_hunk() |
      \   endif |
      \ endif
```

**Comment by timhtheos** [comment]
Hi @airblade ,

Still, no result.  I am setting this up in .vimrc file. :)

**Comment by timhtheos** [comment]
I tested the following:
`:pclose` - working fine when I did `<Leader>hp` then `pclose`.
`:call gitgutter#preview_hunk()` - working fine too (same with `<Leader>hp`.
`:call gitgutter#hunk#current_hunk()` - this returns `E117: Unknown function: gitgutter#hunk#current_hunk`.
`exists('*gitgutter#utility#is_active')` - returns nothing.
`gitgutter#utility#is_active()` - returns `E117: Unknown function: gitgutter#utility#is_active`.

**Comment by timhtheos** [comment]
Anyhow, I'm good at the moment with the preview not being closed.

```
au CursorMoved * if !executable('git') |
  \ call gitgutter#preview_hunk() |
  \ endif
```

I'll still be interested in closing it, though. Thanks for the help. 👍

**Comment by airblade** [comment]
I have that chunk of code in my vimrc.  It works for me; I don't know why it doesn't work for you.

`exists('*gitgutter#utility#is_active')` returns `1` (true) or `0` (false).  Try it with `:echo exists('*gitgutter#utility#is_active')`.

I don't know why you would get an E117 error when the plugin has been loaded.

**Comment by airblade** [comment]
Also your code snippet doesn't make sense: it says if I can't call git, show me a hunk preview (which entails calling git).

**Comment by airblade** [comment]
Have you got it working yet?

**Comment by MiChatz** [comment]
I know this Issue is old but I was facing the same issue.
I couldn't access the ```gitgutter#hunk#current_hunk())``` function.
So I added this function on init.vim file

```
function! Current() abort
  let bufnr = bufnr('')
  let current_hunk = []

  for hunk in gitgutter#hunk#hunks(bufnr)
    if gitgutter#hunk#cursor_in_hunk(hunk)
      let current_hunk = hunk
      break
    endif
  endfor

  return current_hunk
endfunction

 au CursorMoved *  if Current() != [] |
      \     GitGutterPreviewHunk |
      \   else |
      \     pclose |
      \   endif
```

**Comment by airblade** [comment]
Thanks for posting that, @MiChatz.

There isn't a `gitgutter#hunk#current_hunk()` function any more.  I would suggest this:

```viml
au CursorMoved * if gitgutter#hunk#in_hunk(line(".")) | GitGutterPreviewHunk | else | pclose | endif
```

**Comment by Midren** [comment]
For me, it was not convenient to always see the hunk preview, as it was hiding the real code, so I slightly modified `in_hunk` function to show preview only if a cursor is on the last line on hank. So, if anyone needs a similar solution:
```vim
function! s:in_last_hunk_line(lnum) abort
  " Hunks are sorted in the order they appear in the buffer.
  for hunk in gitgutter#hunk#hunks(bufnr(''))
    " if in a hunk on first line of buffer
    if a:lnum == 1 && hunk[2] == 0
      return 1
    endif

    " if in a hunk generally
    if a:lnum >= hunk[2] && a:lnum == hunk[2] + (hunk[3] == 0 ? 1 : hunk[3]) - 1
      return 1
    endif

    " if hunk starts after the given line
    if a:lnum < hunk[2]
      return 0
    endif
  endfor

  return 0
endfunction

autocmd CursorMoved * if s:in_last_hunk_line(line(".")) | GitGutterPreviewHunk | else | pclose | endif
```
