### ISSUE TITLE
Saving file hangs vim for ~20 seconds

### ISSUE THREAD

**Issue by iryan2** [airblade/vim-gitgutter#373]
Found GitGutter to be the culprit from [this thread](https://github.com/spf13/spf13-vim/issues/349)

Every time I save a js file, terminal nvim freezes for 20 seconds or so.

run `:GitGutterDisable` and it's back to normal.

I've disabled GitGutter in my vimrc for now, would really like to use it again!

Edit: strangely, the problem persists after disabling GitGutter so sorry if this blame is misplaced. However, if I re-enable it and run `:GitGutterDisable`, the problem does go away.

Any help would be appreciated but I understand if you'd prefer to close this issue ;)

Edit 2: `:GitGutterDisable` only temporarily fixes the issue. I think it's clear that something else is to blame so I apologise for creating this issue.

**Comment by airblade** [comment]
The best way to track down the problem is to profile vim while you save a js file: see `:h profile`.

**Comment by iryan2** [comment]
Thanks, turns out it was [syntastic](https://github.com/scrooloose/syntastic). I've been meaning to switch to [neomake](https://github.com/neomake/neomake/) for a while, so I did and it's great!

Appreciate the help :)
