### ISSUE TITLE
Jumping to a tag produces E12: Command not allowed from exrc/vimrc in current dir or tag search

### ISSUE THREAD

**Issue by mgedmin** [airblade/vim-gitgutter#374]
I used `:tag` to jump to a tag, then `:split` the window and used `:tsel` to jump to a different definition of the tag, and got this error:

```
Error detected while processing function gitgutter#async#handle_diff_job_vim_close[10]..gitgutter#handle_diff:
line    3:
E12: Command not allowed from exrc/vimrc in current dir or tag search
```

**Comment by airblade** [comment]
I've never seen that before.

Were your two definitions in different buffers?

**Comment by mgedmin** [comment]
Yes, different files.

**Comment by mgedmin** [comment]
Oh dear, if I understand this right, it was vim that invoked the gitgutter#async#handle_diff_job_vim_close() function asynchronously when an external process finished, and it just so happened to happen while vim was performing a tag search?  Ouch.  Reproducing this may be difficult, if it's indeed a race.

I'm also not a fan of the way it blames an empty line of source code.

**Comment by airblade** [comment]
Something is triggering the plugin to run a diff, which happens asynchronously by default, and when the async job is complete it calls back.

The stack trace points to [this line](https://github.com/airblade/vim-gitgutter/blob/402257f920ea7e75af6c0a0c1a33ec4c0cd9d4a8/autoload/gitgutter.vim#L47), assuming you're running the latest version of the plugin.  I have no idea why that would raise an E12 error.

**Comment by mgedmin** [comment]
Yes, I'm on the current version (commit 402257f).

**Comment by airblade** [comment]
Please can you update vim-gitgutter and try it again?

**Comment by mgedmin** [comment]
I've updated vim-gitgutter and will report if this happens again.

(I've seen this error perhaps twice more since I reported the bug, so it's not exactly easy to reproduce.)

**Comment by mgedmin** [comment]
This happened again.

Possibly relevant: I had an outdated tags file, and so vim produced
```
E435: Couldn't find tag, just guessing!
```

right before the

```
Error detected while processing function gitgutter#async#handle_diff_job_vim_close[11]..gitgutter#handle_diff:
line    3:
E12: Command not allowed from exrc/vimrc in current dir or tag search
```

(and then immediately the same E12 in another vim plugin).

**Comment by mgedmin** [comment]
This is reproducible, but apparently only when my tags file is outdated.  It doesn't matter if I use Ctrl-] or Ctrl-W Ctrl-] to jump to the tag. It matters that the tag is in a different file than when I started from.

The `tags` file had an outdated Python function signature

```
_create_project	testdata.py	/^def _create_project(qvarn, name, project_id, responsible_org_reg_no):$/;"	f
```

meanwhile the current source code had the same function with some extra arguments, added in a recent commit.

(For the record, vim guesses correctly and finds my function.)

**Comment by mgedmin** [comment]
FWIW I haven't seen this bug in a long time.

**Comment by airblade** [comment]
Ok, let's hope it's gone away.  Thanks for the update!

**Comment by airblade** [comment]
This is solved in https://github.com/vim/vim/issues/8511.
