### ISSUE TITLE
vim-gitgutter sets `&shell` to `sh` and doesn't set it to origial value

### ISSUE THREAD

**Issue by unclechu** [airblade/vim-gitgutter#379]
`Vundle.vim` commit hash: `fef1c2f31862c44cf5295ef86c086efba4af20a9`
`vim-gitgutter` commit hash: `297678a08da0c2d1819d6cb98504f8a843395456`

Minimal config example (neovim): https://gist.github.com/unclechu/01578f6380fff18be8f67478844736a2

I guess may be something wrong with these helpers?: https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/utility.vim#L191-L208

Also you could watch this screencast that demonstrates this issue: https://youtu.be/YOi-DynJmaE

**Comment by airblade** [comment]
Thanks for reporting this.  I can reproduce it and I'll work on a fix.

**Comment by unclechu** [comment]
@airblade thanks a lot for the fix!

**Comment by unclechu** [comment]
@airblade I still can reproduce the issue using `:GitGutterUndoHunk` command.

**Comment by airblade** [comment]
Oops.  It should be ok now.

**Comment by unclechu** [comment]
@airblade now it's ok, thanks again!
