### ISSUE TITLE
Unknown function: job_start

### ISSUE THREAD

**Issue by przepompownia** [airblade/vim-gitgutter#380]
Hi,

it would be good to disable `vim-gitgutter` for vim binaries that are compiled without `job`.

**Comment by airblade** [comment]
You don't need to disable the entire plugin: `job` is only needed for asynchronous diffing.  You can `let g:gitgutter_async=0` to turn that off and run the diffs synchronously (to be honest I don't notice any speed difference between sync and async).

However the plugin [already tries to detect](https://github.com/airblade/vim-gitgutter/blob/0d455a7af787176864612cde69a72f1a07cfc35a/autoload/gitgutter/async.vim#L12-L16) whether `job` is supported.  It doesn't explicitly check for `job` though; did you exclude job support when you compiled Vim?

**Comment by przepompownia** [comment]
As I have experienced, not each [sufficiently fresh](https://github.com/airblade/vim-gitgutter/blob/0d455a7af787176864612cde69a72f1a07cfc35a/autoload/gitgutter/async.vim#L12-L16) vim instance has 'job' support compiled. Why not to explicitly check this?

**Comment by airblade** [comment]
Closed by 64a445b.
