### ISSUE TITLE
realtime updates cause whole file to be marked as added

### ISSUE THREAD

**Issue by relapi** [airblade/vim-gitgutter#382]
Opening a file and changing one line causes every line in the file to be marked as added. I have verified that this occurs with a minimal vimrc (just pathogen), no packages installed other than GitGutter, and no local or global gitconfig. Saving the file causes GitGutter to display the correct diff in the sign column.

Operating System: OS X 10.11.6
GitGutter version: 64a445b

:GitGutterDebug output

```

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 26 2016 12:44:21)
MacOS X (unix) version
Included patches: 1-46

git version 2.10.1

grep (BSD grep) 2.5.1-FreeBSD
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]] [-e pattern] [-f file] [--binary-files=value] [--color=when]    [--context[=num]] [--directories=action] [--label] [--line-buffered]    [--null] [pattern] [file ...]

updatetime=4000
shell=/usr/local/bin/zsh
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

**Comment by relapi** [comment]
Looking into this a bit more and found some very very odd behavior...

This bug seems to only be happening on most files in a Rails project. Setup / repro steps below

- Empty gitconfig
- Vimrc contents...
~~~~
call pathogen#infect()
call pathogen#helptags()
filetype plugin indent on
syntax enable
set updatetime=250
~~~~
- Pathogen installed
- Gitgutter installed
- rails new testapp
- git init && git commit -m 'initial commit'
- vim app/controllers/application_controller.rb
- make changes
- gitgutter thinks every line is new (see below)
![screen capture on 2016-10-26 at 15-12-08](https://cloud.githubusercontent.com/assets/23083813/19743429/e558dff2-9b8e-11e6-9638-66265f84992c.gif)

**Comment by airblade** [comment]
That's weird.  What's your git config?

**Comment by relapi** [comment]
output of git config -l in the new rails app repo I created as part of my previous comment....

~~~~
credential.helper=osxkeychain
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
~~~~

**Comment by airblade** [comment]
I followed your steps but gitgutter worked as expected for me.  I'm on OS X 10.11.6, vim-gitgutter @ ee48158, git 2.9.0, vim 8.0 included patches 1-3.

My current hypothesis is that this is due to different line endings, which the "realtime" update code path notices but the "on-save" code path ignores.

Do you still get the problem with `let g:gitgutter_diff_args="-w"` in your vimrc?  How about if you turn off async diffing with `let g:gitgutter_async=0`?

**Comment by relapi** [comment]
The issue still occurs with the following in my vimrc
~~~~
let g:gitgutter_diff_args="-w"
let g:gitgutter_async=0
~~~~

Doing a little more digging / debugging, I made gitgutter echo the command it is using to diff for realtime diffs right here: https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/diff.vim#L126

This is the command that is run...
~~~~
cd app/controllers && (git show :'/Users/relapi/Dropbox/Code/Rails/testapp/app/controllers\
app/controllers/application_controller.rb' > /var/folders/fr/wl33_5ns491582xh1__hjzth0000gn/T/vSQRWZ2/2.rb && git -c "diff.autorefreshindex=0" diff --no-ext-diff --no-color -U0 -w  -- /var/folders/fr/wl33_5ns491582xh1__hjzth0000gn/T/vSQRWZ2/2.rb /var/folders/fr/wl33_5ns491582xh1__hjzth0000gn/T/vSQRWZ2/3.rb | grep --color=never -e '^@@ ' || exit 0)
~~~~

The problem looks to be with this part of the command, specifically that gitgutter is determining the blob_name incorrectly, which makes git show output nothing, so the diff will show that the whole file is added:
~~~~
git show :'/Users/relapi/Dropbox/Code/Rails/testapp/app/controllers\
app/controllers/application_controller.rb'
~~~~

**Comment by airblade** [comment]
Aha!  Yes, I agree the blob name looks wrong, and that would explain why every line in the buffer is marked as changed.

The blob name after the colon comes from `gitgutter#utility#shellescape(gitgutter#utility#file_relative_to_repo_root())` (line 71).  Please could you add `:echo gitgutter#utility#file_relative_to_repo_root()` to gitgutter?  Hopefully we can isolate where the problem actually is.

**Comment by relapi** [comment]
`:echo gitgutter#utility#file_relative_to_repo_root()`

outputs...

~~~~
/Users/relapi/Dropbox/Code/Rails/testapp/app/controllers
app/controllers/application_controller.rb
~~~~

**Comment by airblade** [comment]
I can't imagine why there would be a new line in the middle of the path.  The [file_relative_to_repo_root](https://github.com/airblade/vim-gitgutter/blob/1742a8f568df549f4daeda90174b54d0c371501f/autoload/gitgutter/utility.vim#L138-L147) function basically does this:

- runs `git rev-parse --show-prefix` to get the path of the current directory relative to the repo's top-level directory
- strips the trailing new line from the directory (an artifact of vim's `system()` function)
- appends the filename

Please could you add an `:echo` after each line to pinpoint where the new line in the middle of the path appears?

**Comment by relapi** [comment]
This:
~~~~
gitgutter#utility#system(gitgutter#utility#command_in_directory_of_file(g:gitgutter_git_executable.' rev-parse --show-prefix')
~~~~

and digging down further, specifically this line in system()

~~~~
silent let output = (a:0 == 0) ? system(a:cmd) : system(a:cmd, a:1)
~~~

returns

~~~~
/Users/relapi/Dropbox/Code/Rails/testapp/app/controllers
app/controllers/
~~~~

**Comment by airblade** [comment]
Could you `echo a:cmd` just above the `silent let output...` line?

**Comment by relapi** [comment]
Also... system(a:cmd) is what's running...

echo(a:cmd) => "cd app/controllers && git rev-parse --show-prefix"
echo(system(a:cmd)) => 
~~~~
/Users/hoth/Dropbox/Code/Rails/testapp/app/controllers
app/controllers/
~~~~

**Comment by relapi** [comment]
Running :echo system("cd app/controllers && git rev-parse --show-prefix") manually in vim yields:
~~~~
app/controllers/
~~~~

**Comment by airblade** [comment]
Do you have any zsh configuration which echoes the absolute path of current directory after a command?

**Comment by relapi** [comment]
Got it figured out... looks like it was caused by zsh cdpath. Removing the current directory '.' from it fixed the issue.

Specifically I changed it from...

~~~~
export CDPATH=.:$HOME/Dropbox:$HOME/Dropbox/Documents
~~~~

to

~~~~
export cdpath=($HOME/Dropbox $HOME/Dropbox/Documents)
~~~~

Thanks SOOOOOOOOOOOOOO much for your help!

**Comment by airblade** [comment]
Good news :)
