### ISSUE TITLE
Question: does gitgutter disable itself for a buffer if no git repo is detected?

### ISSUE THREAD

**Issue by Alok** [airblade/vim-gitgutter#385]
I noticed that gitgutter was enabled on a file that was not in a git repo, which seems odd since it can't do anything useful in that file.

**Comment by airblade** [comment]
Gitgutter doesn't disable itself for a file which isn't in a git repo.  It'll keep trying to process the file, but the first thing it does is run `git ls-files --error-unmatch` which will tell it not to go any further.

The reason gitgutter keeps trying the file is so if you add it to a git repo, gitgutter will automatically start showing signs for it.

**Comment by Alok** [comment]
For performance, wouldn't it be better to only keep trying if the file is in a git repo, even if it's untracked? Since options `g:eager` exist, performance seems to be a concern.

**Comment by airblade** [comment]
Yes, probably.  However I haven't seen any actual slowdown.

The "eager" option is left over from when gitgutter was slower than it is now.  I don't think it's necessary any more.
