### ISSUE TITLE
Gitgutter mappings conflict with native vimdiff mappings

### ISSUE THREAD

**Issue by yevhen-m** [airblade/vim-gitgutter#390]
I have a mapping conflict. Vim diff uses `[c` & `]c` to jump between junks. When I enable gitgutter mappings, they work, but native diff mappings don't. How can I fix this? I really want to use the same mappings, this is the whole point.

**Comment by airblade** [comment]
When you're in a diff, GitGutter should leave `[c` and `]c` [alone](https://github.com/airblade/vim-gitgutter/blob/eaea1c5bba8e0f72cbc923c51a18c5c9918eb513/plugin/gitgutter.vim#L144-L145).

**Comment by yevhen-m** [comment]
Ok, thanks. I've look into it. Must be my mistake then in settings.
