### ISSUE TITLE
Breaks in Neovim after partials commit

### ISSUE THREAD

**Issue by sunjon** [airblade/vim-gitgutter#392]
`Error detected while processing function gitgutter#async#handle_diff_job_nvim:
line    1:
E121: Undefined variable: self`.

I believe it's related to the commit of the partials/timers [patches](https://github.com/neovim/neovim/pull/5529).

**Comment by sondangdev** [comment]
Same issue here with neovim. Plugin works fine with vim.

**Comment by phcerdan** [comment]
Same

**Comment by jamessan** [comment]
This is being tracked in https://github.com/neovim/neovim/issues/5763, however note that this patch will make the function work before and after the partials patch.

```diff
--- a/autoload/gitgutter/async.vim
+++ b/autoload/gitgutter/async.vim
@@ -79,7 +79,7 @@
 endfunction
 
 
-function! gitgutter#async#handle_diff_job_nvim(job_id, data, event) abort
+function! gitgutter#async#handle_diff_job_nvim(job_id, data, event) dict abort
   call gitgutter#debug#log('job_id: '.a:job_id.', event: '.a:event.', buffer: '.self.buffer)
 
 let job_bufnr = self.buffer
```
