### ISSUE TITLE
Automatically update preview window when changing to a different hunk?

### ISSUE THREAD

**Issue by RobBednark** [airblade/vim-gitgutter#396]
Is there a way to automatically show the preview for the hunk the cursor is in?

As I understand it, to show the preview for a given hunk, I have to go that hunk and then do `<leader>hp`   It would be nice if I could go from hunk to hunk and automatically see the preview updated in the preview window.  Is that currently possible?  If not, is it a feature that could be implemented?

**Comment by airblade** [comment]
That sounds similar, though not quite the same as, #369.

It's not directly built-in to gitgutter but you could map your own command which moves to the next hunk and updates the preview window, e.g.:

```viml
nnoremap <silent> <leader>x :GitGutterNextHunk<CR>:GitGutterPreviewHunk<CR>
```

**Comment by airblade** [comment]
Four and a half years later I have added this ;)
