### ISSUE TITLE
Feature request: Colored line numbers

### ISSUE THREAD

**Issue by tuzz** [airblade/vim-gitgutter#397]
Hello, thanks for building a great plugin that I use all the time.

I was wondering how feasible it would be to make gitgutter change the color of the line numbers on diff lines, rather than adding extra symbols into the gutter.

That way, you'd save a little bit of space, allowing buffers to be a bit bigger, which might be significant if you have multiple vsplits open.

I'm happy to help if I can, though I have limited VimL experience.

**Comment by airblade** [comment]
That's a nice idea but unfortunately Vim doesn't allow changing of line numbers' colours on a line by line basis.
