### ISSUE TITLE
Terminal gets destroyed when autowrite is set

### ISSUE THREAD

**Issue by AndrewVos** [airblade/vim-gitgutter#398]
When using `autowrite`, running make will sometimes destroy your terminal output.

I have also tested https://github.com/mhinz/vim-signify and the bug doesn't appear there.

My `vim` dotfiles are [here](https://github.com/AndrewVos/vimfiles).

## Reproduce

```
:set autowrite
```

1. Open a file
1. Make a change to that file, and do *not* save
1. `:make`

## Example

https://asciinema.org/a/4ju8px1w9rpgg5h9n3iagtjrl

Notice how the `Press ENTER` text is now highlighted in green. This is coming from the `+` that would get added to that new line, I assume.

**Comment by airblade** [comment]
I'm not quite sure what the expected result is.  Perhaps you could upload a screenshot (or another asciicinema) or the desired result, e.g. via vim-signify?

**Comment by airblade** [comment]
In the meantime, does the problem occur with `let g:gitgutter_async=0`?

I wonder if this is happening: the `:make` command autowrites the file, which triggers vim-gitgutter, which runs a diff in the background; while that's happening, make is doing its thing; at which point the background job finishes and calls back into vim to update the signs – but the lines aren't where they were.

**Comment by AndrewVos** [comment]
Well in my asciicinema you can see the the terminal output is all broken. Not sure how else I can demo it? Maybe you missed the last frame there? Have a look at `0:16`...

I've set `g:gitgutter_async`, so I'll try that out for a while and report back. It seems to be working for now...

**Comment by AndrewVos** [comment]
The issue is definitely related to `autowrite`. What seems to be happening is:

1. I run make
1. `autowrite` causes a save to happen, which triggers gitgutter
1. The buffer is closed(?) and make happens
1. gitgutter tries to set the sign

Because the buffer isn't open, the terminal gets the sign highlighting probably? Just guessing at this point! Though you do use vim api for setting the sign, so maybe this is a vim bug.

Thanks for your help so far!

**Comment by airblade** [comment]
Does it still happen with async disabled (`let g:gitgutter_async=0`)?

I agree that this looks like a vim bug at this stage...

**Comment by AndrewVos** [comment]
I've been using `g:gitgutter_async` all day and haven't seen the problem occur once! Looks good as a workaround.

I am already missing the async support though :)

**Comment by airblade** [comment]
I'm putting this down to a bug in the way vim handles asynchronous jobs and terminal output.

I'm surprised you're missing the async diffs – for me the synchronous diffs are fast enough to feel instantaneous.
