### ISSUE TITLE
vim-gitgutter and dein and on_event

### ISSUE THREAD

**Issue by Mephistophiles** [airblade/vim-gitgutter#399]
dein has feature 'on_event', which loaded plugin on event, for example 'CursorHold'. This plugin not supported this feature.

https://github.com/Shougo/dein.vim/issues/160

**Comment by airblade** [comment]
How would I make the plugin support that feature?

**Comment by airblade** [comment]
Closing until there's more information.

**Comment by Rikorose** [comment]
Sourcing this plugin increases my nvim's start-up time for more than .5 seconds. I would love to see async plugin loading with either dein.vim or plug.vim. 

Start-up profile:
```
936.378  000.136  000.136: sourcing /home/rik/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter.vim
936.923  000.087  000.087: sourcing /home/rik/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/async.vim
937.170  000.121  000.121: sourcing /home/rik/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/debug.vim
1341.040  402.360  402.360: sourcing /home/rik/.local/share/nvim/plugged/vim-gitgutter/autoload/gitgutter/diff.vim
...
1482.582  106.772: BufEnter autocommands
```

**Comment by Rikorose** [comment]
Yeah this is what I did for profiling, but with neovim instead. It was a quite empty git repo with only two files. vim-signify only takes a few ms.

**Comment by airblade** [comment]
I just tried with neovim and it took 4ms.

**Comment by airblade** [comment]
Are you using an up to date version of the plugin?

**Comment by Rikorose** [comment]
I think so, just did PlugInstall / PlugUpdate

**Comment by airblade** [comment]
Something odd is going on, so it might be worth `cd`ing into the installation directory and seeing what commit the plugin is at there.

The only code that is executed when sourcing `diff.vim` is this:

```viml
function! s:git_supports_command_line_config_override() abort
  call system(g:gitgutter_git_executable.' -c foo.bar=baz --version')
  return !v:shell_error
endfunction

let s:c_flag = s:git_supports_command_line_config_override()
```

If you comment that out, and write `let s:c_flag=0` instead, does it make a difference?

Other than that, I cannot think why your neovim would take 400ms to source a file.

**Comment by Rikorose** [comment]
Yes this fixes the loading time. So I guess this is a git issue on my end?

**Comment by airblade** [comment]
Maybe.  If you run `time git -c foo.bar=baz --version` in your shell and it takes 400ms, then it's a git issue at your end.

If it takes approximately 0ms, then it's some kind of neovim weirdness with `system()`.
