### ISSUE TITLE
recommended addition to docs

### ISSUE THREAD

**Issue by mvolkmann** [airblade/vim-gitgutter#402]
To remove the gutter background color, add this to .vimrc:
````
highlight clear ALEErrorSign
highlight clear ALEWarningSign
````
This is especially useful when using emojis for error and warning signs that are configured like this:
````
let g:ale_sign_error = '💣'
let g:ale_sign_warning = '⚠'
````

**Comment by airblade** [comment]
I don't recognise the ale prefix.  Are you sure you're not thinking of another plugin?

**Comment by mvolkmann** [comment]
Sorry. You are correct. I posted this issue to the wrong repo.
