### ISSUE TITLE
Error detected while processing

### ISSUE THREAD

**Issue by faaaar** [airblade/vim-gitgutter#411]
Error detected while opening macvim
![image](https://cloud.githubusercontent.com/assets/12553862/24754147/d4f6a33a-1b07-11e7-8330-54ced3f0c83b.png)

MacVim version 8.0.525(130)

**Comment by airblade** [comment]
I can't reproduce this with MacVim 8.0.525 (via Homebrew).

Do you still have the problem if you only load vim-gitgutter and not the other plugins you use?

**Comment by faaaar** [comment]
everything is ok now...
maybe the plugin was self-healing when I was sleeping...
hahahah...😂
thanks
