### ISSUE TITLE
Does not show gutter after `:tabedit` or `tab drop` from unnamed buffer

### ISSUE THREAD

**Issue by ohjames** [airblade/vim-gitgutter#413]
Fine:
```
:edit file
```

Not fine:
```
:tabedit
:tabedit file
```

The first `:tabedit` is only there to make sure the second `:tabedit` happens from an unnamed buffer, if you have just started vim then it isn't necessary. After the `:tabedit` from the unnamed buffer the gutter is not shown (it reappears when you re-enter the tab or type `:edit`).

Tested with latest master on neovim `0.1.7`.

**Comment by ohjames** [comment]
If I switch to another tab and back I get the gutter, or run `:edit` and a few other commands.

**Comment by ohjames** [comment]
After more experimenting I can see that this only occurs when you `:tabedit` or `:tab drop` from an unnamed buffer. Doing so from a named buffer works fine.

**Comment by airblade** [comment]
Please can you update and try again?

**Comment by ohjames** [comment]
Cool I'll check it out in 40 mins, thanks!

**Comment by ohjames** [comment]
@airblade Still doesn't work with latest master.

1. vim
2. `:tab drop file-with-changes`
3. Don't see gutter

**Comment by ohjames** [comment]
However `:tabe` now works, and it did not before this change. I switched to using https://github.com/ohjames/tabdrop which supports `:TabDropHere` and does it via `:tabe` so this change helps me even if it doesn't completely fix the bug.

**Comment by airblade** [comment]
Ah, I didn't test `:tab drop`.  What's the difference between `:tabedit` and `:tab drop`?

**Comment by ohjames** [comment]
`:tabedit` always opens a new tab so you can end up with the same file loaded in multiple tabs. `:tab drop` will switch to the tab containing the file if it is already open with one. So I think, it's much nicer to use with a command-t/ctrl-p type plugin than alternatives.

**Comment by ohjames** [comment]
Although my preference is actually the `:TabDropHere` plugin which is just like `:tab drop` but when the file is already open it gets moved to the "current tab position".

**Comment by airblade** [comment]
I added these to my vimrc:

```viml
au TabEnter * echom 'TabEnter'
au BufEnter * echom 'BufEnter'
```

– and then tried your 3 steps [above](https://github.com/airblade/vim-gitgutter/issues/413#issuecomment-297360155).  I got the same result.  It looks like Vim doesn't fire either `BufEnter` or `TabEnter` with `:tab drop file` – which would explain why gitgutter doesn't do anything.

I did a bit of searching and found a similar bug report from 2011: [autocmd bug with 'tab drop' and BufEnter?](http://vim.1045645.n5.nabble.com/autocmd-bug-with-tab-drop-and-BufEnter-td4713311.html).  Naturally nobody ever replied to it ;)

So to get gitgutter working with `:tab drop` we'll need to find a way for `:tab drop` to trigger `BufEnter` or `TabEnter` (or similar).

**Comment by ohjames** [comment]
Maybe could file a bug with the neovim guys. I think that's how you get vim fixed right? Have the neovim guys do it shaming the vim guys into finally getting their fingers out ;)

**Comment by airblade** [comment]
I raised this in vim/vim#1660.

**Comment by airblade** [comment]
Closing this because `:tabedit` is fixed and `:tab drop` is vim's issue.
