### ISSUE TITLE
Plugin doesn't recognize changes, but can operate on them

### ISSUE THREAD

**Issue by amsross** [airblade/vim-gitgutter#416]
Here are the symptoms:
* Signs are enabled but not showing up.
* `:GitGutterNextHunk` or `:GitGutterPreviousHunk` always returns `vim-gitgutter: No more hunks` regardless of git status.
* `:GitGutterStageHunk` correctly stages the hunk under the cursor as expected.
* `:GitGutterPreviewHunk` correctly shows the change under the cursor.

I thought this might be a plugin conflict, so I disabled all plugins via `vi --noplugin [file]` and loaded vim-gitgutter via `source ~/.vim/bundle/vim-gitgutter/plugin/gitgutter.vim`. Unfortunately, calling `:GitGutterNextHunk` returns this error (perhaps I'm not loading the plugin correctly):
```
Error detected while processing function gitgutter#hunk#next_hunk[1]..gitgutter#utility#is_active[1]..gitgutter#utility#is_file_buffer:
line    1:
E121: Undefined variable: s:bufnr
E116: Invalid arguments for function getbufvar(s:bufnr, '&buftype'))
E116: Invalid arguments for function empty(getbufvar(s:bufnr, '&buftype'))
E15: Invalid expression: empty(getbufvar(s:bufnr, '&buftype'))
Press ENTER or type command to continue
```

Here is the output of `:GitGutterDebug` (on 9ecce5a):
```

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 21 2017 07:14:19)
MacOS X (unix) version
Included patches: 1-344

git version 2.11.1

grep (BSD grep) 2.5.1-FreeBSD
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]	[-e pattern] [-f file] [--binary-files=value] [--color=when]	[--context[=num]] [--directories=action] [--label] [--line-buffered]	[--null] [pattern] [file ...]

updatetime=4000
shell=/bin/zsh
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

**Comment by amsross** [comment]
Here's another weird case: `:GitGutterPreviewHunk` opens a new pane to display the diff, at which point gutter signs and `:GitGutter[Next|Previous]Hunk` begins to work. When that pane is closed, those stop working again. `:GitGutterPreviewHunk` on a line that is not a hunk causes gutter signs and Next|Prev Hunk to work and stay working until the file is closed. Upon reopening the issue presents again.

**Comment by airblade** [comment]
Does your grep produce colourful output?

Please can you do `let g:gitgutter_log=1`, edit some file with gitgutter loaded, then paste the gitgutter.log file you'll find in the directory where gitgutter is installed?

**Comment by amsross** [comment]
What do you mean by this?
> Does your grep produce colourful output?

`:grep const index.js` returns results that have color encoding characters (or whatever you call that), but not colors: `index.js|1| ^[[01;31m^[[Kconst^[[m^[[K EventEmitter = require("events").EventEmitter;`

Here's the contents of gitgutter.log:
```


 42.376890 function gitgutter#process_buffer[10]..gitgutter#diff#run_diff[76]..gitgutter#async#execute[47]:
 42.376890 [vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 3 open, 'process': 87770}, buffer: 1] cd . && (git -c "diff.autorefreshindex=0" -c "diff.noprefix=false" diff --no-ext-diff --no-color -U0   -- index.js | grep '^@@ ' || exit 0)

 42.394465 function gitgutter#async#handle_diff_job_vim[1]:
 42.394465 channel: channel 3 buffered, line: ^[[01;31m^[[K@@ ^[[m^[[K-1,2 +1 @@

 42.394786 function gitgutter#async#handle_diff_job_vim[1]:
 42.394786 channel: channel 3 buffered, line: ^[[01;31m^[[K@@ ^[[m^[[K-3,0 +3,3 @@ const h = require("highland");

 42.395041 function gitgutter#async#handle_diff_job_vim[1]:
 42.395041 channel: channel 3 buffered, line: ^[[01;31m^[[K@@ ^[[m^[[K-5,12 +7,27 @@ const config = require("./config");

 42.395295 function gitgutter#async#handle_diff_job_vim[1]:
 42.395295 channel: channel 3 closed, line: ^[[01;31m^[[K@@ ^[[m^[[K-18 +35,25 @@ aggregator

 42.395552 function gitgutter#async#handle_diff_job_vim_close[1]:
 42.395552 channel: channel 3 closed

 42.395928 function gitgutter#async#handle_diff_job_vim_close[11]..gitgutter#handle_diff[1]:
 42.395928 ^[[01;31m^[[K@@ ^[[m^[[K-1,2 +1 @@
^[[01;31m^[[K@@ ^[[m^[[K-3,0 +3,3 @@ const h = require("highland");
^[[01;31m^[[K@@ ^[[m^[[K-5,12 +7,27 @@ const config = require("./config");
^[[01;31m^[[K@@ ^[[m^[[K-18 +35,25 @@ aggregator
```

**Comment by airblade** [comment]
Thanks for all that.  The problem is the colour encoding characters or whatever they are called.

Either you have an alias for grep along the lines of `alias grep="grep --color=always"` or you have something like that in GREP_OPTIONS or similar.

To solve the problem, either figure out what is making grep use the colour codes when called in a shell pipeline, and prevent it, or use `let g:gitgutter_grep_command="grep --color=never"`.

**Comment by amsross** [comment]
That solved it right away. Maybe this was an update I didn't track with my shell.

Thanks for the useful plugin, the quick response, and for helping me out with this problem that was really just my own.

**Comment by airblade** [comment]
Glad we solved the problem.

I just pushed f16cf53 to adjust for GREP_OPTIONS in future.
