### ISSUE TITLE
Buffer is saved when previewing or undoing a hunk

### ISSUE THREAD

**Issue by airblade** [airblade/vim-gitgutter#417]
I wrote the hunk staging / undoing / previewing one after the other, starting with the staging.  It makes sense to save the buffer before staging a hunk – otherwise you'd be staging a hunk which doesn't exist in the working copy.  After that I implemented undoing and previewing and just adapted the code from the staging, including saving the buffer first.

However there's no real reason to write the buffer before previewing or undoing a hunk.

cc @kubapok

**Comment by kubapok** [comment]
I see. Perhaps, it would be a good idea to include this information about saving a buffer during previewing/unduing a hunk in readme. 

I mean, 

> save a buffer and preview a hunk

 is not expected behaviour from function 

` preview_hunk`

And can lead to confusion for people not familiar with gitgutter.

**Comment by airblade** [comment]
As of 5bfe5b9 previewing/staging/undoing a hunk no longer saves the buffer.
