### ISSUE TITLE
`:!git add %` doesn't update gitgutter

### ISSUE THREAD

**Issue by tylerbrazier** [airblade/vim-gitgutter#418]
To reproduce:

1. make a change in a file, wait for gitgutter update
2. `:!git add %` to stage the current file
3. gitgutter doesn't update until I `:e`, even when `autoread` is set

**Comment by airblade** [comment]
I'm not sure how gitgutter could know you have staged the file when you stage it via `:!`.  The file in question doesn't change (which is why `autoread` doesn't make any difference).

**Comment by tylerbrazier** [comment]
I think it would work if gitgutter updated on `ShellCmdPost` autocmd
