### ISSUE TITLE
E885: Not possible to change sign GitGutterLineRemoved

### ISSUE THREAD

**Issue by kmhofmann** [airblade/vim-gitgutter#420]
I am getting the following error:

    Error` detected while processing function gitgutter#process_buffer[13]..sign#update_signs[12]..sign#upsert_new_gitgutter_signs:
    line   10:
    E885: Not possible to change sign GitGutterLineRemoved
    Press ENTER or type command to continue

Steps to reproduce:
- In a file either staged or committed to a git repository, modify the first line (e.g. delete the line, or swap the first two lines).

I'm using vim-gitgutter commit `f7ea5f40a680797b0ad8d78ec972e32cf17e63c7` and vim 8.0 (recent version compiled by Homebrew)

    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 26 2017 22:08:45)
	MacOS X (unix) version
	Included patches: 1-586
	Compiled by Homebrew
	Huge version without GUI.  Features included (+) or not (-):
	+acl             +file_in_path    +mouse_sgr       +tag_old_static
	+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
	+autocmd         +float           +mouse_urxvt     -tcl
	-balloon_eval    +folding         +mouse_xterm     +termguicolors
	-browse          -footer          +multi_byte      +terminfo
	++builtin_terms  +fork()          +multi_lang      +termresponse
	+byte_offset     -gettext         -mzscheme        +textobjects
	+channel         -hangul_input    +netbeans_intg   +timers
	+cindent         +iconv           +num64           +title
	-clientserver    +insert_expand   +packages        -toolbar
	+clipboard       +job             +path_extra      +user_commands
	+cmdline_compl   +jumplist        +perl            +vertsplit
	+cmdline_hist    +keymap          +persistent_undo +virtualedit
	+cmdline_info    +lambda          +postscript      +visual
	+comments        +langmap         +printer         +visualextra
	+conceal         +libcall         +profile         +viminfo
	+cryptv          +linebreak       +python          +vreplace
	+cscope          +lispindent      -python3         +wildignore
	+cursorbind      +listcmds        +quickfix        +wildmenu
	+cursorshape     +localmap        +reltime         +windows
	+dialog_con      -lua             +rightleft       +writebackup
	+diff            +menu            +ruby            -X11
	+digraphs        +mksession       +scrollbind      -xfontset
	-dnd             +modify_fname    +signs           -xim
	-ebcdic          +mouse           +smartindent     -xpm
	+emacs_tags      -mouseshape      +startuptime     -xsmp
	+eval            +mouse_dec       +statusline      -xterm_clipboard
	+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
	+extra_search    -mouse_jsbterm   +syntax
	+farsi           +mouse_netterm   +tag_binary
	   system vimrc file: "$VIM/vimrc"
	     user vimrc file: "$HOME/.vimrc"
	 2nd user vimrc file: "~/.vim/vimrc"
	      user exrc file: "$HOME/.exrc"
	       defaults file: "$VIMRUNTIME/defaults.vim"
	  fall-back for $VIM: "/Users/michael/homebrew/share/vim"
	Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
	Linking: clang   -L. -L/usr/local/lib  -L/usr/local/lib -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/Users/michael/homebrew/opt/python/Frameworks -framework Python   -lruby.2.0.0 -lobjc

I have found other references to this error in the closed issues (e.g. #188), but this is popping up with very recent versions of either vim, git, or the plugin.
Besides including the plugin via vim-plug, I have no other options related to vim-gitgutter set in my .vimrc.

**Comment by airblade** [comment]
That commit (`f7ea5f40a680797b0ad8d78ec972e32cf17e63c7`) doesn't exist in my repo.  Please can you check it?

I can't reproduce the error on MacVim 8.0.586 compiled by Homebrew.

**Comment by kmhofmann** [comment]
Oooops - please ignore my bug report. Turns out I had a copy-paste error in my .vimrc, getting the plugin via `Plug 'vim-gitgutter'`, which vim-plug seems to expand (without warning) to `Plug 'vim-scripts/vim-gitgutter'`, which results in getting some ancient, unmaintained version. Never noticed that mistake before; my apologies. :) Your version of course works fine.

**Comment by airblade** [comment]
That sounds like an easy mistake to make and a hard one to spot :)

Thanks for writing it out...I'm sure it'll come up again (and actually I think this has happened a few times before but I've never known why).

**Comment by airblade** [comment]
I thought it was worth bringing this up at vim-plug (junegunn/vim-plug#625).
