### ISSUE TITLE
vim-gitgutter error!!! cannot find git. Please set g:gitgutter_git_executable. please help

### ISSUE THREAD

**Issue by IndieThink** [airblade/vim-gitgutter#421]
Hey, I'm newbie in vim text editor and newbie in github ,but im loveit for develop my project
ok this is a seriosly problem, because vim-gitgutter not working in my vim 

my configuration:
i'm using  -windows 10
                -vim version 8
                - [amix/vimrc](https://github.com/amix/vimrc) for my configuration vim.
                -Git ver 1.9.2-preview20140411

when i clone [amix/vimrc](https://github.com/amix/vimrc) and run my vim this massage was pop up

i'm tired to change PATH of my git ,but is doesn't working.

![screenshot_1](https://cloud.githubusercontent.com/assets/23519166/25649608/2004bbce-3001-11e7-8ff3-6d24ceb7d5bd.png)

im sorry for my bad english...
thanks for your respond.

**Comment by airblade** [comment]
The error means that `git` is not on the PATH that is available to vim.  This is probably because of the way git was installed but I can't say for sure.

You can fix this by telling gitgutter where to find the `git` command, by setting `let g:gitgutter_git_executable=...` (you need to replace `...` with the full path).

Also, that's an old version of git.  I recommend you install the latest version; everything will work better :)

**Comment by IndieThink** [comment]
Thank you somuch for your response..

i will try it 👍 

![thumbs up](https://cloud.githubusercontent.com/assets/23519166/25650467/50a54522-3007-11e7-9546-8c53f936177a.gif)

**Comment by Lilyhappiness** [comment]
Hi I had the same problem.

I tried g:gitgutter_git_executable="C:\Users\lli2\AppData\Local\Programs\Git\mingw64\libexec\git-core", but it still doesn't work. What directory shall I use?

**Comment by airblade** [comment]
@Lilyhappiness I'm sorry, I don't know.  This [StackOverflow post](https://stackoverflow.com/questions/11928561/where-is-git-exe-located) has some suggestions you could try.

**Comment by sourchak** [comment]
This problem might be caused because of git not being installed on the system too.

**Comment by daaawx** [comment]
I managed to solve this issue by using forward slashes instead of backslashes when setting path.

`let g:gitgutter_git_executable="c:/program files/git/mingw64/libexec/git-core/git.exe"`
