### ISSUE TITLE
Use of -U0 in git-diff causes diffs to be mis-aligned

### ISSUE THREAD

**Issue by blueyed** [airblade/vim-gitgutter#425]
I have noticed with vim-quickfixsigns, that with `-U0` git-diff might not produce a diff that is as good as when using context.  See https://github.com/tomtom/quickfixsigns_vim/issues/74 for details.

In https://github.com/airblade/vim-gitgutter/issues/371#issuecomment-246287980 it was mentioned that `-U0` simplifies things, and should not get changed.
In this case `--function-context` could be used as a workaround (but likely adds more processing on Git's end?!)

Anyway, I was just curious, if `-U0` was used here also, and found it: https://github.com/airblade/vim-gitgutter/blob/dcac1f74ee5c26125363dca164463bde6657c838/autoload/gitgutter/diff.vim#L103.

**Comment by airblade** [comment]
I still feel that the extra work to adjust each `-U1` hunk's line numbers and line counts to figure out what actually changed outweighs the benefit of the occasional diff being aligned a little better.
