### ISSUE TITLE
Signs are not shown correctly

### ISSUE THREAD

**Issue by cartoonist** [airblade/vim-gitgutter#431]
I have came across with this problem recently. The signs are not displayed correctly. This snapshot shows a file (right pane) compared to its HEAD version (left pane):

![2017-07-31-155046_1004x276_scrot](https://user-images.githubusercontent.com/1281559/28781244-b912c38a-7609-11e7-9e57-38a9c6684936.png)

As you see, the first line is not annotated by `~` sign although it is detected as a hunk (for example during navigation by `[c` or `]c`). This is just an example. I am facing other similar issues; e.g. missing `+`s.

**Comment by airblade** [comment]
What commit of the plugin are you using?  Nvim or Vim?

**Comment by cartoonist** [comment]
I am using last commit in `master` branch and Vim 8.0.

**Comment by airblade** [comment]
I have occasionally experienced a hunk missing a sign while the hunk navigation still works.  I've never been able to reproduce it reliably though and I'm not sure what the cause might be.

Next time it happens, please could you show the result of `:echo getbufvar('', 'gitgutter')`?

**Comment by cartoonist** [comment]
Yes, sure.

**Comment by cartoonist** [comment]
It seems that these two lines in my `~/.vimrc` are responsible for hiding the sign of the first line:

    autocmd BufEnter * sign define dummy
    autocmd BufEnter * execute 'sign place 9999 line=1 name=dummy buffer=' . bufnr('')

I added these two lines to always show the sign column. When I commented those out, it works fine.

**Comment by airblade** [comment]
Aha, that makes sense.

You could try placing your dummy sign at line 9999, the [same line as gitgutter](https://github.com/airblade/vim-gitgutter/blob/c92f61acdc1841292b539a8515a88ed811eafa3f/autoload/gitgutter/sign.vim#L51), and also make sure you don't tell gitgutter to always show the sign column.

It's one of the strange things about Vim's signs – the line number for a sign doesn't need to exist.

**Comment by cartoonist** [comment]
Excuse me, I do not know much about vim signs. You mean I should change `line=1` to `line=9999`? By change the line number from 1 to 9999 the problem would just transfer from line 1 to 9999. It hides the sign for line 9999 instead of the first line.
And how can I tell gitgutter not to always show the sign column?

**Comment by airblade** [comment]
Yes, I mean change `line=1` to `line=9999`, assuming you don't have any files with 9999 lines.

By not telling gitgutter to show the sign column, I meant don't add `let g:gitgutter_sign_column_always=1` to your vimrc.

But I just checked and as of Vim 7.4.2201 you don't need to do this because it's built into Vim.  You can just do this instead: `set signcolumn=yes`.

**Comment by cartoonist** [comment]
Thanks a lot. I did not know about `set signcolumn=yes`. That does what I want.

**Comment by airblade** [comment]
Great!
