### ISSUE TITLE
Cannot create tmp file after long time not using vim

### ISSUE THREAD

**Issue by wsfreund** [airblade/vim-gitgutter#433]
Dear developers,

I usually let the vim open in tmux windows for a long time and I am facing the following error: 

```
Error detected while processing function gitgutter#all[4]..gitgutter#process_buffer[10]..gitgutter#diff#run_diff[79]..gitgutter#utility#system:
line   12:
E484: Can't open file /tmp/<account>/vrKs4rN/48
Error detected while processing function gitgutter#all:
line    4:
E171: Missing :endif
``` 

on windows that have the vim process idle for long time. Probably it is happening since the tmp folder is not available anymore, so I believe that testing availability of the tmp folder and creating a new one in case the tmp folder is not available anymore would solve the reported error.

Thanks !

**Comment by airblade** [comment]
I agree it's because the OS has removed the temp folder while vim has been open.

Unfortunately there's nothing we can do about it.  We can catch the error and ask vim for a new temporary file handle (via `tempname()`) but vim doesn't realise the temporary directory has been removed and just hands out another filename in that deleted directory.

See also #395.

**Comment by airblade** [comment]
An alternative to relying on vim's handling of temporary files is to implement it ourselves in, say, `~/.vim-gitgutter/`.  But I don't want to get into that.

**Comment by trisys3** [comment]
Have there been any issues opened on vim itself related to this? It might help to link to that issue, so developers coming to this issue can track it and maybe even help out. I couldn't find any by searching, but there are over 500 issues.

**Comment by airblade** [comment]
I haven't opened any.

**Comment by trisys3** [comment]
I opened an issue over there, vim/vim#2987.
