### ISSUE TITLE
vim-gitgutter highlights the wrong lines if I use filters in .gitattributes

### ISSUE THREAD

**Issue by mgedmin** [airblade/vim-gitgutter#435]
**Background**: when you keep gettext translation files in Git, you get huge painful diffs on all the comment lines that mention source locations -- line numbers of many messages shift when you insert or delete lines.  One way to reduce the pain is to configure Git to strip off the comments by doing

    git config filter.po.clean "msgcat - --no-location"

in every git checkout, and keeping a `.gitattributes` file with

    *.po    filter=po
    *.pot   filter=po

**Problem**: when I re-generate the .po files with new strings to be translated, vim-gitgutter gets confused and highlights the wrong lines as changed.

**Comment by airblade** [comment]
Please could you give specific steps to reproduce?  I'm not familiar with how gettext works.

**Comment by mgedmin** [comment]
Steps to reproduce:

0. make sure you've got `gettext` and `intltool` installed (e.g. `apt install gettext intltool make`)
1. `git clone https://github.com/gtimelog/gtimelog`
2. `make update-translations`
3. `vim po/lt.po`
4. change something between the quotes on line 449
5. observe how vim-gitgutter doesn't highlight line 449 as changed
7. hit `[c` and observe how it shows line 351 as changed, even though it's not

Step 2 does two things: it defines the `po` filter in `./.git/config`, and it re-extracts translatable strings from the source file, which adds back the comments containing source locations to the `.po` and `.pot` files.

Note that if you break gettext's syntax (e.g. add some garbage after the quotes, instead of inside them), vim-gitgutter stats showing the differences correctly.  This is because the configured git filtter (`msgcat - --no-location`) complains about the syntax error and exits with a non-zero status, which makes `git diff` compare the actual file instead of the cleaned version.

**Comment by mgedmin** [comment]
A simpler reproducer that doesn't require gettext or intltool:

1. `git init repo && cd repo`
2. `echo '*.txt  filter=txt' > .gitattributes`
3. `git config filter.txt.clean 'grep -v ^#'`
4. create a `file.txt` like this

```
# comment 1
line 1

# comment 2
line 2

# comment 3
line 3
```

5. `git add file.txt && git commit -m Initial`
6. `vim file.txt` and change `line 2` to `line 2a`

**Comment by airblade** [comment]
Thanks for the reproducers, especially the second.  I see the problem you're having.

It looks like SublimeText's GitGutter has already run into this: see their [#74](https://github.com/jisaacks/GitGutter/issues/74), [387345](https://github.com/deathaxe/GitGutter/commit/38734581a64d0bf6e3cf89ba3795319d36c5883e), and [1f05f50](https://github.com/jisaacks/GitGutter/commit/1f05f5018da9fe3e357adf9dd276240de038d0f2).

The conclusion seems to be that you can work around smudge filters but not clean filters.

In essence GitGutter works like this:

```
git diff <file1> <file2>
```

where `<file1>` is a temporary file containing the contents of your buffer; and `<file2>` is the file from git's index, obtained via:

```
git show ref:path/to/file
```

where `ref` is usually `HEAD` but could be a SHA or similar.

There's no obvious way to apply filters to `<file1>`.  With `<file2>`,  `git-show` does not apply filters but you could apply smudge filters with `git cat-file --filters` (git 2.11.0+).  This would, I think, mean that the plugin would be diffing two smudged files.

However there doesn't seem to be a way to deal with clean filters.  Therefore I can't see a way to solve your problem.

That doesn't mean it's not possible, just that I can't see it ;)

**Comment by mgedmin** [comment]
I agree completely that this is a non-trivial problem to solve.

AFAICT `git diff` applies the clean filter to the temporary file already, so the only problem is mismatched line numbers.  I've a vague thought to run a diff on the file against the cleaned version of the same file, to see which lines get deleted, so it would be possible to adjust the line numbers reported by `git diff`.

You can see whether a file needs a filter by running `git check-attr filter -- path/to/file`.

You can get the command line of the clean filter by running `git config filter.filtername.clean`.

This should allow you to get a cleaned version of the file, which can be diffed against the original to build a line number map.  Which sounds like an interesting programming exercise.  (I think I coulddo it in Python; I'm not sure about vimscript.)

This might work well for my use case, where the clean filter removes whole lines.  I think it should work well enough with filters that expand tabs to spaces, or convert line endings/character encodings, or reindent code, and other similar things that don't actually insert or delete lines.  This would not work with filters that replace the entire file with a reference to external storage (which is how git-annext works AFAIU), but I don't think that use-case is solvable.

I think it's safe to ignore smudge filters -- we're passing an already-smudged file to git diff, which cleans it and compares against the already-cleaned blob from the git repository.

So: a lot of work for minor gain.  Is it worth it?  (I'm tempted to say "yes" and try to create a pull request. ;)

**Comment by airblade** [comment]
From my point of view that's a lot of code to maintain and support for a feature that won't benefit many people.  You'd have to make it work on Windows and Linux and I expect it would cause a big support headache ;)

Feel free to maintain your own fork but I won't merge a PR for this.  Sorry!
