### ISSUE TITLE
Gitgutter Undo_Hunk results in signs and quickfix losing sync

### ISSUE THREAD

**Issue by systemmonkey42** [airblade/vim-gitgutter#437]
For many changes you can make to a file, vim tracks the positions of signs and the line numbers in quickfix and location lists, (as well as marks).

When undoing a hunk, the "undo_hunk" function seems to change the file on disk and reload the current
buffer.  If the hunk that was un-done changes the number of lines in the buffer, all the existing signs/marks/quickfix/locationlist indexes become out of sync, effectively offset by that many lines.

Is it possible to detect when the hunks (current, vs undone) are a different number of lines and simulate the insertion/deletion to make the results match?

This is visible when you are reviewing errors in the quickfix list, and revert a hunk. The quickfix list goes out of sync.

This is also visible if you have "YCM" highlighting errors or warnings below a section of code which is changed with undo_hunk.  The file changes, and the lines move, but the signs remain in their original location.

I hope this makes sense.  I can try and make a movie of it if you want to see the problem in action.

Thanks

**Comment by systemmonkey42** [comment]
This is a trivial modification to undo_hunk() which counts the '+' and '-' rows in the diff hunk, calculates a delta, and adjusts the file before calling 'edit' so the lines numbers for quickfix and signs match up after reloading.
```
function! gitgutter#undo_hunk() abort
      ...
      let diff_for_hunk = gitgutter#diff#generate_diff_for_hunk(diff, 'undo')
      let diff_delta = 0
      for diff_line in split(diff_for_hunk,'\n')
          if diff_line[0] ==? '+'
              let diff_delta -= 1
          elseif diff_line[0] ==? '-'
              let diff_delta += 1
          endif
      endfor
      if diff_delta > 0
          exe 'normal! '.diff_delta.'o'
      elseif diff_delta < 0
          exe 'normal! '.diff_delta.'dd'
      endif
      set nomodified
      call gitgutter#utility#system(gitgutter#utility#command_in_directory_of_file(g:gitgutter_git_executable.' apply --reverse --unidiff-zero - '), diff_for_hunk)
```

Hopefully you get the idea and can do something a little more elegant.

Thanks

**Comment by airblade** [comment]
Thanks for pointing this out and providing a workaround.  I'll see if I can come up with a neater implementation.

I've been meaning to amend the hunk staging and undoing so they don't save the buffer.  Once I've done that I don't think your solution will be viable any more – would you agree?  The only way I can think of would be to manually move all the signs below the hunk and manually adjust the quickfix and location lists – which would be quite a hassle.

**Comment by systemmonkey42** [comment]
I agree.  Fixing quickfix might be one thing (which would potentially lose your place, and you have to deal with quickfix entries which no longer exist) but fixing signs would be a nightmare.  You can't know who owns then, or what the side effect could be if you moved or deleted them (some implementations use the line number as the sign placement id, and track those id's in buffer local variables.  moving the sign would break too much)

**Comment by systemmonkey42** [comment]
FYI, If you use VIM commands to insert or delete lines, VIM handles the tracking and adjustment of signs/location lists/quickfix lists/marks/etc.   If you modified the buffer from vimscript, you don't need to deal with any of this.  (Python is another matter).  So parsing the diff and applying the insertions and deletions using 'o' and 'd' would automatically keep everything in sync.

**Comment by airblade** [comment]
I have [re-implemented hunk undo](https://github.com/airblade/vim-gitgutter/blob/5bfe5b92099e0d332a7ca26c0263fab509ee9617/autoload/gitgutter/hunk.vim#L187-L194) along the lines you suggested.

Thanks!
