### ISSUE TITLE
Inconsistency between GitGutterNext/PrevHunk and GitGutterStage/RevertHunk

### ISSUE THREAD

**Issue by amadeus** [airblade/vim-gitgutter#438]
So I've found a small kind of annoying consistency with the hunk navigation API vs the staging/revert api.

Basically when navigating hunks, if the type of hunk is a pure deletion hunk with no edits or adds, then the cursor navigates to the line AFTER the deletion. Normally it's not really a big deal, however I often use the hunk navigation to then immediately stage a particular hunk. The line after the hunk is not valid as a place to stage a deletion hunk, and therefore I have to move the cursor up a line, and then stage the deletion.

It would be awesome if either the navigation could put the cursor below the deletion, or enable staging to act on the line above the cursor.

**Comment by airblade** [comment]
I can't reproduce this.  When I use the hunk navigation it puts the cursor on the line before a pure-deletion hunk.

What commit SHA are you on?

**Comment by amadeus** [comment]
I am on master currently.

 Actually, you know what, the issue occurs when in diff view (i.e. fugitive's `:Gvdiff`)

**Comment by airblade** [comment]
When Vim is in diff view, the `[c` and `]c` commands aren't vim-gitgutter's.

**Comment by amadeus** [comment]
Hmm, I guess that means it's probably not fixable. Thanks anyways tho!
