### ISSUE TITLE
Error when starting Neovim

### ISSUE THREAD

**Issue by rinti** [airblade/vim-gitgutter#442]
Hi.

When I start Neovim I get the following errors (sorry it's localized to Swedish):

```
Fel upptäcktes vid bearbetning av function <SNR>112_on_exit_nvim:
rad    1:
E118: För många argument till funktion: function
```

Basically it says the function on_exit_nvim gets too many arguments.

**Comment by airblade** [comment]
It'll work if you upgrade NeoVim.

**Comment by rinti** [comment]
I was so sure I had upgraded NeoVim already! Sorry and thanks! :)
