### ISSUE TITLE
<SNR>156_on_exit_vim

### ISSUE THREAD

**Issue by ernestas-poskus** [airblade/vim-gitgutter#443]
Hey, these errors :point_down: for any command after updating to lastest version.

![screenshot from 2017-10-20 09-12-46](https://user-images.githubusercontent.com/4499780/31807449-e4f8d97e-b576-11e7-8a1c-7664b9112b64.png)

**Comment by ernestas-poskus** [comment]
Did checkout before HEAD https://github.com/airblade/vim-gitgutter/commit/54209a0199bcb9f6b7c452deb0ffbc3aa60b857d and it works, so it looks like last commit introduced this.

**Comment by airblade** [comment]
Upgrading your nvim will fix this.

**Comment by gilesorr** [comment]
I was having a very similar problem:

    Error detected while processing function <SNR>112_on_exit_nvim:
    line    1:
    E118: Too many arguments for function: function
    E116: Invalid arguments for function <SNR>112_buffer_exec

This occurred on focus/unfocus of terminal windows, and on save or save-and-exit (it happened a lot).

My version of NeoVim is as current as it gets within Fedora, and I'd like to stick with the OS-packaged version so I've disabled gitgutter for the moment.

**Comment by ernestas-poskus** [comment]
> My version of NeoVim is as current as it gets within Fedora

same here, I will try to compile neovim master

**Comment by tomasz-sodzawiczny** [comment]
For me updating nvim to v0.2.0 fixed the issue (on Mac OS).

**Comment by airblade** [comment]
579f0a5 should make the plugin backward compatible with nvim < 0.2.0.

**Comment by gilesorr** [comment]
I re-installed the plugin and am having no problem!  Thanks very much.

**Comment by ernestas-poskus** [comment]
Backwards compatibility helped, thanks !
