### ISSUE TITLE
`let g:gitgutter_signs = 0` didn't work..

### ISSUE THREAD

**Issue by CindyLinz** [airblade/vim-gitgutter#445]
`let g:gitgutter_enabled = 0` or `let g:gitgutter_highlight_lines = 1` worked, but `let g:gitgutter_signs = 0` didn't work...

And I found that `:GitGutterSignsDisable` didn't work, either..

My vim version 8.0.1176

**Comment by airblade** [comment]
That's strange.  I tried `let g:gitgutter_signs=0` in my vimrc and it stopped signs showing when I opened a file with changes.  Did you put it in your vimrc or just type it into an existing vim session?  If into a vim session, it won't have any effect; you'll need to `:GitGutterSignsToggle` instead.

`:GitGutterSignsDisable` also worked for me.

Is your vimrc online?

**Comment by airblade** [comment]
Closing because this has gone quiet...
