### ISSUE TITLE
Additional mappings by default (firs hunk, last hunk)

### ISSUE THREAD

**Issue by dtcyganok** [airblade/vim-gitgutter#448]
`[C` - jump to first hunk
`]C` - jump to last hunk

**Comment by airblade** [comment]
Just put this in your vimrc:

```viml
nnoremap [C gg]c
nnorenap ]C G[c
```

**Comment by dtcyganok** [comment]
I suggested this as I thought it would be convenient (like in [vim-unimpaired](https://github.com/tpope/vim-unimpaired)). But if until now it was only needed for me, then probably it is worth closing the issue.
