### ISSUE TITLE
Error with Dedupe(list)

### ISSUE THREAD

**Issue by AdeelK93** [airblade/vim-gitgutter#449]
Hi,

I'm using your plugin in conjunction with the [ultimate vimrc setup](https://github.com/amix/vimrc) and I appear to be getting an error from [this part of the dedup code](https://github.com/airblade/vim-gitgutter/blob/1c034be0d31168c8f4770ef7b69adb67d00d6f3d/autoload/gitgutter/utility.vim#L187).

The error I'm getting is:
```
E121: Undefined variable: v:key
E116: Invalid functions for index(a:list, v:val, v:key + 1) == -1
```

I'm not entirely sure what list this is deduping, but removing the two calls to this function from gitgutter.vim and replacing them with the undeduped list itself doesn't seem to be causing any errors, and shows the proper git changes in the gutter.

Any idea what might be causing this? Thank you!

**Comment by airblade** [comment]
The `dedup()` function is used to when the plugin is updating all the visible windows.  We need a list of the windows' buffers.  As we only want to update each buffer once, and there may be more than one window onto the buffer in a tab page, we need to dedup the list from `tabpagebuflist()`.

For example, open a file in Vim then split the window.  `:echo tabpagebuflist()` will list the buffer twice.  If you only want to process that buffer once, you need to dedup the list.

I don't know why you're getting the error though.  Do you get it with only gitgutter installed?

**Comment by airblade** [comment]
Forgot to say: bypassing the deduplication won't cause any problems; it'll just mean you'll update each buffer as many times as it has visible windows, which is extra work if you have any.

**Comment by airblade** [comment]
I have taken the deduplication out in 5bfe5b9.
