### ISSUE TITLE
Sign can not be shown in neovim

### ISSUE THREAD

**Issue by wsdjeg** [airblade/vim-gitgutter#450]
@airblade  I use gitgutter in spacevim for git layer, but the sign can not be shown in neovim. and in vim it works well.

any recommand command to debug?

**Comment by wsdjeg** [comment]
`GitGutterGetHunkSummary()` return [0,0,0] in neovim, but in vim, it is [7,0.0]

**Comment by airblade** [comment]
That's a strange one.  What version of nvim are you using?

When you run nvim, do you have `grep` configured differently (specifically to produce colourful output)?

What does `:GitGutterDebug` give you for vim and for nvim?

**Comment by wsdjeg** [comment]
@airblade I am sorry, but this is ok now, I can not reproduce it in neovim, I will report new issue when I can reproduce it everytime.
