### ISSUE TITLE
windows: gitgutter doesn't work if vim is started from git bash

### ISSUE THREAD

**Issue by moopie** [airblade/vim-gitgutter#453]
Gitgutter completely fails and just displays an error every 10-30 seconds if I start it from bash that is provided by the git install
Tried to also reproduce in PowerShell but it seems like gitgutter works fine if I start vim from there

```
Error detected while processing function gitgutter#utility#git_supports_command_line_config_override:
line    1:
E484: Can't open file C:/Users/$USER/AppData/Local/Temp/VIo528F.tmp
```

Vim version: `8.0`
Git Version: `2.15.1.windows.2`
GitGutter Version: `1e60667 (master)`

**Comment by airblade** [comment]
I don't use Windows so I'm afraid I don't know or understand the different ways of installing git / bash and how they work.

Having said that, the `$USER` in the error message looks odd.  Shouldn't that resolve to an actual value?

Also, the 10-30s interval seems like an odd length of time.  What is your `&updatetime` in vim?

**Comment by moopie** [comment]
Oh I just replaced my account name with `$USER`

Also I might have been overestimating the interval for dramatic purposes

**Comment by mini-gui** [comment]
+1

**Comment by airblade** [comment]
I have just pushed a big refactor (5bfe5b9) which simplified the path handing.  Please could you update and try again?

**Comment by airblade** [comment]
Closing because this has gone quiet.
