### ISSUE TITLE
Cannot use h* mappings

### ISSUE THREAD

**Issue by shmup** [airblade/vim-gitgutter#455]
It's strange.

`map: <leader>h` shows:

```
n  \<Space>hp    <Plug>GitGutterPreviewHunk
n  \<Space>hr    <Plug>GitGutterUndoHunk:echomsg '\<Space>hr is deprecated. Use \<Space>hu'<CR>
n  \<Space>hu    <Plug>GitGutterUndoHunk
n  \<Space>hs    <Plug>GitGutterStageHunk
```

Interestingly, doing a `<leader>r` (as do many other combinations) pauses waiting for the next input, but `<leader>h` (or j and k and l and some others) does not. Referring to the characters that display on `laststatus`. Maybe not useful information, but a symptom I noticed.

And so `<leader>hu` is just always doing the most recent undo. 

Curious if you had any ideas. I've blanked out my vimrc but haven't taken the time yet to go through disabling the ~15 plugins.

**Comment by airblade** [comment]
`<leader>r` would pause if you also have mappings starting `<leader>r`, e.g. `<leader>rx`.  The pause is governed by `timeout` and `ttimeout`.  (It could be some other reason but that's what I would check first.)

What actually happens when you type `<leader>hp`?

**Comment by shmup** [comment]
Oh you're totally right re: "only pause if you have mappings", and I definitely do have mappings heh.

And doing `<leader>hp` just pastes, heh. It's ignoring the `<leader>h` and I'm unsure why.

**Comment by shmup** [comment]
This was a classic user error. Recently I swapped all of my <leader> maps for explicit keys. And so I didn't realize when I had changed mapleader "\<Space>" to '\<Space>' and well, broke my leader.
