### ISSUE TITLE
Gutter signs disappear right after opening file in neovim

### ISSUE THREAD

**Issue by kblin** [airblade/vim-gitgutter#456]
Hi there.
First of all, thanks a bunch for vim-gitgutter. I've been a happy user for years.

I'm using the plugin on multiple machines, with multiple versions of both vim and neovim, and I've noticed that as of recently, the gutter signs on my Ubuntu machine are somewhat broken.

When opening a file that contains changes, the gutter signs plop up for a split-second, and then disappear and almost never come back. The diff output looks reasonable, according to the logs:
[gitgutter.txt](https://github.com/airblade/vim-gitgutter/files/1622289/gitgutter.txt)

This might have something to do with neovim, as it only seems to affect the neovim builds from the ppa (currently my version is 0.2.2ubuntu1+git201801032111-dc4a9cb-7e4bb0d-c30ab2e~ubuntu16.04.1). On my Debian machine, 0.2.2 as available from the sid repo at the moment is working fine.

Let me know if there is anything else you need, and thanks again for this great piece of software.

**Comment by airblade** [comment]
Thanks for the logfile.  I agree it looks fine and you don't have any ANSI colour codes from grep in the diff output.

At the moment vim-gitgutter actually has two ways to produce a diff: one way (a simple `git diff`) when you write a buffer and another (writing the buffer to a temp file, and the file from the index to a temp file, and diffing those) when you edit a buffer.  I wonder if one method is working for you and the other isn't.

If you turn off the realtime diffing with `let g:gitgutter_realtime=0`, do the signs still disappear?

Your logfile just shows the diff commands from writing a buffer.  Please could you try to capture the command from a change to the buffer?

**Comment by kblin** [comment]
Wow, thanks for the quick feedback.

Here's my attempt to capture a change, not sure if it worked.
[gitgutter_change.txt](https://github.com/airblade/vim-gitgutter/files/1622446/gitgutter_change.txt)
A second or so after I stopped typing, the gutter signs quickly showed up and disappeared again. The time interval seems to be the same as on my Debian box until the real time signs show up.

But mentioning the real time thing gave me the idea to try `let g:gitgutter_async=0`, and that does fix the gutter signs. I've got a log line of opening and writing a buffer with that line in .vimrc as well.
[gitgutter_sync.txt](https://github.com/airblade/vim-gitgutter/files/1622461/gitgutter_sync.txt)

Running in sync mode without realtime gutter updates is a nice workaround already. :smile:

**Comment by airblade** [comment]
Aha, that's useful information.  So is this correct?

| | Async | Sync |
|--|--|--|
| Realtime | broken | ok |
| Not realtime | broken | ok |

**Comment by kblin** [comment]
Yes. For a moment I thought realtime updates were broken in sync mode as well, but they just take a bit longer to show up. Your table is 100% accurate.

**Comment by airblade** [comment]
(The pause before realtime updates are run is governed by the `updatetime` option.)

In that case there's something up with neovim's async execution.  I wonder if it's the specific neovim in the ppa or whether it's the Ubuntu machine.  Is `sh` available on that machine?

**Comment by kblin** [comment]
Yes, `sh` is available and should be `dash`, like on most debian-based systems. I can grab a neovim build off linuxbrew to check if that works. Will just take a bit because that'll likely rebuild the world. :)

**Comment by kblin** [comment]
The same with nvim v0.2.2 from linuxbrew.

**Comment by airblade** [comment]
Hmm.  I don't have any bright ideas unfortunately.  I think it's a case of stepping through the async code inserting `echo` statements and seeing where it goes wrong.

**Comment by kblin** [comment]
I'll see if I can reproduce this on another ubuntu machine on the weekend. Seeing how it works in sync mode, this is not urgent.

**Comment by airblade** [comment]
Sounds good, thanks.

**Comment by kblin** [comment]
Ok, could repro on another Ubuntu 16.04 install. I'm still not quite sure what's going on. It's not happening on vim because vim as shipped with 16.04 is too old to return true on the "async available" check.
From the log output, I do see 2 stdout events triggering the callback, one with contents, and one just a newline (before `stringify` does anything with it). From the way I read the comment on the "exit" handler, an empty string sent to `gitgutter#handle_diff()` means "no changes". Maybe that's what's happening? Would a single newline cause this, too?

**Comment by kblin** [comment]
To answer my own question, yes, that seems to be it. The patch below fixes the disappearing change marks for me.
[fix.txt](https://github.com/airblade/vim-gitgutter/files/1629898/fix.txt)
No idea if this'd break anything else and is the right fix. :wink:

**Comment by airblade** [comment]
Thanks for the patch.  However it's for an old version of vim-gitgutter.  Would you mind updating and seeing if things work without the patch?

**Comment by kblin** [comment]
Ack, the new version is fine. And I was sure I did a PlugUpdate, but apparently I didn't. Sorry for the noise.
