### ISSUE TITLE
Option to enable/disable <Leader> mappings only?

### ISSUE THREAD

**Issue by JesseLeite** [airblade/vim-gitgutter#457]
I've always thought of `<Leader>` mappings as a safe zone for Vim devs to customize their workflow without fear of conflicting with default mappings or 3rd party plugin mappings.  Maybe I'm wrong on this, but either way it would be nice to disable ONLY the `<Leader>` mappings for those of us that like default mappings like `]c`, but don't want conflict with our `<Leader>` mappings.  Thoughts?

TL;DR: I know we could use this to disable all mappings...

```
let g:gitgutter_map_keys = 0
```

What about adding this to disable only leader mappings?

```
let g:gitgutter_map_leader_keys = 0
```

**Comment by airblade** [comment]
I see where you're coming from but as there are only two default mappings I don't think it's worth the trouble of introducing yet another configuration option.

I suggest the following for your vimrc:

```viml
let g:gitgutter_map_keys=0
nmap [c <Plug>GitGutterPrevHunk
nmap ]c <Plug>GitGutterNextHunk
```

**Comment by JesseLeite** [comment]
@airblade Fair enough!  Thank you for reply, and for the great plugin.
