### ISSUE TITLE
Possible memory leak with airline integration

### ISSUE THREAD

**Issue by CptnKirk** [airblade/vim-gitgutter#458]
I'm running into a frustrating problem with the combination of gitgutter + airline + airline-clock.

Airline-clock sets up a timer that seems pretty straightforward to refresh airline.

Yet if gitgutter is loaded (even if disabled) neovim will leak memory.  This seems related to gitgutter + airline integration and not releated to gitgutter timers (or async support).  

However, if the ```airline#update_statusline()``` is called within a timer and gitgutter is loaded.  Neovim leaks memory until that timer is killed.

Would you mind taking a look at:
https://github.com/enricobacis/vim-airline-clock/issues/3
https://github.com/vim-airline/vim-airline/issues/1612
https://github.com/neovim/neovim/issues/7871

The vimrc cutdown is part of each issue.  But I can include here too if you like.

**Comment by airblade** [comment]
GitGutter doesn't use timers, only jobs.

GitGutter has a [public function](https://github.com/airblade/vim-gitgutter/blob/1e60667322b7cd1bfcba98762fbba746a888d21a/plugin/gitgutter.vim#L139-L141) which airline calls to get the change stats.  All the function does is call another function which reads a buffer variable.  I don't see how calling it multiple times could leak memory.

It sounds frustrating but I don't know where the problem is.

**Comment by airblade** [comment]
What happens if you edit the public function in your installed gitgutter to just return a fixed list?  In other words:

```diff
diff --git a/plugin/gitgutter.vim b/plugin/gitgutter.vim
index ad39bc1..89a823a 100644
--- a/plugin/gitgutter.vim
+++ b/plugin/gitgutter.vim
@@ -137,7 +137,7 @@ endfunction
 " window.  The format is [ added, modified, removed ], where each value
 " represents the number of lines added/modified/removed respectively.
 function! GitGutterGetHunkSummary()
-  return gitgutter#hunk#summary(winbufnr(0))
+  return [[0, 0, 0]]
 endfunction

 " }}}
```

**Comment by CptnKirk** [comment]
I don't see this code in my code base.  No GitGutterGetHunkSummary function at all.  Wonder what version of the plugin I'm on.  Should be the latest plug update though.

**Comment by CptnKirk** [comment]
Oops.  Was looking in autoload.  Found it.

**Comment by CptnKirk** [comment]
Sadly, change doesn't appear to have any impact.

**Comment by airblade** [comment]
I think that proves that the memory leak isn't coming from GitGutter.

**Comment by CptnKirk** [comment]
Yea.  I'm not convinced it's coming from GitGutter.  Only that it feels like GitGutter is somehow getting put on the pile.  Feels like a neovim bug since you can timer for 200 ticks, watch the memory grow, and then when the timer expires, memory drops when the timer cleans up.

Unfortunately, the neovim guys aren't seeing it.  Yet. :)

**Comment by CptnKirk** [comment]
Looks like we've found the issue in neovim/neovim#7871.  The more you have loaded the higher you need to set updatetime to keep things from piling up.  But with a sufficiently large updatetime (5000 with all my plugs), I seem to be ok.
