### ISSUE TITLE
View changes

### ISSUE THREAD

**Issue by danedavid** [airblade/vim-gitgutter#460]
Forgive me if I didn't see it in the docs, but is there any way I could compare the diff with previos version, something like this:

![image](https://user-images.githubusercontent.com/19928280/35552498-1103af10-05ba-11e8-94c7-44cb8f80e179.png)

_this is from VS Code_

**Comment by airblade** [comment]
Have a look at Vim's help for `diff`: `:h diff`.  There's also a [Vimcast on vimdiff](http://vimcasts.org/episodes/comparing-buffers-with-vimdiff/).
