### ISSUE TITLE
v:t_string not defined for Vim <8.0

### ISSUE THREAD

**Issue by shaneleonard** [airblade/vim-gitgutter#468]
In autoload/gitgutter.vim, the init_buffer function makes use of the v:t_string variable. This variable is not defined until Vim version 8, so on Vim 7.4, the following error is raised every time gitgutter is run:

```
Error detected while processing function gitgutter#init_buffer:
line 3:
E121: Undefined variable: v:t_string
```

To solve this, the function should first check `if exists('v:t_string')`, as per the instructions in the `eval.txt` helpfile for Vim 8.0.

**Comment by airblade** [comment]
This was already fixed in 933af37.
