### ISSUE TITLE
vim-gitgutter is comparing against wrong version of file after branch switch

### ISSUE THREAD

**Issue by relapi** [airblade/vim-gitgutter#472]
> What is the latest commit SHA in your installed vim-gitgutter?
16568f4
> What vim/nvim version are you on?
v8.0.1520
> If no signs are showing at all, what does `:echo getbufvar('','gitgutter').path` give?

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

After changing branches and running :checktime, then :GitGutterAll, git gutter shows signs for the diff between the branches instead of no signs.

Repro steps

- Open a couple files that changed between branches
- Outside of vim, switch to the other branch
- Run :checktime, then :GitGutterAll
- You now see signs when you should see none.
- The only way to get the right signs showing is to run :e or :w. Making a change will cause the correct signs to be shown, but unless you save running :GitGutterAll will cause the wrong signs to be shown again.

**Comment by airblade** [comment]
I can't reproduce this.  Can you be more specific with your first two steps?  Ideally instructions that I can copy-paste, e.g.:

```
git init foo & cd foo
echo asdf > bar && git add bar && git commit -m "first"
git checkout -b stuff
echo fdsa >> bar && git commit -am "second'
vim bar
yyp
...
```

**Comment by relapi** [comment]
```
mkdir test
cd test
touch a.txt
touch b.txt
git init
git add --all
git commit -m "initial commit"
echo "a\nb\nc\nd\ne\nf\n" > a.txt
echo "a\nb\nc\nd\ne\nf\n" > b.txt
git add --all
git commit -m "stuff"
git checkout -b development
echo "a\nb2\nc\nd3\ne4\nf5\n" > a.txt
echo "a1\nb2\nc\nd3\ne\nf\n" > b.txt
git add --all
git commit -m "stuff"

# vim
vim
:e a.txt
:split
:e b.txt

# another terminal in the test directory
git checkout master

# vim
:checktime
:GitGutterAll
```

Then I see...
![screenshot](https://user-images.githubusercontent.com/23083813/36329113-6c774186-132a-11e8-8889-cabfa28d80f6.png)
