### ISSUE TITLE
About recent changes

### ISSUE THREAD

**Issue by kutsan** [airblade/vim-gitgutter#475]
https://github.com/kutsan/dotfiles/blob/d7c26bc9d2798ce6d9d86a7f81c7a3ed993e1b47/.vim/package/gitgutter.vim

I was using `g:gitgutter_realtime` variable, seems like it's gone now. I don't need to update signs in realtime, I was triggering them with my own events like `InsertLeave`. What should I use now? I tried to look into new docs but there wasn't anything useful.

Also, plugin completely doesn't work. My `'updatetime'` is `1000` but still in order to show signs I need to close and re-open the buffer.

Everything works under 5bfe5b92099e0d332a7ca26c0263fab509ee9617.

**Comment by airblade** [comment]
You're right, `g:gitgutter_realtime` is no longer used.  You can avoid realtime updates by adding this to your vim config:

```viml
" .vim/after/plugin/gitgutter.vim
autocmd! gitgutter CursorHold,CursorHoldI
```

This removes the `CursorHold(I)` autocommands that [the plugin sets up](https://github.com/airblade/vim-gitgutter/blob/38a7789be9e3b53c5215184396bf8c373f78e1f5/plugin/gitgutter.vim#L221).

As for the plugin not completely working, please could you give more details?  Ideally, steps to reproduce.  (Please note I fixed a bug this morning; don't know if it was affecting you.)

**Comment by kutsan** [comment]
> You're right, g:gitgutter_realtime is no longer used.

Well, why? Not all people wants to see the signs on `CursorHold`, I think it's better experience to see them as I saved.

> please could you give more details?

I guess there is no bug. I was waiting to see the signs on save, but I assume there is no such trigger for signs on save?

```vim
augroup gitguttertriggeronsave
	autocmd!
	autocmd InsertLeave,TextChanged * call gitgutter#process_buffer(bufnr(''), 0)
augroup end
```

I could get working with this.

**Comment by airblade** [comment]
> I think it's better experience to see them as I saved.

I think it's a personal preference.  I prefer to see the diff of the buffer as it is in vim; you prefer to see the diff of the buffer as it is on the file system.

> I assume there is no such trigger for signs on save?

That's right; out of the box gitgutter shows you a realtime diff of the buffer, and whether or not the buffer is saved makes no difference to the diff; therefore saving doesn't trigger any special update.

As you know, the updates are all driven by autocommands – so you can remove any or all existing ones and use your own instead.  Whatever works best for you.

**Comment by kutsan** [comment]
You shouldn't have removed the existing functionality just because you don't prefer in that way. What's the exact reason to remove `g:gitgutter_{eager,realtime}`? You removed because you don't use it? 

Besides that, I don't want to spend time in future to figure out why this isn't working. There is literally no guarantee from you to rename `gitgutter#process_buffer()` function to something else.

I know I can tweak everything I want but this was generally about backwards compatibility, not the features I wanted to see. Please, revert those variables back.

**Comment by airblade** [comment]
> I don't want to spend time in future to figure out why this isn't working.

I don't want to spend time in future supporting code I (and I suspect most other gitgutter users) don't use.

Backwards compatibility is nice if one has the time to invest in it, but I don't.

**Comment by kutsan** [comment]
Dear gitgutter users, as you can see there is no such thing like backwards compatibility in this project nor sympathy for its users. Existing functionality may be removed with literally no reason and without any notice, your configurations may be obsolete because one man desires like that and he has certainly no time for you. If you want to keep something existing, something like it was there for years, that's absolutely your problem, you have to have time to fix that mess.

I'm glad there are other alternatives which their authors care about backwards compatibility.

**Comment by airblade** [comment]
You have several options:

- Continue to use the plugin as of 932ffaca.
- Add a small amount of configuration to your vimrc.
- Fork the plugin and make the changes you would like.
- Use a different plugin.

You have already benefited from hundreds and hundreds of hours of my work, without charge.  I don't owe you anything.
