### ISSUE TITLE
git_gutter#init_buffer4

### ISSUE THREAD

**Issue by ernestas-poskus** [airblade/vim-gitgutter#476]
> What is the latest commit SHA in your installed vim-gitgutter?

4692457 - (HEAD -> master, origin/master, origin/HEAD) Document how to disable realtime updates. (23 hours ago) <Andy Stewart>

> What vim/nvim version are you on?

NVIM 0.1.7

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

I get this error when opening any file which has Git.
![screenshot from 2018-02-20 15-23-29](https://user-images.githubusercontent.com/4499780/36426271-32e3a7fe-1652-11e8-9530-6d175a0282b4.png)

Nvim freezes completely. 

Commit: 932ffac works fine.

I use vim-gutter through Plug

```
Plug 'airblade/vim-gitgutter'
```

Have minimal gutter config

```
nmap ]h <Plug>GitGutterNextHunk
nmap [h <Plug>GitGutterPrevHunk]
```

**Comment by airblade** [comment]
I suspect this is due to how older versions of nvim handled callbacks.

Would you have any objection to updating your nvim and trying again?

**Comment by airblade** [comment]
Similar to #443.

**Comment by ernestas-poskus** [comment]
sure, thanks was not aware of new version :+1:
