### ISSUE TITLE
Setup Travis to run tests?

### ISSUE THREAD

**Issue by blueyed** [airblade/vim-gitgutter#483]
I think it would be nice to have Travis or CircleCI run the tests, especially for pull requests.

While at it, https://github.com/Vimjas/covimerage/ could be used to report coverage for it, e.g. by uploading it to codecov.io then.

**Comment by airblade** [comment]
On the one hand it would be nice; on the other it feels like adding a lot of ceremony.

**Comment by blueyed** [comment]
Yeah, "ceremony" is the right word.

But I really like it for complex plugins like Neomake, where Codecov then reports on the coverage of the report (coverage in general, and unexpected changes).

It's ok to close it, but I might come back to it anyway.. :D

**Comment by blueyed** [comment]
Not considering coverage, running the existing tests seems to be a good idea though anyway.
You do not have to do it for multiple versions of Vim, but when desired, there is https://github.com/tweekmonster/vim-testbed/ to help with building a Docker image for this.
CircleCI's integration with Docker is nicer than Travis'.
