### ISSUE TITLE
No signs on Windows with async and git core.autocrlf true

### ISSUE THREAD

**Issue by barrelmaker97** [airblade/vim-gitgutter#486]
When I open gvim on Windows, I get an error message which says "vim-gitgutter: cannot find grep. Please set g:gitgutter_grep". No signs show up when working on a git controlled file. This occurred after updating the plugin using vim-plug a couple days ago, and I am currently at commit 9325986457f18b30e39f27d25b89d62545f6e3ee. Setting  `let g:gitgutter_grep=''` in my vimrc removes the error message but does not fix the signs not appearing. Running `:GitGutterDebug` gives me this, no matter how I set `g:gitgutter_grep`:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 18 2018 23:08:43)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-1523

git version 2.16.1.windows.4

'grep' is not recognized as an internal or external command,operable program or batch file.
'grep' is not recognized as an internal or external command,operable program or batch file.

updatetime=250
shell=C:\WINDOWS\system32\cmd.exe
shellcmdflag=/c
shellpipe=>%s 2>&1
shellquote=
shellredir=>%s 2>&1
shellslash=0
shelltemp=1
shelltype [n/a]
shellxescape="&|<>()@^
shellxquote=(
```

I believe something about the refactor 2 weeks ago broke the behavior of grep for Windows, but I am not sure. It appears to be attempting to use grep from the Windows Command Prompt and failing.

**Comment by airblade** [comment]
Now I look again at how the plugin handles grep, I think the behaviour changed in that big refactor.

Previously, if you didn't set `g:gitgutter_grep_command`, the code [did not warn you](https://github.com/airblade/vim-gitgutter/blob/932ffaca092cca246b82c33e23d2d3a05e192e08/autoload/gitgutter/diff.vim#L1-L12) if it couldn't find `grep` on the path.

Now, if you don't set `g:gitgutter_grep`, it [does warn you](https://github.com/airblade/vim-gitgutter/blob/c3bad229db95bfa239f0120a9cfcbf74ba4f4f8b/plugin/gitgutter.vim#L66-L68) if it can't find `grep`.  I'm not sure whether that change is better or worse.

In both versions it should not try to use grep on the diff if grep is unavailable.

The `:GitGutterDebug` command [calls `system('grep')`](https://github.com/airblade/vim-gitgutter/blob/c3bad229db95bfa239f0120a9cfcbf74ba4f4f8b/autoload/gitgutter/debug.vim#L54-L60) without checking whether it's actually available, which is suboptimal.

It seems clear that `grep` is not available to your vim, which is fine.

The question is why the signs don't appear even when you turn off grep with `let g:gitgutter_grep=''`.  Please can you turn on the logging with `let g:gitgutter_log=1`, execute `:GitGutter` on a buffer where you expect to see signs, and post the log file (in your gitgutter directory)?  Also, what does `:echo b:gitgutter` produce?

**Comment by airblade** [comment]
I restored the previous behaviour around not warning when default grep cannot be found (61a5e01).

**Comment by barrelmaker97** [comment]
> Also, what does `:echo b:gitgutter` produce?

`{'hunks': [], 'path': 'vimrc', 'summary': [0, 0, 0]}`

Here is the [log file](https://github.com/airblade/vim-gitgutter/files/1749044/gitgutter.log)
Using `let g:gitgutter_async=0` seems to fix the issue

**Comment by barrelmaker97** [comment]
After further testing with different buffers, I can confirm that setting `let g:gitgutter_async=0` in my vimrc fixes the issue. Any thoughts on why that is?

**Comment by airblade** [comment]
It must be to do with the async execution of commands.  This is the [only recent change](https://github.com/airblade/vim-gitgutter/commit/5bfe5b92099e0d332a7ca26c0263fab509ee9617#diff-302765a6376ab8c93ca461ad1fdb5d7d) to that file.

In your log file I can see the commands being executed asynchronously but not their results, nor any error messages.  The same commands work synchronously (i.e. via `system()`) so maybe it's a problem with the async callbacks.  All I can suggest is adding some `echom` statements in the [callbacks](https://github.com/airblade/vim-gitgutter/blob/b27ee4d602d7ce6f7b7caf8e9ecb8eded57ffe0a/autoload/gitgutter/async.vim#L74-L89) to see whether they are being called or not.

**Comment by barrelmaker97** [comment]
Here is the [log file](https://github.com/airblade/vim-gitgutter/files/1759566/gitgutter.log) that is produced when I have `let g:gitgutter_async=0` set in my vimrc. Hopefully this helps. As far as this issue, I'd say it's solved for me, I'll just keep async off in my vimrc.

**Comment by airblade** [comment]
Thanks for the second log file.  It's just like the first, except with diffs too ;)

When you run gitgutter asynchronously your async callbacks don't seem to be called; but without more information it's hard to say why not.

Anyway, glad it's working with `let g:gitgutter_async=0`.

**Comment by airblade** [comment]
I was able to reproduce this in a Windows VM.

First I had to add `--no-pager` to the `git show` and `git diff` commands to get output to appear, but maybe that's just my environment.

Anyway, let's say I have a file `foo.txt` in a git repo.  At a high level gitgutter does this to get a diff:

```
git show :foo.txt > tmp_file_a.txt
<<write buffer contents to tmp_file_b.txt>>
git diff --no-index echo tmp_file_a.txt tmp_file_b.txt
```

I have git's `core.autocrlf` set to `true`.  This means that although `foo.txt` has CRLF line endings, inside git's object store its line endings are `LF`.  `git-show` writes out the file from the object store as-is, i.e. with `LF` line endings.

When `git-diff` runs, it sees that `tmp_file_a.txt` has `LF` line endings instead of `CRLF`.  It therefore outputs a warning message on stderr, as well as the actual diff on stdout:

```
warning: LF will be replaced by CRLF in C:\Users\IEUser\AppData\Local\Temp\VIA272A.tmp.1.py.
The file will have its original line endings in your working directory.
```

Despite this everything is fine and we can ignore the warning.

However the plugin's [async stderr handler](https://github.com/airblade/vim-gitgutter/blob/c39a5c240a4f34d00288d51674d54b6b6480694f/autoload/gitgutter/async.vim#L78-L85) sees the output on stderr and thinks that the command has failed somehow, and so resets all the signs.

I think the solution is to stop the async error handler being triggered by the warning message.

**Comment by airblade** [comment]
This patch fixes it for me, i.e. lets gitgutter work asynchronously:

```diff
diff --git i/autoload/gitgutter/diff.vim w/autoload/gitgutter/diff.vim
index 5a4e406..5b58c14 100644
--- i/autoload/gitgutter/diff.vim
+++ w/autoload/gitgutter/diff.vim
@@ -85,6 +85,7 @@ function! gitgutter#diff#run_diff(bufnr, preserve_full_diff) abort
   if s:c_flag
     let cmd .= ' -c "diff.autorefreshindex=0"'
     let cmd .= ' -c "diff.noprefix=false"'
+    let cmd .= ' -c "core.safecrlf=false"'
   endif
   let cmd .= ' diff --no-ext-diff --no-color -U0 '.g:gitgutter_diff_args.' -- '.index_file.' '.buff_file
 ```

Please could you try it and let me know if it works for you?

**Comment by barrelmaker97** [comment]
Good find! I just tried your patch, and it fixes it for me as well. I can now run gitgutter with async on.

**Comment by airblade** [comment]
Thanks for letting me know :)

**Comment by mreishus** [comment]
I'm still having this problem.  Strangely enough, I don't see the CR/LF warning when I `git diff` in powershell, but if I look at the command being executed in channel log and run it myself in cmd.exe, there it is:

```
C:\dev\ABC\projname>cmd.exe /c cd /d "C:\dev\ABC\projname\client\components\asdf\item" && (git --no-pager show :projname/client/components/asdf/item/Abcdef.js > C:\Users\myusername\AppData\Local\Temp\VIECF87.tmp.2.js && git --no-pager -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\c10666a\AppData\Local\Temp\VIECF87.tmp.2.js C:\Users\c10666a\AppData\Local\Temp\VIFCF98.tmp.2.js)
warning: LF will be replaced by CRLF in C:/Users/myusername/AppData/Local/Temp/VIECF87.tmp.2.js.
The file will have its original line endings in your working directory.
diff --git a/a/AppData/Local/Temp/VIECF87.tmp.2.js b/a/AppData/Local/Temp/VIFCF98.tmp.2.js
index 7b5255f05..db1061e88 100644
--- a/a/AppData/Local/Temp/VIECF87.tmp.2.js
+++ b/a/AppData/Local/Temp/VIFCF98.tmp.2.js
```

I don't really get it, and I don't expect help since this problem is so weird, but I will update if I find anything.

**Comment by airblade** [comment]
> As a dirty hack I emptied out the on_stderr_vim function.

Funnily enough I've been wondering for a while whether the stderr callback handler is actually needed.  Originally I thought that any output on stderr indicated a problem so the plugin should not try to show any signs as they could be mistaken.  Now I think that the plugin should just use whatever's produced on stdout and if there is a problem then stdout won't have anything useful; i.e. ignore stderr.
