### ISSUE TITLE
Staging hunk is not working.

### ISSUE THREAD

**Issue by shea-parkes** [airblade/vim-gitgutter#494]
> What is the latest commit SHA in your installed vim-gitgutter?
```
commit b27ee4d602d7ce6f7b7caf8e9ecb8eded57ffe0a (HEAD -> master, origin/master, origin/HEAD)
Author: Andy Stewart <boss@airbladesoftware.com>
Date:   Thu Feb 22 16:23:17 2018 +0000

    Rename variable for clarity.
```

> What vim/nvim version are you on?
NVIM v0.2.2 on Windows 10

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?
Signs are showing fine.

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?
Signs are showing fine.

I'm not able to stage a hunk.  I believe the issue is related to the creation of the patch diff.  It's not being ~mutated to look like it applies to the real files.  Here's the output from `gitgutter.log`:
```
2066.327010 function gitgutter#hunk#stage[1]..<SNR>70_hunk_op[6]..gitgutter#diff#run_diff[74]..gitgutter#utility#system[1]:
2066.327010 cd "C:\Users\shea.parkes\nvim" && (git --no-pager show :init.vim > C:\Users\SHEA~1.PAR\AppData\Local\Temp\nvimJcmSv9\11.1.vim && git --no-pager -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\SHEA~1.PAR\AppData\Local\Temp\nvimJcmSv9\11.1.vim C:\Users\SHEA~1.PAR\AppData\Local\Temp\nvimJcmSv9\12.1.vim || exit 0)

2066.432263 function gitgutter#hunk#stage[1]..<SNR>70_hunk_op[14]..<SNR>70_stage[4]..gitgutter#utility#system[1]:
2066.432263 cd "C:\Users\shea.parkes\nvim" && git apply --cached --unidiff-zero - 
2066.432263 [diff --git "a/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\11.1.vim" "b/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\12.1.vim"
index f42aeb0..4930403 100644
--- "a/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\11.1.vim"
+++ "b/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\12.1.vim"
@@ -172,0 +173 @@ nnoremap <Leader>gc :Gcommit --verbose<CR>
+nnoremap <Leader>gd :Gdiff<CR>
]

2066.514006 function gitgutter#hunk#stage[1]..<SNR>70_hunk_op[14]..<SNR>70_stage[9]..gitgutter#process_buffer[8]..gitgutter#diff#run_diff[67]..gitgutter#async#execute[1]:
2066.514006 [async] cd "C:\Users\shea.parkes\nvim" && (git --no-pager show :init.vim > C:\Users\SHEA~1.PAR\AppData\Local\Temp\nvimJcmSv9\11.1.vim && git --no-pager -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\SHEA~1.PAR\AppData\Local\Temp\nvimJcmSv9\11.1.vim C:\Users\SHEA~1.PAR\AppData\Local\Temp\nvimJcmSv9\12.1.vim | grep "^@@ " || exit 0)

2066.691090 function <SNR>85_on_exit_nvim[2]..gitgutter#diff#handler[1]:
2066.691090 @@ -172,0 +173 @@ nnoremap <Leader>gc :Gcommit --verbose<CR>
```

For context, I'm trying to stage a change that's in my own `~/nvim/init.vim`.  I saved the patch-diff above to a file and ran the `git apply` in powershell to get the following error:
```
C:\Users\shea.parkes\nvim [master ≡ +0 ~1 -0 !]> git apply --cached --unidiff-zero $env:temp\nvimJcmSv9\diff.txt
C:/Users/SHEA~1.PAR/AppData/Local/Temp/nvimJcmSv9/diff.txt:6: trailing whitespace.
nnoremap <Leader>gd :Gdiff<CR>
error: C:\Users\SHEA~1.PAR\AppData\Local\Temp\nvimJcmSv9\11.1.vim: does not exist in index
C:\Users\shea.parkes\nvim [master ≡ +0 ~1 -0 !]>
```
I thought the whitespace warning was likely some CRLF/LF mess when I saved the generated diff, and the "does not exist in index" sounds like the real culprit.  I tried to read the source code to understand if the filepath is supposed to be mutated, and I ultimately decided that I thought it should have been.  Alas, vimscript is not my strong suit, so I couldn't be sure.

Happy to provide any additional details upon request.

**Comment by airblade** [comment]
What does `diff.txt` look like?

**Comment by airblade** [comment]
When you stage a hunk, gitgutter takes the buffer's overall diff, discards the other hunks, then updates the diff header in two ways:

- It replaces the temp file paths with your file's actual path.
- It adjusts the line offsets (between the @@ markers) as if there were no hunks above it, so it lines up correctly with the index.

**Comment by airblade** [comment]
It looks like the first part isn't working (replacing the temp file paths).  Probably because the code uses this regexp](https://github.com/airblade/vim-gitgutter/blob/05e538e553d05cc728577f2c96dd8abc43aa8a74/autoload/gitgutter/hunk.vim#L232) to match the hunk's paths:

```viml
'\vdiff --git ./(\S+) ./(\S+)\n'
```

But in your log the text is:

```
diff --git "a/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\11.1.vim" "b/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\12.1.vim"
```

I.e. with quotation marks.

Are you able to stage hunks with this change?

```diff
diff --git i/autoload/gitgutter/hunk.vim w/autoload/gitgutter/hunk.vim
index 4289807..84c6a25 100644
--- i/autoload/gitgutter/hunk.vim
+++ w/autoload/gitgutter/hunk.vim
@@ -229,7 +229,7 @@ endfunction
 function! s:fix_file_references(bufnr, hunk_diff)
   let filepath = gitgutter#utility#repo_path(a:bufnr, 0)
   let diff = a:hunk_diff
-  for tmp in matchlist(diff, '\vdiff --git ./(\S+) ./(\S+)\n')[1:2]
+  for tmp in matchlist(diff, '\vdiff --git "./(\S+)" "./(\S+)"\n')[1:2]
     let diff = substitute(diff, tmp, filepath, 'g')
   endfor
   return diff
```

**Comment by shea-parkes** [comment]
Thanks for looking into this.  To answer the first question, the contents of `diff.txt` were pulled from the log above:
```
diff --git "a/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\11.1.vim" "b/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\12.1.vim"
index f42aeb0..4930403 100644
--- "a/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\11.1.vim"
+++ "b/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\12.1.vim"
@@ -172,0 +173 @@ nnoremap <Leader>gc :Gcommit --verbose<CR>
+nnoremap <Leader>gd :Gdiff<CR>
```

I tried out your suggested and change and looks like the regex failed to hit anything.  The specific error it threw was `E874: (NFA) Could not pop the stack !`

I tried to get it down to a reproducible example of a single function call.  I stripped the beginning and end of the regex to try and make it work against a string literal:
```
echo matchlist('diff --git "a/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\11.1.vim" "b/C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\12.1.vim"', 'diff --git "./(\S+)" "./(\S+)"')
```
the above returned an empty list.  I'll futz a bit with the regex shortly to see if I can get it to capture correctly.  Any further help is of course appreciate.  Thanks for making such a great tool and being willing to help on a NVim+Win10 setup (which I'm assuming isn't that common).

**Comment by airblade** [comment]
You left out the `\v` at the start of the regex (this makes it "very magic").  When you add it back in, the regex matches.

I'm not sure where the E874 came from.  I tried forcing both the old and the new regex engines (by prepending `\%#=1` or `\%#=2` to the pattern) but both worked for me.

**Comment by shea-parkes** [comment]
My apologies, I thought it was some special sequence that matched the start of a file or something.  Adding back the `\v` did get it to match.

I now think the issue is that `substitute` is trying to evaluate the value of `tmp` as a regex string.  And `C:\\Users\\SHEA~1.PAR\\AppData\\Local\\Temp\\nvimJcmSv9\\12.1.vim` has all sorts of things that trigger as escaped characters.  I need to head out soon, but I'll be next googling to understand if there is a "dumber" alternative to `substitute`.  (Or something like `\v` that means "match literally")

**Comment by shea-parkes** [comment]
Hrm, doesn't look like explicitly disabling magic would even let those double backslashes through.  My current thought is to change it such that it doesn't try to save the result of the first search into a string to use as a pattern in the second search.  I just need to understand if the regex group is respected in a call to `substitute`.  (i.e. remove the use of `tmp` to pass from `matchlist()` to `substitute()`.

**Comment by shea-parkes** [comment]
Alright, this version worked for me.  I ended up just escaping the string.  I used "very nomagic" (`\V`) to escape everything but the backslashes, and then doubled them:
```viml
" Replaces references to temp files with the actual file.
function! s:fix_file_references(bufnr, hunk_diff)
  let filepath = gitgutter#utility#repo_path(a:bufnr, 0)
  let diff = a:hunk_diff
  for tmp in matchlist(diff, '\vdiff --git "?./(\S+)" "?./(\S+)"\n')[1:2]
    let tmp2 = '\V' . substitute(tmp, '\\', '\\\\', 'g')
    let diff = substitute(diff, tmp2, filepath, 'g')
  endfor
  return diff
endfunction
```

Next I suppose I need to figure out how to make that pattern backward compatible (if you're willing to accept something like the above).

**Comment by shea-parkes** [comment]
Alright, I think this is backwards compatible:
```viml
" Replaces references to temp files with the actual file.
function! s:fix_file_references(bufnr, hunk_diff)
  let filepath = gitgutter#utility#repo_path(a:bufnr, 0)
  let diff = a:hunk_diff
  for tmp in matchlist(diff, '\vdiff --git "?a/([^"]+)"? "?b/([^"]+)"?\n')[1:2]
    let tmp_esc = '\V' . substitute(tmp, '\\', '\\\\', 'g')
    let diff = substitute(diff, tmp_esc, filepath, 'g')
  endfor
  return diff
endfunction
```

One thing I wasn't super comfortable with: I wanted to do something like `[^\s"]` but it looks like you can't use special values inside of a character range in vim regex.

I went ahead and switched to explicitly looking for `a/` and `b/` to be a little more defensive.  Please give a shout if that was a bad assumption (that it will always be `a/` and `b/`).

I'm happy to submit a pull request if you think this solution is plausible.

**Comment by airblade** [comment]
I think my original approach was suboptimal: I hadn't realised it but, as you pointed out, it was treating the temp file paths as regexes.

I've gone with a more literal approach in 5db4a3a.  Please let me know if it works for you.

**Comment by shea-parkes** [comment]
Thanks for the link explaining the brittleness of `a/` and `b/` (and continuing to work on this).

I did `substitute(tmp, '\\', '\\\\', 'g')` because it appears the backslashes are still escaped (i.e. that's actually still going from one to two backslashes).

I also concur the main problem was the lack of literal substitution and the treatment of the temp file paths as regex patterns.  I'll go see about testing your alternative solution now.

**Comment by shea-parkes** [comment]
I tested the solution in 5db4a3a and it worked like a charm.  Took me a few minutes to understand the code changes, but I got there and agree with them as well (although I think `lines[0][11]` was a bold move).  I also appreciate the solid test coverage.  Thanks for churning out a quality product.

**Comment by airblade** [comment]
Thanks for explaining those backslashes – they are tricky beasts!

`lines[0][11]` looks risky but I think the unified diff format is unlikely to change.

Glad we got to the bottom of all this :)
