### ISSUE TITLE
gitgutter#utility#cd_cmd might be unnecessary

### ISSUE THREAD

**Issue by blueyed** [airblade/vim-gitgutter#498]
1. you can temporarily change the directory in Vim before `system()`, but it is not trivial, since you need to handle (and restore) `:lcd`, `:tcd` or `:cd`
2. `--git-dir` can be used with `git` commands to not require changing the directory before, but is not trivial to get (https://github.com/tpope/vim-fugitive/blob/b82abd5bd583cfb90be63ae12adc36a84577bd45/plugin/fugitive.vim#L139-L190).

Feel free to close this, it just appeared to me and I wanted to let you know.

**Comment by airblade** [comment]
Thanks for the feedback – much appreciated.

1. I don't want to change Vim's working directory, only the shell commands'.  And as you say, changing Vim's requires changing it back again afterwards, which is more work than prefixing each shell command with `cd /some/path && `.
2. I reckon `cd /some/path && ...` is simpler and safer than that monster function in Fugitive ;)

Thanks again.
