### ISSUE TITLE
vim-gitgutter destroys `:redir` functionality

### ISSUE THREAD

**Issue by SamDM** [airblade/vim-gitgutter#500]
> What is the latest commit SHA in your installed vim-gitgutter?

538e078

> What vim/nvim version are you on?

Nvim v0.2.2

**Problem description:**

I noticed that when I have vim-gitgutter installed, any kind of `:redir` commands are not longer working.

E.g.: the following command sequence:
```
redir => b:messages
echo "foo"
redir END
echo b:messages
```
Should show the string "foo" in the ex command area at the bottom of the screen. When I
1. Comment out the line `Plug 'airblade/vim-gitgutter'` such that it is not loaded on startup.
2. Restart nvim
3. Execute the commands given above.

I can see the message "foo" appearing. However, when the plugin is loaded, the variable "b:messages" is empty.

I also noticed that when gitgutter is loaded, the nvim startup message disappears after a split second.

**Comment by airblade** [comment]
How odd.  I can reproduce here on vim and nvim.

The help for `:intro` says the startup message is removed as soon as the display is redrawn in any way.  The plugin contains 3 redraw commands; I commented out all of them but the problem remained.

Must be something else...

**Comment by airblade** [comment]
Running the commands on one line works:

```
redir => b:mess | echo "foo" | redir END | echo b:mess
```

Which might suggest the display is being redrawn too early when running one command at a time.

**Comment by airblade** [comment]
This is the commit that introduced the problem: 85f6e13.

It "resets" buffers which gitgutter won't process.  Part of the reset clears the signs, which calls:

```viml
  redir => signs
    silent execute "sign place buffer=" . a:bufnr
  redir END
```

This `redir` aborts any open `redir` and triggers a redraw.

**Comment by airblade** [comment]
I think the code needs to distinguish a buffer which could be processed but won't be (e.g. because vim's in diff mode) from a buffer which couldn't be processed (e.g. because it does not have a file).

**Comment by airblade** [comment]
A related point is we only perform this `redir` so we can avoid overwriting other plugins' signs.  If we decided gitgutter could have sole ownership of vim's signs, we wouldn't need to do it.
