### ISSUE TITLE
Need to call :GitGutter after committing using fugitive

### ISSUE THREAD

**Issue by yevhen-m** [airblade/vim-gitgutter#502]
> What is the latest commit SHA in your installed vim-gitgutter?
`37bdd03d17`
> What vim/nvim version are you on?
`NVIM v0.2.2`

When I commit using fugitive, signs in gutter aren't updated. Need either to trigger `:GitGutter` or trigger "focus gained" event switching tmux panes. 
I guess I remember that before the plugin refactoring signs were updated after commit automatically.

**Comment by airblade** [comment]
Before the refactor the plugin listened to `BufWritePost`, which Fugitive was emitting at my request.

Now the plugin doesn't listen to that event.  I have asked [whether Fugitive can emit `ShellCmdPost` or a custom autocommand](https://github.com/tpope/vim-fugitive/issues/503#issuecomment-374968526) instead.

**Comment by yevhen-m** [comment]
@airblade thanks. Let's wait.

**Comment by airblade** [comment]
As a workaround you could do this:

```viml
autocmd gitgutter BufWritePost * GitGutter
```

cc @amadeus

**Comment by airblade** [comment]
@lisinge Sorry, I don't know.  Does gitgutter work otherwise for you in neovim?

**Comment by lisinge** [comment]
@airblade yup! Works perfectly other than not updating the signs once fugitive is done

**Comment by thisgeek** [comment]
I've had a nice experience so far with a slight tweak to @airblade's workaround:

```vim
autocmd BufWinLeave * GitGutterAll
```

Main benefit: The gutter resets as soon as `COMMIT_EDITMSG` is closed.
Disclaimer: I have not thought about whether this is a sledgehammer solution. It works for me.

**Comment by micke** [comment]
@thisgeek thanks dude! Will try this out right away!

**Comment by mk12** [comment]
I'm using:

```vim
autocmd BufWritePost,WinEnter * GitGutter
```

The `BufWritePost` I like to keep regardless because I want an update after save but don't want to reduce my `updatetime` from 4s. However, it would be nice if the present issue was fixed for Neovim too so that I wouldn't need the `WinEnter`.

**Comment by blueyed** [comment]
It would be helpful if there were steps to reproduce this..

(Note that this _might_ be related to Vim incrementing `b:changedtick` when `BufWritePost` is executed via `:w` / `:up`, but not via `:doautocmd BufWritePost` (what vim-fugitive is using in its `BufWriteCmd`) (https://github.com/vim/vim/issues/2764).  But that's the case also for Neovim (AFAIK), and (also AFAIK) vim-gitgutter does not special-casing for this (like Neomake is doing))
