### ISSUE TITLE
Endless process spawning

### ISSUE THREAD

**Issue by ConnorKrammer** [airblade/vim-gitgutter#505]
Using gVim 7.4 on Windows 7 and the as-of-now latest version of gitgutter (3724e1c207c980b5de914b4857e8b44dc3551506), opening a file with gVim causes the program to hang as new processes are spawned in a loop. I believe this is a regression related to #42.

Reverting 33c4c4a685a48894dbac7c33c2a25ab9b904c030 specifically fixed the problem.

**Comment by airblade** [comment]
Do you happen to know whether gVim 8.0 fixes the problem?  If so, I can add that conditional back in but limiting it to gVim 7.4...

**Comment by ConnorKrammer** [comment]
Found time today to test with 8.0.586—where yep, it does seem to be fixed. (Which version between 7.4 unpatched and 8.0 fully patched specifically fixed the bug, I'm not sure, but anyone who downloads gVim right now and uses gitgutter won't encounter the bug.)

**Comment by ConnorKrammer** [comment]
Did some more testing. If I modify `gitgutter#async#available` to always return false, then the bug manifests even when using gVim 8.0. Based on that, I would guess this is specifically an issue with non-async versions of gVim.

**Comment by ConnorKrammer** [comment]
Yep, that does seem to stop the problem.

**Comment by Snaptags** [comment]
I am still having this issue :-( My gvim is reporting
gitgutter#utility#windows() = 1
gitgutter#async#available() = 1
thus the workaround is never executed...

**Comment by airblade** [comment]
@Snaptags I see you have turned async off (https://github.com/Snaptags/vimconfig/blob/8f110dbb8545412b0c8b47b47e5a6a20b5081a29/config/plugin_settings.vimrc#L8) which is presumably why you are still having the problem.

The plugin is missing a condition:

```viml
if gitgutter#utility#windows() && !(g:gitgutter_async && gitgutter#async#available())
  set noshelltemp
endif
```

I'll add it now...

**Comment by Snaptags** [comment]
I had indeed, seems to be a very old workaround for a no longer existing problem :-) Thanks for pointing this out, git-gutter is now running smoothly again!
