### ISSUE TITLE
Feature request: Support --color-moved

### ISSUE THREAD

**Issue by mantoni** [airblade/vim-gitgutter#506]
Hey! Thanks for making one of the best vim plugins. I love this thing.

I started using the more recent git diff option `--color-moved` to have a visual distinction for moved, but otherwise unchanged lines. It would be awesome if this could be supported by gitgutter.

My vimscript skills are not good enough to provide a PR myself – sorry ❤️🙏

**Comment by airblade** [comment]
Glad you like the plugin!

I didn't know about `--color-moved` – it looks handy.

However as far as I can tell it only affects the colour output of `git-diff`, not the `-`/`+` markers.  Since `git-diff` produces plain text output when the plugin runs it, there's no way for the code to detect moved lines.

**Comment by mantoni** [comment]
Ah I see. I assumed there would be a plain text equivalent, but from the `git diff` documentation it appears there isn’t.

So I guess the only way to make this work is to either build move detection, or to force diff color output and parse the color code escape sequences. Not sure if that’s going a bit too far though 🤔

**Comment by airblade** [comment]
That's going too far for me :)  I imagine duplicating git's move detection in vimscript would slow things down, perhaps noticeably, and parsing escape sequences would doubtless be a nightmare to support on all the various terminals and platforms in the wild.

It's a nice idea but I think the costs outweigh the benefits in this context.

**Comment by mantoni** [comment]
I agree. If I come across a better way to do it, I’ll update this issue. Thanks.
