### ISSUE TITLE
Automatically disable plugin for git-ignored files

### ISSUE THREAD

**Issue by glhrmv** [airblade/vim-gitgutter#507]
I have a `.txt` file in a project with 974k lines (specifically this [Project Gutenberg dictionary](http://www.gutenberg.org/files/29765/)). It is included in my `.gitignore`. It opens in about one second if I have `vim-gitgutter` disabled with `:GitGutterDisable`, but it takes significantly longer to open with it enabled, and it makes actually editing the file nearly impossible due to the 100ms delay I set as recommended in the `README`, as (I assume) it traverses the entire file looking for changes.

Since it is a file that is ignored by git, the plugin doesn't actually affect the sign column or the indicator in `vim-airline`, as expected. However, the plugin is still in effect as evidenced by the airline indicator -- if it was disabled, the indicator would not show up at all -- and the obvious (and significant) performance hit caused by its presence. 

Ideally I would like for the plugin to not even be called on files that are ignored by git. Is this at all possible?

> What vim/nvim version are you on?

Vim 8.0.1650

**Comment by glhrmv** [comment]
The link doesn't 404 for me, can you try again? 

I'm also on macOS and I copied the `/usr/share/dict/words` file to my repo and it opens very quickly, though naturally not as fast as a regular file with a reasonable number of lines. 

When I `:echo b:gitgutter` with my cursor in the large dictionary file I mentioned, I get:
```
{'hunks': [], 'path': 'dict.txt', 'summary': [0, 0, 0], 'other_signs': [], 'dummy_sign': 0, 'gitgutter_signs': {}, 'tick': 2}
```

I believe I'm using the latest commit of `vim-gitgutter`: I ran `:PlugUpdate` and it was `Already up to date`.

**Comment by airblade** [comment]
The link still 404s for me.  Weird.

Anyway, the `path` value in your `b:gitgutter` dictionary shows that git is not ignoring your file; if it were, the path would be `-2`.

You can test this with:

```
:!git ls-files --error-unmatch --full-name dict.txt
```

We want an error due to the file being ignored; if you get the path, it's not ignored.

**Comment by glhrmv** [comment]
Thanks to that information I found out It was a git-related issue, I guess if you've ever staged a particular file and committed it in the past, you cannot add it to `.gitignore` a posteriori without first removing it from the git cache.

I ran the commands outlined in [this StackOverflow answer](https://stackoverflow.com/a/11451731/6304441), pushed to remote and it is now working as expected: the file no longer has the slowdown caused by `vim-gitgutter`.

I'm still not sure why, if the file was still being tracked by git, neither the sign column nor the status line indicator changed when I made any change to the file. But at this point I'm not sure if I know how to reproduce the steps.

Maybe to avoid future confusion there could be a small indicator in the status bar for when the file is not being tracked by git, as currently every file in the repository has the `+X ~X -X` indicator, regardless.

**Comment by airblade** [comment]
The `+X ~X -X` indicator comes from airline – you'll have to ask those guys to show something different for files which git isn't tracking.

Or you could add a function to your vimrc which tests whether the file is known to git before displaying the `+X ~X -X` indicator`, and plug that into airline instead of its default hunks function.
