### ISSUE TITLE
Do not run git via cmd.exe, which can be a vulnerability.

### ISSUE THREAD

**Issue by igrep** [airblade/vim-gitgutter#508]
> What is the latest commit SHA in your installed vim-gitgutter?

```
> git show
commit 5481318fc1b97e7c04eab5496ec45c63335d6bc1 (HEAD -> master, origin/master, origin/HEAD)
...
```

> What vim/nvim version are you on?

Vim ver. 8.0 patch 596 on Windows 10 Pro 64 bit

# Steps to reproduce

1. Write a file named `git.js` below:
    ```
    while(true) { }
    ```
1. Open `git.js` (or any file in the same directory with `git.js`) from Explorer (usually by double-clicking).

# Result

- GVim stalls until its window gets closed.
- git.js is executed as a JScript file by WSH until closing GVim.

# Cause

This is caused by `cmd.exe`'s malicious behavior,
which **gives priority to the current directory** over the paths in `PATH` when resolving the command path.
In addition, `.js` files are recognized as a command by default because `.JS` is in the `PATHEXT` environment variable.

# How to fix

This should be fixed by avoiding calling `git` command via `cmd.exe`.
There are two ways to do so:

1. Build the command line as a list.
    According to `:help job_start` on vim and `:help jobstart` on neovim (ver. 0.2.2),
    both `job_start` and `jobstart` don't call `cmd.exe` if their first argument is a list.
    So I recommend this way.
    This makes calling `shellescape` unnecessary in addition!
1. Use `powershell.exe` instead. It's available by default since Windows 7.

# Workaround

Specify git command's full path in vimrc.
For example:

```vim
if has('win32')
  let g:gitgutter_git_executable = 'C:\Program Files\Git\bin\git.exe'
endif
```

**Comment by airblade** [comment]
Thanks for the detailed report.

Regarding your first solution, I believe we need to call `cmd.exe` (or `powershell.exe`) because we need a shell for the pipes and or (`||`) operator.  Would you agree?

Regarding your second solution, are there any disadvantages to powershell?

**Comment by igrep** [comment]
> I believe we need to call cmd.exe (or powershell.exe) because we need a shell for the pipes and or (||) operator. Would you agree?

Oh... You're right. I've missed the point. I've forgot vim's subprocess APIs are very limited... 😞 

> Regarding your second solution, are there any disadvantages to powershell?

The differences between powershell and cmd.exe must be considered.
For example, in powershell, [backquote is used to escape](https://ss64.com/ps/syntax-esc.html).

**Comment by igrep** [comment]
Unfortunately, no.
If `git.exe` exists in the current directory, it gets higher priority.

But it makes me think of a new idea that gitgutter can search `git.exe` from `PATH` by itself.
This way could be easier to rewrite to call via powershell.

**Comment by airblade** [comment]
I'm "solving" this with documentation (de200ff); I can't think of a better solution for now.

Thanks again for reporting this.
