### ISSUE TITLE
Many error messages after inserting php FQCN

### ISSUE THREAD

**Issue by greg0ire** [airblade/vim-gitgutter#509]
> What is the latest commit SHA in your installed vim-gitgutter?

5481318

> What vim/nvim version are you on?

<details>
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  6 2018 08:24:16)
Included patches: 1-1573
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +clientserver      +dialog_con_gui    +find_in_path      +keymap            +modify_fname      +multi_byte        +profile           +statusline        +textobjects       +wildignore
+arabic            +clipboard         +diff              +float             +lambda            +mouse             +multi_lang        +python/dyn        -sun_workshop      +timers            +wildmenu
+autocmd           +cmdline_compl     +digraphs          +folding           +langmap           +mouseshape        -mzscheme          +python3/dyn       +syntax            +title             +windows
-autoservername    +cmdline_hist      +dnd               -footer            +libcall           +mouse_dec         +netbeans_intg     +quickfix          +tag_binary        +toolbar           +writebackup
+balloon_eval      +cmdline_info      -ebcdic            +fork()            +linebreak         +mouse_gpm         +num64             +reltime           +tag_old_static    +user_commands     +X11
+balloon_eval_term +comments          +emacs_tags        +gettext           +lispindent        -mouse_jsbterm     +packages          +rightleft         -tag_any_white     +vertsplit         -xfontset
+browse            +conceal           +eval              -hangul_input      +listcmds          +mouse_netterm     +path_extra        +ruby/dyn          -tcl               +virtualedit       +xim
++builtin_terms    +cryptv            +ex_extra          +iconv             +localmap          +mouse_sgr         +perl/dyn          +scrollbind        +termguicolors     +visual            +xpm
+byte_offset       +cscope            +extra_search      +insert_expand     +lua/dyn           -mouse_sysmouse    +persistent_undo   +signs             +terminal          +visualextra       +xsmp_interact
+channel           +cursorbind        +farsi             +job               +menu              +mouse_urxvt       +postscript        +smartindent       +terminfo          +viminfo           +xterm_clipboard
+cindent           +cursorshape       +file_in_path      +jumplist          +mksession         +mouse_xterm       +printer           +startuptime       +termresponse      +vreplace          -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1
-I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0
 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread    -O2 -g -pipe -Wall -Werror=format-security -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib
/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/python3.6m -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -W
l,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobj
ect-2.0 -lglib-2.0  -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm -lnsl  -lselinux   -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro -specs=/usr/lib/rpm/
</details>

# The issue

I use https://github.com/arnaud-lb/vim-php-namespace to insert php namespaces in my files, and everytime I do that, I will get many error messages from git gutter. Typing `:messages` after that yields this:

```
Error detected while processing function <SNR>161_on_exit_vim[1]..gitgutter#diff#handler[3]..gitgutter#hunk#set_hunks[1]..gitgutter#utility#setbufvar:
line    1:
E712: Argument of get() must be a List or Dictionary
Error detected while processing function <SNR>161_on_exit_vim[1]..gitgutter#diff#handler[3]..gitgutter#hunk#set_hunks[2]..<SNR>167_reset_summary[1]..gitgutter#utility#setbufvar:
line    1:
E712: Argument of get() must be a List or Dictionary
Error detected while processing function <SNR>161_on_exit_vim[1]..gitgutter#diff#handler[4]..gitgutter#hunk#hunks[1]..gitgutter#utility#getbufvar:
line    1:
E712: Argument of get() must be a List or Dictionary
Error detected while processing function <SNR>161_on_exit_vim[1]..gitgutter#diff#handler[15]..gitgutter#sign#update_signs[1]..<SNR>168_find_current_signs:
line    6:
E158: Invalid buffer name: 
line    5:
E121: Undefined variable: signs
Error detected while processing function <SNR>161_on_exit_vim[1]..gitgutter#diff#handler[3]..gitgutter#hunk#set_hunks[1]..gitgutter#utility#setbufvar:
line    1:
E712: Argument of get() must be a List or Dictionary
Error detected while processing function <SNR>161_on_exit_vim[1]..gitgutter#diff#handler[3]..gitgutter#hunk#set_hunks[2]..<SNR>167_reset_summary[1]..gitgutter#utility#setbufvar:
line    1:
E712: Argument of get() must be a List or Dictionary
Error detected while processing function <SNR>161_on_exit_vim[1]..gitgutter#diff#handler[4]..gitgutter#hunk#hunks[1]..gitgutter#utility#getbufvar:
line    1:
E712: Argument of get() must be a List or Dictionary
Error detected while processing function <SNR>161_on_exit_vim[1]..gitgutter#diff#handler[15]..gitgutter#sign#update_signs[1]..<SNR>168_find_current_signs:
line    5:
E121: Undefined variable: signs
```

I'm sometimes getting very similar behavior with w0rp/ale, less often though, and the messages differ, and I think it's only if gitgutter is enabled.

**Comment by airblade** [comment]
That plugin has cropped up before (#351).

**Comment by airblade** [comment]
This is the [problematic line](https://github.com/airblade/vim-gitgutter/blob/ad25925f1ec8790a3b0532c367c40470342d73fb/autoload/gitgutter/utility.vim#L10) according to the stack trace:

```viml
let dict = get(getbufvar(a:buffer, ''), 'gitgutter', {})
```

For this to fail, `getbufvar(a:buffer, '')` must be not returning a dictionary.  In turn this can only happend if `a:buffer` doesn't refer to an existing buffer.  But `a:buffer` ultimately comes from `bufnr('')` in the [autocommands](https://github.com/airblade/vim-gitgutter/blob/ad25925f1ec8790a3b0532c367c40470342d73fb/plugin/gitgutter.vim#L223-L228).

Somehow the vim-php-namespace plugin must be interfering with that.

**Comment by airblade** [comment]
Does running vim-gitgutter synchronously help?  `let g:gitgutter_async = 0`

**Comment by airblade** [comment]
@greg0ire @jessarcher Please could you try this change and let me know if it cures the problem?

```diff
diff --git i/autoload/gitgutter/diff.vim w/autoload/gitgutter/diff.vim
index d9f4419..1f8acb8 100644
--- i/autoload/gitgutter/diff.vim
+++ w/autoload/gitgutter/diff.vim
@@ -146,6 +146,10 @@ endfunction
 function! gitgutter#diff#handler(bufnr, diff) abort
   call gitgutter#debug#log(a:diff)
 
+  if bufexists(a:bufnr)
+    return
+  endif
+
   call gitgutter#hunk#set_hunks(a:bufnr, gitgutter#diff#parse_diff(a:diff))
   let modified_lines = gitgutter#diff#process_hunks(a:bufnr, gitgutter#hunk#hunks(a:bufnr))
 
```

(I don't know any PHP at all and I can't reproduce this problem.)

Thanks!

**Comment by greg0ire** [comment]
I dropped vim-php-namespace from my toolchain, will test if @jessarcher cannot.

**Comment by jessarcher** [comment]
@airblade @greg0ire That has indeed fixed the problem!

I re-enabled `g:gitgutter_async` and first made sure I could replicate the problem, and then I applied your patch and could no longer replicate it.

Great work and thanks for sticking with this.

**Comment by airblade** [comment]
@jessarcher Thanks for testing this and sorry it took so long to fix!
