### ISSUE TITLE
Next/prev hunk should be repeatable motions

### ISSUE THREAD

**Issue by watsoncj** [airblade/vim-gitgutter#514]
> What is the latest commit SHA in your installed vim-gitgutter?
ad25925

> What vim/nvim version are you on?
NVIM v0.2.2

GitGutterNextHunk/GitGutterPrevHunk should be repeatable motions so that `;` can jump to next hunk.

**Comment by airblade** [comment]
`GitGutterNextHunk`/`GitGutterPrevHunk` are set up to behave the same way as vim does when jumping forward/backward to the next change (`:help jumpto-diffs`).  These take a count but aren't repeatable motions.

Also `;` is a left-right motion whereas `GitGutterNextHunk`/`GitGutterPrevHunk` are vertical motions.

I would prefer to stay consistent with vim here, i.e. not make `;` jump to the next hunk.  Of course, you could set this up in your own vimrc.
