### ISSUE TITLE
Doesn't auto update with mvim?

### ISSUE THREAD

**Issue by 9mm** [airblade/vim-gitgutter#518]
> What is the latest commit SHA in your installed vim-gitgutter?

Latest

> What vim/nvim version are you on?

MacVim 8.0.1633 (146)

I had GitGutter for a long time but this only recently started happening, so I assume something changed about either MacVim or GitGutter.

Basically when I have a bunch of files open in MacVim, then I go to terimal and commit/push. I go back to GitGutter and it still says the same changes. I have to hit command+s to save or `:w` for it to update. Is there an option I can turn it on to make it so just the MacVim window/different tab focusing will be enough to update it?

**Comment by 9mm** [comment]
I should mention as im editing it auto-updates fine. It's only when I commit and come back to vim, it's like it doesn't see that.

**Comment by airblade** [comment]
It works for me (I'm using MacVim 8.0.1420).

The strange thing is that it does update when you write the buffer.  That sounds like an old version of gitgutter – the current one doesn't do anything when you write the buffer.

You didn't give the actual commit sha your installed vim-gitgutter is at.  Please could you check it?

**Comment by 9mm** [comment]
Hmm... Ok you are right, I forgot that I hadnt run `:PlugUpdate` in a week or so. I got the latest latest and it seems to work on one test, but on another it did it again. I will wait till I can make some real code changes to test later today. Sorry if that was all it was 

```
commit ad25925f1ec8790a3b0532c367c40470342d73fb (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Andy Stewart <boss@airbladesoftware.com>
Date:   Thu Apr 19 13:03:45 2018 +0100

    Add missing condition to determine whether running async.

    See #505.
```
