### ISSUE TITLE
Add ability to refresh on save file

### ISSUE THREAD

**Issue by dylan-chong** [airblade/vim-gitgutter#523]
> What is the latest commit SHA in your installed vim-gitgutter?

a7206c41fc174f576b3f7085d48319dbdad760a5

> What vim/nvim version are you on?

NVIM v0.2.2

**Comment by airblade** [comment]
Add this to your vimrc:

```viml
autocmd BufWritePost * GitGutter
```

I'm curious about why you need this.  If your `&updatetime` is a reasonable value and you haven't disabled gitgutter, the signs should always be up to date regardless of whether the buffer has unmodified changes or not.

**Comment by dylan-chong** [comment]
Just in case there is any performance problem if changing updatetime. I'm gladly surpriseed that there doesn't seem to be one...
