### ISSUE TITLE
Is it possible to add different highlighting for inactive windows?

### ISSUE THREAD

**Issue by JesseLeite** [airblade/vim-gitgutter#524]
Not sure if this is the correct forum to ask questions about user customizability?  Is it possible to add different highlighting for inactive windows, similar to `StatusLine`'s `StatusLineNC` (for non-current windows)?  I wouldn't expect this to be added to vim-gitgutter core, but I'm wondering if it's even possible by the end user?

The purpose btw is for dimming inactive windows via plugins like https://github.com/blueyed/vim-diminactive or https://github.com/bimlas/vim-high, example...

![](https://user-images.githubusercontent.com/5187394/40274022-98fbd380-5b9a-11e8-870c-e2fc6abe87c4.png)

PS. Ignore the `CursorLineNR` green highlight I've pointed to there, I realize it's out of scope for gitgutter!

Any help/advice would be appreciated ❤️

**Comment by airblade** [comment]
This should be possible.

I think you would write a function which updates gitgutter's [sign highlight colours](https://github.com/airblade/vim-gitgutter/blob/a7206c41fc174f576b3f7085d48319dbdad760a5/autoload/gitgutter/highlight.vim#L58-L61) to a dim version or the default, and call that function from a `WinEnter` autocommand.

**Comment by JesseLeite** [comment]
Cool thanks for reply!  I'll dig in and see what I can come up with.  Thank you!

**Comment by airblade** [comment]
I'm closing this now but let me know if you have any problems.
