### ISSUE TITLE
gitgutter marks are not updated on file save

### ISSUE THREAD

**Issue by marbu** [airblade/vim-gitgutter#526]
I was using bit older commit and when I updated to current master c4301f9a103ac1429d05131e7debdac5eb6c4c23, I noticed that the gitgutter signs are not shown when I save the file (eg. via typing `:w`). The signs will appear eventually (roughly after the default 4 seconds, or almost immediatelly when tweaking `updatetime`), but when I disable realtime updates, I still see no signs when saving a file.

Is this expected behavior?

> What is the latest commit SHA in your installed vim-gitgutter?

5bfe5b92099e0d332a7ca26c0263fab509ee9617 (this is the 1st commit which causes the problem, found using git bissect)

> What vim/nvim version are you on?

vim-enhanced-8.1.020-1.fc28.x86_64

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

`README.rst` (which is a name of currently opened file)

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

This has no effect.

**Comment by airblade** [comment]
It is expected behaviour: whether or not the buffer has unsaved changes makes no difference to the diff.

The idea is you set `updatetime` to a sensible value, e.g. `200`, and then the signs are always up to date.

**Comment by airblade** [comment]
If you really want to update the signs when you save a file, add this to your vimrc:

```viml
autocmd BufWritePost * GitGutter
```

**Comment by marbu** [comment]
That works, thank you for the help. I guess that I can close it now.

**Comment by marbu** [comment]
Ah, I just noticed that about a week ago, someone asked the same question: https://github.com/airblade/vim-gitgutter/issues/523 Sorry for missing that. Would it make sense to update the FAQ (something like https://github.com/airblade/vim-gitgutter/pull/527)?
