### ISSUE TITLE
GitGutter crashed when wiping buffers before signs updated

### ISSUE THREAD

**Issue by shirohana** [airblade/vim-gitgutter#529]
### What is the latest commit SHA in your installed vim-gitgutter?

- `c4301f9`

### What vim/nvim version are you on?

- NVIM v0.2.2

### Description

As title, closing buffers too quick will cause GitGutter crashed as image shown below:

![2018-06-01 4 18 34](https://user-images.githubusercontent.com/11359892/40806246-7a87998a-6553-11e8-88cb-d3079bf232ff.png)

then crashed GitGutter will report an error when enter a buffer which contains unstaged changes or about every [4 seconds](https://github.com/airblade/vim-gitgutter/blob/master/doc/gitgutter.txt#L224-L226) automatically:

![2018-05-30 3 57 05](https://user-images.githubusercontent.com/11359892/40806582-8e5ec6ee-6554-11e8-9992-031582966856.png)

**Comment by airblade** [comment]
I'm not sure how to reproduce this.  Can you give me instructions please?

**Comment by shirohana** [comment]
I recorded a video for you (๑ơ ω ơ)

https://youtu.be/IqQxuVp_Y0o

**Comment by shirohana** [comment]
As I mentioned in title, it only breaks when you **wipe** the buffer. You can reproduce that in slow by vim commands like: [demo](https://youtu.be/p-VPr_22A4s)

ANd here's my [key mappings](https://github.com/shirohana/environment/wiki/NeoVim-%E2%80%94-Key-Mappings#buffer) so I can wipe buffers as that quick ฅ' ω 'ฅ

**Comment by airblade** [comment]
So to reproduce: `:e file-with-changes | bp | bw #`

When I do that, I don't get any errors.  Sorry ;)

**Comment by shirohana** [comment]
Because you just fixed it several weeks ago XD

Thank you for the awesome plugin ฅ' ω 'ฅ

https://github.com/airblade/vim-gitgutter/commit/64663ab24f00acc75e7813afe17e64d8b1f7247a

**Comment by airblade** [comment]
Yay!
