### ISSUE TITLE
Custom signs are not applied when added to after/plugin/gitgutter.vim

### ISSUE THREAD

**Issue by ahmedelgabri** [airblade/vim-gitgutter#530]
> What is the latest commit SHA in your installed vim-gitgutter?

https://github.com/airblade/vim-gitgutter/commit/a986ab054788776dca269d6c289b470255d54e8c

> What vim/nvim version are you on?

NVIM v0.2.2

I put my plugins settings inside `after/plugin/<plugin name>.vim`, so in the case of `gitgutter` it's `after/plugin/gitgutter.vim` & these are my settings:

```vim
scriptencoding utf-8

if !exists(':GitGutter')
  finish
endif

autocmd! BufWritePost * GitGutter

let g:gitgutter_highlight_lines = 0
let g:gitgutter_async = 1
let g:gitgutter_diff_args = '--ignore-all-space'
let g:gitgutter_grep_command = executable('rg') ? 'rg' : 'grep'
let g:gitgutter_sign_added='┃'
let g:gitgutter_sign_modified='┃'
let g:gitgutter_sign_removed='◢'
let g:gitgutter_sign_removed_first_line='◥'
let g:gitgutter_sign_modified_removed='◢'
```

Everything seems to work fine except the custom signs, if I move this to `.vimrc`/`init.vim` it works, any idea why?

**Comment by airblade** [comment]
It's because you're defining custom signs after the plugin has already set up the signs it's going to use ([here](https://github.com/airblade/vim-gitgutter/blob/a986ab054788776dca269d6c289b470255d54e8c/plugin/gitgutter.vim#L77)).  If you add this to the end of your config in `after/plugin/gitgutter.vim`, I would expect it to work:

```viml
call gitgutter#highlight#define_signs()
```

**Comment by airblade** [comment]
FYI these are the default values so you don't need to configure them:

```viml
let g:gitgutter_highlight_lines = 0
let g:gitgutter_async = 1
```

**Comment by ahmedelgabri** [comment]
adding `call gitgutter#highlight#define_signs()` worked 👍

I removed the other two options too, since they are the default, thanks :)
