### ISSUE TITLE
Cursor Disapears When Sign Column Expands

### ISSUE THREAD

**Issue by philFernandez** [airblade/vim-gitgutter#535]
When ever I'm beginning work on a file in a clean git repo, upon the first addition/change/deletion of any line, and the subsequent expanding of the sign column my cursor disappears until I type another character. 

This happens both inside and outside of tmux. As soon as the width of the sign column expands to make room for the gitgutter signs, this is when the cursor disappears. 

I was able to eliminate the issue by setting `set signcolumn=yes` in my vimrc. This makes the sign column stay expanded at all times so when a new sign shows up in the gutter it doesn't make my cursor disappear. I don't really like the sign column being expanded all the time though. I was wondering how I could resolve this? 

It's not a huge deal, but I just wanted to check and see if there was a simple solution. Thank You.

[vimrc](https://gist.github.com/philFernandez/4e7df4964c9ff33f150e432e39d1053b)

> What is the latest commit SHA in your installed vim-gitgutter?
a986ab0

> What vim/nvim version are you on?
**Terminal Vim** 
**VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453**

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?
**N/A**

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?
**N/A**

**Comment by airblade** [comment]
I don't think this is a gitgutter-specific problem – can you reproduce it without any plugins?

```
vim -u NONE -N
:sign define foo text=>>
:sign place 1 line=1 name=foo buffer=1
```

**Comment by philFernandez** [comment]
The cursor does not disappear under these conditions when running vim without any plugins. It must be something else. 

It's strange because I'm having the issue in Vim8. I'm also running the most current neovim for experimenting. It has most of the same plugins, and settings. I don't have the cursor disappear in neovim when the sign column expands or any other time. It also does not happen in Gvim, just terminal Vim8. 

I tried disabling all plugins besides gitgutter, and the cursor still disappears when the sign column expands. It's not a huge deal, just a minor annoyance. Mostly caused by the fact that I don't know why it's happening.
