### ISSUE TITLE
All lines showing up as added

### ISSUE THREAD

**Issue by idvorkin** [airblade/vim-gitgutter#536]
> What is the latest commit SHA in your installed vim-gitgutter?

a986ab054788776dca269d6c289b470255d54e8c

> What vim/nvim version are you on?

vim 8.1 (complied 2018 May 18) windows 32-bit gui

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

It gives the path relative to the git root.

!git runs correctly, as does fugitive. Please advise on how to debug.

**Comment by airblade** [comment]
Please could you switch on logging with `let g:gitgutter_log=1`?  Then when all the lines show as added, look for the log file in the directory where the plugin is installed and post it here.

I doubt you're using zsh, but just in case you are, and you set CDPATH, make sure CDPATH doesn't include the current directory.

**Comment by idvorkin** [comment]
````


==== start log session ====

  0.000026 function <SNR>83_on_bufenter[13]..gitgutter#process_buffer[8]..gitgutter#diff#run_diff[67]..gitgutter#async#execute[1]:
  0.000026 [async] cd /d "C:\gits\idvorkin.github.io" && (git --no-pager show :search.html > C:\Users\idvorkin\AppData\Local\Temp\VIAC1B3.tmp.7.html && git --no-pager -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\idvorkin\AppData\Local\Temp\VIAC1B3.tmp.7.html C:\Users\idvorkin\AppData\Local\Temp\VIBC1D3.tmp.7.html || exit 0)

  6.087392 function gitgutter#process_buffer[8]..gitgutter#diff#run_diff[67]..gitgutter#async#execute[1]:
  6.087392 [async] cd /d "C:\gits\idvorkin.github.io" && (git --no-pager show :search.html > C:\Users\idvorkin\AppData\Local\Temp\VIAC1B3.tmp.7.html && git --no-pager -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\idvorkin\AppData\Local\Temp\VIAC1B3.tmp.7.html C:\Users\idvorkin\AppData\Local\Temp\VIBC1D3.tmp.7.html || exit 0)

```

**Comment by airblade** [comment]
I agree, I would expect some more lines.  Specifically, the diffs that result from those two async commands.

What happens if you run those commands manually?  (You might have to update the temp paths):

```viml
:echo cd /d "C:\gits\idvorkin.github.io" && (git --no-pager show :search.html > C:\Users\idvorkin\AppData\Local\Temp\VIAC1B3.tmp.7.html && git --no-pager -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\idvorkin\AppData\Local\Temp\VIAC1B3.tmp.7.html C:\Users\idvorkin\AppData\Local\Temp\VIBC1D3.tmp.7.html || exit 0
```

Does running synchronously help?  `let g:gitgutter_async=0`.

**Comment by idvorkin** [comment]
Apologies, I thought I'd replied :( Setting 

      let g:gitgutter_async=0.

Fixes the issue but then it's unusably slow

**Comment by airblade** [comment]
I don't know why running diffs synchronously would be unusably slow.  Presumably the slowness isn't from git-diff itself; which would point the finger at the interaction between Vim and Windows.

Also I don't know why the async version shows all lines as added.  When this happens, if you insert a character at the cursor and then remove it again, to force gitgutter to run, do the signs correct themselves?

**Comment by idvorkin** [comment]
No, the signs never got corrected. I ended up flattening that computer, so I no longer have a repro. 

My original thought was the issue was that I was running gvim 8.1 (vs 8.0 on my other computers).  I upgraded my other computer to 8.1 and I can't get a repro. 

I'll close for now.
