### ISSUE TITLE
Unwanted behavior on windows 10 when opening a <file>.rb in a folder that also contains a file named `git.rb`

### ISSUE THREAD

**Issue by Frydac** [airblade/vim-gitgutter#538]
> What is the latest commit SHA in your installed vim-gitgutter?
64663ab - (50 minutes ago) Handle buffers which no longer exist when callback executed.
> What vim/nvim version are you on?
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:36:07)
MS-Windows 32-bit GUI version with OLE support
> If no signs are showing at all, what does `:echo b:gitgutter.path` give?
-2
> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

I've noticed this for a while, and never understood what happened. Took me a while to figure out it was gitgutter (by disabling/enabling my plugins).
But apparently when I try to open a ruby filetype file in a folder with a file named a `git.rb`  (I tried renaming git2.rb which fixed this). It starts opening the git.rb file multiple times or something, at least I keep getting a message the swap file already exists, and it keeps on opening and opening the file while creating more and more swap files.
I haven't tried onother windows box.
On linux I haven't noticed this issue.

Other than that I absolutely love this plugin, Thx!

**Comment by airblade** [comment]
This sounds like #508.

The workaround given there is to put this in your vimrc (amend the path as appropriate for your system):

```viml
if has('win32')
  let g:gitgutter_git_executable = 'C:\Program Files\Git\bin\git.exe'
endif
```

**Comment by Frydac** [comment]
That workaround seems to work, thx!

**Comment by airblade** [comment]
Closing as the workaround works and we'll track the solution in #508.
