### ISSUE TITLE
throws error on startup, perhaps related to shell

### ISSUE THREAD

**Issue by sam-github** [airblade/vim-gitgutter#539]
> What is the latest commit SHA in your installed vim-gitgutter?

6076c9678643a8b2fc9973f16ec9efcd5dbe1aca

> What vim/nvim version are you on?

zsh 5.5.1

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  6 2018 14:18:28

installed using homebrew on OS X

Opening and subsequently saving any file errors:

```
"main.go" 124L, 3496C
Command terminated
Error detected while processing function <SNR>49_git_supports_command_line_config_override:
line    1:
E484: Can't open file /var/folders/z5/7wd_wz797s3b3yrwhpk6tx2r0000gn/T/vwY5vmG/0
Error detected while processing function <SNR>17_on_bufenter:
line    6:
E171: Missing :endif
```

I added `set shell=/bin/bash` to the top of my .vimrc, and it stopped throwing the errors, but now the gutter doesn't update in realtime, I need to do `:e` to get the gutter to be correct.

The gutter was working fine for years! until a hour ago, when I updated vim and I started getting errors like above, so I then updated most of my plugins, including vim-gitgutter. Eventually I realized that moving all my plugins out of ~/.vim/bundle and moving vim-gitgutter back in was sufficient to cause the error so I suspect vim-gitgutter is interacting badly with something else about my system, but I'm not sure what.

I dread going back to a world without a realtime git gutter, so what other info can I give that is useful?

**Comment by airblade** [comment]
The error is being thrown by this function which just executes a plain `system()` call:

https://github.com/airblade/vim-gitgutter/blob/6076c9678643a8b2fc9973f16ec9efcd5dbe1aca/autoload/gitgutter/diff.vim#L6-L9

Does `:echo system('ls')` work for you?  If so, how about `:echo system('git --version')`?

I wonder whether you have some zsh configuration which is adding ANSI escape codes to the shell output which Vim can't handle.  There was a previous issue about this somewhere.

Strange that `set shell=/bin/bash` stops the realtime update.  It shouldn't do.  What is your `&updatetime`?

**Comment by airblade** [comment]
Also you can try `let g:gitgutter_log=1`, then look at the log file in the directory where the plugin is installed.  You should see the git commands being executed and the diff results.

**Comment by airblade** [comment]
Closing because this has gone quiet.  Happy to reopen if it's still a problem.
