### ISSUE TITLE
Work under .git folder

### ISSUE THREAD

**Issue by disconsis** [airblade/vim-gitgutter#540]
> What is the latest commit SHA in your installed vim-gitgutter?
6076c96
> What vim/nvim version are you on?
NVIM v0.3.0-1058-gbe14482
> If no signs are showing at all, what does `:echo b:gitgutter.path` give?
`b:gitgutter`  doesn't exist

Oddly specific request - in a moment of extremely bad judgement, I chose to put all my cloned git repos under `~/.git` [and it's too late to change it now]. Gitgutter doesn't seem to work in any repositories under that folder. Example: `~/.git/gittest`.
Copying the repo to somehere like `/tmp/gittest` makes it work perfectly.

**Comment by disconsis** [comment]
The concerned code is:

```vimscript
function! gitgutter#utility#is_active(bufnr) abort
  return g:gitgutter_enabled &&
        \ !pumvisible() &&
        \ s:is_file_buffer(a:bufnr) &&
        \ s:exists_file(a:bufnr) &&
        \ s:not_git_dir(a:bufnr)
endfunction

function! s:not_git_dir(bufnr) abort
  return s:dir(a:bufnr) !~ '[/\\]\.git\($\|[/\\]\)'
endfunction
```

**Comment by disconsis** [comment]
I'm not entirely sure what the rationaly for using  `not_git_dir` here is

**Comment by airblade** [comment]
The rationale was #239.

I don't think git "allows" worktrees inside the `.git/` directory – it's for git's own housekeeping.  So I don't think gitgutter should process files inside `.git/`.

**Comment by disconsis** [comment]
>  I don't think git "allows" worktrees inside the .git/ directory
It does, but oh well, it's a minor issue.
The cons seem to outweight the benefits of a change anyway. I'll just lay out my file structure more sensibly next time.
