### ISSUE TITLE
gitgutter misbehaves when $TMP or $TMPDIR points inside the git work tree.

### ISSUE THREAD

**Issue by systemmonkey42** [airblade/vim-gitgutter#541]
> What is the latest commit SHA in your installed vim-gitgutter?
6076c9678643a8b2fc9973f16ec9efcd5dbe1aca

> What vim/nvim version are you on?
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  7 2018 21:12:27)
Included patches: 1-157

Symptom: Signs not showing - unable to stage hunks.
Reason: '$TMPDIR' points to a location within the git work tree

Hi,
It took me a while to track this issue down, since you are using the git command in ways I hadn't previously imagined.

As far as I can tell, GitGutter attempts to copy the working and latest staged/committed files to a "safe" location outside the current git tree, then perform 'git diff', (taking advantage of the fact that `git diff` can diff two files outside a git tree)

In the rare instance that `$TMP` or `$TMPDIR` points to a location within the git tree, GitGutter writes its temp to a location within the git work tree. When this happens, `git diff` seems to think the files being diff'ed are actually untracked files in the current repository, and does not work as expected.

Solution:  As `git diff` is being used with the "implicit" expectation of being outside the git-work-tree, make it explicit with  `--git-dir=''`

Example:
```
diff --git autoload/gitgutter/diff.vim autoload/gitgutter/diff.vim
index 9441f7a..3a68d8c 100644
--- autoload/gitgutter/diff.vim
+++ autoload/gitgutter/diff.vim
@@ -101,6 +101,7 @@ function! gitgutter#diff#run_diff(bufnr, preserve_full_diff) abort

   " Call git-diff with the temporary files.
   let cmd .= g:gitgutter_git_executable.' --no-pager'
+  let cmd .= " --git-dir=''"
   if s:c_flag
     let cmd .= ' -c "diff.autorefreshindex=0"'
     let cmd .= ' -c "diff.noprefix=false"'
```

**Comment by airblade** [comment]
> ...you are using the git command in ways I hadn't previously imagined.

That's to work around Vim's quirks.  The git side of things was originally straightforward but Vim imposed various constraints.

I never imagined $TMP or $TMPDIR pointing into a git working tree.

Doesn't setting `--git-dir=''` tell git the repo is the current working directory?  Which might not solve your problem?

**Comment by systemmonkey42** [comment]
> I never imagined $TMP or $TMPDIR pointing into a git working tree.

Ugh.. legacy build system..

> Doesn't setting --git-dir='' tell git the repo is the current working directory? Which might not solve your problem?

Surprisingly not.

In a git repo, if you type `git --git-dir='' status`, the response you get is `fatal: not a git repository ''`  I even tried `git diff -- Makefile` (which return nothing) and `git --git-dir='' diff -- Makefile` which gave me help on running `git diff` outside a repository.

I'm using the patch in my private fork and it's solved the problem I was having.  Of course its only the `git diff` which needs the fix.  Everything else works fine.

**Comment by systemmonkey42** [comment]
https://github.com/systemmonkey42/vim-gitgutter/commit/896f501c092c8bb9f05884b5377c756cc8e43fad

**Comment by samuelwagen** [comment]
After this patch GitGutter no longer shows hunks for me.
My $TMPDIR is not inside the repo, Git is 2.18.0
Reverting this patch fixes things for me.

**Comment by airblade** [comment]
I reverted the `--git-dir=""` commit and in the next commit added the variable `g:gitgutter_git_args` so @systemmonkey42 can set it to `'--git-dir=""'`.

**Comment by samuelwagen** [comment]
Thank you, works fine now.
