### ISSUE TITLE
Disable gitgutter when selecting text in vim

### ISSUE THREAD

**Issue by BrianAker** [airblade/vim-gitgutter#542]
Is there a way to automatically disable gitgutter so that when you yank some text the "gutter" is not copied into the clipboard?

**Comment by airblade** [comment]
Sounds like an error in Vim itself if yanking copies text from the sign column – might be worth asking about this on the vim-use google group.

I think the best workaround would be to map the yank key to `set signcolumn=no`, do the yank, then `set signcolumn=auto`.  Or, perhaps better, define an operator function (see `:help map-operator`) to do this.

**Comment by airblade** [comment]
Closing this as it's not really a problem with the plugin.
