### ISSUE TITLE
Replace sign parsing code with getbufinfo()

### ISSUE THREAD

**Issue by airblade** [airblade/vim-gitgutter#544]
The function `getbufinfo({bfnr})` was added in Vim [7.4.2204](https://github.com/vim/vim/releases/tag/v7.4.2204).  It lets you get a buffer's signs directly, intead of parsing the output of `sign place`.

```viml
:echo getbufinfo('%')[0].signs
```

**Comment by blueyed** [comment]
By now there is also `sign_getplaced()`, which allows for handling sign groups.

**Comment by airblade** [comment]
Thanks for letting me know about that :)
