### ISSUE TITLE
vim-gitgutter stop to work from 'Explicitly tell git to diff outside any repo' commit

### ISSUE THREAD

**Issue by mimadrid** [airblade/vim-gitgutter#546]
> What is the latest commit SHA in your installed vim-gitgutter?
b4e43ae9e72da0d77474b0c3c010efa8e804cd07
> What vim/nvim version are you on?
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:50:25)
NVIM v0.3.1
> If no signs are showing at all, what does `:echo b:gitgutter.path` give?
A path
> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?
No :(

My Git Gutter config (extracted from https://github.com/mimadrid/.dotfiles/)
> " Git Gutter {{{
> let g:gitgutter_grep = 'rg'
> let g:gitgutter_sign_removed = '-'
> " Symbols color
> highlight GitGutterAdd ctermfg=green ctermbg=235
> highlight GitGutterChange ctermfg=yellow ctermbg=235
> highlight GitGutterDelete ctermfg=red ctermbg=235
> highlight GitGutterChangeDelete ctermfg=yellow ctermbg=235
> " Move between hunks
> nmap <localleader>k <Plug>GitGutterPrevHunk
> nmap <localleader>j <Plug>GitGutterNextHunk
> " Stage and undo hunks without git add --patch
> nmap <Leader>s <Plug>GitGutterStageHunk
> nmap <Leader>u <Plug>GitGutterUndoHunk
> " Preview deleted hunk
> nmap <Leader>p <Plug>GitGutterPreviewHunk
> " Hunk object manipulation
> omap ih <Plug>GitGutterTextObjectInnerPending
> omap ah <Plug>GitGutterTextObjectOuterPending
> xmap ih <Plug>GitGutterTextObjectInnerVisual
> xmap ah <Plug>GitGutterTextObjectOuterVisual
> " }}}

Don't hesitate to ask more information

Thanks a lot for this awesome plugin!

**Comment by airblade** [comment]
Does it work if you go back to the previous commit (6076c96)?

**Comment by mimadrid** [comment]
Thanks a lot for your quick answer, @airblade 

Yes with https://github.com/airblade/vim-gitgutter/commit/6076c9678643a8b2fc9973f16ec9efcd5dbe1aca return to work

**Comment by airblade** [comment]
@systemmonkey42 Any idea what the problem could be here?  The problem is `--git-dir=""`.

**Comment by airblade** [comment]
@mimadrid Please could you switch on logging (`let g:gitgutter_log=1`), run the plugin a little, then post the log file you'll find in the directory the plugin is installed in?

**Comment by mimadrid** [comment]
[channel.log](https://github.com/airblade/vim-gitgutter/files/2240240/channel.log)
[gitgutter.log](https://github.com/airblade/vim-gitgutter/files/2240241/gitgutter.log)

Thanks a lot in advance!

**Comment by airblade** [comment]
The channel log file captured this error: `fatal: The empty string is not a valid path`.

What version of git are you using?  (It works for me on git 2.15.1 and 2.18.0.)

**Comment by mimadrid** [comment]
I'm using 2.18.0 and and my git config is https://github.com/mimadrid/.dotfiles/blob/master/git/.config/git/config

Don't hesitate to ask if you need more information
Thanks a lot

**Comment by mimadrid** [comment]
https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.16.0.txt

> An empty string as a pathspec element that means "everything"
>    i.e. 'git add ""', is now illegal.  We started this by first
>    deprecating and warning a pathspec that has such an element in
>    2.11 (Nov 2016)

Could that be the problem?

**Comment by mimadrid** [comment]
@airblade and @systemmonkey42, I've upload a patch

Could you test it?

**Comment by systemmonkey42** [comment]
Thanks for providing your git-config

The lines
```
# https://git-scm.com/docs/git-config#_includes
# use other username and mail for the specific folder structure
[includeIf "gitdir:~/forks/Work/BSC/INAB/"]
  path = .config.work
```

seem to be the culprit.  I'll need to investigate the includeif a little more.  It might be a git bug.  Either way, explicitly settings gitdir to '' seems to break it

**Comment by systemmonkey42** [comment]
I had a look at your suggested patch.  it will set the 'git-dir' to the current working directory, which is potentially risky.

As a test, I set git-dir to '/dev/null' which is technically gibberish.  (Its not a directory, or a git-soft-link to a directory) but this seems to solve both problems.

I'm wary that this is just breaking rules for the sake if it and will backfire at some point.  @airblade, Consider leaving a placeholder for 'extra git args' (g:gitgutter_git_args ?) so people like me who need to work around bad repository design don't impact people with complex configurations.

**Comment by systemmonkey42** [comment]
Have you considered using 'diff -u' instead of git diff?   Since the point is to parse the 'diff' output without actually triggering any 'git' behaviour, it strike me that it might be easier to call 'diff' if available.

I understand this causes portability issues, so again, it might been to be wrapped in `if executable('diff')` or an explicit global flag.

**Comment by airblade** [comment]
Originally gitgutter simply diffed against the repo, instead of temporary files, so it made sense then to use git-diff instead of diff.

As you point out plain diff would probably suffice now, but I don't want to change it because git-diff will be available everywhere whereas diff might not be.

git-diff has always worked fine until your legacy set up ;)

**Comment by systemmonkey42** [comment]
You are right :) and :(...   Feel free to revert the patch for this fix.  It clearly breaks otherwise normal configurations.  I'm happy to keep trying to find another way.   At the very least I learnt something new...

**Comment by airblade** [comment]
I reverted the `--git-dir=""` commit and in the next commit (d2d2da1) added the variable `g:gitgutter_git_args` so @systemmonkey42 can set it to `'--git-dir=""'`.
