### ISSUE TITLE
Feature request : GitGutterPrevCommit

### ISSUE THREAD

**Issue by vitaly-zdanevich** [airblade/vim-gitgutter#549]
The plugin is useful for navigation and because of that I avoid committing incomplete tasks (I want to see lines with changes for current task), but I would like to commit my unfinished code to the end of the day. Maybe is it possible to show this marks comparable to another branch, maybe in different colours..?

Thank you for the plugin!

**Comment by airblade** [comment]
There's no way to show different commits' changes in different colours.  It's always just a diff.

**Comment by airblade** [comment]
Closing this but let me know if you have any further questions.
