### ISSUE TITLE
Include VimResume (neovim) alongside FocusGained autocommand

### ISSUE THREAD

**Issue by ipwnponies** [airblade/vim-gitgutter#550]
`gitgutter` has an autocommand listening on `FocusGained` events to trigger refresh. But this event doesn't exist for suspend/resume of the process. `neovim 0.3.0` introduced `VimResume` and `VimSuspend` events in this [PR](https://github.com/neovim/neovim/pull/8280). My workaround before this feature was to resume the process and immediately switch back and forth between the terminal and a different window, to force trigger of the `FocusGained` event.

Can we append this to the existing `FocusGained` autocommand? I believe this is neovim only and am not sure vim has any related plans for similar feature.

The workaround I've been using is to put this in my vimrc:
```
  if has('nvim-0.3.0')
      augroup gitgutter_resume
          autocmd!
          autocmd VimResume * call gitgutter#all(1)
      augroup end
  endif
```

**Comment by airblade** [comment]
Sounds good.

How about just testing for the existence of `VimResume`?

```viml
if exists('##VimResume')
  ...
endif
```

**Comment by ipwnponies** [comment]
Yes, that works better! I quickly tested against nvim 0.3.1, vim 7.4, and vim 8.1 and this feature is nvim only.

Would you like me to submit a PR?

**Comment by airblade** [comment]
Yes please.  I don't think the autocmd needs to go in its own separate group; we can just put it below the `FocusGained,ShellCmdPost` one.
