### ISSUE TITLE
Doesn't detect file name change after :saveas

### ISSUE THREAD

**Issue by pmcmorris** [airblade/vim-gitgutter#551]
> What is the latest commit SHA in your installed vim-gitgutter?
a986ab054788776dca269d6c289b470255d54e8c

> What vim/nvim version are you on?
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?
Signs are showing but they are wrong.

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?
Signs are showing but they are wrong.

After using the :saveas command, gitgutter continues to compare against the previous file instead of using the new name (which is probably a new name and not in the repo).  I can see all the +/-/~ get updated as I edit for a file not in the repo.

**Comment by airblade** [comment]
This is because gitgutter caches the file's path after the first run, so when you rename the file with `:saveas` the plugin continues to use the original path in the git commands.

Maybe we could detect a `:saveas` by comparing file names in `BufWritePre` and `BufWritePost` events and using the new file path if they differ.

**Comment by airblade** [comment]
Closing because this has gone quiet.  Happy to reopen if it's still a problem.

**Comment by pylipp** [comment]
I'm facing the same issue and would like to help. Could you point me to where I could start listening for the `BufWrite*` events?

**Comment by airblade** [comment]
You could add event handler in `plugin/gitgutter.vim`.  If the filenames differ pre and post, clear the path in `b:gitgutter.path` and force GitGutter to run.

**Comment by airblade** [comment]
Thanks for letting me know.  I'll reopen this so I don't forget.

**Comment by blueyed** [comment]
@pylipp 
Can you create a PR for it, please?

Or do you plan to cherry-pick / apply it manually?

For reference: relevant autocommands being emitted:

```
BufNew: abuf: 12, amatch: …/vim/plugged/vim-gitgutter/meh.vim, winnr():1, ft: vim, bt: )
BufFilePre: abuf: 1, amatch: …/vim/plugged/vim-gitgutter/bar.vim, winnr():1, ft: vim, bt: )
BufFilePre: abuf: 12, amatch: …/vim/plugged/vim-gitgutter/meh.vim, winnr():1, ft: vim, bt: )
BufFilePost: abuf: 1, amatch: …/vim/plugged/vim-gitgutter/meh.vim, winnr():1, ft: vim, bt: )
BufFilePost: abuf: 12, amatch: …/vim/plugged/vim-gitgutter/bar.vim, winnr():1, ft: vim, bt: )
BufAdd: abuf: 12, amatch: …/vim/plugged/vim-gitgutter/bar.vim, winnr():1, ft: vim, bt: )
BufCreate: abuf: 12, amatch: …/vim/plugged/vim-gitgutter/bar.vim, winnr():1, ft: vim, bt: )
BufWrite: abuf: 1, amatch: …/vim/plugged/vim-gitgutter/meh.vim, winnr():1, ft: vim, bt: )
BufWritePre: abuf: 1, amatch: …/vim/plugged/vim-gitgutter/meh.vim, winnr():1, ft: vim, bt: )
"meh.vim" [New] 176L, 4882C written
BufWritePost: abuf: 1, amatch: …/vim/plugged/vim-gitgutter/meh.vim, winnr():1, ft: vim, bt: )
```

But I think using BufWritePost is a good fit here.

**Comment by blueyed** [comment]
Well, actually using `BufFilePost` would be better to also handle ´:file`.

**Comment by blueyed** [comment]
Tried to do it via `autocmd FileChangedShellPost,BufFilePost * call gitgutter#process_buffer(bufnr(''), 1)`, but it appears that `gitgutter#utility#is_active` might prevent it (I've passed `force` through to `s:setup_path` before).

**Comment by blueyed** [comment]
Came up with:
```diff
diff --git i/plugin/gitgutter.vim w/plugin/gitgutter.vim
index 1bb27a1..3641859 100644
--- i/plugin/gitgutter.vim
+++ w/plugin/gitgutter.vim
@@ -194,6 +194,17 @@ function! s:on_bufenter()
   endif
 endfunction

+function! s:on_buffilepost(bufnr)
+  if gitgutter#utility#is_active(a:bufnr)
+    if gitgutter#utility#file(a:bufnr) != fnamemodify(bufname(a:bufnr), ':p')
+      call gitgutter#utility#setbufvar(a:bufnr, 'path', -1)
+      " Causes endless loop, with ':file autoload/gitgutter.vim' in
+      " plugin/gitgutter.vim.
+      " call gitgutter#process_buffer(a:bufnr, 1)
+    endif
+  endif
+endfunction
+
 " Autocommands {{{

 augroup gitgutter
@@ -203,6 +214,8 @@ augroup gitgutter

   autocmd BufEnter * call s:on_bufenter()

+  autocmd BufFilePost * call s:on_buffilepost(expand('<abuf>'))
+
   autocmd CursorHold,CursorHoldI * call gitgutter#process_buffer(bufnr(''), 0)
   autocmd FileChangedShellPost   * call gitgutter#process_buffer(bufnr(''), 1)
```

But while it updates the filename, it does not update the hunks etc.

There are two cases this needs to handle:
1. using `file` with file known to Git
2. using `file` with a file not known to Git

**Comment by pylipp** [comment]
@blueyed PR is opened. I didn't have time yet to integrate your suggestions.
