### ISSUE TITLE
The whole file is marked as added,I don't use zsh

### ISSUE THREAD

**Issue by z-wh** [airblade/vim-gitgutter#553]
The whole file is marked as added. 
I don't use zsh, I use gvim in Windows7 X64.
vim-gitgutter in Nvim v0.3.1 can work correctly on this computer system, but in gvim v8.1.240 MS64bit can't.

> What is the latest commit SHA in your installed vim-gitgutter?
commit 50a7062909d91a290fae04219887b1b45f3138db (grafted, HEAD -> master, origin
/master, origin/HEAD)
Author: John Nguyen <ipwnponies@gmail.com>
Date:   Tue Aug 14 22:02:33 2018 -0700

> What vim/nvim version are you on?
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug  5 2018 12:53:55)
Version  8.1.240
MS-Windows 64-bit Gui version with OLE support
Included patches: 1-240
Compiled by micbou <contact@micbou.com>
Huge version with GUI.  

> If no signs are showing at all, what does :echo b:gitgutter.path give?
Signs are showing but the whole file is marked as added. 

> If no signs are showing at all, and the path value is a path and not -2, does it work with let g:gitgutter_grep=''?
Signs are showing but the whole file is marked as added.

**Comment by airblade** [comment]
Sounds like #536 (which never got resolved).  Does `let g:gitgutter_async=0` make any difference?

It would help to see some log info.  Please could you `let g:gitgutter_log=1` and then, once all the lines are marked as added, post the contents of the log file (in the directory where gitgutter is installed)?

**Comment by z-wh** [comment]
> Sounds like #536 (which never got resolved). Does `let g:gitgutter_async=0` make any difference?
> 
> It would help to see some log info. Please could you `let g:gitgutter_log=1` and then, once all the lines are marked as added, post the contents of the log file (in the directory where gitgutter is installed)?

When I add `let g:gitgutter_async=0`  into my vimrc file, gitgutter can work correctly in gvim.
Thank you very much!

**Comment by z-wh** [comment]
The below is the contents of gitgutter.log when all the lines are marked as added.

`==== start log session ====

  0.000023 function <SNR>70_on_bufenter[5]..gitgutter#init_buffer[4]..gitgutter#utility#set_repo_path[11]..gitgutter#async#execute[1]:
  0.000023 [async] cd /d "E:\zwh\software\Vim" && git ls-files --error-unmatch --full-name -- _vimrc

  0.479453 function <SNR>70_on_bufenter[6]..gitgutter#process_buffer[8]..gitgutter#diff#run_diff[67]..gitgutter#async#execute[1]:
  0.479453 [async] cd /d "E:\zwh\software\Vim" && (git --no-pager show :_vimrc > C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 && git --no-pager  -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 C:\Users\ADMINI~1\AppData\Local\Temp\VICCC85.tmp.2 || exit 0)

  0.684838 function gitgutter#all[9]..gitgutter#process_buffer[8]..gitgutter#diff#run_diff[67]..gitgutter#async#execute[1]:
  0.684838 [async] cd /d "E:\zwh\software\Vim" && (git --no-pager show :_vimrc > C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 && git --no-pager  -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 C:\Users\ADMINI~1\AppData\Local\Temp\VICCC85.tmp.2 || exit 0)

  0.803647 function gitgutter#process_buffer[8]..gitgutter#diff#run_diff[67]..gitgutter#async#execute[1]:
  0.803647 [async] cd /d "E:\zwh\software\Vim" && (git --no-pager show :_vimrc > C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 && git --no-pager  -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 C:\Users\ADMINI~1\AppData\Local\Temp\VICCC85.tmp.2 || exit 0)

  1.115032 function <SNR>73_on_exit_vim[1]..gitgutter#diff#handler[1]:
  1.115032 diff --git "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\VIBCC84.tmp.2" "b/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\VICCC85.tmp.2"
index e69de29..d880167 100644
--- "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\VIBCC84.tmp.2"
+++ "b/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\VICCC85.tmp.2"`

And This is the contents of channel.log when all the lines are marked as added.

`==== start log session ====
  0.001180 : Starting job: cmd.exe /c cd /d "E:\zwh\software\Vim" && git ls-files --error-unmatch --full-name -- _vimrc
  0.001244 on 7: Created channel
  0.458784 RECV on 7: '_vimrc
'
  0.458800 ERR on 7: channel_handle_events(): Read error from ch_part[2], closing
  0.458880 RECV on 2: 'Content-Length: 94

{"jsonrpc":"2.0","method":"eval","params":["!!get(g:, 'LanguageClient_autoStart', 1)"],"id":1}
'
  0.458923 RECV on 0: '["ex", "pythonx neovim_rpc_server.process_pending_requests()"]["ex", "pythonx neovim_rpc_server.process_pending_requests()"]'
  0.458926 : looking for messages on channels
  0.458938 on 7: Invoking channel callback <SNR>73_on_stdout_vim
  0.458986 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.459223 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.459360 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.459503 SEND on 2: '{"id":1,"jsonrpc":"2.0","result":1}
'
  0.459738 on 0: Executing ex command 'pythonx neovim_rpc_server.process_pending_requests()'
  0.461683 on 0: Executing ex command 'pythonx neovim_rpc_server.process_pending_requests()'
  0.461738 on 7: Job ended
  0.474407 ERR on 7: channel_handle_events(): Read error from ch_part[1], closing
  0.474506 RECV on 2: 'Content-Length: 58

{"jsonrpc":"2.0","method":"eval","params":["[[]]"],"id":2}
'
  0.474538 : looking for messages on channels
  0.474551 on 7: Closing channel because all readable fds are closed
  0.474562 on 7: Closing channel
  0.474572 on 7: Invoking callbacks and flushing buffers before closing
  0.474582 on 7: Invoking close callback <SNR>73_on_exit_vim
  0.474719 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.475102 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.475420 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.475692 SEND on 2: '{"id":2,"jsonrpc":"2.0","result":[[]]}
'
  0.480966 : Starting job: cmd.exe /c cd /d "E:\zwh\software\Vim" && (git --no-pager show :_vimrc > C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 && git --no-pager  -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 C:\Users\ADMINI~1\AppData\Local\Temp\VICCC85.tmp.2 || exit 0)
  0.481057 on 8: Created channel
  0.568943 SEND on 2: '{"method":"languageClient/handleCursorMoved","jsonrpc":"2.0","params":{"languageId":"vim","line":346,"LSP#visible_line_start()":336,"LSP#visible_line_end()":357,"buftype":"","filename":"E:\\zwh\\software\\Vim\\_vimrc"}}
'
  0.607664 : Starting job: git status --porcelain -- "E:\zwh\software\Vim\_vimrc"
  0.607703 on 9: Created channel
  0.686064 : Starting job: cmd.exe /c cd /d "E:\zwh\software\Vim" && (git --no-pager show :_vimrc > C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 && git --no-pager  -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 C:\Users\ADMINI~1\AppData\Local\Temp\VICCC85.tmp.2 || exit 0)
  0.686126 on 10: Created channel
  0.701373 RECV on 2: 'Content-Length: 197

{"jsonrpc":"2.0","method":"eval","params":["[get(g:, 'LanguageClient_loggingFile', v:null), get(g:, 'LanguageClient_loggingLevel', 'WARN'), get(g:, 'LanguageClient_serverStderr', v:null)]"],"id":3}
'
  0.701395 : looking for messages on channels
  0.701407 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.701550 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.701666 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.701774 SEND on 2: '{"id":3,"jsonrpc":"2.0","result":[null,"WARN",null]}
'
  0.770893 RECV on 2: 'Content-Length: 826

{"jsonrpc":"2.0","method":"eval","params":["[!!get(g:, 'LanguageClient_autoStart', 1), get(g:, 'LanguageClient_serverCommands', {}), get(g:, 'LanguageClient_selectionUI', v:null), get(g:, 'LanguageClient_trace', v:null), expand(get(g:, 'LanguageClient_settingsPath', '.vim/settings.json')), !!get(g:, 'LanguageClient_loadSettings', 1), get(g:, 'LanguageClient_rootMarkers', v:null), get(g:, 'LanguageClient_changeThrottle', v:null), get(g:, 'LanguageClient_waitOutputTimeout', v:null), !!get(g:, 'LanguageClient_diagnosticsEnable', 1), get(g:, 'LanguageClient_diagnosticsList', 'Quickfix'), get(g:, 'LanguageClient_diagnosticsDisplay', {}), get(g:, 'LanguageClient_windowLogMessageLevel', 'Warning'), get(g:, 'LanguageClient_hoverPreview', 'Auto'), get(g:, 'LanguageClient_completionPreferTextEdit', 0), has('nvim')]"],"id":4}
'
  0.770924 : looking for messages on channels
  0.770966 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.771165 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.771287 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.771518 SEND on 2: '{"id":4,"jsonrpc":"2.0","result":[1,{"scss":["node","C:/Users/Administrator/AppData/Roaming/npm/node_modules/vscode-css-languageserver-bin/cssServerMain.js","--stdio"],"javascript":["node","C:/Users/Administrator/AppData/Roaming/npm/node_modules/lsp-tsserver/dist/server.js"],"css":["node","C:/Users/Administrator/AppData/Roaming/npm/node_modules/vscode-css-languageserver-bin/cssServerMain.js","--stdio"]},null,null,".vim\\settings.json",1,null,null,null,1,"Quickfix",{},"Warning","Auto",0,0]}
'
  0.801998 RECV on 2: 'Content-Length: 165

{"jsonrpc":"2.0","method":"eval","params":["[get(g:, 'LanguageClient_diagnosticsSignsMax', v:null), get(g:, 'LanguageClient_documentHighlightDisplay', {})]"],"id":5}
'
  0.802025 : looking for messages on channels
  0.802038 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.802217 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.802333 on 2: Invoking channel callback <SNR>122_HandleStdoutVim
  0.802446 SEND on 2: '{"id":5,"jsonrpc":"2.0","result":[null,{}]}
'
  0.804814 : Starting job: cmd.exe /c cd /d "E:\zwh\software\Vim" && (git --no-pager show :_vimrc > C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 && git --no-pager  -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\ADMINI~1\AppData\Local\Temp\VIBCC84.tmp.2 C:\Users\ADMINI~1\AppData\Local\Temp\VICCC85.tmp.2 || exit 0)
  0.804852 on 11: Created channel
  0.865653 on 9: Job ended
  0.865695 : Starting job: git status --porcelain -- "E:\zwh\software\Vim\_vimrc"
  0.865725 on 12: Created channel
  0.927761 RECV on 9: 'fatal: not a git repository (or any of the parent directories): .git
'
  0.927779 RECV on 8: 'diff --git "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\VIBCC84.tmp.2" "b/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\VICCC85.tmp.2"
index e69de29..d880167 100644
--- "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\VIBCC84.tmp.2"
+++ "b/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\VICCC85.tmp.2"`

**Comment by airblade** [comment]
I'm glad it works when async is off.

Thanks for the logs.  The channel log has a bit of noise from other plugins but channels 8, 10 and 11 seem to be the ones we are interested in.

The first two calls to git-diff don't seem to return a result.  I would expect the `on_exit_vim` handler to be called back each time, with an empty result, but it doesn't seem to be called at all.

The third call to git-diff does call the handler but the result is not empty.  Even stranger it consists of a diff header but no "body" (i.e. there are no hunks listed).

This is odd but I don't think it would cause gitgutter to think all the lines have been added because gitgutter only looks at the hunks.

I can't explain what is going on.

**Comment by airblade** [comment]
Is your `updatetime` less than `200`?

**Comment by z-wh** [comment]
> Is your `updatetime` less than `200`?

No, when I add let g:gitgutter_async=0 into my vimrc file, the updatetime  was  very very slow.  So,  I can't  use  this plug in Vim.

**Comment by airblade** [comment]
Are you talking about the Vim option `updatetime` (which I am), or how long it takes your system to update the signs in Vim?

**Comment by airblade** [comment]
This should be fixed by 32d53f1.

**Comment by airblade** [comment]
I was seeing this problem sporadically myself, but not since 32d53f1 nearly a month ago.

I'm assuming this is fixed now but please let me know if you still have this.
