### ISSUE TITLE
Very slow in Neovim (>6 seconds)?

### ISSUE THREAD

**Issue by olalonde** [airblade/vim-gitgutter#555]
> What is the latest commit SHA in your installed vim-gitgutter?

622193a625b6f26622b9821933f9424ccf0b6fd8

> What vim/nvim version are you on?

NVIM v0.3.1

For some reason, this plugin is really slow in my neovim. I'm not using any custom settings. When I save a file, it takes up to 5-10s for the gutter to update.

**Comment by olalonde** [comment]
![slow-git-gutter](https://user-images.githubusercontent.com/416585/47006656-00cce780-d169-11e8-9f85-4ebbcf3de034.gif)

**Comment by airblade** [comment]
If you had said 4 seconds, I would have suggested checking your `updatetime` option (which defaults to `4000`ms, i.e. 4s).  But 5-10 seconds sounds odd.

Please could you [profile](https://github.com/airblade/vim-gitgutter/wiki/How-to-profile-vim-gitgutter) the slow behaviour and post the results?

**Comment by olalonde** [comment]
I will try to play with the updatetime option. Here's the profile: http://termbin.com/43bg

**Comment by olalonde** [comment]
Oops, the issue was indeed `updatetime`... I added `set updatetime=100` to my config and it's really fast now.
