### ISSUE TITLE
nvim hangs

### ISSUE THREAD

**Issue by HaleTom** [airblade/vim-gitgutter#557]
> What is the latest commit SHA in your installed vim-gitgutter?

```
0597380 Prompt user to choose hunk when overlapping.
```

> What vim/nvim version are you on?

```
NVIM v0.3.1
```

I first noticed this issue about 10 October:

My `nvim` is hanging at seemingly random points while in command mode. 

Sometimes it's just cursor movement which causes the hang.

After the hang, I've found no way to get `nvim` to respond again.

The files that I am editing are sometimes not in a git repository.

When hung, there is always a 100% CPU usage by the `nvim` process.

This doesn't tell me too much:
```
    % sudo strace -fs200 -p 18878  |& uniq
    strace: Process 18878 attached with 2 threads
    strace: [ Process PID=18878 runs in x32 mode. ]
    [pid 18894] epoll_pwait(15, strace: [ Process PID=18878 runs in 64 bit mode. ]
     <unfinished ...>
    [pid 18878] epoll_pwait(9, [], 1024, 0, NULL, 8) = 0
    [pid 18878] madvise(0x7f54d8401000, 33562624, MADV_FREE) = 0
    [pid 18878] madvise(0x7f54d8401000, 33562624, MADV_DONTNEED) = 0
    [pid 18878] epoll_pwait(9, [], 1024, 0, NULL, 8) = 0
    [pid 18878] madvise(0x7f54d7400000, 16781312, MADV_FREE) = 0
    [pid 18878] epoll_pwait(9, [], 1024, 0, NULL, 8) = 0
    [pid 18878] madvise(0x7f54d8401000, 33562624, MADV_FREE) = 0
    [pid 18878] madvise(0x7f54d8401000, 33562624, MADV_DONTNEED) = 0
    [pid 18878] epoll_pwait(9, [], 1024, 0, NULL, 8) = 0
    [pid 18878] madvise(0x7f54d7400000, 16781312, MADV_FREE) = 0
    [pid 18878] epoll_pwait(9, [], 1024, 0, NULL, 8) = 0
    [pid 18878] madvise(0x7f54d8401000, 33562624, MADV_FREE) = 0
    [pid 18878] madvise(0x7f54d8401000, 33562624, MADV_DONTNEED) = 0
    [... <repeats>]
```

I checked out fd 9 in `/proc/$PID/fd`, and it was: `9 -> 'anon_inode:[eventpoll]'`.

When killed with `SIGTERM`, I see:

```
Error detected while processing function gitgutter#all[9]..gitgutter#process_buffer[8]..gitgutter#diff#run_diff[30]..<SNR>159_write_buffer:
line   16:
E482: Can't open file /tmp/nvimLmrnCr/2.1 for writing: no such file or directory
Error detected while processing function gitgutter#all:
line    9:
E171: Missing :endif% 
```

The file `/tmp/nvimLmrnCr/2.1` can't be accessed:

```
 % ls -ld /tmp/nvimLmrnCr
ls: cannot access '/tmp/nvimLmrnCr': No such file or directory
```

But then again, it may have been deleted by nvim's `SIGTERM` handler.  I'll try `SIGKILL` next time and update this issue.

[Here](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter.vim#L9) is the associated code block:

```
  for bufnr in range(1, bufnr('$') + 1)
    if buflisted(bufnr)                              " This is line 9
      let file = expand('#'.bufnr.':p')
      if !empty(file)
        if index(visible, bufnr) != -1
          call gitgutter#init_buffer(bufnr)
          call gitgutter#process_buffer(bufnr, a:force)
        elseif a:force
          call s:reset_tick(bufnr)
        endif
      endif
    endif
  endfor
endfunction
```

**Comment by airblade** [comment]
Was you nvim process open for several days?  If so, perhaps your OS cleaned up the temp directory `/tmp/nvimLmrnCr` (this is a known problem with Vim's temp files).

**Comment by HaleTom** [comment]
@airblade Nope, in some cases it hung after only about half an hour or so.  

FYI, I use Manjaro based on Arch Linux.

**Comment by airblade** [comment]
Ah, ok.

Your error points to this line:

https://github.com/airblade/vim-gitgutter/blob/0597380f6b22f43a3ea6ff8364d5c239bb2504ea/autoload/gitgutter/diff.vim#L381

All this does is call `writefile()`.  That seems to be failing because the temporary directory generated by `tempname()` doesn't exist or cannot be read.  As both are these are built-in functions, it looks to me like a (neo)vim problem rather than something the plugin is doing wrong.

**Comment by airblade** [comment]
Closing because this has gone quiet.  Happy to reopen if it's still a problem.
