### ISSUE TITLE
Usability improvements w.r.t. buffer to 'working_tree' diffs

### ISSUE THREAD

**Issue by orao** [airblade/vim-gitgutter#558]
I would like to be able to get [vim-gitgutter](airblade/vim-gitgutter) to show me the diff between my current buffer and the working tree, or more specifically the file on disk if the file is not tracked by Git.

In Git we have the working tree, the index, and commits to diff against but with Vim's buffers we are adding yet another point to potentially diff from and it would be nice to allow for this in the plugin.

This is the list of places changes could be introduced and from which we may want to be able to diff:
  - Buffer contents
  - Working tree (saved contents)
  - Index
  - Commit

This plugin already does the diff between the buffer and the working tree internally [here](https://github.com/airblade/vim-gitgutter/blob/0597380f6b22f43a3ea6ff8364d5c239bb2504ea/autoload/gitgutter/diff.vim#L115-L117), and it should only be a matter of exposing it to the [process_buffer()](https://github.com/airblade/vim-gitgutter/blob/0597380f6b22f43a3ea6ff8364d5c239bb2504ea/autoload/gitgutter.vim#L36-L58) function which directly sets the `'index'` as the target of the diff.

Ideally, I want to be able to set up some shortcuts to see the following diffs:
  - [ ] Diff buffer to what is on disk (working tree)
  - [x] Diff buffer to what is in the index
  - [x] Diff buffer to what is in an arbitrary commit (i.e. `@{upstream}`)

The last two I know I can do, but the first one I'm not sure how to set up... I have a workaround using the command line but I would really like to be able to have [vim-gitgutter](airblade/vim-gitgutter) display this information.

Is this something that would be of interest to other users or is it just my own workflow?

If this is already possible, would you mind updating the [README.mkd](https://github.com/airblade/vim-gitgutter/blob/0597380f6b22f43a3ea6ff8364d5c239bb2504ea/README.mkd) with information about how to achieve it?

**Comment by airblade** [comment]
> Diff buffer to what is on disk (working tree)

In other words, your unsaved modifications to the buffer.

This should be easy to implement.  I'll try to get to in the next day or two.

**Comment by airblade** [comment]
Sorry for the delay on this.  Would you still like this feature?

**Comment by orao** [comment]
I would but it depends on whether you think it fits with the extension and is worth implementing/supporting.
