### ISSUE TITLE
Changed text within a changed line - DiffText vs DiffChange

### ISSUE THREAD

**Issue by orao** [airblade/vim-gitgutter#560]
**Version info**:

 - [vim-gitgutter](airblade/vim-gitgutter) commit: 0597380f6b22f43a3ea6ff8364d5c239bb2504ea
 - [base16-vim](https://github.com/chriskempson/base16-vim) at commit [7e9af12d680d81cc1277c07ef5acee8c83828f3f](https://github.com/chriskempson/base16-vim/commit/7e9af12d680d81cc1277c07ef5acee8c83828f3f)
 - Vim version: 8.1 (2018 May 18, compiled Oct 29 2018 13:49:36)

**Problem**:

The [base16 monokai](https://github.com/chriskempson/base16-vim/blob/7e9af12d680d81cc1277c07ef5acee8c83828f3f/colors/base16-monokai.vim) colour scheme from [base16-vim](https://github.com/chriskempson/base16-vim) shows the changed lines far too dimly to be useful and this is different to viewing a patch with syntax highlighting or even a diff in Vim.

This is because the colour scheme attempts to highlight the difference between the text that actually changed within the _"changed line"_ while the [vim-gitgutter](airblade/vim-gitgutter) plugin only highlights the line itself and does not differentiate the text changed within the line itself.

**Investigation so far**:

I have noticed that the patch syntax highlighting and diffs in Vim seem to use the [`DiffText`](http://vimdoc.sourceforge.net/htmldoc/syntax.html#hl-DiffText) with [these colours](https://github.com/chriskempson/base16-vim/blob/7e9af12d680d81cc1277c07ef5acee8c83828f3f/colors/base16-monokai.vim#L259) for the text. I haven't seen this value being used by [vim-gitgutter](airblade/vim-gitgutter) and I'm not sure which side this should be fixed in. [Vim diff documentation](http://vimdoc.sourceforge.net/htmldoc/diff.html) itself states:

    |hl-DiffChange|	DiffChange	Changed lines.
    |hl-DiffText|	DiffText	Changed text inside a Changed line.  Vim
                    finds the first character that is different,
                    and the last character that is different
                    (searching from the end of the line).  The
                    text in between is highlighted.  This means
                    that parts in the middle that are still the
                    same are highlighted anyway.  Only "iwhite" of
                    'diffopt' is used here.

**Temporary resolution**:

I'm not sure where the problem lies and I've fixed it temporarily by changing the [base16-vim](https://github.com/chriskempson/base16-vim) `DiffChange` foreground colour to match `DiffText`.

**Linked issues**:

 - [base16-vim #191](https://github.com/chriskempson/base16-vim/issues/191)
 - [vim-signify #276](https://github.com/mhinz/vim-signify/issues/276)

**Comment by airblade** [comment]
This sounds related to #545 although that concerns the signs' colours.

I don't know how to make vim-gitgutter highlight the text changed within a changed line (efficiently).

**Comment by orao** [comment]
For two files:

    $ cat left.txt
    Hello there!

    I am going to use this file
    to demonstrate the diff
    functionality of Vim

    Hopefully it will work...

and

    $ cat right.txt
    Hello there!

    I am going to use this file
    to demonstrate the exciting diff
    functionality of Vim

    This is going to be fun!

You can get `git diff` to print you the markers with the `--word-diff` argument like this:

    $ git diff --no-index --word-diff left.txt right.txt
    diff --git a/left.txt b/right.txt
    index 03795fc..f8f9a59 100644
    --- a/left.txt
    +++ b/right.txt
    @@ -1,7 +1,7 @@
    Hello there!

    I am going to use this file
    to demonstrate the {+exciting+} diff
    functionality of Vim

    [-Hopefully it will work...-]{+This is going to be fun!+}

**Comment by airblade** [comment]
Thanks, but I can't see a way to process `--word-diff` output efficiently, i.e. quickly.  Right now the code discards everything in the diff output except the hunk headers (e.g. `@@ -1,7 +1,7 @@`).

Also the plugin just deals with signs; handling intra-line highlighting would be a new kettle of fish.

**Comment by orao** [comment]
Ok. That's fair enough. If it doesn't fit, lets not jam it in. However, I would recommend using the `DiffText` as the foreground colour for the line if we are not going to detect what changed within the line. I think it will play better with more colour schemes.

**Comment by orao** [comment]
Happy to close with the same solution as in [vim-signify #276](https://github.com/mhinz/vim-signify/issues/276). Just adding a note about `DiffText` in the `README.md` for those who may be new to Vim and unaware of it...

**Comment by airblade** [comment]
Please see fdecc23.
