### ISSUE TITLE
SignColumn starts out grey, but then changes correctly after ^L

### ISSUE THREAD

**Issue by sbromberger** [airblade/vim-gitgutter#561]
> What is the latest commit SHA in your installed vim-gitgutter?

`0597380f6b22f43a3ea6ff8364d5c239bb2504ea`

> What vim/nvim version are you on?
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2018 06:55:58)
macOS version
Included patches: 1-500
```
> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

N/A

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

N/A

When I start up vim, the SignColumn background is grey except for where GitGutter labels are (then it's black, which it should be). If I hit `^L` to redraw the screen, the SignColumn background turns black. Also, the line numbers start off brown, but then go to the (correct) grey once `^L` is hit.

I'm using
```
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'itchyny/lightline.vim'
Plug 'joshdick/onedark.vim'
Plug 'w0rp/ale'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'SirVer/ultisnips'
Plug 'maximbaz/lightline-ale'
Plug 'Shougo/deoplete.nvim'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'tomtom/tcomment_vim'
Plug 'zchee/deoplete-go', { 'do': 'make'}
Plug 'JuliaEditorSupport/julia-vim'
Plug 'airblade/vim-gitgutter'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'python-mode/python-mode', { 'branch': 'develop' }
```

and I think this may be an interaction with `onedark`.

**Comment by sbromberger** [comment]
I take it back - when I enable `vim-hug-neovim-rpc`, the grey column appears.

**Comment by airblade** [comment]
Given that redrawing the screen changes various colours, it sounds like an ordering problem with the highlight definitions.

GitGutter sets up its colours in `highlight.vim`.  By [default](https://github.com/airblade/vim-gitgutter/blob/0597380f6b22f43a3ea6ff8364d5c239bb2504ea/autoload/gitgutter/highlight.vim#L36-L37) it links the `SignColumn` to `LineNr` but you can stop that with `let g:gitgutter_override_sign_column_highlight=0`.

GitGutter also [tries](https://github.com/airblade/vim-gitgutter/blob/0597380f6b22f43a3ea6ff8364d5c239bb2504ea/autoload/gitgutter/highlight.vim#L44) to set the background colour of its signs to match the background colour of the sign column.

It does all this when it [starts up](https://github.com/airblade/vim-gitgutter/blob/0597380f6b22f43a3ea6ff8364d5c239bb2504ea/plugin/gitgutter.vim#L77-L79).

I can't think why `vim-hug-neovim-rpc` would affect any colours but I can see how `onedark.vim` might.  The latter [links](https://github.com/joshdick/onedark.vim/blob/2a6155a255e83bb930da2627dce4259a3fe4ce3a/colors/onedark.vim#L494-L496) GitGutter's highlights to Signify's, but defines the Signify ones ten lines later; I'm not sure whether vim can link to highlight groups which don't exist at the time.

GitGutter doesn't do anything to the `LineNr` highlight group, so something else must be affecting that.

To find out why the sign column starts with a grey background, you could try `:verbose hi signcolumn`, before and after `^L`.  That should give you an idea of what is setting it when.

**Comment by sbromberger** [comment]
Thanks for the very detailed explanation. I wound up just removing deoplete and associated plugins in favor of completor, and the issues appear to have resolved. Closing this out as it's not at all evident that it's a problem with GitGutter.
