### ISSUE TITLE
Signs not shown in git-annex v6 repository with clean/smudge filter

### ISSUE THREAD

**Issue by sorsasampo** [airblade/vim-gitgutter#563]
It seems `git-annex` version 6 repositories with clean/smudge filters do not get signs. More specifically, commenting out the following from `.git/config` makes the signs present again:

```
[filter "annex"]
	smudge = git-annex smudge %f
	clean = git-annex smudge --clean %f
```

Steps to reproduce:

```
$ git init repo
$ cd repo
$ git annex init
$ git annex upgrade
# commit a file
# open it with vim and make changes
```

Not sure whether this is related to `git-annex` or filters in general. Any debugging tips?

> What is the latest commit SHA in your installed vim-gitgutter?

0597380f6b22f43a3ea6ff8364d5c239bb2504ea

> What vim/nvim version are you on?

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)                                                                                                                                                
Included patches: 1-197, 322, 377-378, 550, 703, 706-707

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

Proper pathname to the file.

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

Nope.

**Comment by airblade** [comment]
Does `git show :repo_path/to/file` write the staged file's contents to stdout?  The plugin relies on that to produce one side of the diff comparison.

For debugging I suggest `let g:gitgutter_log=1` and tail `gitgutter.log` and `channel.log` in the directory where vim-gitgutter is installed.

**Comment by sorsasampo** [comment]
Thanks for the `let g:gitgutter_log=1`, I realized now it's in `:h gitgutter`, but perhaps it should be in the README as well.

The problem seems to be calling `git diff` on a file outside the repository, which causes `git-annex` and `git` to output a bunch of lines on stderr (even though it seems to produce the diff as well).

```
  0.013866 : Starting job: sh  -c  cd /tmp/gutter && (git --no-pager show :ok.txt > /tmp/vIbYoW5/7.1.txt && git --no-pager  -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- /tmp/vIbYoW5/7.1.txt /tmp/vIbYoW5/8.1.txt | grep '^@@ ' || exit 0) || exit0
  0.013882 on 2: Created channel
  0.014968 : looking for messages on channels
  0.022223 RECV on 1: 'fatal: '../vIbYoW5/7.1.txt' is outside repository
```

`git diff -- /outside/file1.txt /outside/file2.txt` outputs:

```
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
git-annex: git check-attr EOF: user error
git-annex: user error (git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","check-attr","-z","--stdin","annex.backend","annex.numcopies","annex.largefiles","--"] exited 128)
error: external filter 'git-annex smudge --clean %f' failed 1
error: external filter 'git-annex smudge --clean %f' failed
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
git-annex: git check-attr EOF: user error
git-annex: user error (git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","check-attr","-z","--stdin","annex.backend","annex.numcopies","annex.largefiles","--"] exited 128)
error: external filter 'git-annex smudge --clean %f' failed 1
error: external filter 'git-annex smudge --clean %f' failed
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
fatal: '../test.txt' is outside repository
git-annex: git check-attr EOF: user error
git-annex: user error (git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","check-attr","-z","--stdin","annex.backend","annex.numcopies","annex.largefiles","--"] exited 128)
error: external filter 'git-annex smudge --clean %f' failed 1
error: external filter 'git-annex smudge --clean %f' failed
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
fatal: '../test2.txt' is outside repository
git-annex: git check-attr EOF: user error
git-annex: user error (git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","check-attr","-z","--stdin","annex.backend","annex.numcopies","annex.largefiles","--"] exited 128)
error: external filter 'git-annex smudge --clean %f' failed 1
error: external filter 'git-annex smudge --clean %f' failed
diff --git a/tmp/test.txt b/tmp/test2.txt
index 9766475..932d7d5 100644
--- a/tmp/test.txt
+++ b/tmp/test2.txt
@@ -1 +1,2 @@
 ok
+foo
```

Considering `git diff` can indeed be used to show changes between two files outside the repository, this seems like a `git-annex` bug. Ignoring stderr or disabling filters seem like dangerous workaround ideas, so I don't think there is anything vim-gitgutter can do about this.

Anything to add before I go make a bug report for git-annex & @joeyh?

**Comment by sorsasampo** [comment]
`git-annex` bug created: https://git-annex.branchable.com/bugs/v6_smudge_filter_breaks_git_diff_for_files_outside_the_repository/

**Comment by airblade** [comment]
Does the `fatal: '../test.txt' is outside repository` message come from git or git-annex?

Currently vim-gitgutter assumes any kind of output on stderr means the diff has gone wrong, the stdout output cannot be trusted, and all the signs should be cleared.  However that's not always true; sometimes stderr output can be just a warning e.g. https://github.com/airblade/vim-gitgutter/issues/486#issuecomment-369297233.

So I've been thinking about ditching vim-gitutter's stderr callback.  Presumably doing so would help in this case?

**Comment by sorsasampo** [comment]
A quick search suggests it might actually come from git:

https://github.com/git/git/blob/7e8bfb0412581daf8f3c89909f1d37844e8610dd/pathspec.c#L441

And yes, ignoring stderr would probably help in this case, but somehow ignoring stderr does not sound so good idea. It's actually kind of weird to see fatal errors, and then get the diff produced regardless.

I suggest waiting for @joeyh's reply on the `git-annex` issue.

**Comment by airblade** [comment]
It sounds to me like this is not an issue with vim-gitgutter so I'm going to close this.  Please chime in if I'm wrong and I'll reopen it.

**Comment by sorsasampo** [comment]
@airblade: that's a good call. Keeping vim-gitgutter's stderr handling as-is is probably the right way to go.

Joey commented:

> So it seems the best that can be done is for the clean filter to pass through the content of files located outside the repo. At least avoiding error messages and unwanted ingestion, but not generating a useful diff in the second case. **And this is the approach I've implemented**.

So the `git-annex` issue should be fixed. Unfortunately I haven't had time to test it out yet. Apologies for leaving this issue hanging!
