### ISSUE TITLE
slow on large non git tracked files

### ISSUE THREAD

**Issue by grroy** [airblade/vim-gitgutter#564]
> What is the latest commit SHA in your installed vim-gitgutter?
commit 0597380f6b22f43a3ea6ff8364d5c239bb2504ea (grafted, HEAD -> master, origin/master, origin/HEAD)
Date:   Thu Oct 18 15:39:55 2018 +0100

> What vim/nvim version are you on?

VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2018 06:55:58)
macOS version
Included patches: 1-500

Issue:

Everything works great, this is an amazing plugin! However, I have a large file I open from time to time, and this file is locally generated (not even in git). But when I open it from a new vim invocation, it takes a long time (10 seconds to open). If I remove git-gutter it takes less than a second to open

"file.txt" 354509L, 261378185C

No signs come up (this file isn't in git). Is there any way to speed this up? I tried the signify plugin, it doesn't have this extra delay with large non git tracked files.

If you want to try, you can generate a sample file with "seq 10000000 > large-file". Then try to open that file from the command line with and without gitgutter loaded to see the difference.

Thanks!

**Comment by airblade** [comment]
The first thing vim-gitgutter does with a file is determine whether git knows about it, via `git ls-files --error-unmatch ...`.  This is executed asynchronously and if the command exits with a non-zero code, the plugin knows it should not try to diff the file.

It seems there was a race condition in the stdout and stderr callback handlers: with a large file the stderr callback wasn't able to stop the stdout callback from being invoked after the stderr callback had been invoked.  The stderr callback told the plugin the file wasn't known to git, and then the stdout callback contradicted this and said actually it is.  So the plugin then tried to diff the file, which lead to the 10s delay.

I believe I have fixed this in 32d53f1...208b439.  Please could you try it out?

**Comment by grroy** [comment]
I just updated to the latest version and the problem is fixed! It is consistently fast now. This issue is resolved. Thanks!
