### ISSUE TITLE
I want to use the defined bg, but set my own fg

### ISSUE THREAD

**Issue by shmup** [airblade/vim-gitgutter#566]
You set the bg dynamically and I want to tap into that. Really it'll probably be easiest if I just fork and set the default foregrounds to the greyscale I'm going for

https://github.com/airblade/vim-gitgutter/blob/c2651aefbd92dca05de1943619df965b848f9b4f/autoload/gitgutter/highlight.vim#L44

```
function! gitgutter#highlight#define_highlights() abort
  let [guibg, ctermbg] = s:get_background_colors('SignColumn')

  " Highlights used by the signs.

  execute "highlight GitGutterAddDefault    guifg=#009900 guibg=" . guibg . " ctermfg=2 ctermbg=" . ctermbg
  ...
```

I do think it'd be really rad if this plugin _did_ provide an easy "greyscale, less flashy/bright" setting.

**Comment by airblade** [comment]
Is this for the signs' colours?  If so, just [configure them](
https://github.com/airblade/vim-gitgutter#signs-colours-and-symbol)s.

**Comment by airblade** [comment]
#545 would by default link the signs' colours to your colourscheme's diff colours, which would probably do what you want.
