### ISSUE TITLE
Recent changes cause all lines to be marked as changed

### ISSUE THREAD

**Issue by shea-parkes** [airblade/vim-gitgutter#567]
> What is the latest commit SHA in your installed vim-gitgutter?

The plugin worked as of commit 0597380f6b22f43a3ea6ff8364d5c239bb2504ea (Current as of October 18th)
I just tried to update to commit 5c636b128ed40f3ed926d18adb307e01dfc082f8

> What vim/nvim version are you on?

Neovim 0.3.1 on **Windows 10**

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

It's actually that too many signs are showing, but for completeness, this gives `.github/ISSUE_TEMPLATE.md` for my example of broken.

Here's a screenshot from nvim-qt.  Notice that i have a vim-fugitive panel up showing no changes to this file:
![image](https://user-images.githubusercontent.com/5782892/50013753-08a1e000-ff90-11e8-9712-d30c465fd290.png)

I had to roll back to be able to work alas.  Happy to do more diagnostics and trouble shooting upon request.

**Comment by airblade** [comment]
Any chance you could git-bisect this?

Since all lines are showing as modified, I wonder if it's a line ending problem.  If you turn on logging with `let g:gitgutter_log=1` and get all the signs showing as above, what does the log show (it'll be in the directory where gitgutter is installed)?

**Comment by airblade** [comment]
That commit change `writefile()` to use binary mode; there must be some side-effect I didn't account for.

**Comment by shea-parkes** [comment]
And here's the log, with only a single folder name redacted:
```


==== start log session ====

  0.000016 function <SNR>46_on_bufenter[5]..gitgutter#init_buffer[4]..gitgutter#utility#set_repo_path[11]..gitgutter#async#execute[1]:
  0.000016 [async] cd /d "C:\Users\shea.parkes\repos\redacted\.github" && git ls-files --error-unmatch --full-name -z -- ISSUE_TEMPLATE.md

  0.782838 function <SNR>46_on_bufenter[6]..gitgutter#process_buffer[8]..gitgutter#diff#run_diff[83]..gitgutter#async#execute[1]:
  0.782838 [async] cd /d "C:\Users\shea.parkes\repos\redacted\.github" && (git --no-pager show :.github/ISSUE_TEMPLATE.md > C:\Users\SHEA~1.PAR\AppData\Local\Temp\nvim6i8m2G\3.1.1.md && git --no-pager  -c "diff.autorefreshindex=0" -c "diff.noprefix=false" -c "core.safecrlf=false" diff --no-ext-diff --no-color -U0  -- C:\Users\SHEA~1.PAR\AppData\Local\Temp\nvim6i8m2G\3.1.1.md C:\Users\SHEA~1.PAR\AppData\Local\Temp\nvim6i8m2G\4.1.1.md | grep "^@@ " || exit 0)

  1.279277 function <SNR>49_on_exit_nvim[2]..gitgutter#diff#handler[1]:
  1.279277 @@ -1,17 +1,18 @@
```

I am on windows, and I believe that repository is setup with `autocrlf=true`, so I would expect this file in question to have `CRLF` on my filesystem and `LF` only in the "git store" (I butchered that term, but I trust you to know what I meant).

**Comment by shea-parkes** [comment]
Indeed.  Moving to the current commit ( 5c636b128ed40f3ed926d18adb307e01dfc082f8 ) and changing `diff.vim` to `all writefile(bufcontents, a:file)` did fix the problem I was seeing.  (But I perfectly understand that you likely changed it to a binary write for a good reason.)

**Comment by airblade** [comment]
Does this solve your problem?

```diff
diff --git i/autoload/gitgutter/diff.vim w/autoload/gitgutter/diff.vim
index e1bd5a3..7fabaac 100644
--- i/autoload/gitgutter/diff.vim
+++ w/autoload/gitgutter/diff.vim
@@ -377,12 +377,8 @@ function! s:write_buffer(bufnr, file)
   if bufcontents == [''] && line2byte(1) == -1
     " Special case: empty buffer; do not write an empty line in this case.
     " A nearly empty buffer of only a newline has line2byte(1) == 1.
-  else
-    if getbufvar(a:bufnr, '&endofline')
-          \ || (!getbufvar(a:bufnr, '&binary')
-          \     && (!exists('+fixendofline') || getbufvar(a:bufnr, '&fixendofline')))
-      call add(bufcontents, '')
-    endif
+    call system('touch '.a:file)
+    return
   endif
 
   if getbufvar(a:bufnr, '&fileformat') ==# 'dos'
@@ -398,7 +394,7 @@ function! s:write_buffer(bufnr, file)
     let bufcontents[0]='﻿'.bufcontents[0]
   endif
 
-  call writefile(bufcontents, a:file, 'b')
+  call writefile(bufcontents, a:file)
 endfunction
 ```

**Comment by shea-parkes** [comment]
That does solve my problem.

I tried to play around some with an empty buffer to make sure the `Special case: empty buffer` codepath was still working, but I honestly wasn't familiar enough with what problem was it was solving, so I couldn't really confirm it was still working.

So I'd be pleased with that patch, but I can't confirm that deleting that gnarly `getbufvar` logic doesn't break something.

**Comment by airblade** [comment]
Thanks for looking into it and for confirming it solves your problem.

Before the problematic commit the code used `writefile()` in non-binary mode to write the buffer contents.  Then it turned out that when the buffer was empty, the code always produced a file with an EOL even if the empty buffer was truly empty, not just (an empty line terminated by) a single EOL.

So the commit switched to using binary mode for `writefile()`, which means the caller gets more control of when and where EOLs are written.  The `getbufvar` logic was there to ensure an empty buffer produced a file which only had an EOL when appropriate.

The patch above reverts to using `writefile()` in non-binary mode, which we know generally works well, and uses a simpler way to write a properly empty file.

I was a bit worried about the commit because I suspected that binary mode for `writefile()` has various undocumented side-effects.  Evidently you ran into one of them.

**Comment by shea-parkes** [comment]
That all seems reasonable to me.  Would you like me to submit a pull request with the above changes?

**Comment by airblade** [comment]
Thanks for the offer but I've already taken care of it (1d422b9).

The new code doesn't work for noeol files but that's the best I can do for now.

**Comment by shea-parkes** [comment]
I got a chance to pull the new changes.  Things are back to working.  Thanks again for a great plugin (and being responsive).

**Comment by airblade** [comment]
Thanks – that's good to hear.

I'm still curious about what the original problem actually was.  Given the file was unchanged, having all lines marked as modified certainly suggests a line-ending mismatch.

There are several places where this could all go wrong.

One side of the diff is the buffer contents:

- git index → working tree (subject to git's CRLF config)
- working tree → vim buffer
- vim buffer → temporary file (the gitgutter function we've been patching)

The other side of the diff is the index:

- git index → temporary file (via `git show`)

Then the diff itself:

- `git -c "core.safecrlf=false" ... diff -- ... ...`

If you don't mind, when you have the issue template buffer open, what does this give?

```viml
:set ff? enc? fenc? eol? fixeol? bomb?
```

**Comment by shea-parkes** [comment]
```
fileformat=dos
encoding=utf-8
fileencoding=utf-8
endofline
fixendofline
nobomb
```

**Comment by airblade** [comment]
Thank you.

I still don't understand why there's any difference between binary and non-binary mode when writing a non-empty buffer.
