### ISSUE TITLE
buffer-local settings

### ISSUE THREAD

**Issue by goerz** [airblade/vim-gitgutter#568]
Is there a way to disable gitgutter for a particular buffer? It appears that all the options (e.g. `:gitgutter_enabled`, which is set by `GitGutterDisable`) are global.

My problem is that gitgutter produces nonsense signs when the text in the buffer doesn't actually reflect the content of the file on disk, such as in the [`jupytext.vim` plugin](https://github.com/goerz/jupytext.vim) of which I'm the author. Thus, I'd like to turn off gitgutter for *.ipynb files only, respectively in `jupytext.vim` for the "current buffer".

Alternatively, if there was some way to communicate to gitgutter how to get the correct diff (compare against the baseline filtered through jupytext), that would be even better. But that would also be a buffer-local setting.

Version info:

* What is the latest commit SHA in your installed vim-gitgutter?

    1d422b9f98194e38bc56e54192c9bc66d95c21f1

* What vim/nvim version are you on?

    NVIM v0.3.2-dev

**Comment by goerz** [comment]
I just realized that for the particular use case of disabling nonsensical signs, `set signcolumn=no` is probably the simple way to go. But still, it seems like maybe it would be possible to get the correct diff by setting buffer-local versions of `g:gitgutter_git_executable`, `g:gitgutter_git_args`, etc.

**Comment by airblade** [comment]
I've just added `GitGutterBufferDisable`, `GitGutterBufferEnable`, and `GitGutterBufferToggle` in 2dce8e0.

I don't think there's a nice way to get the correct diff with your plugin.  You'd have to pipe one side of the diff only (the file from the index) through your conversion command, which would complicate the code generally for this special case.

**Comment by lukelbd** [comment]
Thanks for the buffer-local commands! Just wanted to point out they are not currently mentioned in the documentation.

**Comment by airblade** [comment]
@lukelbd Oops, thanks for letting me know :)  18d1298
