### ISSUE TITLE
Gitgutter doesn't update after commit via git from nvim-built-in-terminal

### ISSUE THREAD

**Issue by astier** [airblade/vim-gitgutter#570]
> What is the latest commit SHA in your installed vim-gitgutter? 1d422b9

> What vim/nvim version are you on? nvim v0.3.3

## Problem
Gitgutter doesn't update after commit via git from the neovim-built-in-terminal.

## Replicate
1. Open file with nvim which is tracked by git
2. Make a change to the file and save it
3. Gitgutter should show now respective signs in the gutter
4. Open a new window and type *:terminal*
5. Commit file with git from the opened terminal
6. Switch back to the window with the commited file
7. Observe that the gitgutter still shows the changes

## Expected Behavior
Gitgutter should automatically detect when commits were made and update the respective windows.

**Comment by astier** [comment]
This issue #502 might be related.

**Comment by airblade** [comment]
The difficulty is detecting when commits were made.  GitGutter listens to `ShellCmdPost` and `FocusGained` to detect when commits are made but evidently they are not fired in this situation.

There doesn't seem to be a `TermLeave` or `TermWinLeave` autocommand.  Maybe this could suffice as a workaround (untested):

```viml
autocmd WinLeave * if bufname('') =~ '^term://' | GitGutterAll | endif
```

**Comment by astier** [comment]
Thanks. This works indeed. Should I close this issue?
