### ISSUE TITLE
Is there a way to fold everything but hunks?

### ISSUE THREAD

**Issue by oguzbilgic** [airblade/vim-gitgutter#571]
Similar to `:Gdiff` or `vimdiff` I want to see only the changes, but they create a split with 2 files. I was wondering if there is a way to fold everything but hunks in the current file using gitgutter, which already shows/highlights the hunks.

**Comment by airblade** [comment]
Done in ac787af.

**Comment by oguzbilgic** [comment]
Oh wow, you are amazing. Thank you!
