### ISSUE TITLE
colors changed?

### ISSUE THREAD

**Issue by 9mm** [airblade/vim-gitgutter#573]
> Latest

> MVIM 8.1.577 (153), latest OSX

My colors used to show properly and now its dark blue and purple instead of green and red. I haven't changed anything in my setup in quite some time, but I do have plugins auto updating so my guess is it updated recently and I just noticed it now.

Do you know what this mgiht be from?

**Comment by 9mm** [comment]
![image](https://user-images.githubusercontent.com/1386207/51779901-2732e500-20bf-11e9-8c1b-e3150a33a27b.png)

**Comment by oguzbilgic** [comment]
If you have recently updated/installed the plugin, It might be related to https://github.com/airblade/vim-gitgutter/commit/afa4f2ddf0fecb37914ec37357636abb18013422

**Comment by 9mm** [comment]
awesome, thank you!
