### ISSUE TITLE
[Question] Is there a way to disable gitgutter automatically in diff mode

### ISSUE THREAD

**Issue by oguzbilgic** [airblade/vim-gitgutter#574]
Thanks for the amazing plugin and support @airblade.

When I use `:Gdiff`, gitgutter signs get out off sync and they are also kind of redundant, since vim already highlight the diffs. So I was wondering if there is a way to disable gitgutter automatically in diff mode.

First of all I'm not sure if gitgutter already has an option for this, but I could also achieve this by using `GitGutterDisable` and `autocmd` but I'm not sure how to detect if vim is in the diff mode.

**Comment by airblade** [comment]
You can detect diff mode by checking the window-local option `&diff`.

I understand the problem but fixing it is not as easy as it first appears.

It's worth reading #303 for context and the linked commits, including 37bdd03d.  If come up with a solution, let me know!

**Comment by oguzbilgic** [comment]
Okay thanks for the direction, I will take a look and try to share If I come across something useful.

**Comment by airblade** [comment]
Closing but happy to consider a pull request with a solution ;)
