### ISSUE TITLE
Its display is not norma

### ISSUE THREAD

**Issue by taigacute** [airblade/vim-gitgutter#575]
> What is the latest commit SHA in your installed vim-gitgutter?
the latest
> What vim/nvim version are you on?
nvim 0.3.3
> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

Its display is not normal  like this pic
![3331](https://user-images.githubusercontent.com/41671631/51801151-1035f380-2275-11e9-944b-de76a84bacc6.png)

**Comment by airblade** [comment]
Please the commit message in afa4f2ddf0.  In short you need to update your colorscheme or add 3 highlight groups to your vimrc.
