### ISSUE TITLE
Add feature to highlight change within a line

### ISSUE THREAD

**Issue by airblade** [airblade/vim-gitgutter#577]
It would be nice to have the ability to highlight change within a line.  I envisage this being something the user would invoke for the line their cursor is on; it would add too much overhead to calculate this for all changes all the time.

**Comment by oguzbilgic** [comment]
my 2 cents, If I'm using a light colorscheme I keep gitgutter's line highlighting always on, with subtle green/red/yellow background colors which give me a look that is similar to github commit view. So I would vote for `highlighting changes within a line` to be opt-in feature as well to avoid clutter.

**Comment by airblade** [comment]
See also https://github.com/rickhowe/diffchar.vim.

**Comment by airblade** [comment]
`git diff --color-words=. --word-diff=plain` (or `word-diff=porcelain`).

**Comment by airblade** [comment]
https://github.com/git/git/tree/master/contrib/diff-highlight

https://github.blog/2016-06-13-git-2-9-has-been-released/#beautiful-diffs

**Comment by airblade** [comment]
https://github.com/tpope/vim-git/pull/51/files

**Comment by airblade** [comment]
See GitHub's output, e.g. for 0469b84.

**Comment by zfogg** [comment]
+1
