### ISSUE TITLE
SignColumn colors looks obtrusive after the latest commit

### ISSUE THREAD

**Issue by subev** [airblade/vim-gitgutter#578]
Hello,

I noticed the signs background and color became messed up after the last commit. I do not use any extra settings for this plugin - just the default behavior, can I somehow make them as they used to be? Check the screenshots to understand what I mean.

Now: ![screen shot 2019-01-28 at 16 01 23](https://user-images.githubusercontent.com/1330872/51841194-b554d880-2316-11e9-89b4-65ca7070d0f7.png)
Before: ![screen shot 2019-01-28 at 16 00 50](https://user-images.githubusercontent.com/1330872/51841202-ba198c80-2316-11e9-96a4-2ba408a5ae3a.png)

If I revert the "afa4f2d" commit, it looks as before.

Any advises if I did something wrong are appreciated!

**Comment by airblade** [comment]
Please read the commit message for afa4f2d.  It's all explained there :)
