### ISSUE TITLE
How to display in real time

### ISSUE THREAD

**Issue by taigacute** [airblade/vim-gitgutter#579]
> What is the latest commit SHA in your installed vim-gitgutter?
the latest
> What vim/nvim version are you on?
neovim 0.3.4
> If no signs are showing at all, what does `:echo b:gitgutter.path` give?
langserver/doc.go
> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

Hi ！How to display in real time? It will appear when it returns to normal. It is real-time when it is deleted. What do I have to set to make it appear in real time? I added async, but whether it is 0 or 1, it is like a picture.
![git](https://user-images.githubusercontent.com/41671631/52163768-f20f3e00-2721-11e9-845a-5dae630d59d6.gif)

**Comment by airblade** [comment]
What is your `updatetime`?

**Comment by taigacute** [comment]
> What is your `&updatetime`?

set updatetime=100

**Comment by taigacute** [comment]
hmm .i update gitgutter. this is my setting
```
let g:gitgutter_sign_added = '▎'
let g:gitgutter_sign_modified = '▎'
let g:gitgutter_sign_removed = '▏'
let g:gitgutter_sign_removed_first_line = '▔'
let g:gitgutter_sign_modified_removed = '▋'
" ---------------------------------------------------------
highlight! GitGutterAdd ctermfg=22 guifg=#006000 ctermbg=NONE guibg=NONE
highlight! GitGutterChange ctermfg=58 guifg=#5F6000 ctermbg=NONE guibg=NONE
highlight! GitGutterDelete ctermfg=52 guifg=#600000 ctermbg=NONE guibg=NONE
highlight! GitGutterChangeDelete ctermfg=52 guifg=#600000 ctermbg=NONE guibg=NONE
```
befor 
![qq20190203-153839](https://user-images.githubusercontent.com/41671631/52174087-ce9fce00-27c9-11e9-80c6-f809a19398f6.png)
but  now 
![777](https://user-images.githubusercontent.com/41671631/52174095-ebd49c80-27c9-11e9-8612-e3048b84858a.png)
i see this  [afa4f2d](https://github.com/airblade/vim-gitgutter/commit/afa4f2ddf0fecb37914ec37357636abb18013422),but i set ctermbg= 0 its not change
i use [hybrid_reverse](https://github.com/kristijanhusak/vim-hybrid-material)

**Comment by airblade** [comment]
What does `:highlight SignColumn` give?  And `:highlight GitGutterAdd`?

**Comment by airblade** [comment]
I've just pushed fd834e4.  Please can you try that?

Also, is your original problem (real time updating) fixed?

**Comment by taigacute** [comment]
> 我刚推了[fd834e4](https://github.com/airblade/vim-gitgutter/commit/fd834e48eed21cc3c3ab66779a2296a16f41cbca)。请你试试吗？
> 
> 此外，您的原始问题（实时更新）是否已修复？

No， it also still， It only appears if I return to normal.

**Comment by airblade** [comment]
What does `:autocmd CursorHoldI` give?

**Comment by taigacute** [comment]
@airblade  hi ! i update, it display normal. but the color is strange

**Comment by taigacute** [comment]
> :autocmd CursorHoldI

```
:autocmd CursorHoldI
--- Autocommands ---
coc_nvim  CursorHoldI
    *         call s:Autocmd('CursorHoldI', +expand('<abuf>'))
gitgutter  CursorHoldI
    *         call gitgutter#process_buffer(bufnr(''), 0)
```
got these

**Comment by airblade** [comment]
If you get rid of the `coc_nvim` autocmd, do the signs start updating in insert mode?

**Comment by taigacute** [comment]
> 如果你摆脱`coc_nvim`autocmd，标志是否在插入模式下开始更新？


I tried it, but it is still the same

**Comment by taigacute** [comment]
> 好，谢谢。
> 
> 你能试试这个补丁吗？
> 
> ```diff
> diff --git i / autoload / gitgutter / utility.vim w / autoload / gitgutter / utility.vim
> index 470f222..648ad68 100644
> --- i / autoload / gitgutter / utility.vim 
> +++ w / autoload / gitgutter / utility.vim 
> @@ -54,7 +54,6 @@ endfunction
>  功能！gitgutter＃utility＃is_active（bufnr）abort
>    return g：gitgutter_enabled &&
>          \ gitgutter＃utility＃getbufvar（a：bufnr，'enabled'，1）&&
> -         \！pumvisible（）&&
>          \ s：is_file_buffer（a：bufnr）&&
>          \ s：exists_file（a：bufnr）&&
>          \ s：not_git_dir（a：bufnr）
> ```


Do I need to set up `let g:gitgutter_async `? I have been annotating this line

**Comment by airblade** [comment]
No, you don't need to do that.  `g:gitgutter_async=1` (default) means that the diff will be run in a background job; `g:gitgutter_async=0` means that the diff will be run in the foreground via `system()`.  It should not make a difference to whether or not the signs show.

**Comment by taigacute** [comment]
No change, is it normal for you?
![git](https://user-images.githubusercontent.com/41671631/52219167-13fdf180-28d7-11e9-922c-4b853c2e05db.gif)

**Comment by taigacute** [comment]
and the color becoms light.
befor 
![123124](https://user-images.githubusercontent.com/41671631/52219415-8b338580-28d7-11e9-83f2-6e43df3828b6.png)
now
![123213](https://user-images.githubusercontent.com/41671631/52219423-8f5fa300-28d7-11e9-9463-e4ec974fecef.png)

**Comment by airblade** [comment]
For me, the signs appear 100ms after I stop typing (because my `&updatetime` is 100), regardless of whether I am in insert mode or normal mode.

The latest commit (fd834e4) means that, by default, the signs have the foreground colours of the `Diff*` highlight groups and the background colour of the sign column.

The background colour looks correct for you.  What does `:verbose highlight GitGutterAdd` show now?

**Comment by taigacute** [comment]
My updatetime is also 100, but I didn't get any hints, it only appeared when I returned to normal. 
![31](https://user-images.githubusercontent.com/41671631/52219943-a783f200-28d8-11e9-954e-e97fbbaca3dd.png)

It has become lighter

**Comment by airblade** [comment]
It is lighter because, by default, the sign uses `DiffAdd`'s foreground colour.  Your custom overrides above are not working.  Try this:

```viml
highlight GitGutterAdd ctermfg=22 guifg=#006000
```

**Comment by taigacute** [comment]
> It is lighter because, by default, the sign uses `DiffAdd`'s foreground colour. Your custom overrides above are not working. Try this:
> 
> ```viml
> highlight GitGutterAdd ctermfg=22 guifg=#006000
> ```


It doesn't work

**Comment by airblade** [comment]
I don't know why not, sorry.

**Comment by taigacute** [comment]
> > It is lighter because, by default, the sign uses `DiffAdd`'s foreground colour. Your custom overrides above are not working. Try this:
> > ```viml
> > highlight GitGutterAdd ctermfg=22 guifg=#006000
> > ```
> 
> It doesn't work

it appeared in insert mode.thanks a lot.  happy new year 
This is a custom in China. We are celebrating the New Year today.

**Comment by taigacute** [comment]
> I don't know why not, sorry.

it doesn't matter。
![git](https://user-images.githubusercontent.com/41671631/52220898-eca92380-28da-11e9-8937-276b369f3573.gif)

**Comment by airblade** [comment]
Happy New Year to you too :)

By the way, how do you make the animated gifs?

**Comment by taigacute** [comment]
> Happy New Year to you too :)
> 
> By the way, how do you make the animated gifs?

[LICEcap](https://www.cockos.com/licecap/) its very small

**Comment by airblade** [comment]
Thanks!

**Comment by taigacute** [comment]
> Thanks!

Should this issue continue to be open? Maybe I should change the title to show that the color is not normal?If you feel that it is not necessary, I will close this issue

**Comment by airblade** [comment]
Let's leave it open for now as a reminder for me.  Maybe I'll have an idea about why your signs aren't updating in insert mode.

Also I don't know why your highlight configuration is being ignored by Vim.  Maybe it's to do when vim-gitgutter is loaded compared to your colourscheme?

**Comment by taigacute** [comment]
It seems to be a problem with the loading of colorscheme, I removed my colorsmeme and it works fine.
![color](https://user-images.githubusercontent.com/41671631/52221885-27ac5680-28dd-11e9-9ef4-c5cb1576eda7.gif)

Regarding the markup, I got it in the inert mode, but it takes a while. Maybe this time is 100s

**Comment by airblade** [comment]
Maybe open an issue on the hybrid_reverse repo?  They might know.

You can see exactly when vim-gitgutter runs by setting `let g:gitgutter_log=1` and tailing the log file you'll find in the directory where vim-gigutter is installed.  You could set `&updatetime` to, say, 3000, and then 50, and watch the difference.

**Comment by taigacute** [comment]
> Maybe open an issue on the hybrid_reverse repo? They might know.
> 
> You can see exactly when vim-gitgutter runs by setting `let g:gitgutter_log=1` and tailing the log file you'll find in the directory where vim-gigutter is installed. You could set `&updatetime` to, say, 3000, and then 50, and watch the difference.

yeah  its right.i will open an issue on hybrid_reverse, i test the time now

**Comment by taigacute** [comment]
I found a very strange thing, when I switch other programs and then switch back to Nvim, it will appear immediately。
![git](https://user-images.githubusercontent.com/41671631/52222740-30059100-28df-11e9-90f3-edb4d152eae3.gif)

**Comment by airblade** [comment]
That looks like update on `FocusGained`:

https://github.com/airblade/vim-gitgutter/blob/fd834e48eed21cc3c3ab66779a2296a16f41cbca/plugin/gitgutter.vim#L215

**Comment by taigacute** [comment]
@airblade  i think i got problem. if  i remove coc. gitgutter it works fine. you can see this pic
![git1](https://user-images.githubusercontent.com/41671631/52467437-81a06b00-2bc0-11e9-90a9-124ec59c74f3.gif)

**Comment by taigacute** [comment]
[coc](https://github.com/neoclide/coc.nvim/issues/414)

**Comment by taigacute** [comment]
#https://github.com/neoclide/coc.nvim/issues/414

**Comment by airblade** [comment]
@taigacute Well done finding the problem – a bug in NeoVim where CursorHoldI is not triggered.

And I'm glad vim-gitgutter works properly for you (without coc).  Hopefully NeoVim / coc will be fixed soon.

In the meantime I'm going to close this because it's not a vim-gitgutter bug.

**Comment by taigacute** [comment]
> @taigacute干得好找到问题 - NeoVim中没有触发CursorHoldI的错误。
> 
> 我很高兴vim-gitgutter适合你（没有coc）。希望NeoVim / coc即将修复。
> 
> 与此同时，我要关闭它，因为它不是一个vim-gitgutter bug。

thanks a  lot

**Comment by taigacute** [comment]
@airblade   this bug is neovim，I got a reply from the coc author。
>It's not caused by coc using CursorHoldI, it happens when rpc channel is created.
You can make vim-gitgutter to implement CursorHoldI itself, instead of relay on vim's autocmd.

what do you think ？

**Comment by airblade** [comment]
I don't want to add code and complexity to work around a NeoVim bug.  I would prefer NeoVim fixed the bug.

**Comment by taigacute** [comment]
all right  thanks

**Comment by taigacute** [comment]
@airblade  
Can I adjust the width of this sign, it is too thin now, I think it may not be a problem with vim-gitgutter，now
![3123](https://user-images.githubusercontent.com/41671631/52710288-f3662380-2fc9-11e9-9a5f-ebd952b509c3.png)

**Comment by airblade** [comment]
That's not a sign which vim-gitgutter would produce by default.  It's either from another plugin or something you configured.

You can find out with these commands:

```viml
:sign place
:sign list
```

**Comment by taigacute** [comment]
@airblade  
This is a headache. The plugin that uses the rpc channel will cause CursorHoldI to not work as expected. The fix of the coc is canceled. It will cause a bug in the coc, so this problem occurs again. Of course it is neovim. Bug, can I trigger gitgutter's CursorHoldI by write a function, How i write this function? I hope to get your help.

**Comment by airblade** [comment]
I would use the TextChangedI autocommand to set/reset a timer which executes the GitGutter command.

**Comment by taigacute** [comment]
That’s great, it’s avoiding this bug.

**Comment by taigacute** [comment]
Hi bro，When do i get updates? as keen as mustard

**Comment by airblade** [comment]
As I said above, I'm not adding code and complicating the plugin to work around a NeoVim bug.
