### ISSUE TITLE
fd834e4 breaks signs in nvim

### ISSUE THREAD

**Issue by ode79** [airblade/vim-gitgutter#582]
> What is the latest commit SHA in your installed vim-gitgutter?
fd834e48eed21cc3c3ab66779a2296a16f41cbca
> What vim/nvim version are you on?
0.3.1 (I have also tested on 0.3.4 and have the same effect). 
> If no signs are showing at all, what does `:echo b:gitgutter.path` give?
Nothing.
> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?
No change.

Checking out afa4f2ddf0fecb37914ec37357636abb18013422 brings back signs.

**Comment by airblade** [comment]
Does `:sign place` list the diff signs you would expect to see?  If so, this is a colour problem.

Having said that, `b:gitgutter.path` should not be empty for a file which should show signs.  But nothing in fd834e4 affects that.

**Comment by ode79** [comment]
`:sign place` shows the below, which is correct.
```
    line=3304  id=3000  name=GitGutterLineAdded
    line=3305  id=3001  name=GitGutterLineAdded
```

I was wrong about what `:echo b:gitgutter.path` gives.
Running it again, it gives the filename of the file I am editing.

**Comment by airblade** [comment]
So the problem is with the signs' colours.  What is your colorscheme?  What do these give? :-

```viml
:verbose highlight DiffAdd
:verbose highlight GitGutterAddDefault
:verbose highlight GitGutterAddAdd
```

**Comment by ode79** [comment]
```
:verbose highlight DiffAdd
DiffAdd        xxx cterm=bold ctermfg=16 ctermbg=121 guibg=DarkBlue
        Last set from ~/.config/nvim/colors/grb256.vim
```
```
:verbose highlight GitGutterAddDefault
GitGutterAddDefault xxx ctermfg=16 guibg=black
        Last set from ~/.config/nvim/plugged/vim-gitgutter/autoload/gitgutter/highlight.vim
```
```
:verbose highlight GitGutterAddAdd
E411: highlight group not found: GitGutterAddAdd
```

**Comment by airblade** [comment]
Sorry, that last one was meant to be `:verbose highlight GitGutterAdd`.

**Comment by ode79** [comment]
```
:verbose highlight GitGutterAdd
GitGutterAdd   xxx links to GitGutterAddDefault
        Last set from ~/.config/nvim/plugged/vim-gitgutter/autoload/gitgutter/highlight.vim
```

**Comment by airblade** [comment]
Thank you.

So the sign for an added line is using the foreground colour from your colorscheme's `DiffAdd` highlight group, which is what it is supposed to do.

The background colour for the sign should be the background colour of the `SignColumn` highlight group.

You have a couple of options if you want to change the signs' colours:

- Either update the colourscheme to use better foreground colours for the `Diff*` highlight groups.
- Or configure the `GitGutter{Add,Change,Delete}` highlight groups in your vimrc.  The commit message for afa4f2d explains how to do that to get vim-gitgutter's previous sign colours.

**Comment by ode79** [comment]
Ok, I have changed the foreground colors and it works fine now.

Thanks
