### ISSUE TITLE
error when loading file not in git

### ISSUE THREAD

**Issue by bon-ami** [airblade/vim-gitgutter#583]
> What is the latest commit SHA in your installed vim-gitgutter?
I have just got the zip of the code.
> What vim/nvim version are you on?

I am not using this now, just keeping it in my pathogen (bundle) directory.
When opening any files not in git, errors pop
`Error detected while processing function <SNR>90_on_bufenter[5]..gitgutter#init_buffer:
line    1:
E118: Too many arguments for function: gitgutter#utility#is_active`
all are using as sth. like "utility#is_active(a:bufnr)" while it seems to declare one parameter.

**Comment by airblade** [comment]
Where did you get the zip from?

**Comment by bon-ami** [comment]
right here, github's "code"

**Comment by airblade** [comment]
I can't reproduce the problem.  What does your version of the `gitgutter#init_buffer(bufnr)` function look like?  It's in `autoload/gitgutter.vim`.

**Comment by bon-ami** [comment]
`function! gitgutter#init_buffer(bufnr)
  if gitgutter#utility#is_active(a:bufnr)
    let p = gitgutter#utility#repo_path(a:bufnr, 0)
    if type(p) != s:t_string || empty(p)
      call gitgutter#utility#set_repo_path(a:bufnr)
      call s:setup_maps()
    endif
  endif
endfunction`

**Comment by bon-ami** [comment]
<addr>function! gitgutter#init_buffer(bufnr)
  if gitgutter#utility#is_active(a:bufnr)
    let p = gitgutter#utility#repo_path(a:bufnr, 0)
    if type(p) != s:t_string || empty(p)
      call gitgutter#utility#set_repo_path(a:bufnr)
      call s:setup_maps()
    endif
  endif
endfunction</addr>

**Comment by airblade** [comment]
Your error message points to the first line of the `init_buffer()` function, i.e. `if gitgutter#utility#is_active(a:bufnr)`, saying the function was called too many arguments.  But that function does indeed take 1 argument.

The only thing I can think of is that perhaps you have a really old version of vim-gitgutter somewhere on your vim's runtime path which is clashing.  But that's grasping at straws.

**Comment by bon-ami** [comment]
Oh I was using a modified compile from vim.org. Now that I've switched back to 8.1.1 from vim.org, an different error occurs, but for same reason, detecting a:bufnr as more than one argument, seemingly. Sorry I do not know the grammar here.
`Error detected while processing function gitgutter#all[9]..gitgutter#process_buffer:`
`line    8:`
`E118: Too many arguments for function: gitgutter#diff#run_diff`
code is `gitgutter#diff#run_diff(a:bufnr, 'index', 0)`
calling `function! gitgutter#diff#run_diff(bufnr, from, preserve_full_diff) abort`
I'm using tens of plugins, only this plugin has this error so far. It worked find on 8.0. So I wonder whether there are some compatibility issues. Thanks a bunch. (no other version of this plugin elsewhere when I run gvim, I am sure.)

**Comment by airblade** [comment]
Weird.  I'm using Vim 8.1 and it works for me.

Is your vimrc online anywhere?  Or a list of the plugins you're using?

All I can suggest is to add some `echom "buffer " a:bufnr` debugging statements to the code just before line 8 of the `process_buffer()` function to see what exactly the values are.

**Comment by bon-ami** [comment]
thank you for quick responses. But since I am not in the need of it right now, I will put this aside.
