### ISSUE TITLE
No live output in neovim

### ISSUE THREAD

**Issue by zubairakram** [airblade/vim-gitgutter#584]
gutter is not showing live output in neovim.
Effect appear after reopening the file.

**Comment by chemzqm** [comment]
I have same issue, the code blocked here:
https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/diff.vim#L71

so gitgutter doesn't work at all.

**Comment by airblade** [comment]
NeoVim version?

**Comment by chemzqm** [comment]
I'm using master of neovim https://github.com/neovim/neovim/commit/9327ea3e5a9b004fc494fd5a3864ad43086cddc9, the problem doesn't exists yesterday.

**Comment by airblade** [comment]
It sounds like something changed in NeoVim.  Can you bisect NeoVim to find the breaking change?

**Comment by zubairakram** [comment]
I upgrade my neovim to ```NVIM v0.3.1``` and everything is working fine.
Thanks @airblade for nice plugin.

**Comment by airblade** [comment]
You're welcome.

**Comment by airblade** [comment]
I think this is caused by https://github.com/neovim/neovim/issues/9675.
