### ISSUE TITLE
Signs don't desappear after commit from nvim-builtin-terminal

### ISSUE THREAD

**Issue by astier** [airblade/vim-gitgutter#587]
> What is the latest commit SHA in your installed vim-gitgutter? 78db200

> What vim/nvim version are you on? nvim v0.3.4

> Related #570

> Steps to reproduce

1. Set up git-repository
```sh
mkdir rep
cd rep
git init
touch file
git add file
git commit -m "Initial commit"
echo bug > file
nvim file
```
2. See the line-added-sign produced by gitgutter
3. Open a nvim-terminal by executing `:te`
4. `git commit -am "Bug incoming"`
5. Switch back to file-buffer `:bn`
6. See that the sign is still there

**Comment by airblade** [comment]
I can't reproduce this.  When I follow your instructions, in step 6 the sign is no longer there.

I'm using nvim v0.3.4 and vim-gitgutter 78db200, just like you.

What does `:au WinLeave` produce?  What does `:echo bufname('')` in the nvim-terminal give?

**Comment by astier** [comment]
It was caused by `set hidden`. I should have tested it on a minimal vimrc before opening an issue. Sorry. Lesson learned. Since I don't know if this is the expected behavior I will let you close the issue.

**Comment by airblade** [comment]
I would never have guessed `set hidden` was the culprit.  And `nohidden` I can reproduce your problem.

This isn't the expected behaviour but I think I have a fix.  Please could you try this?

```diff
diff --git i/plugin/gitgutter.vim w/plugin/gitgutter.vim
index e0b0b92..028f677 100644
--- i/plugin/gitgutter.vim
+++ w/plugin/gitgutter.vim
@@ -213,7 +213,7 @@ augroup gitgutter
   autocmd VimEnter * if winnr() != winnr('$') | call gitgutter#all(0) | endif
 
   autocmd FocusGained,ShellCmdPost * call gitgutter#all(1)
-  autocmd WinLeave * if bufname('') =~ '^term://' | call gitgutter#all(1) | endif
+  autocmd WinLeave * nested if bufname('') =~ '^term://' | call gitgutter#all(1) | endif
 
   if exists('##VimResume')
     autocmd VimResume * call gitgutter#all(1)
```

**Comment by airblade** [comment]
Actually I think this is neater:

```diff
diff --git i/plugin/gitgutter.vim w/plugin/gitgutter.vim
index e0b0b92..73dc289 100644
--- i/plugin/gitgutter.vim
+++ w/plugin/gitgutter.vim
@@ -213,7 +213,7 @@ augroup gitgutter
   autocmd VimEnter * if winnr() != winnr('$') | call gitgutter#all(0) | endif
 
   autocmd FocusGained,ShellCmdPost * call gitgutter#all(1)
-  autocmd WinLeave * if bufname('') =~ '^term://' | call gitgutter#all(1) | endif
+  autocmd BufLeave term://* call gitgutter#all(1)
 
   if exists('##VimResume')
     autocmd VimResume * call gitgutter#all(1)
```

**Comment by astier** [comment]
I tried the last solution and it works for me.

**Comment by airblade** [comment]
Thanks for confirming.
