### ISSUE TITLE
allow showing of branch name on sublime 3.2

### ISSUE THREAD

**Issue by maddanio** [airblade/vim-gitgutter#598]
I actually switch off the git integration of 3.2, because i like the gutter one better, the status bar tends to show only a commit hash, and i dont like that it opens the costly sublime merge upon click.
So I would really like if I can show the branch name also on 3.2 :)

**Comment by airblade** [comment]
This is the Vim version of gitgutter, not the Sublime one.

**Comment by maddanio** [comment]
oops, my bad
