### ISSUE TITLE
Startup is very slow

### ISSUE THREAD

**Issue by DroneKid** [airblade/vim-gitgutter#600]
Hi!

The startup is very slow on the latest master. It is blazingly fast if I roll back to `932ffaca092cca246b82c33e23d2d3a05e192e08`. It looks like `5bfe5b92099e0d332a7ca26c0263fab509ee9617 Big refactor` had introduced something to slow it down.

Slow startup is only experienced if I pass a file to vim at command line.

> What is the latest commit SHA in your installed vim-gitgutter?
`7eeea63e62b1cc088a75c7a7c244fc774d82e5bb`

> What vim/nvim version are you on?
vim 8.1.1000

Cheers,
A.

**Comment by airblade** [comment]
Dup of #599 (you opened two identical issues).
