### ISSUE TITLE
Problem of using j in normal mode

### ISSUE THREAD

**Issue by NiaBie** [airblade/vim-gitgutter#601]
I add this function to my `.vimrc` to let my vim come back to the position where I leave before:
```
au BufEnter * call MyView()
fun! MyView()
  if (expand("%") != "")
	silent loadview
  	au VimLeave * silent mkview
  endif
endfun
```
If I push the key `j` in normal mode, it will trigger a keymap and had a small delay. And this problem only happens in the files which have been changed. I don't know which key maps I have triggered.

**Comment by airblade** [comment]
I can't quite see how this relates to vim-gitgutter.  Anyway, what does `:verbose nmap j` produce?

**Comment by NiaBie** [comment]
n  jhs          @<Plug>GitGutterStageHunk
n  jhu          @<Plug>GitGutterUndoHunk
n  jhp          @<Plug>GitGutterPreviewHunk

**Comment by airblade** [comment]
So when you press `j` Vim has to wait for a while to see if you're going to press `h` next.

I suggest choosing a different first letter.  Personally I use `g`.

**Comment by NiaBie** [comment]
I found that I used to map `j` to `<leader>` and this setting has been deleted several days before, I don't know this mapping will still exist...... and I don't know how to find the key maps. Thank you for your reply.

**Comment by airblade** [comment]
Type `:nmap` to find all the normal mode mappings.  `:help map.txt` explains it all.

I'm closing this because the plugin isn't doing anything wrong.  You can get good help for maps on https://vi.stackexchange.com.
