### ISSUE TITLE
Signs are not shown when using git-crypt

### ISSUE THREAD

**Issue by reneatzi** [airblade/vim-gitgutter#602]
> What is the latest commit SHA in your installed vim-gitgutter?
7eeea63

> What vim/nvim version are you on?
NVIM v0.3.4

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?
{'hunks': [[3, 0, 4, 1], [5, 1, 5, 0], [12, 2, 11, 0], [15, 1, 12, 0], [30, 0, 28, 7], [44, 1, 48, 1]], 'path': 'Program.cs'
, 'summary': [8, 1, 4], 'other_signs': [], 'dummy_sign': 0, 'gitgutter_signs': {}, 'tick': 3}

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?
No

---
Everything works fine, except when the files are encrypted with https://github.com/AGWA/git-crypt

**Comment by airblade** [comment]
This sounds like #563: vim-gitgutter relies on being able to `git show :repo_path/to/file` and diff the output with the buffer's contents.  If files are encrypted in the index, this isn't going to work.

**Comment by blueyed** [comment]
Maybe allowing to customize the command would help here?

**Comment by blueyed** [comment]
..but that could also be done by injecting a custom `git` wrapper I suppose.

**Comment by airblade** [comment]
I think this is out of scope of the plugin, for now at least.
