### ISSUE TITLE
Support for multiple signcolumn in neovim

### ISSUE THREAD

**Issue by ratheesh** [airblade/vim-gitgutter#603]
Support for multiple signcolumn is merged into the neovim `master` branch today. It will be really helpful if gitgutter support this option to display signs on the dedicated sign column to avoid clashes with `marks` and other plugins like `ALE`.

**Comment by airblade** [comment]
I looked at https://github.com/neovim/neovim/commit/36762a00a8010c5e14ad4347ab8287d1e8e7e064.  I can't see anything that plugins need to do – it seems to me that neovim handles everything.

**Comment by blueyed** [comment]
Yeah, looks like it - maybe @ratheesh confused this with the recent Vim feature of sign groups / priorities?

**Comment by airblade** [comment]
FYI #576 covers sign groups / priorities.

**Comment by ratheesh** [comment]
@airblade, @blueyed. Thanks for the clarification. Closing this.
