### ISSUE TITLE
delete/modified content can't see

### ISSUE THREAD

**Issue by xjxia** [airblade/vim-gitgutter#604]
![image](https://user-images.githubusercontent.com/3295317/54905804-d99af300-4f1c-11e9-976d-e7a1a392f34c.png)

--git diff 
![image](https://user-images.githubusercontent.com/3295317/54905817-e28bc480-4f1c-11e9-9c3b-0d477fb06781.png)

**Comment by xjxia** [comment]
let g:gitgutter_async = 0
 highlight GitGutterAdd    guifg=#009900 ctermfg=2
 highlight GitGutterChange guifg=#bbbb00 ctermfg=3
 highlight GitGutterDelete guifg=#ff2222 ctermfg=1
 let g:gitgutter_sign_removed_first_line = '^^'
 let g:gitgutter_sign_modified_removed = 'ww'
 let g:gitgutter_sign_removed = '-'
 let g:gitgutter_max_signs = 500

**Comment by airblade** [comment]
I don't understand what is supposed to be wrong here.

**Comment by xjxia** [comment]
> I don't understand what is supposed to be wrong here.

In vim mode，I cann't see the delete row below 
- global : true 
- tag: 0.3.0
but by git diff cli, I can see the contents I had modified or deleted.

**Comment by airblade** [comment]
What is vim mode?

You can't see the deleted rows because they are not in the buffer.  If you want to see the actual diff, use the hunk preview functionality, i.e. `<leader>hp` (by default).  There's more info in the [readme](https://github.com/airblade/vim-gitgutter#hunks).

Does that make sense?

**Comment by xjxia** [comment]
> preview

ok，I will try this later，thank you
