### ISSUE TITLE
Feature request: Have sign column always appear but only in git folders

### ISSUE THREAD

**Issue by Jont828** [airblade/vim-gitgutter#608]
I noticed how you can make the sign column always show using your .vimrc, but I was hoping there would be a way to make it not show in non-git repositories and always show in git repositories. 

I personally prefer to have the sign column but not have my code shift over as the sign column appears when I start typing when the file is up to date, so I set it to always show, but it's a bit necessary to do that on files that aren't tracked by git.

**Comment by airblade** [comment]
The plugin doesn't do this but you could have a `BufEnter` event which checks whether the file is in a git repo and updates the `signcolumn` option appropriately.
