### ISSUE TITLE
Signs do not disappear after commit from another tmux-window

### ISSUE THREAD

**Issue by astier** [airblade/vim-gitgutter#612]
## General Information

> What is the latest commit SHA in your installed vim-gitgutter?

7eeea63

> What vim/nvim version are you on?

NVIM v0.3.5

## Problem

After modifying a file in nvim in a tmux-window the gitgutter-signs do show up. However, if I switch to another tmux-window add/commit the changes and then switch back to the window with the opened file the signs do not disappear. I have to run :GitGutter manually.

**Comment by airblade** [comment]
It sounds like `FocusGained` is not being triggered:

https://github.com/airblade/vim-gitgutter/blob/7eeea63e62b1cc088a75c7a7c244fc774d82e5bb/plugin/gitgutter.vim#L221-L223

Have you tried the suggestions in the [README](https://github.com/airblade/vim-gitgutter#when-signs-dont-update-after-focusing-vim)?

**Comment by astier** [comment]
I solved it by setting `set -g focus-events on` in my tmux.conf
Thank you for your help.

**Comment by airblade** [comment]
Glad you solved it.  I updated the docs with your solution.
