### ISSUE TITLE
sleep causes problems with other plugins

### ISSUE THREAD

**Issue by bhcleek** [airblade/vim-gitgutter#613]
Using `sleep` can cause races in handling async job output. There are two instances of `sleep` in gitgutter. They could both be replaced with `time_start` instead, which should make sure that Vim and Neovim don't try processing async job output in multiple callbacks concurrently.

refs:
* https://github.com/fatih/vim-go/issues/2274#issuecomment-490647086
* https://github.com/neovim/neovim/issues/10018

**Comment by bfredl** [comment]
For the `sleep 5m` in `gitgutter#diff#run_diff`, a safe alternative would be to `jobwait()` the job that is expected to set the `path` variable.

**Comment by airblade** [comment]
@bfredl Thanks for the suggestion, though I don't know what the equivalent for vim would be.

I'm planning to rearrange the code to eliminate the `sleep`.

**Comment by airblade** [comment]
The `sleep` has been eliminated in 064a3d6.
