### ISSUE TITLE
Missing :endwhile,  Missing :endif

### ISSUE THREAD

**Issue by decentral1se** [airblade/vim-gitgutter#615]
> What is the latest commit SHA in your installed vim-gitgutter?

e5936a22cfd2e25893e2ac34af4b0afdec1e36f5.

> What vim/nvim version are you on?

```
➜  vim-gitgutter (master) ✔ nvim --version
NVIM v0.3.2-912-g684c7d922
Build type: RelWithDebInfo
```

---

I see with `:messages` and on startup:

```
Error detected while processing function <SNR>31_on_bufenter[6]..gitgutter#process_buffer[8]..gitgutter#diff#run_diff:
line    2:                                                                                                                                    
E170: Missing :endwhile
Error detected while processing function <SNR>31_on_bufenter:
line    6:
E171: Missing :endif
```

**Comment by decentral1se** [comment]
Ah, important to mention, I do see gutter indicators! So, not totally broken ...

**Comment by airblade** [comment]
I can't reproduce this on NVIM 0.3.4.

The error message points to this line:

https://github.com/airblade/vim-gitgutter/blob/e5936a22cfd2e25893e2ac34af4b0afdec1e36f5/autoload/gitgutter/diff.vim#L72

Maybe related to #613?

**Comment by decentral1se** [comment]
Aha! I upgraded to v0.3.5 but it is still present ...

**Comment by blueyed** [comment]
Yeah, there is likely an error elsewhere, and then the function is aborted there.

Does it happen always?  How to reproduce it?

Try https://github.com/airblade/vim-gitgutter/pull/593 (just rebased).

**Comment by decentral1se** [comment]
Ah, thanks. I will try to test out that patch soon. I've noticed that this is actually just happening when I am loading my our init.vim configuration file. Strange. The configuration file is over at https://git.coop/decentral1se/dotfiles/blob/master/roles/restore/files/neovim/init.vim.

**Comment by decentral1se** [comment]
Aha, after trying #593, I saw in `:messages`:

```
Error detected while processing function <SNR>120_on_exit_clean[2]..<SNR>120_set_clean_variables:
line    5:
E94: No matching buffer for /home/decentral1se/.config/nvim/init.vim
```

**Comment by airblade** [comment]
The `sleep` that was hiding your problem has been eliminated as of 064a3d6.

Your `on_exit_clean` and `set_clean_variables` aren't from gitgutter.

**Comment by decentral1se** [comment]
Aha, thanks! I am now left with these remaining errors :)
