### ISSUE TITLE
What does this symbol ("[") stand for?

### ISSUE THREAD

**Issue by unihon** [airblade/vim-gitgutter#616]
![image](https://user-images.githubusercontent.com/42078581/58376938-973b7400-7fa8-11e9-87f8-88c1f15c9cb6.png)

**Comment by unihon** [comment]
'[' is stand for remove line 1 and line 3（original content）?

**Comment by airblade** [comment]
It means you have deleted lines at the start of the file and also between lines 1 and 2 in your screenshot.

GitGutter uses an underscore to show lines deleted after/below a line.  However that doesn't work if lines are deleted at the start of the file: there's no "line 0" to place an underscore beside.  So in that case GitGutter uses an "overscore" on line 1.  But then there's a problem if lines have been deleted above and below line 1.  You can only show one sign per line, so GitGutter uses `[` to try to mimic an overscore and an underscore.
