### ISSUE TITLE
[Feature Request] Hunks QuickFix/Location List?

### ISSUE THREAD

**Issue by ChrisPenner** [airblade/vim-gitgutter#617]
Hey there! Love GitGutter; use it all the time. Great for jumping around changes in huge files!

Not sure if this is related to your vision for gitgutter at all; but I think it'd be very interesting to have a command which populates your quickfix/location list with the locations of all your changed files or hunks! 

That said; I can probably whip up a search using FZF to do the files part, but I still think it could be handy to see a single list of all changes across a project.

Cheers!

**Comment by airblade** [comment]
That's an interesting idea.

I imagine you would want it to find all changed files, not just those which happen to be open in Vim.

I'll add it to the list but I can't guarantee when I'll get to it.

**Comment by somini** [comment]
If this is buffer-specific, should it populate the location list instead? The quickfix window is global.

**Comment by airblade** [comment]
I don't see it as buffer specific: it finds changes across all files in the repo.

I suppose I could add a similar thing to load changes in the current buffer into the location list.

**Comment by somini** [comment]
> I don't see it as buffer specific: it finds changes across all files in the repo.

That's right, I was testing with changes on a single file. Disregard this.
