### ISSUE TITLE
Errors when plugin is loaded

### ISSUE THREAD

**Issue by cbtlsl** [airblade/vim-gitgutter#618]
When I start vim I am seeing the following errors from gitgutter:

```
Error detected while processing function <SNR>114_on_bufenter..gitgutter#process_buffer:
line 7:
E118: Too many arguments for function: function
E116: Invalid arguments for function s:setup_path(A:bufnr, function('gitgutter#process_buffer', [a:bufnr, a:force]))
E15: Invalid expression s:setup_path(a:bufnr, function('gitgutter#process_buffer, [a:bufnr, a:force]))
Press ENTER or type command to continue
Error detected while processing function gitgutter#all..gitgutter@process_buffer:
line 7:
E118: Too many arguments for function; function
Press ENTER or type command to continue

```
Also, everytime that the plugin tries to update the signs I get these errors:

```
Error detected while processing function gitgutter@process_buffer:
line 7:
E118: Too many arguments for function: function
Press ENTER or type command to continue
```

> What is the latest commit SHA in your installed vim-gitgutter?
6affbc9

> What vim/nvim version are you on?
7.4

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

**Comment by airblade** [comment]
What patchlevel is your Vim 7.4 at?  I expect it doesn't support function partials yet.

**Comment by cbtlsl** [comment]
gvim --version says:

Included patches: 1-207, 209-629
--
Brent Loertscher
brent@loertscher.org
480-570-3874

**Comment by mooreniemi** [comment]
Also seeing this after latest update:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 31 2018 23:07:42)
Included patches: 1-898, 985, 8056
Compiled by root@apple.com
```

**Comment by airblade** [comment]
I'll try to fix this but in the meantime you may want to consider upgrading to a more recent Vim.  7.4 is pretty old now :)

**Comment by cbtlsl** [comment]
Thanks.  I work in a corporate environment on a server and have no control
over the version of vim that is available to me.

--
Brent Loertscher
brent@loertscher.org
480-570-3874

**Comment by tuckerrc** [comment]
I am also seeing this issue. It looks like it was introduced in this commit 064a3d6b10622f6fabe524ef3183668732f9fd06. 

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 30 2018 19:56:57)
    Included patches: 1-160, 399, 402-403, 1099
    Modified by <bugzilla@redhat.com>
    Compiled by <bugzilla@redhat.com>


I am on a CentOS 7 machine so this may be an issue for quite a few users

**Comment by unihon** [comment]
I have a similar problem.

```
CentOS Linux release 7.6.1810 (Core)
VIM - Vi IMproved 7.4
git version 1.8.3.1
```

When open a file with vim, the following error will occur.

![image](https://user-images.githubusercontent.com/42078581/58616893-5ec1d000-82f1-11e9-89c1-216aabf53cc2.png)

**Comment by airblade** [comment]
Aha, found it: allowing `function()` to take arguments was added in Vim [7.4.1559](https://github.com/vim/vim/commit/1735bc988c546cc962c5f94792815b4d7cb79710).

Now for the fix...

**Comment by airblade** [comment]
Please can you try this patch?

```diff
diff --git i/autoload/gitgutter.vim w/autoload/gitgutter.vim
index affaed4..3a56573 100644
--- i/autoload/gitgutter.vim
+++ w/autoload/gitgutter.vim
@@ -27,7 +27,12 @@ function! gitgutter#process_buffer(bufnr, force) abort
 
     call s:setup_maps(a:bufnr)
 
-    let how = s:setup_path(a:bufnr, function('gitgutter#process_buffer', [a:bufnr, a:force]))
+    if has('patch-7.4.1559')
+      let Callback = function('gitgutter#process_buffer', [a:bufnr, a:force])
+    else
+      let Callback = ['gitgutter#process_buffer', [a:bufnr, a:force]]
+    endif
+    let how = s:setup_path(a:bufnr, Callback)
     if [how] == ['async']  " avoid string-to-number conversion if how is a number
       return
     endif
diff --git i/autoload/gitgutter/utility.vim w/autoload/gitgutter/utility.vim
index 424b3eb..d4d2e82 100644
--- i/autoload/gitgutter/utility.vim
+++ w/autoload/gitgutter/utility.vim
@@ -121,7 +121,11 @@ function! s:set_path_handler.out(buffer, path) abort
   let path = s:strip_trailing_new_line(a:path)
   call gitgutter#utility#setbufvar(a:buffer, 'path', path)
 
-  call self.continuation()
+  if type(self.continuation) == type([])
+    call call(self.continuation[0], self.continuation[1])
+  else
+    call self.continuation()
+  endif
 endfunction
 
 function! s:set_path_handler.err(buffer) abort
```

**Comment by unihon** [comment]
OK! This patch can solve the problem I mentioned earlier [(Details)](https://github.com/airblade/vim-gitgutter/issues/618#issuecomment-497239016).  Thank you very much! And I hope it will appear in the new version.😆

**Comment by airblade** [comment]
Should be fixed now.

**Comment by cbtlsl** [comment]
Thanks, that fixed the error that I was seeing.

--
Brent Loertscher
brent@loertscher.org
480-570-3874
