### ISSUE TITLE
Easy to integrate diff stats into status line - How?

### ISSUE THREAD

**Issue by mclang** [airblade/vim-gitgutter#626]
Hello

The documentation says that `vim-gitgutter` is _Easy to integrate diff stats into status line_, but I cannot find how?

I found [this](https://github.com/zenbro/dotfiles/blob/d3f4bd3136aab297191c062345dfc680abb1efac/.nvimrc#L67) example, but it doesn't work.

**Comment by airblade** [comment]
You just need a call to `GitGutterGetHunkSummary()` in your `statusline`.  For example:

```
vim -c 'set statusline+=%{string(GitGutterGetHunkSummary())}' path/to/file
```

Here's another example with a slightly prettier output: [gist](https://gist.github.com/airblade/c05b8104a1ec80ea59a6b9331b9fd23c).

**Comment by mclang** [comment]
Okay, that works.

So the problem with the example was probably in the check if `GitGutterGetHunkSummary()` exists...

Thanks for the quick reply!
