### ISSUE TITLE
signs: might clobber existing signs / allow multiple signs per line

### ISSUE THREAD

**Issue by blueyed** [airblade/vim-gitgutter#627]
There is code to not clobber existing signs for a line.

But

1. Neovim supports displaying multiple signs per line (e.g. `set signcolumn=auto:3`), so that should be optional

2. it uses incrementing IDs, so eventually might use an already existing ID from another plugin, and then would clobber that sign (regardless of the line it is being used in)

As for 2., AFAIK it is not necessary really to have different IDs per sign, i.e. gitgutter could just use a single ID (or maybe per sign type), as long as it unplaces all signs.

**Comment by airblade** [comment]
Regarding (2), originally gitgutter always removed all signs then added the new ones – but Vim was way too slow at placing and unplacing signs.  So gitgutter effectively diffs the signs when it needs to update them, removing just the signs it needs to.  This requires each sign to have its own id.

Vim is much faster now at placing/unplacing signs thanks to some speed-up work (done around January this year, if I recall).  I don't know if it's faster enough now to return to the original workflow, but as quite a few people use linux distros with older Vims which don't have the faster sign code, I don't want to throw away the current workflow.

I agree there's nothing to stop gitgutter using an id from another plugin, but I don't think there's anything one can do about that.  Maybe the new(ish) sign groups help?

**Comment by airblade** [comment]
Regarding (1), I agree that with recent Neovims there's no need for gitgutter to worry about non-gitgutter signs.  Do you know when the `auto:3` syntax was introduced?  Then I can branch the code's behaviour accordingly.

**Comment by airblade** [comment]
Ah, I see it's in https://github.com/neovim/neovim/commit/36762a00a8010c5e14ad4347ab8287d1e8e7e064.  Do you know of a way to test for this patch in vim script?

In the meantime I'll merge #565.

**Comment by blueyed** [comment]
> Do you know of a way to test for this patch in vim script?

You can use `has('nvim-0.4.0')` - while it might not have that patch then really with a development build before it, the released version will have it, and you can assume that a recent development build is used when using the development version.

**Comment by airblade** [comment]
Thanks.  With fef14f1, are you happy to close this issue?  I realise only (1) has been addressed but I don't see what can be done about (2).

**Comment by airblade** [comment]
Commit cbaa22e puts signs into the `gitgutter` group and allows (Neo)Vim to handle the id generation and assignment, which addresses (2).
