### ISSUE TITLE
feature request git-gutter support for yadm dot file management

### ISSUE THREAD

**Issue by hholst80** [airblade/vim-gitgutter#628]
I think we need to be able to specify the `--git-dir` option in some way to git-gutter to pick up that the files in the current directory are indeed version controlled.

Sources:

https://yadm.io/#

https://www.atlassian.com/git/tutorials/dotfiles

**Comment by airblade** [comment]
The [README](https://github.com/airblade/vim-gitgutter#extra-arguments-for-git-when-running-git-diff) explains how to do exactly this.

**Comment by hholst80** [comment]
Explains how to setup git-dir yes, but that is not sufficient it turns out. 

```
236.140702 cd /home/holst && git ls-files --error-unmatch --full-name -z -- .vimrc
```

I don't see any trace of the `--git-dir=/home/holst/.yadm/repo.git` I put into vimrc.

**Comment by hholst80** [comment]
I think what we really want to have here is a new default buffer variable called `b:gitgutter_git_dir` that is empty by default but IF it is set it prepends `--git-dir=...` to the git argument.

Indeed, we want to fix the `g:gitgutter_git_args` as shown here as well.

https://github.com/hholst80/vim-gitgutter/commits/master

**Comment by airblade** [comment]
Good point, not all the `git` calls were using `g:gitgutter_git_args`.  They do as of dc3c0dc.

I'm reluctant to add a special `b:gitgutter.git_dir` variable because we can already handle this situation with the general `g:gitgutter_git_args`, and it would set a precedent of adding special variables for all the different options git accepts.

**Comment by blueyed** [comment]
I think using the one from vim-fugitive would be good as a default - it gets updated there for example with `:e` after `:lcd` (i.e. if you go to a submodule / separate git project in a subdirectory).
