### ISSUE TITLE
Don't change register contents when undoing hunks

### ISSUE THREAD

**Issue by wellle** [airblade/vim-gitgutter#629]
> What is the latest commit SHA in your installed vim-gitgutter?

dc3c0dc

> What vim/nvim version are you on?

NVIM v0.3.5

----

Steps to reproduce:
1. Make a change so a gitgutter sign appears
2. Yank some text to the default register
3. Undo the hunk (`\hu`)
4. Paste from the default register

It should paste the text you yanked earlier. But instead if pastes some text related to the hunk you just undid.

**Comment by airblade** [comment]
Does this fix it for you?

```diff
diff --git i/autoload/gitgutter/hunk.vim w/autoload/gitgutter/hunk.vim
index e24dc20..6537a8d 100644
--- i/autoload/gitgutter/hunk.vim
+++ w/autoload/gitgutter/hunk.vim
@@ -240,10 +240,10 @@ function! s:undo(hunk_diff)
   if removed_only
     call append(lnum, lines)
   elseif added_only
-    execute lnum .','. (lnum+len(lines)-1) .'d'
+    execute lnum .','. (lnum+len(lines)-1) .'d _'
   else
     call append(lnum-1, lines[0:hunk[1]])
-    execute (lnum+hunk[1]) .','. (lnum+hunk[1]+hunk[3]) .'d'
+    execute (lnum+hunk[1]) .','. (lnum+hunk[1]+hunk[3]) .'d _'
   endif
 endfunction
 ```

**Comment by wellle** [comment]
Yes it does 🎉

**Comment by airblade** [comment]
🍻
