### ISSUE TITLE
BUG：airline status overlap

### ISSUE THREAD

**Issue by arthurkiller** [airblade/vim-gitgutter#633]
> What is the latest commit SHA in your installed vim-gitgutter?
91471746fe687ee867877508dfd809460dab5698

> What vim/nvim version are you on?
version 8.1.1450

gitgutter works with `vim-airline` and status are not shown correctly. 

![image](https://user-images.githubusercontent.com/11133870/60789036-b117cb80-a190-11e9-9f7b-28c5515a9018.png)

![image](https://user-images.githubusercontent.com/11133870/60789056-bb39ca00-a190-11e9-9112-72805e38ce89.png)

**Comment by airblade** [comment]
I think this is a vim-airline issue because vim-gitgutter hasn't changed the way it exposes the diff stats.
