### ISSUE TITLE
Key mapping set only on first buffer when starting vim with `-o`

### ISSUE THREAD

**Issue by odormond** [airblade/vim-gitgutter#634]
> What is the latest commit SHA in your installed vim-gitgutter?

91471746fe687ee867877508dfd809460dab5698

> What vim/nvim version are you on?

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 20 2019 14:53:30)
Included patches: 1-1575

When starting vim with multiple files and the `-o` (or `-O`) option, only the first buffer get the mapping set properly.

In my understanding, this is due to `VimEnter` autocomand calling `gitgutter#all(0)` which will eventually call `s:setup_maps(bufnr)` for each buffer. But the current buffer is always the first one (as noted at the top of `gitgutter#process_buffer`) so the checks `hasmapto()` returns that they found a mapping (the one from the first buffer which is still the current one). Therefore the invocation of `nmap` and friends are skipped but that would not have worked anyway as they define buffer local mapping and the current buffer is still the first. And finally `s:setup_maps` calls `gitgutter#utility#setbufvar(a:bufnr, 'mapped', 1)` which will prevent any further invocation of `s:setup_maps` from doing anything so even when you really switch to the other buffer the mapping never get setup.

Here is a proposed patch to fix it by switching to each buffer before calling `gitgutter#process_buffer`:

```diff
diff --git a/autoload/gitgutter.vim b/autoload/gitgutter.vim
index cc6f7cf..8e3a3fb 100644
--- a/autoload/gitgutter.vim
+++ b/autoload/gitgutter.vim
@@ -5,11 +5,16 @@ let s:t_string = type('')
 function! gitgutter#all(force) abort
   let visible = tabpagebuflist()
 
+  let saved_switchbuf = &switchbuf
+  set switchbuf=useopen,usetab
+  let saved_current_buffer = bufnr('')
+
   for bufnr in range(1, bufnr('$') + 1)
     if buflisted(bufnr)
       let file = expand('#'.bufnr.':p')
       if !empty(file)
         if index(visible, bufnr) != -1
+          exec bufnr "buffer"
           call gitgutter#process_buffer(bufnr, a:force)
         elseif a:force
           call s:reset_tick(bufnr)
@@ -17,6 +22,8 @@ function! gitgutter#all(force) abort
       endif
     endif
   endfor
+  exec saved_current_buffer "buffer"
+  let &switchbuf = saved_switchbuf
 endfunction
 
 
```

I haven't tested it with tabs as I'm not used to them but it works fine without them.

**Comment by airblade** [comment]
Thanks for the bug report – much appreciated.

I went with a different solution because gitgutter avoids ever switching to a different buffer, to avoid side-effects.  Instead we set the maps only when entering a buffer.
