### ISSUE TITLE
How to show the staged file first

### ISSUE THREAD

**Issue by fenghse** [airblade/vim-gitgutter#635]
> What is the latest commit SHA in your installed vim-gitgutter?

9147174 - (HEAD -> master, origin/master, origin/HEAD) Avoid asynchronous job while vim is starting. (12 days ago, 20190701-112445) (Andy Stewart, Andy Stewart)

> What vim/nvim version are you on?

NVIM v0.3.8

Now, the Gstatus show the untracked file first, then unstaged. How can it turn it to the git command order, staged first, then changes not staged and finally untracked.

**Comment by airblade** [comment]
Gstatus is a Fugitive command, not a GitGutter one.

**Comment by fenghse** [comment]
Sorry that I filed on a wrong repo. Is that possible to move the issue to a different repo?

**Comment by airblade** [comment]
Just open a new one.
