### ISSUE TITLE
Error occurred when open a file 

### ISSUE THREAD

**Issue by drazde** [airblade/vim-gitgutter#636]
> What is the latest commit SHA in your installed vim-gitgutter?
SHA-1: 91471746fe687ee867877508dfd809460dab5698

> What vim/nvim version are you on?
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 23:02:29)
MS-Windows 64-big GUI version with OLE support

SO: Windows 10

When I open a file, vim give me the error under. 
If I remove the plugin I have no problem

Seems to be an error opening temporary file

![immagine](https://user-images.githubusercontent.com/2643448/61380057-faf76480-a8a8-11e9-8670-02f72b01aaf6.png)

**Comment by airblade** [comment]
This means Vim couldn't execute a `system()` call but doesn't give any hint why not.

Has your Vim been open for several days?  It could be that the OS cleaned up the temporary directory Vim had been using.

**Comment by airblade** [comment]
Closing because there's nothing I can really do without further information – but let me know if you still have this problem and, if so, whether it's every time or just sometimes.
