### ISSUE TITLE
Neovim + vim-plug + gitgutter

### ISSUE THREAD

**Issue by wave-blessed** [airblade/vim-gitgutter#637]
Hello.
I just try to lern vin/neovim and have tried to use gitgutter also (I love git). I install any vim addons by vim-plug manager. `Vim + vim-plug + gitgutter` work perfectly, but if I try install gitgutter to neovim, I see the next things:
* After `:PlugInstall` plugin works.
* After restarting neovim plugin doesn't work like it doesn't exist. `:GitGutter` neovim says it's not an editor command. Etc.

After manual install gitgutter to neovim it works. But settings in init.vim like this — do not.
`let g:gitgutter_sign_added = '✚'`
`let g:gitgutter_sign_removed = '✘'`
`let g:gitgutter_sign_modified = '❖'`
`let g:gitgutter_sign_modified_removed = '➤'`

I don't know who is wrong: neovim, vim-plug or gitgutter. What to do?

nvim.exe x64 latest, vim-plug latest, gitgutter latest.

**Comment by blueyed** [comment]
> After manual install gitgutter to neovim it works

What is "manual install"?

Sounds like an issue with the plugin manager - not a vim-gitgutter issue.

(I am using vim-plug myself, so that should work in general)

In Neovim, see `:checkhealth`, and also `:scriptnames` maybe to see what is going on.

**Comment by wave-blessed** [comment]
Manual install means unpack autoload and plugin folders from vim-gitgutter-master.zip to \share\nvim\runtime.

`:checkhealth` shows error with python2 (doesn't installed) and two warnings about ruby and node (doesn't installed).

`:scriptnames` doesn't show any gitgutter scripts if gitgutter installed by vim-plug but does if gitgutter installed manually.

> Sounds like an issue with the plugin manager - not a vim-gitgutter issue.
Ok, agree. Thanks.

**Comment by airblade** [comment]
> :scriptnames doesn't show any gitgutter scripts if gitgutter installed by vim-plug but does if gitgutter installed manually.

This sounds like a problem with how you're using vim-plug.  vim-gitgutter doesn't have any unusual installation requirements.
