### ISSUE TITLE
E475: Invalid argument: numhl=

### ISSUE THREAD

**Issue by vhoyer** [airblade/vim-gitgutter#639]
> What is the latest commit SHA in your installed vim-gitgutter?

6c320c71c5a56e08d8313c9c188d2a64523bfb8d

> What vim/nvim version are you on?

```
NVIM v0.3.2-631-g14ae39453
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -
DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/a
uto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-dd9e6418-f62d-4de9-a757-24cfda2156db

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```

> What error are you having?

Error detected while processing function gitgutter#highlight#define_signs[12]..<SNR>23_define_sign_line
nr_highlights:
line   10:
E475: Invalid argument: numhl=

**Comment by airblade** [comment]
@delphinus How would you suggest fixing this?  It's your code ;)

**Comment by delphinus** [comment]
Neovim has started to support the `numhl` feature in v0.3.2 release.

https://github.com/neovim/neovim/releases/tag/v0.3.2

And I has written the code to check [here][here]. It detects this feature will be enabled when Neovim returns he version is v0.3.2.

[here]: https://github.com/delphinus/vim-gitgutter/blob/83d4f715dd85d499b1805f3d3431179b981c58e4/autoload/gitgutter/highlight.vim#L174

This is the problem. Neovim includes the `numhl` feature on https://github.com/neovim/neovim/commit/bddcbbb5716a005001da3bacb4c1df4ae05e51bc (at 2018-10-13 19:33 +0200), but @vhoyer 's Neovim is on https://github.com/neovim/neovim/commit/14ae394532aae5e1be3b20c0ade98b9d7625ae4b (at 2018-10-02 15:10 +0200), that is NOT the release version of v0.3.2.

There are two solutions for this.

1. Fix the code to check Neovim is not v0.3.2 but v0.3.3.
2. We request @vhoyer to rebuild Neovim (sorry!)

@airblade Which do you prefer? If you choose the plan 1, I will p-r for that.

**Comment by vhoyer** [comment]
it you want my opinion, we shouldn't have any broken code in the repo 🤷🏼, but I can rebuild no problem.(yet, you should probably still fix it)

**Comment by airblade** [comment]
Is there a way to distinguish a released Neovim release from a "pre-release" release?  (Hope that makes sense.)

If not, I'd probably add a `try` / `catch /E475/` just inside the `if` / `endif`.

**Comment by delphinus** [comment]
AFAIK, there's no method to know that.

> If not, I'd probably add a try / catch /E475/ just inside the if / endif.

That's a good idea. I'll send PR with this.

**Comment by delphinus** [comment]
I did in #641.

**Comment by airblade** [comment]
@vhoyer Thanks for reporting this.

@delphinus Thanks for fixing it.

**Comment by blueyed** [comment]
@vhoyer 
I think it is better to check the version, and would argue that it is OK to assume that the latest development version is used (i.e. you are following its development then / update it).
Is there a reason you are using NVIM v0.3.2-631-g14ae39453 specifically?  (i.e. why don't you use 0.3.8, or 0.4.0-dev?)

I think it is OK to keep the current method now (try/catch), but this adds boilerplate, which I am usually avoiding with own plugins - therefore I'm wondering about how it comes to it.. :)

**Comment by vhoyer** [comment]
oh, now I got what was happening, thanks @blueyed. I didn't realize I was using an development version, that I remember, I think I just did an apt install, but I could be wrong. Well, now that it is already in master, so be it, sorry for the trouble. thanks for the attention.

**Comment by airblade** [comment]
> I think it is better to check the version, and would argue that it is OK to assume that the latest development version is used (i.e. you are following its development then / update it).

Sounds good to me.

I'll leave the try/catch in for now but in future I'll stick with the @blueyed's policy :)
