### ISSUE TITLE
`<leader>hs` is broken in normal mode

### ISSUE THREAD

**Issue by nesmyslny** [airblade/vim-gitgutter#642]
Hey,

First, thank for this plugin :)

I think bc1d28db46f7d8f174df4b0c98da092e10369281 broke `<Leader>hs` in normal mode by adding the `xmap` before the `nmap` (see https://github.com/airblade/vim-gitgutter/commit/bc1d28db46f7d8f174df4b0c98da092e10369281#diff-effd17f6c7177d451369a08a5b211317). I guess the second `!hasmapto('<Plug>GitGutterStageHunk')` resolve to false, because there's already a `xmap`.

> What is the latest commit SHA in your installed vim-gitgutter?
070cfc5

> What vim/nvim version are you on?
NVIM v0.3.8

**Comment by airblade** [comment]
Thanks for letting me know!

This should be fixed by 71bbe88.
