### ISSUE TITLE
[Feature request] Hunk preview in a floating window

### ISSUE THREAD

**Issue by aymanbagabas** [airblade/vim-gitgutter#643]
Hi,

I just had this idea of having git hunks in a floating window instead of a preview window. Preview windows are so annoying because they push/move text in the current window.

So, I was wondering if this would be an appealing feature especially that Vim8 soon going to have floating windows and NeoVim already have floating windows in 0.4.

Thank you.

**Comment by airblade** [comment]
I would be happy to incorporate floating windows as long as the user can choose not to use them.

> Preview windows are so annoying because they push/move text in the current window.

They don't for me.  My preview window opens below my other windows so it doesn't move the text at all.

**Comment by ccjmne** [comment]
For the record, `splitkeep=screen` will prevent existing content from being pushed when opening a preview window!
