### ISSUE TITLE
Mappings broken

### ISSUE THREAD

**Issue by deathlyfrantic** [airblade/vim-gitgutter#648]
> What is the latest commit SHA in your installed vim-gitgutter?

0469b84

> What vim/nvim version are you on?

Neovim 0.3.8

The change to `<Plug>(GitGutterStageHunk)` from `<Plug>GitGutterStageHunk` etc seems to have broken the default mappings. From the little bit of troubleshooting I did, it seems like the problem is having the new mapping in the text of the old mapping. For instance, this mapping to warn about the change:

```
nnoremap <silent> <Plug>GitGutterStageHunk     :call gitgutter#utility#warn('please change your map <Plug>GitGutterStageHunk to <Plug>(GitGutterStageHunk)')<CR>
```

means `hasmapto('<Plug>(GitGutterStageHunk)', 'n')` puzzlingly evaluates to true. This might be a Neovim quirk? You could probably work around this by factoring out the warning text into a separate function and just including the `GitGutterStageHunk` etc in the mapping.

**Comment by deathlyfrantic** [comment]
Further research indicates both Vim and Neovim defer to `strstr()` to determine whether a mapping exists:

Vim:
https://github.com/vim/vim/blob/581ba39aefe837298a9943b04a1dab13a7ec6772/src/map.c#L980

Neovim: 
https://github.com/neovim/neovim/blob/82d52b229df711b710862ce772603ea55113a32e/src/nvim/getchar.c#L3464

Weird! But given the complexities of VimL mapping I can't think of a better solution. At least it explains this bug.

**Comment by airblade** [comment]
Oops, I handled this for next/prev hunk etc but evidently not every case.

Thanks for letting me know!

**Comment by airblade** [comment]
Extracting the warning text into a separate function would solve the problem, but you can also get around `strstr()` with some escaping ;)

Thanks for digging into this and the links to Vim/Neovim source code.
