### ISSUE TITLE
:GitGutterQuickFix error undefined fname

### ISSUE THREAD

**Issue by OJFord** [airblade/vim-gitgutter#649]
> What is the latest commit SHA in your installed vim-gitgutter?

b71ab64dc16a4665c3214f109000a11d30708079

> What vim/nvim version are you on?
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  2 2019 07:02:04)
macOS version
Included patches: 1-1950
```

When calling `GitGutterQuickFix` (with a diff that I've verified that function's command can find) I get a lot of errors like:
```
line    8:
E684: List index out of range: 1
line   14:
E121: Undefined variable: fname
E116: Invalid arguments for function add
```

I'm not sure what part of my diff is causing it (when I have a smaller one I'll share a reproduction), but I must be hitting this line without having previously matched one of the others:
https://github.com/airblade/vim-gitgutter/commit/88d396f1b49747fadbbde5c038a85067d94954e5#diff-effd17f6c7177d451369a08a5b211317R202

**Comment by airblade** [comment]
The first error (line 8) is the significant one.  It suggests that the `if` condition matches but not the `matchlist()` regex:

https://github.com/airblade/vim-gitgutter/blob/b71ab64dc16a4665c3214f109000a11d30708079/autoload/gitgutter.vim#L195-L196

When this next occurs, please can you post the line which looks like `diff --git ...`?

**Comment by OJFord** [comment]
Ah, yes, that won't match because I have `diff.prefix = false` in my config - i.e. no `a/`, `b/`, et al.

**Comment by airblade** [comment]
Oops, I forgot about that option.  I'll amend the code to handle it.

**Comment by airblade** [comment]
Does this work for you?

```diff
diff --git i/autoload/gitgutter.vim w/autoload/gitgutter.vim
index 13f5168..84c89af 100644
--- i/autoload/gitgutter.vim
+++ w/autoload/gitgutter.vim
@@ -193,9 +193,13 @@ function! gitgutter#quickfix()
   let lnum = 0
   for line in diff
     if line =~ '^diff --git [^"]'
-      let fname = matchlist(line, '^diff --git [abciow12]/\(\S\+\) ')[1]
+      let paths = line[11:]
+      let mid = (len(paths) - 1) / 2
+      let [fnamel, fnamer] = [paths[:mid-1], paths[mid+1:]]
+      let fname = fnamel ==# fnamer ? fnamel : fnamel[2:]
     elseif line =~ '^diff --git "'
-      let fname = matchlist(line, '^diff --git "[abciow12]/\(.\+\)" ')[1]
+      let [_, fnamel, _, fnamer] = split(line, '"')
+      let fname = fnamel ==# fnamer ? fnamel : fnamel[2:]
     elseif line =~ '^@@'
       let lnum = matchlist(line, '+\(\d\+\)')[1]
     elseif lnum > 0
```

**Comment by airblade** [comment]
I decided to be optimistic and merged the change :)
