### ISSUE TITLE
Considers last line without trailing newline as modified

### ISSUE THREAD

**Issue by blueyed** [airblade/vim-gitgutter#650]
vim-gitgutter considers the final line of an unmodified buffer/file to have changed when it does not contain a trainling/final newline.

Writing the buffer will change it to contain the newline then (due to Vim's `'fixeol'` setting likely):
```
@ pyproject.toml:1 @
 [tool.black]
 line-length = 120
-include = 'django-stubs/.*\.pyi$'
\ No newline at end of file
+include = 'django-stubs/.*\.pyi$'
```

Haven't investigated, but it reminded me of https://github.com/airblade/vim-gitgutter/pull/510.

**Comment by airblade** [comment]
Reminds me of #510 too ;)

I'll look into it.

**Comment by airblade** [comment]
As you know the code uses `writefile()` in non-binary mode to write the buffer's contents to a temporary file.  According to the help docs (and Vim's source) `writefile()` will always write a trailing new line when not in binary mode:

[`writefile()`](https://github.com/vim/vim/blob/cd67059c0c3abf1e28aa66458abdf6f338252eb2/src/filepath.c#L1917) calls [`writelist()`](https://github.com/vim/vim/blob/cd67059c0c3abf1e28aa66458abdf6f338252eb2/src/list.c#L1000) to do the actual writing.

The source also shows there are no side effects to binary mode so I'm happy to switch to it.

**Comment by airblade** [comment]
I think we don't need to worry about `&binary` or `&fixendofline` because we are diffing what's in the buffer, not the file that would result from the user writing the buffer.

**Comment by blueyed** [comment]
Thanks!
