### ISSUE TITLE
Refresh signs for current tab page

### ISSUE THREAD

**Issue by mg979** [airblade/vim-gitgutter#651]
> What is the latest commit SHA in your installed vim-gitgutter?
b71ab64dc16a4665c3214f109000a11d30708079

> What vim/nvim version are you on?
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 21 2019 04:10:35)                                                                                                                             
Patch incluse: 1-197, 322, 377-378, 550, 649, 651, 703, 706-707                                                                                                                                
Patch aggiuntive: 8.1.1401, 8.1.1382, 8.1.1368, 8.1.1367, 8.1.1366, 8.1.1365, 8.1.1046, 8.1.0613, 8.1.0547, 8.1.0546, 8.1.0544, 8.1.0540, 8.1.0539, 8.1.0538, 8.1.0506, 8.1.0208, 8.1.0206, 8.1
.0205, 8.1.0189, 8.1.0177, 8.1.0067, 8.1.0066                                                                                                                                                  
```

Basically I'd like a command to refresh signs for the current tab, like when doing `!git add -u` or `!git reset`. The commad GitGutterAll seems a bit heavy, it'd be more something like:
```vim
command! -bar GitGutterTab call gitgutter#tab()

function! gitgutter#tab() abort
  for bufnr in tabpagebuflist()
    if buflisted(bufnr)
      let file = expand('#'.bufnr.':p')
      if !empty(file)
        call gitgutter#process_buffer(bufnr, 1)
      endif
    endif
  endfor
endfunction
```

Would it make sense to include something like that or is there a setting or a command that acts similarly? Thanks

**Comment by airblade** [comment]
`GitGutterAll` refreshes signs for windows in the current tab (only) – why is it a bit heavy for you?

**Comment by mg979** [comment]
The help file says :
```
:GitGutterAll           Update signs for all buffers.  You shouldn't need to
                        run this.
```

and in the function I read

    for bufnr in range(1, bufnr('$') + 1)

so I assumed it was running on all buffers and that it was a bit heavy, but if you say it's not the case it's ok.

**Comment by airblade** [comment]
If you read on in the function you'll see this;

https://github.com/airblade/vim-gitgutter/blob/b71ab64dc16a4665c3214f109000a11d30708079/autoload/gitgutter.vim#L12

– where `visible` is from `tabpagebuflist()`.

It's only processing buffers with windows in the current tab.

**Comment by mg979** [comment]
I see.. thanks.
