### ISSUE TITLE
Question: Is there way to also show staged Hunks in different color

### ISSUE THREAD

**Issue by oguzbilgic** [airblade/vim-gitgutter#652]
Is there way to show staged Hunks in different color, like blue? So that we can basically do a three way diff between Head/Index/Workingtree in a single file and stage/unstage hunks.

**Comment by airblade** [comment]
No, because the staged version of a file isn't necessarily a subset of what you have in your Vim buffer.  For example, if you stage a hunk, then modify the same region again, it's not possible to show both the staged and unstaged version simultaneously.
