### ISSUE TITLE
Preview in floating window: error before display

### ISSUE THREAD

**Issue by JoshMcguigan** [airblade/vim-gitgutter#653]
Before I start, I'd like to thank you for your work on this plugin. I've really enjoyed it and I was really happy to see you recently added an option to show the preview in a floating window. 

I've enabled the feature with `let g:gitgutter_preview_win_floating = 1` in $MYVIMRC, and it works great, as long as I havn't used netrw in that vim session. If I have used netrw, I get several error messages when I try to display vim-gitgutter preview (using <leader>hp). 

```
Error detected while processing /usr/share/vim/vim81/syntax/netrw.vim:                                                                                                                    
line  128:
E930: Cannot use :redir inside execute()
line  130:
E930: Cannot use :redir inside execute()
Press ENTER or type command to continue
```

After pressing enter here, the preview popup works as expected.

> What is the latest commit SHA in your installed vim-gitgutter?
76aa5920dba9b05991940f7dc29dc79ad7af0a3e
> What vim/nvim version are you on?
vim 8.1.1890

Let me know if I can provide any other diagnostic information.

Thanks!

**Comment by blueyed** [comment]
For refererence, the netrw code that triggers it: https://github.com/vim/vim/blob/9a4a8c4d5993c6371486c895a515c2ad351e9aaa/runtime/syntax/netrw.vim#L128-L130

The first question is: why does "syntax netrw" get used, and where?
Does the error show up before the floating window already?

gitgutter appears to trigger it via https://github.com/airblade/vim-gitgutter/blob/76aa5920dba9b05991940f7dc29dc79ad7af0a3e/autoload/gitgutter/hunk.vim#L425 - try commenting that line.

Also try the following patch instead:
```
diff --git i/autoload/gitgutter/hunk.vim w/autoload/gitgutter/hunk.vim
index d196d68..becddfc 100644
--- i/autoload/gitgutter/hunk.vim
+++ w/autoload/gitgutter/hunk.vim
@@ -422,7 +422,7 @@ function! s:open_hunk_preview_window()
             \ })
 
       call setbufvar(winbufnr(s:winid), '&filetype', 'diff')
-      call win_execute(s:winid, 'syntax enable')
+      call win_execute(s:winid, 'doautocmd FileType')
 
       return
     endif
```

**Comment by JoshMcguigan** [comment]
Wow, thanks for the quick response. Either solution (commenting line 425, and replacing it as shown in the patch) solves the problem.

**Comment by blueyed** [comment]
Cool.
Do you get the expected highlighting/syntax in both cases?  (original (with the error), and when using the patch)
(there should be no highlighting when commenting the line)

**Comment by JoshMcguigan** [comment]
Hmm, you mean the syntax in the preview floating window? Best I can tell, I get the same behaviour in all cases (original (with the error), commented line, patch). 

If you are talking about the optional highlighting feature of gitgutter, I don't have that turned on, but I can try it out if it would help.

**Comment by blueyed** [comment]
Yes, in the preview floating/popup window.
It should be highlighted as "diff".

I'll check it with Vim, normally using Neovim.

**Comment by blueyed** [comment]
FWIW: I am seeing a similar issue on master:
```
Error detected while processing function neomake#signs#DefineHighlights[6]..neomake#utils#defin
e_derived_highlights[8]..<SNR>30_define_derived_highlight_group[19]..neomake#utils#highlight_is
_defined[4]..neomake#utils#parse_highlight[1]..neomake#utils#redir:
line   24:
E930: Cannot use :redir inside execute()
Error detected while processing function neomake#signs#DefineHighlights[6]..neomake#utils#defin
e_derived_highlights[8]..<SNR>30_define_derived_highlight_group:
line   19:
E171: Missing :endif
Error detected while processing function neomake#signs#DefineHighlights[6]..neomake#utils#defin
e_derived_highlights:
line    8:
E170: Missing :endfor
Error detected while processing function neomake#setup#define_highlights:
line    2:
E171: Missing :endif
Error detected while processing /usr/share/vim/vim81/syntax/synload.vim:
line   19:
E171: Missing :endif
Error detected while processing function gitgutter#hunk#preview[1]..<SNR>165_hunk_op[62]..<SNR>
165_preview[5]..<SNR>165_open_hunk_preview_window:
line   35:
E171: Missing :endif
Error detected while processing function gitgutter#hunk#preview[1]..<SNR>165_hunk_op:
line   62:
E171: Missing :endif
```

**Comment by blueyed** [comment]
Hmm, the doc might be wrong: https://github.com/vim/vim/blob/cd67059c0c3abf1e28aa66458abdf6f338252eb2/runtime/doc/popup.txt#L140-L141

The `call setbufvar(winbufnr(s:winid), '&filetype', 'diff')` appears to be enough (Vim 8.1.1968).

**Comment by JoshMcguigan** [comment]
That would align with what I'm seeing.

**Comment by airblade** [comment]
@JoshMcguigan Thanks for reporting this.

I'm glad you like being able to see the hunk preview in a floating window.  I think it's worth mentioning the caveat that you can't stage only part of a hunk via Vim's floating windows (they are effectively read-only).

@blueyed Thanks for finding the fix!

**Comment by Gee19** [comment]
Didn't want to create a new issue but I still see this behaviour with neovim HEAD and latest version of this plugin. I confirmed the line was deleted from `/autoload/gitgutter/hunk.vim` as well. I've settled with `let g:gitgutter_preview_win_floating = 0` for now.

Thanks for the awesome plugin :)

**Comment by airblade** [comment]
@Gee19 Hmm, I can't reproduce the error with nvim v0.5.0 release build and the plugin as of 1c53af9.

When you say the line was deleted from `hunk.vim`, please could you confirm which line?  Or perhaps which commit of vim-gitgutter you're at?
