### ISSUE TITLE
Show signs on folded regions

### ISSUE THREAD

**Issue by petRUShka** [airblade/vim-gitgutter#655]
Suppose we have a buffer with changes within fold. There is no sign on left column in case of closed fold (take a look at line 20):

![2019-09-23-232820_162x208_scrot](https://user-images.githubusercontent.com/146893/65460716-30956c80-de5b-11e9-95f0-9e888c083929.png)

In case of opened fold one can see `+` sings:

![2019-09-23-233910_145x271_scrot](https://user-images.githubusercontent.com/146893/65460795-5c185700-de5b-11e9-89ba-89ae800a6054.png)

So when fold is closed one doesn't see any changes at all. 

Feature request to add some sign in case folded region has some changes hunks inside.

> What is the latest commit SHA in your installed vim-gitgutter?

commit 76aa5920dba9b05991940f7dc29dc79ad7af0a3e
and
commit 68e735b92c8801c30208586ab34c52f1767fdafb
> What vim/nvim version are you on?
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  3 2019 19:23:34)
Included patches: 1-1968
Compiled by Arch Linux    
```
and

```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
```

**Comment by blueyed** [comment]
This might be more a feature request for Vim/Neovim, to display signs (optionally?) for/with folds.

(I would have expected it to display a sign for line 17 at least still, but it seems like with folds no signs are shown next to it always then?)

At least it's not trivial to do this in a plugin I assume.

**Comment by airblade** [comment]
Vim/Neovim don't currently allow showing signs beside a fold, so I agree with @blueyed that you'd have to make a feature request to them.

Instead I suppose the fold text summary (`:help fold-foldtext`) could include diff stats, for example (pseudocode): "<foldtext()> (X added, Y deleted)".

**Comment by airblade** [comment]
I'm tending towards just providing a simple indicator of whether any folded lines have been modified.  I can't see any benefit to breaking it down by added/removed/modified, and calculating that is quite tricky.

**Comment by petRUShka** [comment]
@airblade, totally agree.

So next steps are:
1. Issues in vim and neovim repositories.
2. simple indicator of whether any folded lines have been modified added here.

Is it true?

**Comment by airblade** [comment]
Sounds good.  I'll do (2); (1) is out of scope for the plugin.
