### ISSUE TITLE
Using line number highlights only doesn't work

### ISSUE THREAD

**Issue by 0xC0FFEE** [airblade/vim-gitgutter#656]
> What is the latest commit SHA in your installed vim-gitgutter?

ba049e707abe9c75f050fa4a26a4a61929f5dc2d

> What vim/nvim version are you on?

NVIM v0.5.0-63-g2621f4455

I was trying the line number highlight feature (which I love btw!) and discovered, that this feature only works in combination with either signs or line highlight.

If both signs and line highlights are disabled, turning on line number highlighting has no effect. I'd expect this to work standalone, similar as line highlighting works without signs and without line number highlighting. 

My work around is to enable line number highlighting and line highlighting and use a nop-highlight  (one which highlights nothing) for the line highlight.

**Comment by airblade** [comment]
Thanks for reporting this!

**Comment by 0xC0FFEE** [comment]
Thanks for fixing this so quickly :rocket:
