### ISSUE TITLE
Using --git-dir option

### ISSUE THREAD

**Issue by ranebrown** [airblade/vim-gitgutter#658]
gitgutter: 5c73edb3c2fd8794661d7c7ac72eed1fc9d36761

Vim: 8.1 patches 1-1722

Is there a way to set some sort of per file setting to use the `--git-dir` option? I have my config files tracked using the setup described [here](https://www.atlassian.com/git/tutorials/dotfiles) and use an alias `alias config='git --git-dir=$HOME/.cfg/ --work-tree=$HOME'` to view any changes. I would still like to see the changes when editing a file with gitgutter if possible.

Hopefully that makes sense. Thanks.

**Comment by airblade** [comment]
You can [do this](https://github.com/airblade/vim-gitgutter#extra-arguments-for-git-when-running-git-diff):

```viml
let g:gitgutter_git_args = '--git-dir-"/path/to/wherever"'
```

Does that work for you?

**Comment by ranebrown** [comment]
Awesome, I overlooked that option. I ended up with this and it seems to work so far:

```vim
augroup GitGutterDotsGroup
    autocmd!
    autocmd BufWinEnter * if @% =~# '.bashrc\|.vimrc' | let g:gitgutter_git_args = '--git-dir=$HOME/.cfg/ --work-tree=$HOME' | else | let g:gitgutter_git_args = ''
augroup END
```

Thanks!

**Comment by airblade** [comment]
Excellent, glad you got it doing what you want.

I would have thought you might need an `endif` but if it works, it works :)
