### ISSUE TITLE
Prevents Git Startup when editing inside a non git repo

### ISSUE THREAD

**Issue by marcusobrien** [airblade/vim-gitgutter#663]
> What is the latest commit SHA in your installed vim-gitgutter?
tip.

> What vim/nvim version are you on?
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:26:56)                                                      MS-Windows 32-bit console version

Add the plug in.
Edit a new file, or a  file that is not part of a repo

F:\Program Files (x86)\Vim>vim
"messages.log" "messages.log" 4L, 49Cfatal: not a git repository (or any of the parent directories): .git
"messages.log" "messages.log" 7L, 84C written
F:\Program Files (x86)\Vim>vi j
"messages.log" "messages.log" 7L, 84Cfatal: not a git repository (or any of the parent directories): .git
"messages.log" "messages.log" 10L, 120C written
F:\Program Files (x86)\Vim>

**Comment by airblade** [comment]
I can't reproduce this.

Please could you add `let g:gitgutter_log=1` to your vimrc, restart vim and trigger the problem?  You'll then find a `gitgutter.log` file in gitgutter's directory; it would be great if you could post it here.

If you have the appetite for it, it would really help if you could `git-bisect` to find when the problem appeared.

**Comment by airblade** [comment]
Are you still having this problem?
