### ISSUE TITLE
GitGutterNextHunkCycle (next hunk cycles in current buffer)

### ISSUE THREAD

**Issue by andys8** [airblade/vim-gitgutter#667]
I was missing a function that jumps to the next hunk but cycles through the buffer. 
With the example in the [README](https://github.com/airblade/vim-gitgutter#cycle-through-hunks-in-all-buffers) it was fairly easy to figure out a working solution. I came up with this:

```vimrc
nmap <silent> <leader>m :call GitGutterNextHunkCycle()<CR>

function! GitGutterNextHunkCycle()
  let line = line('.')
  silent! GitGutterNextHunk
  if line('.') == line
    normal! 1G
    GitGutterNextHunk
  endif
endfunction
```

I'm used to jump-to-next-with-cycle behavior from plugins like `ale` or `coc`. I'm opening this issue because ...

* a command `GitGutterNextHunkCycle`
* an option `let g:gitgutter_cycle_hunks = 1`
* another snippet in the `README.md`

might be helpful for other people :)

(BTW, thanks for the plugin :))

---

> What is the latest commit SHA in your installed vim-gitgutter?

fa8d0feb4103f15b97e2abb4e76cbaaf03495d1d

> What vim/nvim version are you on?

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 12 2019 12:02:28)
Included patches: 1-2292

**Comment by airblade** [comment]
Thank you!
