### ISSUE TITLE
Neovim: GitGutter not showing signs

### ISSUE THREAD

**Issue by Colocasian** [airblade/vim-gitgutter#668]
> What is the latest commit SHA in your installed vim-gitgutter?
c31581c25b4896ccb6418137c70a3a3c37326c89

> What vim/nvim version are you on?
Output of `nvim --version` below
```console
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

Whenever I use Neovim inside of a git folder, gitgutter doesn't work, even after saving the file.
Initial window:
![initial](https://user-images.githubusercontent.com/40887886/69903981-c2bf7100-13c6-11ea-8933-75ab68710e91.png)

Final window (Should show diff, but doesn't):
![final](https://user-images.githubusercontent.com/40887886/69903984-c8b55200-13c6-11ea-88e8-6de018b08829.png)

Gist of init.vim, gitgutterprofile log, and gitgutterlog generated via `set g:gitgutter_log = 1`:
https://gist.github.com/Colocasian/efe7cfbeebbb7c63f516947c64411f6f.

**Comment by Colocasian** [comment]
Tried reinstalling, but issue persisted. Is the problem something to do with PowerShell?

**Comment by Colocasian** [comment]
It doesn't even show any change in the statusbar, where it should show the number of updates. I tried on nvim-qt, but still doesn't work.

**Comment by airblade** [comment]
Thanks for the gist.  The log shows that gitgutter executes the following line but receives no response.

```
cd /d "C:\Users\rishv\Documents\Colocasian.github.io" && C:\Program Files\Git\bin\git.exe  ls-files --error-unmatch --full-name -z -- index.html
```

This implies that either `index.html` is not in a git repo, which presumably it is, or that nvim is encountering an error calling out to the shell.

What happens if you run that command like this? :-

```
:echo system(...)
```

– where `...` is the command above.

**Comment by Colocasian** [comment]
Output of `:echo system(...)`,
```console
'C:\Program' is not recognised as an internal or external command, operable program or batch file
```

Oh, I think the problem here is that git executable path isn't surrounded by quotes, so the space in the path is messing things up. When I add the quotes to git executable path, the output of `:echo system(...)` is,
```console
index.html
```
which I believe is the expected output.

As a botch, I tried to replace `let g:gitgutter_git_executable = 'C:\Program Files\Git\bin\git.exe'` with `let g:gitgutter_git_executable = '"C:\Program Files\Git\bin\git.exe"'`, but then it couldn't find my git.

**Comment by airblade** [comment]
Yes, in this case `index.html` is the expected output.

It's definitely a quoting problem.  I don't use Windows so I can't do any trial-and-error for you, but you could try something like:

```
let g:gitgutter_git_executable = 'C:\\Program\ Files\\Git\\bin\\git.exe'
```

**Comment by airblade** [comment]
You could also try [using forward slashes](https://github.com/airblade/vim-gitgutter/issues/421#issuecomment-472257680):

```
let g:gitgutter_git_executable = 'C:/Program Files/Git/bin/git.exe'
```

**Comment by Colocasian** [comment]
Tried many variations, didn't work

For all these variation, it couldn't find git:
```viml
let g:gitgutter_git_executable = 'C:\\Program\ Files\\Git\\bin\\git.exe'  " escaping space and backslash
let g:gitgutter_git_executable = '"C:\Program Files\Git\bin\git.exe"'  " adding quotes to path
let g:gitgutter_git_executable = 'C:\Program^ Files\Git\bin\git.exe'  " escaping the space according to cmd
let g:gitgutter_git_executable = 'C:\Program` Files\Git\bin\git.exe'  " escaping the space according to powershell
```

For all these variations, issue still persisted
```viml
let g:gitgutter_git_executable = 'C:/Program Files/Git/bin/git.exe'  " using forward slashes
let g:gitgutter_git_executable = "C:\Program Files\Git\bin\git.exe"  " changing surrounding quotes to double quotes
```

Removing this setting from `init.vim` renders the plugin to be inert.

PS: I believe the string is used atleast twice somewhere within the code, once where the path needs to be provided as is, and the other time is used in the function `cd` where it needs to be surrounded in quotes. Can this count as a bug? Moving git to somewhere with no spaces is a pain in the butt.

**Comment by gayashanbc** [comment]
> After all experimentation, only working when I remove the statement altogether. Seems the issue can be closed.
> 
> PS: Tried many variations, didn't work
> 
> For all these variation, it couldn't find git:
> 
> ```viml
> let g:gitgutter_git_executable = 'C:\\Program\ Files\\Git\\bin\\git.exe'  " escaping space and backslash
> let g:gitgutter_git_executable = '"C:\Program Files\Git\bin\git.exe"'  " adding quotes to path
> let g:gitgutter_git_executable = 'C:\Program^ Files\Git\bin\git.exe'  " escaping the space according to cmd
> let g:gitgutter_git_executable = 'C:\Program` Files\Git\bin\git.exe'  " escaping the space according to powershell
> ```
> 
> For all these variations, issue still persisted
> 
> ```viml
> let g:gitgutter_git_executable = 'C:/Program Files/Git/bin/git.exe'  " using forward slashes
> let g:gitgutter_git_executable = "C:\Program Files\Git\bin\git.exe"  " changing surrounding quotes to double quotes
> ```
> 
> PS PS: I believe the string is used atleast twice somewhere within the code, once where the path needs to be provided as is, and the other time is used in the function `cd` where it needs to be surrounded in quotes. Can this count as a bug? Moving git to somewhere with no spaces would a pain in the butt.

Removing the `let g:gitgutter_git_executable ` line from the init.vim file worked for me as well.
@airblade do you think this could cause the PATH problem you have mentioned in the README file?

**Comment by airblade** [comment]
@gayashanbc What PATH problem is that?

You can see where `g:gitgutter_git_executable` is used with [this search](https://github.com/airblade/vim-gitgutter/search?q=g%3Agitgutter_git_executable).  Looking at this afresh I realise that it is never escaped in any way.

I just saw this [suggestion in Fugitive](https://github.com/tpope/vim-fugitive/issues/1751#issuecomment-845656351):

```
let g:gitgutter_git_executable = 'C:/PROGRA~1/Git/cmd/git.exe'
```

Does that work?

**Comment by airblade** [comment]
> That does not work either

It's exasperating that in 2021 it's still non-trivial to get Vim to recognise a standard path on Windows :(

> By `PATH` problem I meant...

Oh ok.  You only need to (try to) configure the path to your git executable if you're worried about a malicious file named `git` being in your current directory.  It seems pretty unlikely to me.

**Comment by airblade** [comment]
Does this work?

```vim
let g:gitgutter_git_executable = '"C:\\Program Files\\Git\\cmd\\git.exe"'
```

Source: https://stackoverflow.com/a/25974500/151007

**Comment by gayashanbc** [comment]
> Does this work?
> 
> ```viml
> let g:gitgutter_git_executable = '"C:\\Program Files\\Git\\cmd\\git.exe"'
> ```
> 
> Source: https://stackoverflow.com/a/25974500/151007

Nope

> > That does not work either
> 
> It's exasperating that in 2021 it's still non-trivial to get Vim to recognise a standard path on Windows :(

yeah :(

> 
> > By `PATH` problem I meant...
> 
> Oh ok. You only need to (try to) configure the path to your git executable if you're worried about a malicious file named `git` being in your current directory. It seems pretty unlikely to me.

OK.
In that case, I don't think I have to worry about that configure anymore.
Thank you so much for the assistance.
