### ISSUE TITLE
SignColumn can't actually turn off.

### ISSUE THREAD

**Issue by kevinhwang91** [airblade/vim-gitgutter#669]
> What is the latest commit SHA in your installed vim-gitgutter?
1c53af9a0d3b622af5a62d69ddfc141c841a28c1(up to date now)

> What vim/nvim version are you on?
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Although turned off the signs by `let g:gitgutter_signs = 0`, the SignColumn add dummy column which displayed empty char.

**Comment by airblade** [comment]
The plugin stopped using a dummy sign to keep the sign column open in afe94ed (16.08.2019).

Do you have line highlights turned on?  If so, the sign column will be present because line highlights are in fact signs, even if the sign in the sign column is invisible.

What is `:verbose set signcolumn`?

**Comment by kevinhwang91** [comment]
`:verbose set signcolumn` output: `signcolumn=auto`

I turn on `let g:gitgutter_highlight_linenrs = 1`, before I post this issue I had seen readme said:
>"Note that if you have line highlighting on and signs off, you will have an empty sign column – more accurately, a sign column with invisible signs. This is because line highlighting requires signs and Vim always shows the sign column even if the signs are invisible.

I assume `highlighting` just vim but not neovim, maybe the readme should distinctly include neovim .

**Comment by airblade** [comment]
Sorry that was confusing.  Hopefully the readme is clearer now.
