### ISSUE TITLE
Unknown option: termencoding

### ISSUE THREAD

**Issue by petobens** [airblade/vim-gitgutter#670]
I'm using latest neovim and latest gitgutter and started getting the following errors today (I guess this is because nvim removed `termencoding`):
```
Error detected while processing function gitgutter#utility#supports_overscore_sign:
line    4:
E113: Unknown option: termencoding
E15: Invalid expression: &termencoding ==? &encoding || &termencoding == ''
```

**Comment by blueyed** [comment]
Shouldn't be a problem with the next nightly anymore: https://github.com/neovim/neovim/pull/11662

**Comment by airblade** [comment]
Can we close this?  It sounds like a fleeting problem in neovim's non-release builds.
