### ISSUE TITLE
Small `updatetime` also means aggressive writing to swap-file

### ISSUE THREAD

**Issue by chrisbarber** [airblade/vim-gitgutter#672]
I use vim for writing (not coding) on an old laptop of mine that I put an SSD into, and I just noticed how the disk-I/O LED was very active whenever I was typing. This was due to setting my `updatetime` to 100ms as recommended for this plugin. It's not a huge deal but in principle it just bothers me that my SSD is being written to so frequently when it doesn't need to be.

For my purposes I have just set `updatetime` back to 4s on this machine, since I don't use it for coding often. I've never noticed a performance issue even on machines with spinning disk drives or where the swap file is on a network share, but in general it seems undesirable to have such aggressive writing to the swap-file.

My thoughts... either:

1. Leave it how it is, but make a note in the readme of how swap writing will be affected when changing this setting.
2. Referring to #595 and the vim help, it seems like this issue is driven by the fact that vim uses `updatetime` both for swap writing behavior, as well as generic `CursorHold` autocmd behavior. Probably these should be decoupled in vim itself.
3. Rather than wait to try to get upstream change (2), just use `TextChanged`/`TextChangedI` as described in #595 and do the desired debouncing here in vimscript, to replicate the behavior of the `CursorHold` events. Add a new config variable for the length of time, defaulting to 100ms, and remove the recommendation from the readme, and any dependence on `updatetime`.

Do you see any potential issues here or would this be a good improvement?

**Comment by airblade** [comment]
I hadn't realised that vim also uses `updatetime` for swap file writing (I always disable vim's swap file stuff).

1. I'll do this now.
2. I agree, these should be decoupled in vim.  It's using one option for two different things.
3. We could do this; I'm not sure whether reducing the frequency of swap file writes is worth the slight increase in complexity.  The plugin writes two files to disk per diff anyway so there would still be frequent disk I/O.

If we did proceed with (3), I would maintain backward compatibility with older vims that don't have `TextChanged(I)` (7.3.883) or timers (7.4.2218).

**Comment by chrisbarber** [comment]
I see the point regarding (3). I agree it seems not worth the effort.

So (1) honestly seems good enough to me, anything else nice-to-have, so up to you about closing this or keeping open if you want to track. I might pursue (2) by opening an issue against vim (I did search and see no existing discussion of this) or a PR if I'm really bored; in either case though I might want to research a little more before doing so. It does seem like the most correct solution, though, and probably not too hard to implement on the vim side.

**Comment by airblade** [comment]
Ok, I've done (1) so I'll close this now.  Opening an issue against vim for (2) sounds like a good step to take, if you can be bothered :)
