### ISSUE TITLE
FR: Add (clickable) markers at top/bottom of gutter to indicate next hunk location

### ISSUE THREAD

**Issue by oliv3r** [airblade/vim-gitgutter#673]
We currently see in the gutter using the +- and ~ markers that there are hunks. However (especially on large files) we do not see where the next hunk is.

Add a ^ and ˇ in the first or last line of the visible gutter to indicate next/prev hunks.

Bonus points if these markers are clickable to jump to the next hunk ;)

**Comment by airblade** [comment]
I see the problem you want to solve.

However signs are attached to specific lines so adding indicators at the top and bottom of the visible gutter would mean having to remove and re-add the indicators every time the buffer moved up or down, which would add quite a lot of complexity and possibly a performance penalty.

As far as I know it's not possible to make signs clickable in Vim / Neovim.  I'd recommend using `[c` and `]c` instead.

Instead you could:

- use `:GitGutterFold` to get a quick view of where the hunks are;
- use `:GitGutterQuickFix` to load the hunks into the quickfix or location list and look at the list;
- use a floating window to show whether there are hunks above or below the current line; you could probably make these clickable or chooseable.
- add a function to the status line showing your indicators when appropriate.
