### ISSUE TITLE
GitGutter on Windows does not work if shell is bash.

### ISSUE THREAD

**Issue by parchd-1** [airblade/vim-gitgutter#678]
> What is the latest commit SHA in your installed vim-gitgutter?

da2c785221810b3d57479bb4b3678aabf32f3b88

> What vim/nvim version are you on?

NVIM v0.4.3

GitGutter does not work because it fails at changing directory. I am using neovim on Windows with my shell set to bash - the utility function (correctly) determines that I am running on Windows, and (incorrectly) changes the `cd` command to `cd /d`.

The problem is in:
```
function! gitgutter#utility#cd_cmd(bufnr, cmd) abort
  let cd = s:unc_path(a:bufnr) ? 'pushd' : (gitgutter#utility#windows() ? 'cd /d' : 'cd')
  return cd.' '.s:dir(a:bufnr).' && '.a:cmd
endfunction
```

If I just let cd to 'cd' everything seems to work perfectly. Would you consider adding a check so that 'cd /d' is only used if windows and shell is not set to bash?

**Comment by airblade** [comment]
I don't know much about Windows but that sounds reasonable to me.

How checking if the shell does not end in "sh" instead of specifically "bash"?

**Comment by parchd-1** [comment]
Thank you, and good idea about not being specific to bash. I have also just done a quick test, and powershell users also require just the bare `cd`. I think the `/d` flag is only required/only works for people with the default dos prompt as their shell.

**Comment by parchd-1** [comment]
Afterthought: Ignoring the powershell issue a moment, I think the check needs to be for _sh(\\.exe)?$_ as the .exe may or may not be present in a Windows setup.

**Comment by airblade** [comment]
Maybe it would be better only to add `/d` when the shell is `cmd.exe`?

**Comment by parchd-1** [comment]
Yes, I think that would be better. I don't know of any other shell that requires that flag.

**Comment by airblade** [comment]
How about `command.com`?  It's mentioned in `:help 'shell'`.
