### ISSUE TITLE
Uncaught exception when call GitGutterPreviewHunk/GitGutterUndoHunk from a none git folder.

### ISSUE THREAD

**Issue by thylakoids** [airblade/vim-gitgutter#680]
> What is the latest commit SHA in your installed vim-gitgutter?
da2c785
> What vim/nvim version are you on?
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  3 2020 01:40:55)

When accidentally call GitGutterPrevHunk/GitGutterUndoHunk within a none git folder, GitGutter will cause error:
<img width="1283" alt="Screen Shot 2020-02-21 at 9 27 35 PM" src="https://user-images.githubusercontent.com/13399872/75038469-65cce600-54f1-11ea-9766-84177b638c74.png">

**Comment by airblade** [comment]
I can't reproduce this:

```
mkdir issue
cd issue
vim -c 'GitGutterPrevHunk' foo
```

**Comment by thylakoids** [comment]
Have you tried to run 'GitGutterPrevHunk' in vim? 
I disabled all the other plugs and tried this:

    mkdir issue
    cd issue
    vim -c 'GitGutterPrevHunk' foo

Everything is fine by far.

    :GitGutterPrevHunk

Then the error occurred.

**Comment by airblade** [comment]
Yes, but it still works for me.

Please can you switch on logging in your vimrc (`let g:gitgutter_log=1`), reproduce the problem, then post the log file (in your gitgutter installation directory).

**Comment by thylakoids** [comment]
Here is the log file:
```


==== start log session ====

  0.000010 function <SNR>12_on_bufenter[7]..gitgutter#process_buffer[10]..<SNR>28_setup_path[7]..gitgutter#utility#set_repo_path[16]..gitgutter#utility#system[1]:
  0.000010 cd /home/liyulong/Downloads/test/issue && git  ls-files --error-unmatch --full-name -z -- foo

  0.004376 function <SNR>31_git_supports_command_line_config_override[1]..gitgutter#utility#system[1]:
  0.004376 git  -c foo.bar=baz --version

  0.008397 function <SNR>12_on_bufenter[7]..gitgutter#process_buffer[21]:
  0.008397 Not tracked: /home/liyulong/Downloads/test/issue/foo

  0.008520 function <SNR>12_on_bufenter[7]..gitgutter#process_buffer[28]..gitgutter#diff#handler[1]:
  0.008520 
```
.vimrc
```
call plug#begin('~/.vim/bundle')
Plug 'airblade/vim-gitgutter'
call plug#end()
let g:gitgutter_log=1

```

**Comment by airblade** [comment]
Thanks for the log file.

The first two lines show the plugin finding out whether the file exists in the repo and, if it does, its path.  The `git ls-files` command is run asynchronously.

The next two lines show the plugin testing whether your version of git supports `-c` flags.

The third pair of lines is the callback with the result of the `git ls-files` command.  This correctly discovers that the file is not tracked by git.

The final lines show the plugin processing the file's diff, which is empty.  It seems strange to try to process the diff of an untracked file, even if it's a noop.  I have a patch below to avoid this.

It also looks like gitgutter is running synchronously instead of asynchronously, which is surprising.  Have you set `let g:gitgutter_async=0` anywhere?

Anyway, I still can't reproduce the error when I run it synchronously here, and the log file looks correct to me.

What OS do you use?

Does the following change help?

```diff
diff --git i/autoload/gitgutter.vim w/autoload/gitgutter.vim
index 582ea4b..15e0d44 100644
--- i/autoload/gitgutter.vim
+++ w/autoload/gitgutter.vim
@@ -37,7 +37,7 @@ function! gitgutter#process_buffer(bufnr, force) abort
 
     if a:force || s:has_fresh_changes(a:bufnr)
 
-      let diff = ''
+      let diff = 'NOT SET'
       try
         let diff = gitgutter#diff#run_diff(a:bufnr, g:gitgutter_diff_relative_to, 0)
       catch /gitgutter not tracked/
@@ -47,7 +47,7 @@ function! gitgutter#process_buffer(bufnr, force) abort
         call gitgutter#hunk#reset(a:bufnr)
       endtry
 
-      if diff != 'async'
+      if diff != 'async' && diff != 'NOT SET'
         call gitgutter#diff#handler(a:bufnr, diff)
       endif
 ```

**Comment by thylakoids** [comment]
Thanks for your patience and explanation.

I've applied the change, the error still exits.
I tried both ubuntu(vim8.2) and macOS(vim8.2/nvim0.4.3), they  all raise the same error, which was slightly different from the previous.
<img width="1300" alt="Screen Shot 2020-02-24 at 9 10 22 PM" src="https://user-images.githubusercontent.com/13399872/75155050-1cc39e80-574a-11ea-832c-d4d2d6249882.png">

and here is the log file:
```


==== start log session ====

  0.000025 function <SNR>9_on_bufenter[7]..gitgutter#process_buffer[10]..<SNR>25_setup_path[7]..gitgutter#utility#set_repo_path[16]..gitgutter#utility#system[1]:
  0.000025 cd /Users/dracarys/issue && git  ls-files --error-unmatch --full-name -z -- foo

  0.035358 function <SNR>28_git_supports_command_line_config_override[1]..gitgutter#utility#system[1]:
  0.035358 git  -c foo.bar=baz --version

  0.061779 function <SNR>9_on_bufenter[7]..gitgutter#process_buffer[21]:
  0.061779 Not tracked: /Users/dracarys/issue/foo
```
Your judgment is right, the error has something to do with synchronously. I didn't set `let g:gitgutter_async=0`. Normally the parameter equals to 1, but if this error occurs, the parameter will change from 1 to 0.
```bash
mkdir issue
cd issue
vim foo
```
```vim
:let g:gitgutter_async'    " return 1
:GitGutterPreview    "which would raise the error
:let g:gitgutter_async    " return 0
```

**Comment by airblade** [comment]
Aha, I can reproduce it now.  I was trying with `:GitGutterPrevHunk`, which worked fine, but I just tried `:GitGutterPreviewHunk` and that triggered the error.

**Comment by thylakoids** [comment]
Sorry, that's my mistake. `:GitGutterPrevhunk` works fine. I blame it for the autocompletion：）

**Comment by airblade** [comment]
No worries, I'm working on a fix.
