### ISSUE TITLE
gitgutter_max_signs set to 0 to disable any check

### ISSUE THREAD

**Issue by rightaway** [airblade/vim-gitgutter#681]
I'd always like to see the gitgutter signs. Minor point but would be nicer to set it to 0 than some arbitrarily high value like 999999. I set it originally to values I thought I'd never exceed like 1000 then I would exceed it and have to change the vimrc. Too many signs doesn't slow down my vim but if it ever does I'd temporarily change the value to some maximum.

**Comment by airblade** [comment]
Thanks for bringing this up.  The limit was introduced when Vim was much slower at drawing signs.

I chose -1 as the "no limit" value and it is now the default on newer Vims.
