### ISSUE TITLE
Show sign column right of line numbers column

### ISSUE THREAD

**Issue by fogine** [airblade/vim-gitgutter#682]
> What is the latest commit SHA in your installed vim-gitgutter?
0e509fb0ac
> What vim/nvim version are you on?
vim 8.2
nvim 0.4.3

It would be great if I could configure gitgutter to show the sign column right of the line numbers column. Currently it is always rendered left of the line numbers column.

Thanks for the plugin!

**Comment by airblade** [comment]
That's the way Vim / Neovim displays it.  All I can suggest is that you ask them about it.
