### ISSUE TITLE
Error on PreviewHunk

### ISSUE THREAD

**Issue by hejsan** [airblade/vim-gitgutter#683]
> What is the latest commit SHA in your installed vim-gitgutter?
0e509fb0ac56b24203800a1fab35162c8da9c9b4

> What vim/nvim version are you on?
Normal VIM - Vi IMproved - version 7.4.629 running on Centos commandline

When I run GitGutterPreviewHunk I get the following error across the screen:
But after I exit the error the preview panel is shown correctly.
Maybe you don't need to use win_getid or can at least check if it's there and fallback on something else?
`
"gitgutter://hunk-preview" [New DIRECTORY]
Error detected while processing function gitgutter#hunk#preview..<SNR>67_hunk_op..<SNR>67_preview..<SNR>67_open_hunk_preview_window:
line   43:
E117: Unknown function: win_getid
E15: Invalid expression: win_getid()
Error detected while processing function gitgutter#hunk#preview..<SNR>67_hunk_op..<SNR>67_preview..<SNR>67_populate_hunk_preview_window..gitgutter#diff_highlight#process..<SNR>75_diff:
line    3:
E121: Undefined variable: start:
E116: Invalid arguments for function s:common_prefix(a:rline[start:], a:aline[start:])
E15: Invalid expression: s:common_prefix(a:rline[start:], a:aline[start:])
line    5:
E121: Undefined variable: prefix
line    7:
E121: Undefined variable: prefix
E116: Invalid arguments for function s:common_suffix(a:rline, a:aline, prefix+1)
E15: Invalid expression: s:common_suffix(a:rline, a:aline, prefix+1)
line   10:
E121: Undefined variable: prefix
E15: Invalid expression: a:rline[prefix+1:rsuffix-1]
line   11:
E121: Undefined variable: prefix
E15: Invalid expression: a:aline[prefix+1:asuffix-1]
line   14:
E121: Undefined variable: rtext
E116: Invalid arguments for function empty(rtext)
E15: Invalid expression: empty(rtext)
line   22:
E121: Undefined variable: atext
E116: Invalid arguments for function empty(atext)
E15: Invalid expression: empty(atext)
line   30:
E121: Undefined variable: atext
E116: Invalid arguments for function stridx(atext, rtext)
E15: Invalid expression: stridx(atext, rtext)
line   31:
E121: Undefined variable: j
E15: Invalid expression: j != -1
line   38:
E121: Undefined variable: rtext
E116: Invalid arguments for function stridx(rtext, atext)
E15: Invalid expression: stridx(rtext, atext)
line   39:
E121: Undefined variable: j
E15: Invalid expression: j != -1
line   46:
E121: Undefined variable: rtext
E116: Invalid arguments for function s:lcs(rtext, atext)
E15: Invalid expression: s:lcs(rtext, atext)
line   48:
E121: Undefined variable: lcs
E116: Invalid arguments for function len(lcs) > s:gap_between_regions
E15: Invalid expression: len(lcs) > s:gap_between_regions
line   59:
E121: Undefined variable: prefix
E15: Invalid expression: !a:whole_line || ((prefix != 0 || rsuffix != len(a:rline)) && prefix+1 < rsuffix)
line   64:
E121: Undefined variable: prefix
E15: Invalid expression: !a:whole_line || ((prefix != 0 || asuffix != len(a:aline)) && prefix+1 < asuffix)
`

**Comment by airblade** [comment]
Ah, `win_getid()` was added in Vim 7.4.1557.  I thought I was feature-checking everything but evidently this one slipped through the gap.

I'll fix this up when I get a bit of time.

**Comment by hejsan** [comment]
Yah, centos/redhat are notoriously conservative with their packaged versions. Thanks.

**Comment by airblade** [comment]
Hopefully that commit will avoid the error without breaking anything.
