### ISSUE TITLE
[Petition] Change the color of the columns depending on the changes made in the file

### ISSUE THREAD

**Issue by GGCristo** [airblade/vim-gitgutter#685]
Instead of using icons or symbols can we change the color of the column to create something similar to vs code? 
Maybe can we use symbols to recreate this?

**Comment by airblade** [comment]
I don't know what VSCode looks like.  Perhaps you could post a screenshot.

From the sound of things, you could configure the signs' highlight groups' background colours.

**Comment by GGCristo** [comment]
when you add lines looks like this:
![vscode](https://user-images.githubusercontent.com/58046649/77466620-6fa07c80-6e02-11ea-9c5f-7a983825a6b7.png)

this is my attempt using symbols:
![attempt](https://user-images.githubusercontent.com/58046649/77466684-834be300-6e02-11ea-81b9-cce01b4c56f2.png)
I find it pretty but I think it could look a lot better.

Maybe asking for changing the gutter color partially and when vim is already executed is too much, if that is the case someone could find a way to imitate it?

**Comment by GGCristo** [comment]
![funciona](https://user-images.githubusercontent.com/58046649/77470680-fc4e3900-6e08-11ea-8f27-bd59e1c5936c.png)

Oh you are right I just have to play with these commands from the Readme:
```
highlight GitGutterAdd    guifg=#009900 guibg=<X> ctermfg=2 ctermbg=<Y>
highlight GitGutterChange guifg=#bbbb00 guibg=<X> ctermfg=3 ctermbg=<Y>
highlight GitGutterDelete guifg=#ff2222 guibg=<X> ctermfg=1 ctermbg=<Y>
```
I don't know why I haven't seen these before. Thanks you

**Comment by Azumgi** [comment]
`┃` worked great for me (with Iosevka font).
![image](https://user-images.githubusercontent.com/35058624/78687607-04c06c80-78fd-11ea-85e5-bd46f3fa12b6.png)

```
let g:gitgutter_sign_added              = '┃'
let g:gitgutter_sign_modified           = '┃'
let g:gitgutter_sign_removed            = '┃'
let g:gitgutter_sign_removed_first_line = '┃'
let g:gitgutter_sign_modified_removed   = '┃'
```

**Comment by GGCristo** [comment]
That looks good thanks for telling me
