### ISSUE TITLE
Git-gutter fails on vim builds since 8.2.0473

### ISSUE THREAD

**Issue by systemmonkey42** [airblade/vim-gitgutter#691]
This is more of an FYI in case anyone else notices.

A bug in VIM versions since 8.2.0473 causes the `getbufvar(bufnr,'')` to return the variables from the wrong buffer.  This affects gitgutter when it attempts to update the diff highlighting in visible buffers other than the current buffer.

https://github.com/vim/vim/issues/5878

**Comment by airblade** [comment]
The code uses that pattern in two places: [here](https://github.com/airblade/vim-gitgutter/blob/9cdb90b1e1018c480bd1a3606d36c636bf29b5ad/autoload/gitgutter/utility.vim#L12) and [here](https://github.com/airblade/vim-gitgutter/blob/9cdb90b1e1018c480bd1a3606d36c636bf29b5ad/autoload/gitgutter/utility.vim#L25).

I can change both these to avoid the vim bug.

**Comment by systemmonkey42** [comment]
I'm sure vim will be fixed in the next point release or two.  Most people would never notice.
