### ISSUE TITLE
Signs not shown on CentOS 7, E706 E689

### ISSUE THREAD

**Issue by lpilz** [airblade/vim-gitgutter#693]
As said in the title, when launching vim or using gitgutter commands, I get the errors:

> Error detected while processing function \<SNR\>28_on_bufenter..gitgutter#setup_maps..gitgutter#utility#setbufvar:
> line    5:
> E706: Variable type mismatch for: ggvars
> line    8:
> E689: Can only index a List or Dictionary

I am on CentOS Linux release 7.6.1810, git version 1.8.3.1.

> What is the latest commit SHA in your installed vim-gitgutter?
b7db78b258aa9925f3c86968b348413732964b3b

> What vim/nvim version are you on?
7.4

**Comment by markogrady1** [comment]
i am also getting this error using vim version 7.4

**Comment by airblade** [comment]
Ah, it looks like before [Vim 7.4.1546](https://github.com/vim/vim/commit/f6f32c38bf3319144a84a01a154c8c91939e7acf) there was sticky type checking.

**Comment by lpilz** [comment]
Cheers for the rapid response :)

**Comment by markogrady1** [comment]
nice one, cheers
