### ISSUE TITLE
Can't hank by selecting multiple lines

### ISSUE THREAD

**Issue by tamago324** [airblade/vim-gitgutter#694]
Hi airblade.
I was using a plugin and it didn't work, so I have to report it!

### Environment

vim-gitgutter version: b7db78b
OS: Windows 10
Vim: 8.2

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 13 2020 22:13:23)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-577
Compiled by appveyor@APPVYR-WIN
```

### Actual behaviour

If you select multiple lines in visual mode and execute `:'<,'>GitGutterStageHunk`, an error occurs: `vim-gitgutter: patch does not apply`.

### Steps to reproduce

min_vimrc

```
set encoding=utf-8

syntax enable
filetype plugin indent on

set nocompatible

" use plugins
set runtimepath^=~/vimfiles/plugged/vim-gitgutter
```

1. `gvim.exe -u min_vimrc`
2. `:e sample.py` (The contents of the file are as follows.)

```
import re

print('')
```

3. Select the first and second lines (`ggVj`)
4. execute `:GitGutterStageHunk`.
5. An error is output. (`vim-gitgutter: patch does not apply`)

The output of `git diff` is as follows.

```diff
C:\tmp\dir\demo>git diff
diff --git a/sample.py b/sample.py
index 7cae115..08264e9 100644
--- a/sample.py
+++ b/sample.py
@@ -1,2 +1,3 @@
-import pathlib
+import re
+
 print('')
```

---

Maybe I'm not using it correctly, so if I'm wrong, I'd like to be told.

If it's a bug, I think it would be good to fix it as follows, but what do you think?

```diff
>git diff
diff --git a/autoload/gitgutter/hunk.vim b/autoload/gitgutter/hunk.vim
index 4f0f7c7..7b6a04a 100644
--- a/autoload/gitgutter/hunk.vim
+++ b/autoload/gitgutter/hunk.vim
@@ -323,7 +323,7 @@ function! s:part_of_diff(hunk_diff, first, last)
   " adjust 'to' line count in header
   let diff_lines[4] = substitute(diff_lines[4], '\(+\d\+\)\(,\d\+\)\?', '\=submatch(1).",".(a:last-a:first+1)', '')

-  return join(diff_lines[0:4] + diff_lines[5+a:first:5+a:last], "\n")."\n"
+  return join(diff_lines[0:4] + diff_lines[5+a:first:5+a:last+1], "\n")."\n"
 endfunction
```

Thank you.

**Comment by airblade** [comment]
Ah, I've just remembered that staging (part of) a hunk via visual selection is only supported for additions-only hunks.  This is documented in the readme at line 159 (not sure how to link that here).

Your fix only works in this case because your diff has a deletion of 1 line.

Here's why the `s:part_of_diff(hunk_diff, first, last)` function only works for additions-only hunks.  `a:first` and `a:last` are the numbers of the first and last lines the user has visually selected.  If the diff contains deleted lines, it is not clear how many of them to include in the part hunk.

**Comment by tamago324** [comment]
> To stage part of an additions-only hunk by:
> 
> * either visually selecting the part you want and staging with your mapping, e.g. `<Leader>hs`;
> * or using a range with the `GitGutterStageHunk` command, e.g. `:42,45GitGutterStageHunk`.

I'm sorry!
I didn't read README.md very carefully.

I'll use `:GitGutterPreviewHunk`.

Thank you very much for taking the trouble to reply to me.
