### ISSUE TITLE
q deprecation.

### ISSUE THREAD

**Issue by jtmkrueger** [airblade/vim-gitgutter#697]
I see this a lot lately

```
:Git blame q is deprecated in favor of gq
```

And am curious as to the reasoning for this change. I see the split that gitgutter opens up as a "quickfix" window and `gq` doesn't work in quickfix windows, so it'll require a tricky remap to have it work the same way in both places. This, in my humble _(yes quite humble. I love this extension and use it many times a day! Keep up the great work!)_ opinion, will make it a bit counter-intuitive to use git gutter. I'm sure there's a good reason for it, but just wanted to add my 2 cents as a user.

**Comment by airblade** [comment]
`:Git blame q` is not a vim-gitgutter command.  I expect it's from Fugitive.
