### ISSUE TITLE
Provide autocmd (or callback) for gitgutter hunk operations

### ISSUE THREAD

**Issue by wookayin** [airblade/vim-gitgutter#698]
## Feature Request

Please see #695 for a related discussion.

It would be great if we can have an User autocmd or callback for `gitgutter#hunk#stage`, `gitgutter#hunk#undo`, (and their commands counterparts).

The motivation is the following: As pointed out in #695, [one problem of fugitive](https://github.com/tpope/vim-fugitive/issues/1517) is that it doesn't refresh automatically on external changes (via command line or via gitgutter). This is absolutely fugitive's business (one can write an autocmd to refresh/reload the buffer, but it did not work quite well for me due to other annoying bugs), but so as to have it up-to-date or refresh automatically having an autocmd would be great.

@airblade's comment https://github.com/airblade/vim-gitgutter/issues/695#issuecomment-616159031 :

> If Fugitive doesn't automatically refresh its view of a staged file when the index is updated, that's Fugitive's business, not vim-gitgutter's.
>
> However I'm happy to try to make things easier if possible. Maybe vim-gitgutter could fire a User autocmd when it updates the index; you could listen for that event and refresh any Fugitive buffers which may be open. Would that help?

**Comment by airblade** [comment]
The plugin would only fire an autocmd when the index was updated which only happens when a hunk or part of a hunk is staged.  It wouldn't be fired for hunk-undo.

**Comment by wookayin** [comment]
Oh you are right. I got it wrong — not necessary for hunkundo.
