### ISSUE TITLE
Release management ?

### ISSUE THREAD

**Issue by rmedaer** [airblade/vim-gitgutter#699]
Hi Andy,

I'm going to [package your plugin for Debian](https://salsa.debian.org/vim-team/vim-gitgutter). Currently I set a date as package version because you don't have any release.

So here is my question: do you plan to make a release of your plugin ? It would be really useful to follow upgrades, fixes, etc.

Kind regards,

**Comment by airblade** [comment]
Hi Raphaël,

I understand the benefits of making proper releases.  However, for some reason, unlike the other software I write, this plugin doesn't seem to naturally fit a major.minor.patch release cycle (see #491).  It always feels "done" to me and each commit feels like a patch update; and I'm not sure how useful it is to have x.y.z where x and y never change and z just increases indefinitely.

**Comment by rmedaer** [comment]
> (...) to naturally fit a major.minor.patch release cycle (see #491)

Didn't see #491. Sorry for the duplicate.

>  (...) and I'm not sure how useful it is to have x.y.z where x and y never change and z just increases indefinitely.

Your versioning scheme doesn't have to be x.y.z. It could be only one digit. It's useful in a sense that it to tell the users: _this particular commit is "ready to go", you can upgrade right now_.

In non-rolling-release model, it helps package maintainers to know when they should (or not) publish a new version.

Btw I understand your opinion and I'll keep a date as version. Although I'll prefix the Debian package with a `0~` in case you change your mind.
