### ISSUE TITLE
New gitgutter coloring change

### ISSUE THREAD

**Issue by ckipp01** [airblade/vim-gitgutter#701]
> What is the latest commit SHA in your installed vim-gitgutter?

3cb5cbf

> What vim/nvim version are you on?

NVIM v0.5.0-c9f4cac

I see that you've changed the way the coloring for gitgutter is being set in the last few commits. Probably in relation to #696. I've never had an issue with this, but the latest changes breaks for me, and now I'm stuck with all grey signs...

<img width="68" alt="Screenshot 2020-04-25 at 13 59 27" src="https://user-images.githubusercontent.com/13974112/80279306-019aee00-86fd-11ea-8b8e-6b2ef11d287d.png">

In the documentation I'm now seeing the following:

> If you or your colourscheme has defined `GitGutter*` highlight groups, the plugin will use those for the signs' colours. The signs' background colours will all be set to the sign column's background colour.
Otherwise it will use your colourscheme's `Diff*` highlight groups.

That doesn't seem to be the case. When I look at my `:highlight` groups, they are there, but they aren't being used.

<img width="153" alt="Screenshot 2020-04-25 at 14 01 06" src="https://user-images.githubusercontent.com/13974112/80279327-3eff7b80-86fd-11ea-8077-9e52c4efbda2.png">

I'm I missing something? I really don't want to add in custom settings just to get the colors to display right when they have always worked for me.

Even if I try to now manually link it, it doesn't change anything. For example:
```vim
highlight link GitGutterAddLine DiffAdd 
```

I've tried on both the [light theme I use](https://github.com/rakr/vim-one) and the [dark theme](https://github.com/joshdick/onedark.vim).

**Comment by airblade** [comment]
Ah, it's because the colourscheme defines `GitGutterAdd` et al but as links, rather than in their own right.  I'll fix it.

By the way, you want `GitGutterAdd`, not `GitGutterAddLine`, for the signs in the sign column.

**Comment by ckipp01** [comment]
Ahh, indeed, that fixes it. Thanks!!

**Comment by dawsers** [comment]
My theme defines `diff{Added,Changed,Removed}` and the new change in `autoload/gitgutter/highlight.vim` overwrites them.

https://github.com/airblade/vim-gitgutter/commit/8a380e2f9054d0f20f4284150c8c33e750f047e8

Fugitive also uses the values for diffing in the status window.

Do I need to do something special in my theme or configuration file?

**Comment by airblade** [comment]
@dawsers The latest commit (f411d86) should leave your `diff*` groups intact.

Out of curiosity, does the intra-line highlighting in the preview window work properly for you?  (See the screenshot in the readme for an example, where the brackets are highlighted in reverse.)

**Comment by dawsers** [comment]
Thanks a lot for the fix!

I get exactly the same as in the readme, the brackets are highlighted in reverse.  And if I change more text, everything I change inverts the highlighting too, so it seems to be working

![readme](https://user-images.githubusercontent.com/47487972/80288861-35950400-873b-11ea-8b97-d3a23024de4a.png)

**Comment by airblade** [comment]
Great!  Thanks for confirming.
