### ISSUE TITLE
Can't not have git in path

### ISSUE THREAD

**Issue by normen** [airblade/vim-gitgutter#702]
Hi,

first of all thanks for this plugin, it's a staple in my VIM arsenal.

When running VIM with gitgutter installed on a system that doesn't have a `git` executable a warning message is issued on VIM startup. This can not be avoided, even if checking for the git executable in `.vimrc` like this:

```
if !executable('git')
 let g:gitgutter_enabled = 0
endif
```

Why install gitgutter on a system that has no git you ask? Because I am syncing my `.vim` folder across machines and some don't have git.

Adding the following somewhat solves the issue but only on systems where `/bin/true` is available, I am also running VIM on iPad where that isn't the case.

```
 let g:gitgutter_git_executable = '/bin/true'
```

Maybe you can somehow make gitgutter handle a nonexisting git executable more gracefully? Especially when it's nominally disabled.

Thanks for the attention,
Normen Hansen

> What is the latest commit SHA in your installed vim-gitgutter?
Commit# f411d86

> What vim/nvim version are you on?
VIM Version: 8.1

**Comment by airblade** [comment]
Hi Normen,

Does this help?

```diff
diff --git i/plugin/gitgutter.vim w/plugin/gitgutter.vim
index 33f0b07..fd61bfc 100644
--- i/plugin/gitgutter.vim
+++ w/plugin/gitgutter.vim
@@ -70,6 +70,7 @@ call s:set('g:gitgutter_use_location_list',              0)
 call s:set('g:gitgutter_git_executable', 'git')
 if !executable(g:gitgutter_git_executable)
   call gitgutter#utility#warn('cannot find git. Please set g:gitgutter_git_executable.')
+  finish
 endif
 
 let default_grep = 'grep'
```

**Comment by normen** [comment]
This seems to be what I want:
```
--- a/plugin/gitgutter.vim
+++ b/plugin/gitgutter.vim
@@ -64,7 +64,7 @@ call s:set('g:gitgutter_log',                            0)
 call s:set('g:gitgutter_use_location_list',              0)
 
 call s:set('g:gitgutter_git_executable', 'git')
-if !executable(g:gitgutter_git_executable)
+if !executable(g:gitgutter_git_executable) && g:gitgutter_enabled
   call gitgutter#utility#warn('cannot find git. Please set g:gitgutter_git_executable.')
 endif
```

**Comment by airblade** [comment]
Thanks for the feedback.

**Comment by normen** [comment]
Thank you! 🙂
