### ISSUE TITLE
warning about nonexistant config settings

### ISSUE THREAD

**Issue by normen** [airblade/vim-gitgutter#703]
With the latest version I'm getting the following error on VIM startup although I have no gitgutter configuration values set:

`vim-gitgutter: g:gitgutter_override_sign_column_highlight is obsolete and has no effect.`

> What is the latest commit SHA in your installed vim-gitgutter?
76d1cf6

> What vim/nvim version are you on?
VIM - Vi IMproved 8.2 (2019 Dec 12 kompiliert am Apr 29 2020 01:33:43)                                                                                                            
MacOS Version                                                                                                                                                                     
Inklusive der Patches: 1-654

**Comment by airblade** [comment]
That's weird.  I wonder if you have a colorscheme that sets this?

**Comment by vanhtuan0409** [comment]
Seems like gruvbox colorscheme is calling git gutter
![image](https://user-images.githubusercontent.com/8175932/80792172-0f99b480-8bbe-11ea-8b58-5ac2f76dcafa.png)

**Comment by vanhtuan0409** [comment]
may I know what is the equivalent of `gitgutter_override_sign_column_highlight` now? I can send a PR to gruvbox

**Comment by airblade** [comment]
@vanhtuan0409 Thank you.  Please see 0da302c2.

Previously gitgutter did this:

```viml
   if g:gitgutter_override_sign_column_highlight
     highlight! link SignColumn LineNr
   else
     highlight default link SignColumn LineNr
   endif
 endfunction
```

– where `g:gitgutter_override_sign_column_highlight` was set to `1` by default.

Now gitgutter doesn't touch the `SignColumn`.  It's entirely up to the colorscheme and user how they want the `SignColumn` to look.

**Comment by airblade** [comment]
I removed the warning in 4802c04.
