### ISSUE TITLE
vim-gitgutter: g:gitgutter_override_sign_column_highlight is obsolete and has no effect.

### ISSUE THREAD

**Issue by toomding** [airblade/vim-gitgutter#704]
> What is the latest commit SHA in your installed vim-gitgutter?
76d1cf609dbb00673a6e221f84a063c816d8eecb , latest commit 
> What vim/nvim version are you on?
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 26 2020 11:23:21)

I only have this two setting in my vimrc
let g:gitgutter_enable=1
let g:gitgutter_map_keys=0
Nothing else in my vimrc.

it constantly pop up this sentence when i open vim, but it doesn't affect my normal using , it still work but very annoying since every time i open vim : 
"vim-gitgutter: g:gitgutter_override_sign_column_highlight is obsolete and has no effect." 

i try to comment all my setting to isolate the problem and only left a vim-plug setting which is about vim-gitgutter.

how can i disable such notifications?

Help, do i need to add something else to my vimrc ?

**Comment by airblade** [comment]
It must be coming from a colorscheme.

Anyway, I've removed the warning in 4802c04.

**Comment by toomding** [comment]
Thank you so much, Be safe. it works.

**Comment by toomding** [comment]
By the way, my colorscheme is gruvbox.

**Comment by airblade** [comment]
Gruvbox sets that variable.
