### ISSUE TITLE
GitGutter fails my :cfdo command

### ISSUE THREAD

**Issue by lourenci** [airblade/vim-gitgutter#706]
Have you ever had some errors like that?

![image](https://user-images.githubusercontent.com/2339362/82051521-66a88a80-9690-11ea-97f6-f2c4d07dfd21.png)

It always happens when I try to do some command in a big quickfix list . This is the command I executed in the error above:

`:cfdo noautocmd %s/btn-fix-margin/ml-1/g | update`

Thanks for the plugin.

> What is the latest commit SHA in your installed vim-gitgutter?
`HEAD`
> What vim/nvim version are you on?
`nvim 0.5.0`

**Comment by airblade** [comment]
Never seen it but I never use the quickfix list like that.

How many entries are we talking about here?

Does it help if you also prefix the `update` with a `noautocmd`?

**Comment by lourenci** [comment]
> How many entries are we talking about here?

240 items. I though it was more.

> Does it help if you also prefix the `update` with a `noautocmd`?

Not at all. I tried `:cfdo! noautocmd %s/btn-fix-margin/ml-1/g | noautocmd update` too.

**Comment by airblade** [comment]
For whatever reason the `noautocmd` is not preventing `BufEnter` from firing and in turn executing vim-gitgutter, which is trying to fire off 240+ async jobs, which evidently is too many for the system.

A workaround would be to turn GitGutter off before and on after.

```
:GitGutterDisable
:cfdo ...
:GitGutterEnable
```

But that's a bit tedious.

Ideally the plugin would be able to detect whether Vim was in the middle of a `cfdo` command – however I don't know how.

**Comment by lourenci** [comment]
I was reopening the `vim` without the plugins to perform this kind of work. 

Just out of the curiosity, do your mind sharing your workflow when you have to perform a long search & replace in your "workspace"? I find easier to `:grep` and after that iterate over the quickfix list with the `:cfdo %s` vim command.

**Comment by airblade** [comment]
I rarely have to do a big search and replace so I haven't bothered optimising my workflow.  I just grep for the text to replace and replace each one manually.

I think this should do what you want:

```viml
command! -nargs=+ Cfdo GitGutterDisable | execute 'cfdo <args> | update' | GitGutterEnable
```
