### ISSUE TITLE
Running a macro that writes to 50+ files fails due to 'too many open files'

### ISSUE THREAD

**Issue by Nitrodist** [airblade/vim-gitgutter#707]
# Description

I was making an edit to 435 files via `vim *` and I then wanted to add a line to the end of each file - so I wrote a macro like `qa0gifoo<esc>:w<cr>:n` and then `435@a`. After like 50 files this happened:

<img width="1657" alt="Screen Shot 2020-05-21 at 8 30 42 AM" src="https://user-images.githubusercontent.com/385448/82564528-87645a80-9b3e-11ea-83ac-c313ad354885.png">

vim info:

```
vim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

vim-gitgutter info:

```
commit b356cc9a7da08ebeb919cd04b2831dad71a34d38 (HEAD -> master, origin/master, origin/HEAD)
Author: Andy Stewart <boss@airbladesoftware.com>
Date:   Fri May 1 16:13:53 2020 +0100

    Set background colour on GitGutterChangeDelete
```

**Comment by airblade** [comment]
This is similar to #706.

Every file you enter triggers an asynchronous diff in a new process but the shell can only handle so many all at once.  I'm not sure what the precise constraint is which makes it hard for the plugin to anticipate the failure.

All I can suggest is you `:GitGutterDisable` before executing your macro and `:GitGutterEnable` afterwards.

**Comment by jeffvandyke** [comment]
Thanks, ran into this same issue using `:Ack` and `:cdo` to do global find/replace. It would be nice if gitgutter was able to detect this kind of automatic editing scenario, even a cancellable timeout on buffer open before starting the async process might suffice.

**Comment by airblade** [comment]
I agree, it would be nice if gitgutter could detect that kind of thing, but I don't know of a way that it can.  If you know, I'd love to hear.

As a workaround you could add some commands like this:

```
command! -nargs=+ Cfdo GitGutterDisable | execute 'cfdo <args> | update' | GitGutterEnable
```

Then you can do `:Cfdo %s/foo/bar/g` instead of `:cfdo %s/foo/bar/g`.

A cancellable timeout is an interesting idea but I don't want to add any visual delay to the signs being updated.
