### ISSUE TITLE
Preview Window is messed up (Too long?)

### ISSUE THREAD

**Issue by qazip** [airblade/vim-gitgutter#708]
> What is the latest commit SHA in your installed vim-gitgutter?
How do I check that? I have it installed with VimPlug and just recently did an update, so it is the latest version.

> What vim/nvim version are you on?
NVIM v0.5.0-447-g8745247cb

When doing GitGutterPreviewHunk on a changed hunk, I should be able to see the whole line so I am able to see the changes. This is not true, the line gets cut-off before the changes are actually shown. This is for a long (markdown) line, however.

**Would it be possible to show the preview-window in a new window and not as a popup/floating?** Or just show it as actual text, like sublime-text does?

EDIT:
I've tried adding `let g:gitgutter_preview_win_location = 'bel'` (or 'abo' or 'to') to my init.vim  but nothing changes..

**Comment by airblade** [comment]
You can do `let g:gitgutter_preview_win_floating = 0` to see the diff in a "normal" preview window rather than a floating one.

**Comment by qazip** [comment]
Ah, cool! How do I change the height of this new window? Any option for that?

**Comment by qazip** [comment]
Weirdly enough, set previewheight=50 (or any other value) doesn't change anything. But alright, this is now a (neo)vim issue! Thanks @airblade !

**Comment by airblade** [comment]
More specifically, the preview window's height is set to the smaller of the diff's height and `&previewheight`.

https://github.com/airblade/vim-gitgutter/blob/b356cc9a7da08ebeb919cd04b2831dad71a34d38/autoload/gitgutter/hunk.vim#L463

https://github.com/airblade/vim-gitgutter/blob/b356cc9a7da08ebeb919cd04b2831dad71a34d38/autoload/gitgutter/hunk.vim#L499

**Comment by qazip** [comment]
Hey @airblade, sorry for bothering you again!

I haven't been able to fix this. Doing "set previewheight = 30" (or whatever number) doesn't seem to help, so I guess it is being decided by the "diff's height". How would I change that?

**Comment by airblade** [comment]
I'm not sure what you're trying to fix.  Are you trying to get the preview window to always be 50 (or 30 or whatever you set) lines high, even if the diff it's showing is only 10 lines?

If so, there's no built-in way to change that.  If `previewheight` is 50 and the diff is 10 lines long, the preview window will be 10 lines high.  If the diff is 60 lines long, the preview window will be 50 lines high.

The only way to change this is to comment out line 499 linked above in your copy of vim-gitgutter.

**Comment by qazip** [comment]
Well, I would like the preview-window to show the whole difference. Here is my use case:

- Have a 2 line sentence/hunk;
- Change something on that sentence/hunk;
- See the change using GitPreviewHunk;

It will only show 2 lines, so it will only show the red and not the green. I would like to see the red and the green at the same time. This works if the changed sentence/hunk is only 1 line long. If the hunk is more than 2 lines, then it won't even show the whole hunk as red, and so I have to scroll down to see the whole thing..

**Comment by airblade** [comment]
What is your `previewheight` value?

**Comment by qazip** [comment]
`set previewheight=30`

**Comment by airblade** [comment]
Please can you send me a screenshot of the situation you described just above?  I'm not 100% sure I understand what you're seeing.

**Comment by qazip** [comment]
Sure. First picture shows that it is only showing 2 lines. Second picture shows the whole hunk with "Git diff" from Vim-Fugitire.

![gitgutter1](https://user-images.githubusercontent.com/16175716/83242219-8f01b000-a18b-11ea-9456-cfef8bc34bc3.png)

![gitgutter2](https://user-images.githubusercontent.com/16175716/83242232-91fca080-a18b-11ea-93dc-298240a22c2f.png)

**Comment by airblade** [comment]
Ah, I see now.  Thanks for the screenshots.

So the preview window is working on screen lines, not "real" lines.  I'll come up with a fix...
