### ISSUE TITLE
Feature request: highlight merge conflict sections

### ISSUE THREAD

**Issue by xaljer** [airblade/vim-gitgutter#710]
Like VS Code, highlight the git merge conflict sections and give commands to select one of branch to merge.
![image](https://user-images.githubusercontent.com/8309631/83933821-96a20400-a7de-11ea-9141-0651f995df14.png)

- Accept current change
- Accept incoming change
- Accept both change

**Comment by airblade** [comment]
I'm in two minds about this.

On the one hand, it's a useful feature.

On the other, it doesn't really cohere with the plugin's current features.

**Comment by xaljer** [comment]
I think the basic functions of gitgutter is to show git status and operate on them. It can show the status of changes, it's also suit to show the status of merge conflict. It can jump around changes, it also suit to jump around conflict sections. It can stage/unstage change, it also suit to merge/refuse changes.
I also request this feature on coc-git, which has similar features with gitgutter. Would you like to implement this feature? :-)

**Comment by airblade** [comment]
I suppose this falls into the category of staging hunks so I can add this to the plugin.

P.S. Other plugins' features are irrelevant.

**Comment by ytian81** [comment]
FWIW, https://github.com/rhysd/conflict-marker.vim provides such functionality.

**Comment by airblade** [comment]
@ytian81 Thank you!  I didn't know about that plugin.

@xaljer If you install conflict-marker.vim you can use that to resolve merge conflicts, then stage the result with vim-gitgutter as normal.

**Comment by xaljer** [comment]
@airblade  @ytian81 thanks.
