### ISSUE TITLE
Hunk preview gives errors when using popup window in neovim.

### ISSUE THREAD

**Issue by AitBits** [airblade/vim-gitgutter#711]
> What is the latest commit SHA in your installed vim-gitgutter?
commit 9784226ba766662d298554a5c66fd938497f2233

> What vim/nvim version are you on?
v0.4.3

Error message:
```
`Error detected while processing function gitgutter#hunk#preview[3]..<SNR>124_hunk_op[62]..<SNR>124_preview[6]..<SNR>124_populate_hunk_preview_window:
line   11:
E5555: API call: Vim:E315: ml_get: invalid lnum: 2
line   12:
E5555: API call: Vim:E315: ml_get: invalid lnum: 2
```

Error is caused by two function calls
`call nvim_win_set_width(s:winid, width)`
`call nvim_win_set_height(s:winid, height)`
from `s:populate_hunk_preview_window` function defined in hunk.vim.

Replacing said lines with 
`call nvim_win_set_config(s:winid, {'width': width,'height': height})`
fixes the issue for me.

**Comment by airblade** [comment]
That's odd.  It works for me with nvim 0.5.0.  I think it worked for me on 0.4.3 but I can't say for sure.

**Comment by AitBits** [comment]
It seems like `set scrolloff=999` in my init.vim is somehow causing trouble.

**Comment by airblade** [comment]
Thanks for finding the problem.
