### ISSUE TITLE
Bg color set only after reloading .vimrc

### ISSUE THREAD

**Issue by mredaelli** [airblade/vim-gitgutter#714]
> What is the latest commit SHA in your installed vim-gitgutter?

e31e9bb35f7

> What vim/nvim version are you on?

NVIM v0.4.3

I have this in my config:

```viml
let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '>'
let g:gitgutter_sign_removed = '-'
let g:gitgutter_sign_removed_first_line = '^'
let g:gitgutter_sign_modified_removed = '<'
let g:gitgutter_highlight_linenrs = 1 

source ~/.config/nvim/plugins.vim

set background=dark
let g:jellybeans_use_term_italics = 1
colorscheme jellybeans

highlight GitGutterAdd    guibg=yellow ctermbg=yellow
highlight GitGutterChange guibg=green ctermbg=green
highlight GitGutterDelete guibg=red ctermbg=red
```

When first opening vim, the background color of the gutter column is not set. When I reload the configuration with
`:so $MYVIMRC`, then it is set correctly.

I'm sure I'm missing something obvious...

**Comment by airblade** [comment]
The plugin no longer sets the sign column's colour (0da302c28a08fe62c31c77ac854914affd2180b8).  In the jellybeans repo the [sign column and the line number column](https://github.com/nanotech/jellybeans.vim/blob/ef83bf4dc8b3eacffc97bf5c96ab2581b415c9fa/colors/jellybeans.vim#L461-L473) have different colours:

```viml
call s:X("LineNr","605958",s:background_color,"NONE",s:termBlack,"")
call s:X("SignColumn","777777","333333","","",s:termBlack)
```

I'm not sure why reloading your config changes the sign column's colour.  Do you have any colorscheme autocommands?

**Comment by airblade** [comment]
> the background color of the gutter column is not set.

I assume you mean the whole sign column, not just the signs' backgrounds.

**Comment by mredaelli** [comment]
My bad, I'm very sorry: I had leftovers in another sourced config file. It works perfectly, thank you very much!
