### ISSUE TITLE
QuickFix list is relative to root of workspace...

### ISSUE THREAD

**Issue by cpakkala** [airblade/vim-gitgutter#715]
> What is the latest commit SHA in your installed vim-gitgutter?
e31e9bb35f7346caab4fcf972d44449bdfd3230a

> What vim/nvim version are you on?
nvim 0.4.3

:GitGutterQuickFix populates the list with paths relative to the git workspace root.  It would be great if the list was relative to the current working directory, since we don't all work at the root of the workspace.  In particular, as in my case, when managing one's dotfiles via:  let g:gitgutter_git_args = "--git-dir=$HOME/.config.git/ --work-tree=$HOME"

I was excited about this quickfix feature, but as it stands, I can't use it.

**Comment by airblade** [comment]
`GitGutterQuickFix` doesn't change to the repo root before running `git diff`.  It's just that `git diff` reports files with paths relative to the repo root.

Ideally there would be an option for `git diff` to tell it to report paths relative to the current directory but I'm not aware of one.  Are you?

If there isn't a way to do it with `git diff` we would have to do it in vimscript.  In theory it should be straightforward but inevitably there would be annoying problems with escaping spaces and different path separators etc.

**Comment by airblade** [comment]
`--relative` is close but it ignores changes outside the current working directory.

**Comment by cpakkala** [comment]
> `--relative` is close but it ignores changes outside the current working directory.

Actually, that probably is better behavior because it allows the user to choose which directory tree to diff.  They can move to the root if they want the full workspace diffed.  It's also the behavior of https://github.com/git/git/tree/master/contrib/git-jump

Maybe creating an option for the user to set?

**Comment by cpakkala** [comment]
I guess I'm not the only one who's had this issue.  Greg Hurrell's solution was to query for the root workspace dir and prepend that to the results to make them absolute:
https://github.com/wincent/vcs-jump/blob/master/bin/vcs-jump

Although that does take up more line space in the quickfix window.

**Comment by airblade** [comment]
> Maybe creating an option for the user to set?

You can already set `g:gitgutter_diff_args` to `--relative`.  Here's the code:

**Comment by airblade** [comment]
> query for the root workspace dir and prepend that to the results to make them absolute

I was thinking the same thing, perhaps using `--src-prefix` and `--dst-prefix`.

**Comment by airblade** [comment]
One way to get relative paths would be to use [`git rev-parse --show-cdup`](https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---show-cdup) and prepend that to each location.

However if you changed your directory at some point, the relative paths would become wrong.  I'm assuming Vim treats non-absolute quickfix paths as relative to the current window's directory if set or the global working directory.  When jumping to entries with `:cnext` I wonder if the quickfix list's window's directory is used, or the actual current window.

**Comment by airblade** [comment]
Does this work for you:

```diff
diff --git i/autoload/gitgutter.vim w/autoload/gitgutter.vim
index 4bb0872..b83e424 100644
--- i/autoload/gitgutter.vim
+++ w/autoload/gitgutter.vim
@@ -180,9 +180,14 @@ endfunction
 " - it ignores unsaved changes in buffers
 " - it does not change to the repo root
 function! gitgutter#quickfix()
+  let cmd = g:gitgutter_git_executable.' rev-parse --show-cdup'
+  let path_to_repo = systemlist(cmd)[0]
+
   let locations = []
   let cmd = g:gitgutter_git_executable.' '.g:gitgutter_git_args.' --no-pager'.
-        \ ' diff --no-ext-diff --no-color -U0 '.g:gitgutter_diff_args. ' '. g:gitgutter_diff_base
+        \ ' diff --no-ext-diff --no-color -U0'.
+        \ ' --src-prefix=a/'.path_to_repo.' --dst-prefix=b/'.path_to_repo.' '.
+        \ g:gitgutter_diff_args. ' '. g:gitgutter_diff_base
   let diff = systemlist(cmd)
   let lnum = 0
   for line in diff
```

**Comment by cpakkala** [comment]
> Does this work for you?
> 
> ```diff
> diff --git i/autoload/gitgutter.vim w/autoload/gitgutter.vim
> index 4bb0872..b83e424 100644
> --- i/autoload/gitgutter.vim
> +++ w/autoload/gitgutter.vim
> @@ -180,9 +180,14 @@ endfunction
>  " - it ignores unsaved changes in buffers
>  " - it does not change to the repo root
>  function! gitgutter#quickfix()
> +  let cmd = g:gitgutter_git_executable.' rev-parse --show-cdup'
> +  let path_to_repo = systemlist(cmd)[0]
> +
>    let locations = []
>    let cmd = g:gitgutter_git_executable.' '.g:gitgutter_git_args.' --no-pager'.
> -        \ ' diff --no-ext-diff --no-color -U0 '.g:gitgutter_diff_args. ' '. g:gitgutter_diff_base
> +        \ ' diff --no-ext-diff --no-color -U0'.
> +        \ ' --src-prefix=a/'.path_to_repo.' --dst-prefix=b/'.path_to_repo.' '.
> +        \ g:gitgutter_diff_args. ' '. g:gitgutter_diff_base
>    let diff = systemlist(cmd)
>    let lnum = 0
>    for line in diff
> ```

After adding the g:gitgutter_git_args to the first cmd string as well, it did indeed work perfectly.  Thank you!:

let cmd = g:gitgutter_git_executable.' '.g:gitgutter_git_args.' rev-parse --show-cdup'

**Comment by cpakkala** [comment]
Actually, after testing all the corner cases, the path_to_repo needed a bit more tweaking.  Here's what worked for me:
```diff

diff --git a/autoload/gitgutter.vim b/autoload/gitgutter.vim
index 4bb0872..2bfaeb9 100644
--- a/autoload/gitgutter.vim
+++ b/autoload/gitgutter.vim
@@ -180,9 +180,17 @@ endfunction
 " - it ignores unsaved changes in buffers
 " - it does not change to the repo root
 function! gitgutter#quickfix()
+  let cmd = g:gitgutter_git_executable.' '.g:gitgutter_git_args.' rev-parse --show-cdup'
+  let path_to_repo = get(systemlist(cmd), 0, "")
+  if ( len(path_to_repo) > 0 && path_to_repo[-1:] != '/' )
+         let path_to_repo .= '/'
+  endif
+
   let locations = []
   let cmd = g:gitgutter_git_executable.' '.g:gitgutter_git_args.' --no-pager'.
-        \ ' diff --no-ext-diff --no-color -U0 '.g:gitgutter_diff_args. ' '. g:gitgutter_diff_base
+        \ ' diff --no-ext-diff --no-color -U0'.
+        \ ' --src-prefix=a/'.path_to_repo.' --dst-prefix=b/'.path_to_repo.' '.
+        \ g:gitgutter_diff_args. ' '. g:gitgutter_diff_base
   let diff = systemlist(cmd)
   let lnum = 0
   for line in diff

```

**Comment by airblade** [comment]
Please could you list your corner cases?

> let path_to_repo = get(systemlist(cmd), 0, "")

Why do you need to provide a default value?

>  if ( len(path_to_repo) > 0 && path_to_repo[-1:] != '/' )
>    let path_to_repo .= '/'
>  endif

I thought a non-empty path to the repo would always end in `/`.  When does it not?

**Comment by cpakkala** [comment]
> Please could you list your corner cases?
> 
> ```diff
> + let path_to_repo = get(systemlist(cmd), 0, "")
> ```
> 
> Why do you need to provide a default value?
> 
> ```diff
> +  if ( len(path_to_repo) > 0 && path_to_repo[-1:] != '/' )
> +    let path_to_repo .= '/'
> +  endif
> ```
> 
> I thought a non-empty path to the repo would always end in `/`. When does it not?

This answers all above questions:

1) If CWD is "above" /home/user (example: /tmp, results in absolute path to home dir with no trailing slash):
$ git --git-dir=/home/user/.config.git/ --work-tree=/home/user rev-parse --show-cdup
/home/kyndig
2) If CWD is /home/user: (results in nothing)
$ git --git-dir=/home/user/.config.git/ --work-tree=/home/user rev-parse --show-cdup

3) if CWD is "below" /home/user: (ex: /home/user/tmp, results in relative path ending with slash)
$ git --git-dir=/home/user/.config.git/ --work-tree=/home/user rev-parse --show-cdup
../
4) Without "--git-dir=/home/user/.config.git/ --work-tree=/home/user rev-parse", there are only 2 cases; at the root of the repo or below it and they correspond to the last two cases above.

**Comment by cpakkala** [comment]
git may return an empty string, but systemlist doesn't treat it as an element, probably because it's meant to behave like shell.  Try this in vim:

```vim
:let a = systemlist("echo  ''")
echo a[0]
```
You get an error:

> list index out of range: 0

**Comment by airblade** [comment]
Aha, that doesn't give an error in vim, only in neovim.

**Comment by cpakkala** [comment]
> Aha, that doesn't give an error in vim, only in neovim.

Wha...?   Doesn't everyone use neovim ;)
