### ISSUE TITLE
Question: Run a oneshot diff synchronously?

### ISSUE THREAD

**Issue by somini** [airblade/vim-gitgutter#716]
I sometimes work on computers with a very slow disk, so I disable the automatic git diff. Still, I would like to be able to run GitGutter on a keybinding, in a "oneshot" mode. Meaning it should run whatever git commands, show the gutter and don't run `git` anymore.

I'm using this workaround:

```vim
" One-shot "diff"
function! s:DiffOneShot_GitGutter()
	call gitgutter#buffer_enable()
	GitGutter
	sleep 500 m
	call gitgutter#utility#setbufvar(bufnr(), 'enabled', 0)
endfunction
```

So I'm requesting 2 things:
- A way to run `GitGutter` synchronously
- An option to disable the buffer without blowing away the existing data (not the default)

Note this is a rare thing, if this is too much work it's fine to close this.

**Comment by airblade** [comment]
To run `GitGutter` synchronously: `let g:gitgutter_async = 0`.

I think you've already got the best way to turn off GitGutter without removing the signs.  I think it's a rare need so I wouldn't build in that feature.

**Comment by airblade** [comment]
Perhaps a better option is to remove all the [autocmds which trigger GitGutter](https://github.com/airblade/vim-gitgutter/blob/97a24e903a7841f410903087c19eaf728668ec81/plugin/gitgutter.vim#L238-L281):

```viml
autocmd! gitgutter
```

Then just call `GitGutter` whenever you want.

**Comment by somini** [comment]
> Perhaps a better option is to remove all the [autocmds which trigger GitGutter](https://github.com/airblade/vim-gitgutter/blob/97a24e903a7841f410903087c19eaf728668ec81/plugin/gitgutter.vim#L238-L281):
> 
> ```viml
> autocmd! gitgutter
> ```
> 
> Then just call `GitGutter` whenever you want.

This is the best option, thanks.
