### ISSUE TITLE
Remapped GitGutterPreviewHunk does nothing

### ISSUE THREAD

**Issue by roblevy** [airblade/vim-gitgutter#717]
I've remapped preview to `<leader>cp` using `nnoremap <leader>cp <Plug>(GitGutterPreviewHunk)
` in my vimrc.

To confirm:
```
:map <leader>cp
n  \cp         * <Plug>(GitGutterPreviewHunk)
```

But typing `<leader>cp` on a hunk does nothing.

I can invoke the preview just fine when I do:

```
:GitGutterPreviewHunk
```

I can also invoke the preview using the default `<leader>hp`.

I've also tried removing the brackets around my `nnoremap` command:

```
nnoremap <leader>cp <Plug>GitGutterPreviewHunk
```

but it still doesn't work.

> What is the latest commit SHA in your installed vim-gitgutter?
faf2581

> What vim/nvim version are you on?
NVIM v0.5.0-551-gdbc8ec944

**Comment by airblade** [comment]
I think the problem is the noremap.  Try `nmap <leader>cp <Plug>(GitGutterPreviewHunk)`.

**Comment by roblevy** [comment]
Yeah, that works! Thanks so much.
