### ISSUE TITLE
Use <Esc> to close preview window

### ISSUE THREAD

**Issue by NGPONG** [airblade/vim-gitgutter#718]
> What is the latest commit SHA in your installed vim-gitgutter?
faf2581f00898e4282b846a86652f94dba75c79b
> What vim/nvim version are you on?
0.4.3

As the title suggests, it would be very convenient to be able to close the preview window with `<Esc>`

**Comment by airblade** [comment]
Closing a preview window with `<Esc>` isn't usual Vim/Neovim behaviour so I'm reluctant to add it.

Are you using floating preview windows in Neovim?  If so, just moving the cursor one character will close the preview.

**Comment by NGPONG** [comment]
Yep I am using neovim, but I am not using the floating window that neovim supports to display the diff individual hunks.

The reason for this is that the coc and leaderf I'm using both support closing the preview window with `<Esc>`, and I'm used to actually closing it with `<Esc>`.

Maybe I'm just trying to make my vim conform to a certain specification (just my own). Anyway, thanks for your response, and thank for created such a powerful and beautiful plugin.

**Comment by airblade** [comment]
Thanks for the extra detail.  I presume when you press `<Esc>` to close the preview window, your cursor is in it?  If so, does this work for you?

```diff
diff --git i/autoload/gitgutter/hunk.vim w/autoload/gitgutter/hunk.vim
index f80e93a..7ccbc16 100644
--- i/autoload/gitgutter/hunk.vim
+++ w/autoload/gitgutter/hunk.vim
@@ -455,6 +455,7 @@ function! s:open_hunk_preview_window()
   setlocal filetype=diff buftype=acwrite bufhidden=delete
   " Reset some defaults in case someone else has changed them.
   setlocal noreadonly modifiable noswapfile
+  nnoremap <buffer> <silent> <Esc> :pclose<CR>
 endfunction
 ```

The line wrap symbol is very useful.  It's core Vim/Neovim:

```viml
set breakindent
set breakindentopt=sbr
" Unicode curly arrow, space
set showbreak=↪ 
```

**Comment by NGPONG** [comment]
> Thanks for the extra detail. I presume when you press `<Esc>` to close the preview window, your cursor is in it? If so, does this work for you?
> 
> ```diff
> diff --git i/autoload/gitgutter/hunk.vim w/autoload/gitgutter/hunk.vim
> index f80e93a..7ccbc16 100644
> --- i/autoload/gitgutter/hunk.vim
> +++ w/autoload/gitgutter/hunk.vim
> @@ -455,6 +455,7 @@ function! s:open_hunk_preview_window()
>    setlocal filetype=diff buftype=acwrite bufhidden=delete
>    " Reset some defaults in case someone else has changed them.
>    setlocal noreadonly modifiable noswapfile
> +  nnoremap <buffer> <silent> <Esc> :pclose<CR>
>  endfunction
> ```
> 
> The line wrap symbol is very useful. It's core Vim/Neovim:
> 
> ```viml
> set breakindent
> set breakindentopt=sbr
> " Unicode curly arrow, space
> set showbreak=↪ 
> ```

It's cool! seem work for me.

**Comment by airblade** [comment]
Once you add `let g:gitgutter_close_preview_on_escape=1` in your vimrc this will work for you.

**Comment by sammorley-short** [comment]
Setting `let g:gitgutter_close_preview_on_escape=1` didn't enable this for me. Running `pclose` when the window is open didn't work either. 

Context: I am running nvim, any idea what might be causing this? 

Thanks!

**Comment by airblade** [comment]
@sammorley-short Are you using the floating preview window or ordinary ones?

**Comment by sammorley-short** [comment]
The floating window setting activated via `let g:gitgutter_preview_win_floating = 1`.

**Comment by sammorley-short** [comment]
More info: if I launch nvim without a config file (`nvim -u None`), install GitGutter and then try again, then I can repro the same bug, so it's not something about my nvim config.

**Comment by airblade** [comment]
@sammorley-short The `g:gitgutter_close_preview_on_escape` only applied to non-floating preview windows.  I have updated the code so it works with floating preview windows too.

**Comment by sammorley-short** [comment]
@airblade Thanks! Works like a charm. 🚀
