### ISSUE TITLE
E45: 'readonly' option is set (add ! to override) in .git/COMMIT_EDITMSG with vim-fugitive

### ISSUE THREAD

**Issue by cyrus-and** [airblade/vim-gitgutter#720]
> What is the latest commit SHA in your installed vim-gitgutter?

`c27bfab8c51e77419ee0c4a9c4e3ba359dbc2ad4` (current `master` branch)

> What vim/nvim version are you on?

```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 17 2020 17:49:10)
macOS version
Included patches: 1-503, 505-680, 682-2292
Compiled by root@apple.com
Normal version without GUI.
```

---

## Minimal `.vimrc`

```vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
call vundle#end()
```

Initialise as usual:

```
$ git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
:PluginInstall
```

## Steps to reproduce

```
git init foo
cd foo
echo foo >foo
vim .
:G
<C-n>scc:w
```

This exact sequence of operations is needed, e.g., it does not happen if I `git add foo` outside Vim.

**Comment by airblade** [comment]
What does `:G<C-n>` do?  Nothing happens when I type that.

**Comment by cyrus-and** [comment]
Oh sorry for the unclear instructions, edited. `:G` is the command then in the new window `<C-n>` (Ctrl-n) moves to the file to be staged (`foo`).

**Comment by airblade** [comment]
Ah, thanks for the clarification.

So after `<C-n>scc` I have the commit message (`.git/COMMIT_EDITMSG`) in the window.  I can type a message and `:w` as expected.

**Comment by cyrus-and** [comment]
Weird... what Vim version and OS are you using?

**Comment by cyrus-and** [comment]
Also, (kind of Vim n00b here...) how can I debug this? E.g., understand when the readonly flag is set.

**Comment by airblade** [comment]
macOS 10.14.6.

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 11 2020 10:10:21)
macOS version
Included patches: 1-607
Compiled by Homebrew
Huge version with MacVim GUI.
```

vim-gitgutter never sets `readonly`.  Fugitive sets `readonly` in a few places – you could add some `:echom "here"` statements around those calls to figure out where the flag is set.

**Comment by cyrus-and** [comment]
OK so if I switch from VIM 8.1 (macOS default) to VIM 8.2 (Homebrew) then the issue is resolved. Maybe the have a different system-wide configuration...

Thanks for your support!
