### ISSUE TITLE
Centering cursor after next/prev hunk

### ISSUE THREAD

**Issue by mroavi** [airblade/vim-gitgutter#722]
> What is the latest commit SHA in your installed vim-gitgutter?

c27bfab8c51e77419ee0c4a9c4e3ba359dbc2ad4

> What vim/nvim version are you on? 

NVIM v0.5.0-577-g48ac77a14

I like to center the cursor in the middle of the screen after navigating to the next/prev hunk:
```vim
nmap <Leader>j  <Plug>(GitGutterNextHunk)zz
nmap <Leader>k  <Plug>(GitGutterPrevHunk)zz
```

However, with these mappings, the centering of the cursor happens even when there is no next/prev hunk. Can you think of a way to avoid executing `zz` when there are no next/prev hunks?

**Comment by airblade** [comment]
```viml
function! CentreHunk(dir)
  let lnum = line('.')
  execute 'GitGutter'.a:dir.'Hunk'
  if lnum != line('.')
    normal! zz
  endif
endfunction
nmap <Leader>j :call CentreHunk('Next')<CR>
nmap <Leader>k :call CentreHunk('Prev')<CR>
```

**Comment by mroavi** [comment]
Thank you very much! Works great.
