### ISSUE TITLE
Bug: `g:gitgutter_sign_removed_above_and_below` is undocumented

### ISSUE THREAD

**Issue by psliwka** [airblade/vim-gitgutter#723]
Unlike all other signs, `g:gitgutter_sign_removed_above_and_below` is not described in the help page. I just had a hard time finding out what does this `[` mean ;)

**Comment by airblade** [comment]
Calling this a bug is a bit harsh.

**Comment by psliwka** [comment]
Sorry, this wasn't intended to sound harshly in any way. For what it's worth, I sincerely think the work you've put in this plugin is admirable. I consider vim-gitgutter one of my essential tools in day-to-day work, and I just wanted to make future user's experience even more awesome :)
