### ISSUE TITLE
Suggestion: change default `g:gitgutter_sign_removed_above_and_below` to `‾_`

### ISSUE THREAD

**Issue by psliwka** [airblade/vim-gitgutter#724]
Current default value for `g:gitgutter_sign_removed_above_and_below` is `[`. I think `‾_` is both easier to understand and more aesthetically pleasant.

One disadvantage of such change is that the sign consumes twice as much sign column space. However I think it's acceptable, especially since `g:gitgutter_sign_modified_removed` is already two-character wide by default too.

**Comment by airblade** [comment]
I decided against `‾_` originally because the bars are not aligned.  But I suppose it's more consistent with the other signs than `[`.

BTW Vim's sign column is a fixed 2 characters wide.
