### ISSUE TITLE
Turn Of Default Mappings?

### ISSUE THREAD

**Issue by nishantc1527** [airblade/vim-gitgutter#731]
> What is the latest commit SHA in your installed vim-gitgutter?
The latest, name: "Avoid floating preview window immediately closing itself" hash: 8005f71aabef13f5872b3ef4802f36503a16c451.

> What vim/nvim version are you on?
Vim 8.0.

How do I turn of the default mappings? Specifically, these three:

```vim
<leader>hu
<leader>hp
<leader>hs
```

**Comment by airblade** [comment]
```viml
let g:gitgutter_map_keys = 0
```

Source: https://github.com/airblade/vim-gitgutter#key-mappings and `:help gitgutter-mappings`.
