### ISSUE TITLE
Is there a way to uninstall gitgutter?

### ISSUE THREAD

**Issue by jacobduncan00** [airblade/vim-gitgutter#732]
I installed gitgutter and added the vim plug and removed the directories that I installed in the directions and removed the plugin and I still have a bar next to my numbers on the left side even tho there is not an error or git gutter symbols

**Comment by airblade** [comment]
You can check which plugins Vim has loaded with `:scriptnames`, e.g. `:filter gitgutter scriptnames`.  Then you can verify gitgutter is no longer installed.

The sign column is controlled by the 'signcolumn' option.  If its value is `auto`, the sign column will appear when there are signs.  If it's there, and gitgutter isn't installed, then something else is adding signs.  You can see what they are with `:sign place group=*`.
