### ISSUE TITLE
Enhancement Request: Additional fold level for function

### ISSUE THREAD

**Issue by raven42** [airblade/vim-gitgutter#739]
> What is the latest commit SHA in your installed vim-gitgutter?
commit ea79bc01c2efc84cf8e71fbe5fd8adbf4242739d (HEAD -> master, origin/master, origin/HEAD)

> What vim/nvim version are you on?
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 23 2020 15:06:30)

I would like to propose an enhancement to add an additional fold level for the function containing the git hunk data.

Based on the current fold levels, the levels look like this:
```c
2    23 int funtion2(int i) {
2    24     /*
2    25      * some function that does nothing
2    26      */
2    27 
2    28     return (0);
2    29 }
2    30 
2    31 int funtion3(int i) {
2    32     /*
2    33      * Some function with a union
2    34      */
2    35 
2    36     union {
2    37         char    buf1[10];
|    38         int     int1;
|    39     } var;
|    40 
  >  41     /* some new code */                                                      
  >  42                                                                              
-    43     snprintf(var->buf1, 10, "Some string");
|    44 
|    45     return (0);
-    46 }
2    47 
2    48 int funtion4(int i) {
2    49     return (0);
2    50 }
```

I would like to propose the following with a 3rd fold level:
foldlevel=0  - The git hunk changes
foldlevel=1  - The lines surrounding the git hunk changes
foldlevel=2  - The function containing the git hunk changes
foldlevel=3  - All other lines
```c
3    23 int funtion2(int i) {
3    24     /*
3    25      * some function that does nothing
3    26      */
3    27 
3    28     return (0);
3    29 }
3    30 
2    31 int funtion3(int i) {
2    32     /*
2    33      * Some function with a union
2    34      */
2    35 
2    36     union {
2    37         char    buf1[10];
|    38         int     int1;
|    39     } var;
|    40 
  >  41     /* some new code */                                                      
  >  42                                                                              
-    43     snprintf(var->buf1, 10, "Some string");
|    44 
|    45     return (0);
-    46 }
3    47 
3    48 int funtion4(int i) {
3    49     return (0);
3    50 }
```

**Comment by airblade** [comment]
How do you detect the function containing the git hunk changes across all filetypes?

**Comment by raven42** [comment]
Might be able to write a plugin of sorts for different file types, and if it is an unknown filetype, then it defaults to two levels, or if the hunk is out of the scope of a function, then it defaults to two levels max. Would there be a way to use the syntax files to determine the scope? I know the [Tagbar](https://github.com/preservim/tagbar) plugin has some basic scoping capabilities which recognize different filetypes. I haven't looked at that code, but based on what that plugin does it seems like it should be possible. Though maybe tagbar does it through the tags themselves. However maybe there could be an option to integrate between the two plugins and set some flag that uses tagbar to get the line number or something? Just thinking out loud here.

**Comment by airblade** [comment]
Maybe using `[[` and `]]` would do the right thing most of the time, I don't know.

I understand why seeing the containing function could be useful.  However as it would only be a small improvement to the existing behaviour, it only justifies a small amount of additional complexity.  I'm not prepared to have filetype-specific code for this, or to integrate with some other plugin; it's not worth it.

**Comment by raven42** [comment]
is there an user function in gitgutter that will return true if a given line number is in a modified hunk? i might be able to write my own for my own purposes if so.

**Comment by airblade** [comment]
https://github.com/airblade/vim-gitgutter/blob/ea79bc01c2efc84cf8e71fbe5fd8adbf4242739d/autoload/gitgutter/hunk.vim#L143

**Comment by raven42** [comment]
ok cool... i'll give this a shot. Thanks.
