### ISSUE TITLE
vim-gitgutter: exceeded maximum number of signs (2 > -1, configured by g:gitgutter_max_signs)

### ISSUE THREAD

**Issue by foxale** [airblade/vim-gitgutter#740]
> What is the latest commit SHA in your installed vim-gitgutter?

ea79bc01c2efc84cf8e71fbe5fd8adbf4242739d

> What vim/nvim version are you on?

NVIM v0.4.3
No custom gitgutter setting in vimrc. 

> :GitGutterDebug

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5

git version 2.24.1 (Apple Git-126)

grep (BSD grep) 2.5.1-FreeBSD
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]	[-e pattern] [-f file] [--binary-files=value] [--color=when]	[--context[=num]] [--directories=action] [--label] [--line-buffered]	[--null] [pattern] [file ...]

updatetime=4000
shell=/bin/zsh
shellcmdflag=-c
shellpipe=2>&1| tee
shellquote=
shellredir=>%s 2>&1
shellslash [n/a]
shelltemp=1
shelltype [n/a]
shellxescape=
shellxquote=
```

After changing g:gitgutter_max_signs to 9000 it works. But why?

**Comment by airblade** [comment]
If you don't set `g:gitgutter_max_signs`, what does `:echo g:gitgutter_max_signs` give?

**Comment by foxale** [comment]
`:echo g:gitgutter_max_signs` -> `g:gitgutter_max_signs #-1`

`:echo type(g:gitgutter_max_signs)` -> `0`

**Comment by airblade** [comment]
I would expect the first one to be `-1` not `#-1`...

**Comment by foxale** [comment]
```
❯ vim -V20vimlog
❯ cat vimlog | grep "let g:gitgutter_max_signs"
line 31: "let g:gitgutter_max_signs = 9000
line 5: let g:gitgutter_max_signs = -1
line 31: "let g:gitgutter_max_signs = 9000
line 5: let g:gitgutter_max_signs = -1
```

**Comment by foxale** [comment]
Ok, I double checked and it's been correctly set to -1. The problem still occurs, though.

**Comment by airblade** [comment]
This how the value is used:

https://github.com/airblade/vim-gitgutter/blob/e480eb2b63e337b07e7e5fef288df0b77c06cac5/autoload/gitgutter/diff.vim#L185

If `g:gitgutter_max_signs` is `-1`, the first condition is false.  I don't see `g:gitgutter_max_signs` can be not `-1` and then `-1` (as reported by the next line).

**Comment by foxale** [comment]
Yea, I've seen the code. 

![image](https://user-images.githubusercontent.com/14327763/97336780-abf7f780-187f-11eb-876e-51098f314917.png)
This pops up when I enter any staged file. Then, after entering:
![image](https://user-images.githubusercontent.com/14327763/97336937-e3ff3a80-187f-11eb-8f4b-67ec01e753b2.png)
I get:
![image](https://user-images.githubusercontent.com/14327763/97336957-ecf00c00-187f-11eb-828e-ed897776120b.png).
which does make sense, when compared with the error message. The question is, why it's not respecting the first condition. 

I just fired :PlugUpdate, and it got updated to e480eb2 - with no effect, as expected. 

The `#1` value was a glitch in my mind I suppose.

**Comment by foxale** [comment]
![image](https://user-images.githubusercontent.com/14327763/97337945-2aa16480-1881-11eb-86e2-95099f3d9acd.png)

That's interesting..

**Comment by foxale** [comment]
Ok, I check the timestamps, and it seems I just copied entire `.config` directory from old laptop with WSL onto macbook. That's for help, it motivated me to dig into this issue and set up a git repo for my dot files.

After removing the whole `.config/nvim/pack/airblade/` folder, the issue is resolved.
