### ISSUE TITLE
let g:gitgutter_signs=0 not working as expected

### ISSUE THREAD

**Issue by Yutsuten** [airblade/vim-gitgutter#743]
> What is the latest commit SHA in your installed vim-gitgutter?
```
$ git log -n 1
commit e480eb2b63e337b07e7e5fef288df0b77c06cac5 (HEAD, origin/master, origin/HEAD)
Author: Andy Stewart <boss@airbladesoftware.com>
Date:   Tue Oct 27 16:40:39 2020 +0000

    Use g:gitgutter_grep instead of grep in debug command
    
    Closes #741.
```

> What vim/nvim version are you on?

```
$ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
```

---

When I set `g:gitgutter_signs=0` and restart neovim, the sign column still appear (and ignore my coloring settings). I expected the signs to not appear at all.

![Screenshot1](https://i.imgur.com/ZzzmWtZ.png)

If I select the sign column, I can see the sign.

![Screenshot2](https://i.imgur.com/VXrTlJa.png)

**Comment by airblade** [comment]
The line number highlights are an attribute of signs (see `:help sign-define`) so when you turn on line number highlights the corresponding signs have to be placed.  This causes the sign column to appear unless you have `:set signcolumn=no`.

However the signs should be invisible with `g:gitgutter_signs=0`.

**Comment by airblade** [comment]
Executing `:call gitgutter#highlight#define_highlights()` after neovim comes up fixes the unwanted colours in the sign column.

This function is called by a [`ColorScheme` autocommand]9https://github.com/airblade/vim-gitgutter/blob/e480eb2b63e337b07e7e5fef288df0b77c06cac5/plugin/gitgutter.vim#L284) so I wonder if your colorscheme is being set after that autocommand is set up.

**Comment by Yutsuten** [comment]
Thank you for the fast reply!!

Changing the order of my configuration files didn't change anything, but I was able to solve the problem by adding this auto command to my configuration:

```viml
autocmd VimEnter * call gitgutter#highlight#define_highlights()
```

I wanted gitgutter to only change line number colors (it's enough for me) and ALE to add signs to the sign column, but as you said seems it is a limitation on vim/neovim. The sign column is still spammed after a change in the file...
But for now this enough for me, thank you very much!!

For reference, this is how my configuration file is now: [gitgutter_init.vim](https://github.com/Yutsuten/dev-config/blob/63e33317f92cdbd0e098a43c2ed3ccaf66769b6e/neovim/plugin/gitgutter_init.vim#L18)
