### ISSUE TITLE
Allow to start at custom foldlevel

### ISSUE THREAD

**Issue by albfan** [airblade/vim-gitgutter#745]
> What is the latest commit SHA in your installed vim-gitgutter?
696a6ed389e5b54c8bf480f44ee4e8fc59e6f903

> What vim/nvim version are you on?
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Parches incluidos: 1-1704
```

Fold with context lines could be the first fold status, instead of fold without context lines.

Just doing:

```
diff --git i/autoload/gitgutter/fold.vim w/autoload/gitgutter/fold.vim
index 4c1e30e..39a2e14 100644
--- i/autoload/gitgutter/fold.vim
+++ w/autoload/gitgutter/fold.vim
@@ -4,7 +4,7 @@ function! gitgutter#fold#enable()
   call s:set_fold_levels()
   setlocal foldexpr=gitgutter#fold#level(v:lnum)
   setlocal foldmethod=expr
-  setlocal foldlevel=0
+  setlocal foldlevel=1
   setlocal foldenable
 
   call gitgutter#utility#setbufvar(bufnr(''), 'folded', 1)
```

it always fold with context lines, and you can use `zm` to fold more.

Is it possible to add a parameter to customize that?

Probably related with #739, where you could extend `function! s:set_fold_levels()` to detect function range (or any other level) with something like:

    function! s:get_additional_levels_for_filetype() 'returns custom levels for filetye
    function! s:get_level_for_filetype(lnum) 'return level for line in a file

So a file like `.java` can have two levels (class,function) and so level 2 and 3 will be function and class, and 4 will be the last level.

**Comment by airblade** [comment]
> Is it possible to add a parameter to customize that?

Or your could put this in your vimrc:

```viml
command! Fold GitGutterFold | normal! zr
```

**Comment by albfan** [comment]
Thanks anyway, will keep the fork. If I manage to code something around set_fold_levels will open a PR to discuss
