### ISSUE TITLE
Weird 'gitgutter@process_buffer..<SNR>128_setup' error with Neovim 0.5

### ISSUE THREAD

**Issue by bluz71** [airblade/vim-gitgutter#748]
> What is the latest commit SHA in your installed vim-gitgutter?

HEAD

> What vim/nvim version are you on?

Neovim 0.5.0 HEAD (latest as of Nov 9 2020).

Hello,

I have the following search and replace visual mode helper:

```viml
xnoremap \s "sy:%s/<C-r>s//<Left>
```

On a visual selection this will automatically fill in the substitute command with the currently highlighted text. However over the last little while I notice this gitgutter error when running my `\s` mapping:

![gitgutter](https://user-images.githubusercontent.com/11382509/98626198-44ed3f00-2365-11eb-866d-77f98a95c484.png)

Only with Neovim 0.5.
Neovim 0.4.4 does not emit the same error.

So I dig a little and the issue was introduced in gitgutter commit [8e368ae](https://github.com/airblade/vim-gitgutter/commit/8e368ae8d1613746b6a00726337373268c1cbe25). Specifically this line:

```viml
if gitgutter#utility#has_repo_path(a:bufnr) | return | endif
```

However, if I change it to this everything is good (no errors):

```viml
 if gitgutter#utility#has_repo_path(a:bufnr)
   return
 endif
```

I am way out of my depth here.
This is weird, right?

Obviously I don't want gitgutter errors when invoked my `\s` mapping.
Is this a gitgutter Vimscript bug, or Neovim 0.5 bug?
Can we work around it?

Best regards.

**Comment by airblade** [comment]
I agree, this is weird.

I suppose the workaround is to break the one-liner over three lines, as you did.

Oddly I can't reproduce this on Neovim 0.5.0-bc879dd1f or 0.5.0-bb7ed42.

It's also not clear to me why your map causes gitgutter to process the buffer.

I'm not sure what to suggest...

**Comment by bluz71** [comment]
I think the best bet at the moment is for me to try and produce a minimal repeatable test case for you.

If I can do that we can discuss it here, if it proves to be a Neovim bug we can push it upstream.

Let’s try and understand what’s going on. For the moment the ball is in my court.

Cheers.

P.S. I love this plugin, it is so useful to my day to day workflow

**Comment by bluz71** [comment]
This appears to be a plugin to plugin weird interaction. 
Note I am using Neovim 0.5.0-e786fb5af (Tues Nov 9 2020).

If I have this plugin order I get failure:

```viml
Plug 'airblade/vim-gitgutter'
Plug 'dense-analysis/ale'
```

If I flip the order the failure goes away:

```viml
Plug 'dense-analysis/ale'
Plug 'airblade/vim-gitgutter'
```

Why? I have no idea.

I suspect it is not worth looking into this. 
The workaround is easy enough for me.
Closing.

Many thanks.

**Comment by airblade** [comment]
Really weird.  I'm glad you have let me off the hook for this one :)

**Comment by bluz71** [comment]
Maybe there is a function name conflict between gitgutter and ALE?

I will have a look, if I find anything I will let you know. It feels like when the order is ALE first gitgutter second then gitgutter accidentally calls an ALE function?

Maybe, maybe not.

**Comment by bluz71** [comment]
Interesting, this is an interaction between three plugins not two, these three in this order:

```viml
Plug 'airblade/vim-gitgutter'
Plug 'dense-analysis/ale'
Plug 'antoinemadec/FixCursorHold.nvim'
```

The [FixCursorHold](https://github.com/antoinemadec/FixCursorHold.nvim) plugin is a hack to work [this Neovim bug](https://github.com/neovim/neovim/issues/12587). It is likely doing something weird whilst mostly fixing the Neovim cursor hold bug.

If/when that Neovim issue is fixed I will dump the FixCursorHold plugin.

This ordering works without issue:

```viml
Plug 'dense-analysis/ale'
Plug 'airblade/vim-gitgutter'
Plug 'antoinemadec/FixCursorHold.nvim'
```

Definitely not worth looking into, a rabbit hole of complication for little reward. Solution is for Neovim to fix their [12587](https://github.com/neovim/neovim/issues/12587) issue.

Cheers.

**Comment by airblade** [comment]
That reminds me of #728, which turned out to be due to vim/vim#2053 – another tricky one.
