### ISSUE TITLE
GitGutterQuickFix command not working

### ISSUE THREAD

**Issue by skamsie** [airblade/vim-gitgutter#749]
What is the latest commit SHA in your installed vim-gitgutter?
`987a33355ef424161fdbc4e5d625b5b5aed9704c`

What vim/nvim version are you on?

```bash   
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

Compiled by brew@Catalina

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"
```

I have been using this plugin for more than a year now and I think it's great! I never tried the `GitGutterQuickFix` command until today, but I realised it's not working for me. I don't get an error or anything, it's just that nothing happens when I run `:GitGutterQuickFix` in a buffer with changes.

**Comment by airblade** [comment]
That command only picks up saved changes.

Is that the situation here or is it also not working when you have saved, unstaged changes?

**Comment by skamsie** [comment]
@airblade yes, so the steps to reproduce are:

- open a file that belongs to a git repository in vim
- add two new lines to the file
- I see two + signs in the gutter for the new lines
- I save the file
- I run `:GitGutterQuickFix`
- nothing happens

**Comment by airblade** [comment]
I think `:copen` will show you your change.

`:GitGutterQuickFix` doesn't open the quickfix window by default because that's the way Vim's other quickfix commands behave.  See #676.

Since this has come up a couple of times, I'll document it.

**Comment by skamsie** [comment]
@airblade Thank you, so this works now, if I do `:copen` first and then `::GitGutterQuickFix`. Isn't there a way to integrate it in the plugin to automatically open the quicikfix if it's not already, so we don't need to use two commands?

**Comment by airblade** [comment]
You can make a map for yourself, for example:

```viml
nmap <Leader>gq :GitGutterQuickFix\|copen<CR>
```

**Comment by airblade** [comment]
I just realised a custom command would be better:

```viml
command Gqf GitGutterQuickFix | copen
```

**Comment by skamsie** [comment]
> I just realised a custom command would be better:

Definately, thanks 👍
