### ISSUE TITLE
gitgutter author fail error

### ISSUE THREAD

**Issue by petobens** [airblade/vim-gitgutter#750]
Using latest master and latest nvim master I sometimes randomly getting the following error when editing a non git file:
```
Error detected while processing function gitgutter#process_buffer[10]..<SNR>148_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute:
line   11:
E903: Process failed to start: too many open files: "/usr/bin/sh"
Error detected while processing function gitgutter#process_buffer[19]..gitgutter#diff#run_diff:
line    2:
E605: Exception not caught: gitgutter author fail
```
I have no clear idea how to consistently reproduce this. Maybe the above stacktrace is helpful enough. Otherwise I'll try to cook up a minimal reproducible example.

**Comment by airblade** [comment]
> E903: Process failed to start: too many open files: "/usr/bin/sh"

It looks like your Nvim has got too many files open.  I'm confident this plugin alone wouldn't cause this problem.  What other plugins do you use?

**Comment by airblade** [comment]
Does the discussion in #707 help?

**Comment by petobens** [comment]
Thanks for the quick reply. I'll have a look and report back here. I do use several other plugins  so the problem might be related to some weird clash between those and this plugin.

**Comment by airblade** [comment]
This isn't really something I can do anything about as you are running into an OS limit.

If you think of something, let me know and I'll reopen.

**Comment by iGEL** [comment]
@airblade I updated all my vim plugins the other day and started seeing this problem randomly. :sob: I think it happen so far twice when switching files with fzf.

My vim config: https://github.com/iGEL/dotfiles/tree/31379f8db5ac4d834fd22d24e2681fa31b3ed3f2/nvim

Let me know if there's a way I can debut this further. Vim-plug doesn't keep a log what it updated, does it?

**Comment by airblade** [comment]
> Vim-plug doesn't keep a log what it updated, does it?

I don't know but you should be able to `cd` into a plugin's directory, wherever vim-plug put it, and use `git reflog`.

Are you seeing the `E903 Process failed to start: too many open files: "/usr/bin/sh"` error?  If so, are you using `argdo` or `windo` or similar with lots of files?

**Comment by airblade** [comment]
@iGEL I'm continuing this in #767.

**Comment by Edmartt** [comment]
I had the same issue and I realized that it was because of the line with the path on windows, so I deleted/comment that line and now it works well.

**Comment by airblade** [comment]
> the line with the path on windows

@Edmartt Please could you link to this line?  I'm not sure which one you mean.

**Comment by Edmartt** [comment]
In your readme, you suggested to add something like this:

`" This path probably won't work
let g:gitgutter_git_executable = 'C:\Program Files\Git\bin\git.exe'
`
I used my own path for that, but I removed and now it works normally.

**Comment by airblade** [comment]
@Edmartt Thanks for the extra information.  I would not have suspected that setting the path to git could cause a "too many open files" error
