### ISSUE TITLE
Feature request: support for bare repos

### ISSUE THREAD

**Issue by zelleb** [airblade/vim-gitgutter#754]
> What is the latest commit SHA in your installed vim-gitgutter?
 512e299
> What vim/nvim version are you on?
nvim 0.4.4

^Title. Would this be possible without breaking #517 and f167c33 ?

**Comment by airblade** [comment]
What file are you editing if you have a bare repo?

**Comment by zelleb** [comment]
My dotfiles. I use this to manage them

 
```
dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
```

**Comment by airblade** [comment]
Surely if there's a work tree it's not a bare repo?

What happens when you edit one of your dotfiles?  If you turn on logging (`let g:gitgutter_log=1`), what do the logs say (`gitgutter.log` in the plugin's directory)?

**Comment by zelleb** [comment]
I guess it's because I use an alias to specify the work-tree and gitgutter just uses `git`?

` 0.000017 function gitgutter#process_buffer[10]..<SNR>45_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
0.000017 [async] cd /home/zelleb && git  ls-files --error-unmatch --full-name -z -- .zprofile
`

**Comment by zelleb** [comment]
I'm sorry!

I did some further research and found what I wanted was asked several times! And I found the solution.

`let g:gitgutter_git_args = '--git-dir-""'`

 Thank you.
