### ISSUE TITLE
Floating Window Problem with Latest Nightly NVIM

### ISSUE THREAD

**Issue by cenk1cenk2** [airblade/vim-gitgutter#756]
> What is the latest commit SHA in your installed vim-gitgutter?
512e2999ed7ff367580e0d6bc4d2daa81663221f
> What vim/nvim version are you on?
NVIM v0.5.0-dev+1028-g702208daa

```
Error detected while processing function gitgutter#hunk#preview[3]..<SNR>164_hunk_op[62]..<SNR>164_preview[6]..<SNR>164_populate_hunk_preview_window:
line   14:
E16: Invalid range:       call nvim_win_set_height(s:winid, height)
line   18:
E16: Invalid range:       call nvim_buf_set_lines(winbufnr(s:winid), 0, -1, v:false, [])
line   19:
E16: Invalid range:       call nvim_buf_set_lines(winbufnr(s:winid), 0, -1, v:false, a:body)
line   20:
E16: Invalid range:       call nvim_buf_set_option(winbufnr(s:winid), 'modified', v:false)
line   23:
E16: Invalid range:       call nvim_buf_clear_namespace(winbufnr(s:winid), ns_id, 0, -1)
line   29:
E16: Invalid range:       call nvim_win_set_cursor(s:winid, [1,0])
Error detected while processing function gitgutter#hunk#preview[3]..<SNR>164_hunk_op[62]..<SNR>164_preview:
line    7:
E16: Invalid range:   call s:enable_staging_from_hunk_preview_window()
Press ENTER or type command to continue
```

Hello,

Foremost thanks for maintaining this and many VIM extensions. I would like to report a bug when using the latest nightly NVIM with the floating window preview of hunks. 

- I am not sure if I somehow am causing it because I recently updated NVIM with its all plugins. 
- Not sure about the plugin causing this or NVIM's nightly version. 
- Without the floating window, the hunks work just fine.

**Comment by airblade** [comment]
It works for me on NVIM v0.5.0-bb7ed42.

I'll try upgrading Neovim and see if I can reproduce the problem.

**Comment by airblade** [comment]
I upgraded Neovim to NVIM v0.5.0-dev+d6d4e3d1a (via `brew install nvim --HEAD`) and the floating hunk preview still works fine for me.

I'm not sure what the problem is.

**Comment by cenk1cenk2** [comment]
Hmm, I am not completely sure about the plugin itself causing the problem but maybe a combination of multiple things is causing it, I will try to go in between the lines and find out what the problem is.

Thanks for your help, if you can not reproduce it I will close the issue, and not take more of your time.
