### ISSUE TITLE
How to stage part of any hunk?

### ISSUE THREAD

**Issue by Aster89** [airblade/vim-gitgutter#758]
> What is the latest commit SHA in your installed vim-gitgutter?
ff9d134
> What vim/nvim version are you on?
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 20 2021 22:47:34)
Included patches: 1-2380
```
I've gone through #279 and #694, but apparently I'm not understanding the docs, unless I've found a bug, which looks a bit strange, given the depth of the two linked issues.

Here's the screencast of me trying to add only the addition part of a modification+addition hunk. From the help I understand this is possible (it reads `To stage part of any hunk`), however, I couldn't get it working:
[![asciicast](https://asciinema.org/a/phZFvLZfar131NRF3nA2zwwxr.svg)](https://asciinema.org/a/phZFvLZfar131NRF3nA2zwwxr)

**Comment by airblade** [comment]
Thanks for the crystal-clear report!

When you edit the hunk in the preview window, you're not fully deleting the modified part; you're deleting the modification's "before" lines while leaving its "after" lines.  So the patch you're applying via gitgutter is not only the added lines, it's the "after" part of the modification plus the added lines.

After you patch has been applied, the index still contains the "before" lines (which you deleted in the preview window) but the buffer no longer does.  This shows up as a deletion and you can see the corresponding sign at the end of your screencast (at around 48 seconds) below relative line 27.

**Comment by Aster89** [comment]
Oh my gosh, had I turned on my brain and read the lines in the preview window instead of just deleting what's red, I wouldn't have bothered you, ahahah.

Thank you for clearly guiding me :)
