### ISSUE TITLE
Gray column / Lines no changed

### ISSUE THREAD

**Issue by emanuel36** [airblade/vim-gitgutter#759]
> What is the latest commit SHA in your installed vim-gitgutter?
ff9d134f0c69e25d391138036051b2c5e6bac864

> What vim/nvim version are you on?
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 28 2019 12:17:42)

![Screenshot-20210204144102-1836x901](https://user-images.githubusercontent.com/18536741/106940122-889edd00-66f7-11eb-9bc3-8c54b4470a00.png)

There is a gray column in the left size, but the add, removed and changed seems normal for me, this gray color appears just for no changed lines. I saw [this](https://github.com/airblade/vim-gitgutter/issues/243) similar issue, but this fix did not work for me.

I'm not using any color scheme, it's just the default one.

Here is my .vimrc config:
```
"vim-gitgutter
Plug 'https://github.com/airblade/vim-gitgutter'
set updatetime=250
let g:gitgutter_max_signs = 500 
highlight clear SignColumn
highlight clear SignColumn
highlight GitGutterAdd ctermfg=2
highlight GitGutterChange ctermfg=3
highlight GitGutterDelete ctermfg=1
highlight GitGutterChangeDelete ctermfg=4
```

**Comment by airblade** [comment]
Have you tried `:highlight! link SignColumn LineNr`?

**Comment by emanuel36** [comment]
Hi @airblade, I did not know this command, this worked perfectly! 

Thank you so much and congrats by the project, it's amazing!

**Comment by airblade** [comment]
Thanks!

**Comment by g1n0st** [comment]
Sorry for troubling, I met the gray `SignColumn` issue as well. as you mentioned `:highlight! link SignColumn LineNr`, it fix this problem perfectly when I use it as command input to vim. However, when I added it to the `~/.vimrc` and restart vim, nothing happens. I don't want to input it every time, what should I do?

**Comment by airblade** [comment]
Add it after you set your colorscheme.

**Comment by g1n0st** [comment]
I added `highlight! link SignColumn LineNr` at the end of `vimrc`, while I use the vim default theme and not set any colorscheme explicit. 😢

**Comment by g1n0st** [comment]
Thank you so much! I targeted the colorscheme is `macvim` and I modified `guibg` of `SignColumn` in this file and worked!
And Thanks for your amazing project!

**Comment by airblade** [comment]
@g1n0st Nice!
