### ISSUE TITLE
spellchecker adds word to spell-file in the vim-gitgutter directory

### ISSUE THREAD

**Issue by astier** [airblade/vim-gitgutter#764]
> What is the latest commit SHA in your installed vim-gitgutter?

d249be7

> What vim/nvim version are you on?

NVIM v0.5.0-dev+1080-g971e0ca90

## Problem

If I enable the spellchecker in neovim and try to add a word as a correct word to the spell-file via `zg` it gets added to the spell-file in the vim-gitgutter directory. The notification is as following if I try to add the word `set`:

```
Word 'set' added to ~/.local/share/nvim/plugins/vim-gitgutter//spell/en.utf-8.add
```

If I don't load gitgutter within my init.vim `zg` adds the word to the correct spell-file:

```
Word 'set' added to ~/.config/nvim/spell/en.utf-8.add
```

## Minimal init.vim

```vim
set runtimepath^=~/.local/share/nvim/plugins/vim-gitgutter/
set spell
```

## Steps to reproduce

1. Open minimal init.vim
2. Move cursor above the word `set`
3. Type `zg` to add the word to the spell-file

**Comment by airblade** [comment]
I assume your `'spellfile'` option is empty.

`:help spellfile` says:

> 	When a word is added while this option is empty Vim will set it for
>	you: Using the first directory in 'runtimepath' that is writable.

It looks like neovim is behaving as expected.

**Comment by astier** [comment]
Thanks. Learned something new.
