### ISSUE TITLE
vim-gitgutter adds intrusive mapping xp.

### ISSUE THREAD

**Issue by alibby** [airblade/vim-gitgutter#766]
The commands `x` and `p` in succession in normal mode provides a handy and efficient method to swap characters in vim.  I used this all the time.  While I can't find the code to prove it, behavior seems to indicate that vim-gitgutter adds this mapping when it detects changes and displays characters in the gutter.

The mapping is to perform a git pull, which can be very disruptive when all I intended to do is swap characaters.

Is there a way to deactivate this?  I'd like to keep vim-gitgutter active.  I use it all the time and would like to have it reflected in my status bar and all that.  So deactivating and activating is not ideal.  

Thanks, and keep up the great work.  You've made a great plugin.

> What is the latest commit SHA in your installed vim-gitgutter?

2e3cd54ed696500bb3722226f2103d4b279272c0

> What vim/nvim version are you on?

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec  6 2020 18:39:42)
macOS version
Included patches: 1-2100
Compiled by Homebrew
```

**Comment by airblade** [comment]
That certainly sounds annoying.

The plugin never does a `git-pull` and I use `xp` all the time to swap characters.  Something else is causing this.  You could try `:nmap x` and see if that gives you any clues.

**Comment by alibby** [comment]
> That certainly sounds annoying.
> 
> I also use `xp` all the time to swap characters; furthermore the plugin never does a `git-pull`. Something else must be causing this. You could try `:nmap x` and see if that gives you any clues.

Looks like you're right!  I could have sworn I exaustively tried various things to determine it was vim-gitgutter.  Turns out it's not.  
Without the plugin active, I was able to get it to happen.  So I'm off to searching.  Sorry for the mis-report.  

Thanks!
