### ISSUE TITLE
gitgutter is causing neovim to freeze and become unresponsive for 10+ seconds

### ISSUE THREAD

**Issue by sgalizia** [airblade/vim-gitgutter#767]
> What is the latest commit SHA in your installed vim-gitgutter?
b90aad6

> What vim/nvim version are you on?
NVIM v0.4.4

When opening a new buffer for a file, neovim freezes for about 10 seconds and becomes unresponsive. After a while I am able to do stuff again and the gutter signs show up. I used `:messages` and the picture below is the errors I am presented with.

![image](https://user-images.githubusercontent.com/1574010/108554752-65ecf680-72a9-11eb-8dc4-65161456a768.png)

**Comment by zeitchef** [comment]
I'm getting exactly the same error.

**Comment by airblade** [comment]
This sounds like #750 and #707.  The problem in #707 was having too many files open for the OS, and I proposed one or two workarounds.

Does this apply here, do you think, or does it happen with a fresh neovim?

**Comment by sgalizia** [comment]
So I can't speak for @zeitchef but for me, I can have one or two files open and not that many git files changed either and it throws this error. So I am not really sure why it is throwing the too many files error.

**Comment by sgalizia** [comment]
I just tested this by opening a fresh nvim instance and opened a single file in the project (3 files have git changes) and I received the following error.
![image](https://user-images.githubusercontent.com/1574010/108792295-c5f7cd00-7535-11eb-8726-0cabb121fc60.png)

**Comment by airblade** [comment]
That's interesting to hear.  The way gitgutter handles files hasn't changed for years so at the moment I doubt the plugin alone is the problem.  But to be sure, can you reproduce the problem if gitgutter is your only plugin?

**Comment by airblade** [comment]
You could also switch on logging with `let g:gitgutter_log=1` in your init.vim and then post the log file once the problem has occurred.  The log is `gitgutter.log` in gitgutter's directory.

**Comment by sgalizia** [comment]
> 
> 
> You could also switch on logging with `let g:gitgutter_log=1` in your init.vim and then post the log file once the problem has occurred. The log is `gitgutter.log` in gitgutter's directory.

The log file is pretty big (~3k lines) but I can send it to you if you would like to take a look at it

**Comment by airblade** [comment]
Sure, either post it here or email it to me, whichever you prefer.

**Comment by sgalizia** [comment]
> 
> Sure, either post it here or email it to me, whichever you prefer.
> […](#)
> On 23 Feb 2021, at 18:06, Sam Galizia ***@***.***> wrote: ﻿ You could also switch on logging with let g:gitgutter_log=1 in your init.vim and then post the log file once the problem has occurred. The log is gitgutter.log in gitgutter's directory. The log file is pretty big (~3k lines) but I can send it to you if you would like to take a look at it — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Emailed it to you at the address listed on your GitHub profile.

**Comment by airblade** [comment]
@sgalizia Thanks for the log file.  There are far more diff jobs running than I would expect.

What is your 'updatetime'?  `:echo &updatetime`

There are some jobs being started within 2ms of each other.  This doesn't give a job time to finish before the next one starts up, which means the has-the-buffer-changed guard is bypassed, compounding the problem.

Perhaps the plugin should have a way of handling jobs which pile up like this, e.g. cancelling any outstanding jobs when starting a new job, or cancelling a new job if there is an outstanding job.

Personally I use an 'updatetime' of 100.

**Comment by sgalizia** [comment]
> 
> 
> @sgalizia Thanks for the log file. There are far more diff jobs running than I would expect.
> 
> What is your 'updatetime'? `:echo &updatetime`
> 
> There are some jobs being started within 2ms of each other. This doesn't give a job time to finish before the next one starts up, which means the has-the-buffer-changed guard is bypassed, compounding the problem.
> 
> Perhaps the plugin should have a way of handling jobs which pile up like this, e.g. cancelling any outstanding jobs when starting a new job, or cancelling a new job if there is an outstanding job.
> 
> Personally I use an 'updatetime' of 100.

Mine is set at 4000, not sure where that got set. I will try changing that to see if it helps. And when I opened up the log and saw the same thing, like jobs happening super super quick I had a feeling that was causing issues. Glad you confirmed my suspicion though.

**Comment by airblade** [comment]
4000 is the default.  I’d recommend setting it to 100 but something else must be going on here.

What other plugins do you have installed?

I’m wondering whether something is jumping to another buffer and back on every keystroke (TextChangedI) – that would cause the behaviour you’re seeing.

**Comment by sgalizia** [comment]
![image](https://user-images.githubusercontent.com/1574010/109037641-cd2af200-767f-11eb-899b-b8bd6583f4b5.png)

This is my list of plugins I am using. I also use a few Coc plugins for specific languages. coc-typescript, coc-eslint, coc-prettier

**Comment by airblade** [comment]
Do you get the problem when gitgutter is your only plugin?

**Comment by sgalizia** [comment]
So strangely, it hasn't been happening the past day or so now. I updated my plugins yesterday and morning and the problem hasn't come up again. I'm going to close this for now. If it crops up again I will try with just gitgutter and see if it happens. Thanks for walking through this with me!

**Comment by airblade** [comment]
@sgalizia Good to hear the problem seems to have gone away, even if we don't know why.

@zeitchef How about you?  If you still have the problem, does it occur with gitgutter as your only plugin?

**Comment by zeitchef** [comment]
@airblade I did a little spring cleaning, and I haven't had any problems in the last couple days.
