### ISSUE TITLE
Heatmap Feature request

### ISSUE THREAD

**Issue by kaldown** [airblade/vim-gitgutter#768]
Is there any way to easily adopt heatmap?

> heatmap — shows how recently lines were changed, relative to all the other changes in the file and to now (hot vs. cold)
[source](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)

**Comment by airblade** [comment]
I can't see an easy way; it would be a completely new feature (plus tests).  I also don't find heatmaps useful.

**Comment by airblade** [comment]
You could try Fugitive's blame view which is also a heatmap.

**Comment by kaldown** [comment]
I never though I would need any.
But playing with https://github.com/dandavison/delta makes me wanting to get closer to my code outside from CLI, straight into Vim :)

Now I want more funcy suff.
True, it's not so common.

Will try.
Thank you.
