### ISSUE TITLE
Esc in preview jumps to help window when a specific layout of windows is used

### ISSUE THREAD

**Issue by Aster89** [airblade/vim-gitgutter#769]
At the moment I can't do a screencast, because I still have to understand what are the correct conditions for this behavior to show up.

I've observed it when I have this layout
```
 __________________________
|                |         |
|                |         |
|    help        |         |
|________________|         |
|                |  file2  |
|     file1      |         |
| (cursor here)  |         |
|________________|_________|
```
and the cursor is on a hunk. If I do <kbd>leader</kbd><kbd>h</kbd><kbd>p</kbd>, then move to the hunk preview window, and finally press <kbd>Escape</kbd> (I have `g:gitgutter_close_preview_on_escape == 1`), the preview window closes but the cursor jumps to the `help` window.

Strangely, if I close the window of `file2`, the jump does not occur.

If you can't reproduce it, please tell me and I'll make a screencast and also investigate a bit more.

> What is the latest commit SHA in your installed vim-gitgutter?
1283ec1

> What vim/nvim version are you on?
```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 09 2021 23:51:55)
Included patches: 1-2489
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +channel           +cscope            +ex_extra          -hangul_input      +linebreak         +mouse_dec         -mzscheme          +profile           +sound             +termguicolors     +vartabs           +writebackup
+arabic            +cindent           +cursorbind        +extra_search      +iconv             +lispindent        +mouse_gpm         +netbeans_intg     +python/dyn        +spell             +terminal          +vertsplit         +X11
+autocmd           +clientserver      +cursorshape       -farsi             +insert_expand     +listcmds          -mouse_jsbterm     +num64             +python3/dyn       +startuptime       +terminfo          +virtualedit       -xfontset
+autochdir         +clipboard         +dialog_con_gui    +file_in_path      +ipv6              +localmap          +mouse_netterm     +packages          +quickfix          +statusline        +termresponse      +visual            +xim
-autoservername    +cmdline_compl     +diff              +find_in_path      +job               +lua/dyn           +mouse_sgr         +path_extra        +reltime           -sun_workshop      +textobjects       +visualextra       -xpm
+balloon_eval      +cmdline_hist      +digraphs          +float             +jumplist          +menu              -mouse_sysmouse    +perl/dyn          +rightleft         +syntax            +textprop          +viminfo           +xsmp_interact
+balloon_eval_term +cmdline_info      +dnd               +folding           +keymap            +mksession         +mouse_urxvt       +persistent_undo   +ruby/dyn          +tag_binary        +timers            +vreplace          +xterm_clipboard
+browse            +comments          -ebcdic            -footer            +lambda            +modify_fname      +mouse_xterm       +popupwin          +scrollbind        -tag_old_static    +title             +wildignore        -xterm_save
++builtin_terms    +conceal           +emacs_tags        +fork()            +langmap           +mouse             +multi_byte        +postscript        +signs             -tag_any_white     +toolbar           +wildmenu
+byte_offset       +cryptv            +eval              +gettext           +libcall           +mouseshape        +multi_lang        +printer           +smartindent       +tcl/dyn           +user_commands     +windows
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libm
ount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0
-I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-need
ed -o vim -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lelf -lcanberra -lacl -lattr -lgpm -ldl -Wl,-
E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6 -ldl -lz
-lpthread -lm
```

**Comment by airblade** [comment]
In this context `Esc` simply executes `:pclose`.

I can reproduce this following your directions, and also if I do `:pclose` instead of `Esc` in the preview window.  If I open the preview but keep my cursor in file1, `:pclose` does not move the cursor (as expected).

I'm not actually sure how vim decides which window to move to when the current window is closed.

I wondered if it was to do with the preview's alternate file, but I checked and it is file1 as expected.

It's odd how the presence of absence of file2 makes a difference.  With your layout, help is window number 1, file1 is window number 2, and file2 is window number 3.  Closing file2 doesn't change the other window numbers.

How strange...

**Comment by airblade** [comment]
It doesn't seem to matter whether the top-left window is a help file or a "normal" file.

**Comment by airblade** [comment]
I've traced the problem to this line:

https://github.com/airblade/vim-gitgutter/blob/f3145958dd0fb89e2e4106977455b5f52c90e7f8/autoload/gitgutter/hunk.vim#L473

If I remove the `g:gitgutter_preview_win_location` then everything behaves as expected.  I don't understand why.

Separately, @andymass posted a useful [StackOverflow answer](https://vi.stackexchange.com/a/29630/1643) about how Vim decides which window to move the cursor to.

**Comment by airblade** [comment]
I've just simplified the way the code opens the preview window (64062df).  However the problem remains:

https://github.com/airblade/vim-gitgutter/blob/64062dfe022885f6900ba016eb24faee22a72d26/autoload/gitgutter/hunk.vim#L469

**Comment by andymass** [comment]
I guess the preview `<esc>` map could be something like this

    nnoremap <buffer> <silent> <Esc> :<c-u>wincmd p|pclose<CR>

This way, the previous window is the one wound up in.

**Comment by airblade** [comment]
@andymass That seems to work nicely.  Thanks!

I still think the behaviour is a little odd so I opened https://github.com/vim/vim/issues/7974 for further clarification.

Anyway, I'll roll your suggestion into the code here.

**Comment by Aster89** [comment]
Wow, I triggered quite an investigation! :D

**Comment by airblade** [comment]
@Aster89 It's a trivial thing but it would be nice to get to the bottom of it.

**Comment by airblade** [comment]
@Aster89 You might like to read @andymass's [answer and comments](https://vi.stackexchange.com/a/29630/1643) to my StackOverflow question which explain why you're seeing this behaviour.

In the meantime, 24cc477 adds @andymass's patch (thanks!).  I'm not sure whether something similar is also required [here](https://github.com/airblade/vim-gitgutter/blob/24cc47789557827209add5881c226243711475ce/autoload/gitgutter/hunk.vim#L589) – after a very brief experiment, I don't think so.

I think your issue is now solved :)

**Comment by Aster89** [comment]
Very interesting. It look like he literally looked at Vim's source code to answer. I wouldn't even know where to search.

Thanks, both of you :)
