### ISSUE TITLE
Prev/next hunk mappings not working in init.vim

### ISSUE THREAD

**Issue by farbodsz** [airblade/vim-gitgutter#776]
> What is the latest commit SHA in your installed vim-gitgutter?

24cc47789557827209add5881c226243711475ce 

> What vim/nvim version are you on?

NVIM v0.4.4

---

### Summary

**My issue is about `<Plug>(GitGutterPrevHunk)`/`<Plug>(GitGutterNextHunk)` mappings not working in `init.vim`, although they do work when opening a symlink to `init.vim`.**

### My setup

In my Neovim configuration, I have sym-linked files in the `~/.config/nvim` directory to `~/.dotfiles/neovim/.config/nvim`. My `.dotfiles` directory is a git repo ([can be found here if needed](https://github.com/farbodsz/dotfiles/tree/69ff408f7c0dc1b2c745bb0b02698ad53bffe0d9)):

```sh
~/.config/nvim$ ls -l
total 36
lrwxrwxrwx  1 farbod farbod   43 Nov 30 15:44 ale.vim -> ../../.dotfiles/neovim/.config/nvim/ale.vim
drwxrwxr-x  2 farbod farbod 4096 Mar 24 18:05 bin
lrwxrwxrwx  1 farbod farbod   53 Aug 30  2020 coc-settings.json -> ../../.dotfiles/neovim/.config/nvim/coc-settings.json
lrwxrwxrwx  1 farbod farbod   43 Oct  9 11:34 coc.vim -> ../../.dotfiles/neovim/.config/nvim/coc.vim
lrwxrwxrwx  1 farbod farbod   48 Mar 16 15:38 fugitive.vim -> ../../.dotfiles/neovim/.config/nvim/fugitive.vim
lrwxrwxrwx  1 farbod farbod   43 Nov 30 15:44 fzf.vim -> ../../.dotfiles/neovim/.config/nvim/fzf.vim
lrwxrwxrwx  1 farbod farbod   49 Nov 30 15:44 gitgutter.vim -> ../../.dotfiles/neovim/.config/nvim/gitgutter.vim
lrwxrwxrwx  1 farbod farbod   44 Aug 30  2020 init.vim -> ../../.dotfiles/neovim/.config/nvim/init.vim
drwxr-xr-x  2 farbod farbod 4096 Jul 30  2020 pack
drwxr-xr-x 36 farbod farbod 4096 Apr  5 11:40 plugged
drwxr-xr-x  2 farbod farbod 4096 Feb  5 18:19 spell
drwxrwxr-x  2 farbod farbod 4096 Mar 24 18:53 syntax
lrwxrwxrwx  1 farbod farbod   45 Oct  9 11:34 theme.vim -> ../../.dotfiles/neovim/.config/nvim/theme.vim
drwxrwxr-x  2 farbod farbod 4096 Apr  2 11:36 UltiSnips
```

I also have the following gitgutter configuration:

```viml
let g:gitgutter_map_keys = 0

nmap ]h <Plug>(GitGutterNextHunk)
nmap [h <Plug>(GitGutterPrevHunk)

nmap <leader>hs <Plug>(GitGutterStageHunk)
" etc...
```

### The issue

If I `cd` into the `.config/nvim` directory and open `init.vim` (a symlink), I am able to use my `[h` and `]h` mappings to navigate hunks. Gitgutter works great here.

However, **if I open `init.vim` from `.dotfiles/neovim/.config/nvim`, using the hunk mappings does nothing** (no message at the bottom either - it's as if they weren't mapped). Both maps are set though - running `:map [h` returned:

```
n   [h            <Plug>(GitGutterPrevHunk)
```

### What _is_ working

After opening `init.vim` from `.dotfiles` (not the symlink)...

- I _am_ able to navigate hunks in this file by instead using `:GitGutterPrevHunk`/`:GitGutterNextHunk`
- I can also do `:call gitgutter#hunk#prev_hunk(1)` which works perfectly fine
- This remapping works:

```viml
nmap ]h :GitGutterNextHunk<cr>
nmap [h :GitGutterPrevHunk<cr>
```

- My other mappings also work in this file (e.g. I can do `<leader>hs` in a file and it will stage it, as expected).
- Strangely, there is also **no issue with the two hunk mappings when opening other vim files** in `.dotfiles/neovim/.config/nvim`, so `init.vim` from `.dotfiles` seems to be the only affected file.

**Comment by airblade** [comment]
> `init.vim` from `.dotfiles` seems to be the only affected file

How strange.  Please could you tell me what `:echo gitgutter#utility#is_active(bufnr(''))` produces when you have this file open?

**Comment by farbodsz** [comment]
> > `init.vim` from `.dotfiles` seems to be the only affected file
> 
> How strange. Please could you tell me what `:echo gitgutter#utility#is_active(bufnr(''))` produces when you have this file open?

It outputs `1` (which is the same output I get as for the files that don't display this issue)

**Comment by airblade** [comment]
Thanks.  I have no idea what's wrong so perhaps you could turn on logging (`let g:gitgutter_log=1`), reproduce the problem, then post the file `gitgutter.log` which will be in gitgutter's directory.

**Comment by farbodsz** [comment]
Okay thanks - I've produced the [gitgutter.log](https://github.com/airblade/vim-gitgutter/files/6260768/gitgutter.log) file.

I opened up files 3 times:

1. Opened `init.vim` from the `.config` folder (symlink)
2. Opened `init.vim` from my `.dotfiles` folder
3. Opened another vim file from the `.dotfiles` folder

**Comment by airblade** [comment]
I see you use [`mkview` and `loadview`](https://github.com/farbodsz/dotfiles/blob/69ff408f7c0dc1b2c745bb0b02698ad53bffe0d9/neovim/.config/nvim/init.vim#L43-L44), which can cause surprising behaviour if you change a mapping.

Please could you delete any view file for your non-symlinked `init.vim` and try again?

**Comment by farbodsz** [comment]
Yep, removing `mkview` and `loadview` fixed the problem!

I'll probably just remove them from my `init.vim` since I don't need my `remember_folds` autogroup that much anyway.

Thanks!

**Comment by airblade** [comment]
Great!
