### ISSUE TITLE
Not automatically updating after commit

### ISSUE THREAD

**Issue by Wnthr** [airblade/vim-gitgutter#777]
> What is the latest commit SHA in your installed vim-gitgutter?

24cc477

> What vim/nvim version are you on?

% vi --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 12 2021 19:19:22)
Included patches: 1-814
Modified by Gentoo-8.2.0814-r100
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        -terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
-cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: x86_64-pc-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H     -march=native -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: x86_64-pc-linux-gnu-gcc   -Wl,-O1 -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf   -lacl -lattr -ldl     -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm

*.vimrc:*

call pathogen#infect()
call pathogen#helptags()

colorscheme solarized
set background=dark
let g:lightline = { 'colorscheme': 'lightline_solarized' }

syntax enable
scriptencoding utf-8

let mapleader = ","
nnoremap <leader><leader> <leader>
nnoremap <leader>h :set hls!<cr>
nnoremap <leader>n :set number!<cr>
nnoremap <leader>r :set relativenumber!<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" turn off auto adding comments on next line
" so you can cut and paste reliably
" http://vimdoc.sourceforge.net/htmldoc/change.html#fo-table
set fo=tcq

" set default comment color to cyan instead of darkblue
" which is not very legible on a black background
highlight comment ctermfg=green

" Some default tab options that make sense for general files
set tabstop=2
set expandtab
set softtabstop=2
set shiftwidth=2

" Show trailing tabs and spaces
highlight LiteralTabs ctermbg=darkcyan guibg=darkcyan
match LiteralTabs /\s\  /
highlight ExtraWhitespace ctermbg=darkcyan guibg=darkcyan
match ExtraWhitespace /\s\+$/

set ruler
set number
set hidden
set hidden
set laststatus=2
set textwidth=79
set colorcolumn=+1

" Misc Stuff
filetype plugin indent on

*~/.vim/bundle:*

ale/  ansible-vim/  emmet-vim/  lightline-solarized/  lightline.vim/  tabular/  vim-colors-solarized/  vim-flake8/  vim-gitgutter/  vim-surround/  vim-textobj-python/  vim-textobj-user/  vim-textobj-variable-segment/

Problem:

After commiting code to my git repo, the gitgutter doesn't update until I quit vim and restart, or modify the code so that gitgutter updates.

Expected behavior: On commit, the changes are removed from the gitgutter automatically.

**Comment by airblade** [comment]
I assume your `'updatetime'` is the default `4000`.  Try `:set updatetime=100`.

**Comment by Wnthr** [comment]
What I do: I save my file with some changes. Those make the gitgutter update itself. Once I've done that, I move to the next tmux pane, and I commit using git. Now, the gitgutter won't update the status. If I move back to the vim pane, nothing happens until I do an edit. I can move around in the vim buffer, nothing happens, but as soon as I make the edit, the gutter updates to the current state.

If, on the other hand, I just make an edit and undo it still within vim, the gutter updates as I would expect.

**Comment by airblade** [comment]
Do you have this in your `tmux.conf`?

```
set -g focus-events on
```

**Comment by Wnthr** [comment]
I did not. I added it, still wasn't working, so I added https://github.com/tmux-plugins/vim-tmux-focus-events to my vim, and now it's working. Thanks!
