### ISSUE TITLE
hunk area does not show line number

### ISSUE THREAD

**Issue by CengsBlanky** [airblade/vim-gitgutter#778]
> What is the latest commit SHA in your installed vim-gitgutter?
I use vim-plug manager
``` vimscript
Plug 'airblade/vim-gitgutter'
```
> What vim/nvim version are you on?
gvim8.2 in windows10

my relevant vimrc is:
``` vimscript
let g:gitgutter_git_executable = 'i:/git/bin/git.exe'
let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '*'
let g:gitgutter_sign_removed = '-'
highlight GitGutterAdd    guifg=#009900 ctermfg=2 
highlight GitGutterChange guifg=#bbbb00 ctermfg=3
highlight GitGutterDelete guifg=#ff2222 ctermfg=1
set number
set relativenumber
```
the screen shot is:
![2021-04-21_010533](https://user-images.githubusercontent.com/52321832/115436570-b814ae80-a23d-11eb-8537-9cee6cebfe16.png)

it only shows signs, but I also want line number after sign, and the line number outside the hunk area shows normally.

**Comment by airblade** [comment]
The plugin doesn't affect line numbers; it places signs in the sign column, which is separate from the line number column.

I presume `:echo &signcolumn` gives `number`.  If so, change it to "auto": `set signcolumn=auto`.

**Comment by CengsBlanky** [comment]
> The plugin doesn't affect line numbers; it places signs in the sign column, which is separate from the line number column.
> 
> I presume `:echo &signcolumn` gives `number`. If so, change it to "auto": `set signcolumn=auto`.

Thanks, I thinks the gvim should explicitly `set signcolumn=yes`, and it works
