### ISSUE TITLE
Preview window height & update

### ISSUE THREAD

**Issue by Amparose** [airblade/vim-gitgutter#779]
> What is the latest commit SHA in your installed vim-gitgutter? **24cc477**

> What vim/nvim version are you on? **Vim 8.2**

Couple of issues I am having with the hunk preview window that I'm not sure if are bugs, feature requests, or user error.

1. If I preview a hunk that is one line, the preview window is one line high. If I then move to the next change and trigger the hunk preview, the window remains the height of the shortest previous hunk preview.
2. My preview window is not updating when I cycle through the changes with `]c`.

**Comment by airblade** [comment]
1. Upgrade to 9756e95b.
2. That's the expected behaviour.  However now that you mention it, I can see how it would be helpful if the preview window updated automatically.  I'll work on that.
