### ISSUE TITLE
gitgutter#quickfix very very slow when a file has tons of changes

### ISSUE THREAD

**Issue by jackhub** [airblade/vim-gitgutter#780]
Maybe GitGutter should add an options to just show changed file names with there's first change in quickfix.

**Comment by airblade** [comment]
Approximately how many changes is "tons"?

It shouldn't be slow.  Please could you [profile it](https://github.com/airblade/vim-gitgutter/wiki/How-to-profile-vim-gitgutter)?

**Comment by airblade** [comment]
Closing because this has gone quiet.
