### ISSUE TITLE
Can't understand the hunk which delete lines with prefix `--` properly

### ISSUE THREAD

**Issue by kevinhwang91** [airblade/vim-gitgutter#782]
> What is the latest commit SHA in your installed vim-gitgutter?

lastest

> What vim/nvim version are you on?

NVIM v0.5.0-dev+1318-g61aefaf29

https://github.com/tpope/vim-fugitive/issues/1747

**Comment by airblade** [comment]
I don't understand.  Please give me steps to reproduce, including what you expect to see and what you actually see.

**Comment by kevinhwang91** [comment]
```shell
mkdir -p reproduce_issue && cd reproduce_issue
git init
echo "-- will be deleted\nprint('hello')" > test.lua
git add .
nvim test.lua
```

Now we're inside nvim.
Press `dd` and run `:GitGutterPreviewHunk`, the deleted hunk is regarded as diffadd.

**Comment by airblade** [comment]
Thanks for the steps.

> ... the deleted hunk is regarded as diffadd.

For me it's regarded as deleted:

<img width="182" alt="Screenshot 2021-05-14 at 4 54 48 pm" src="https://user-images.githubusercontent.com/7265/118296716-2ebb6980-b4d5-11eb-9fa0-e608b1081924.png">

**Comment by kevinhwang91** [comment]
Sorry, my color theme mislead me, the syntax is regarded as `DiffText` by `echom synIDattr(synIDtrans(synID(line("."), col("."), 1)), 'name')`

I append this mini.vim:
```vim
highlight DiffAdd ctermbg=green
highlight DiffChange ctermbg=yellow
highlight DiffDelete ctermbg=red
highlight DiffText ctermbg=blue

highlight! link DiffFile DiffText
highlight! link DiffOldFile DiffDelete
highlight! link DiffRemoved DiffDelete
highlight! link DiffAdded DiffAdd
```
`nvim test.lua` -> `nvim -u mini.vim test.lua`

**Comment by airblade** [comment]
> `echom synIDattr(synIDtrans(synID(line("."), col("."), 1)), 'name')`

Is your cursor in the floating window when you do this?  If not, I would expect the result to be `DiffText` because the [filetype is set to `diff`](https://github.com/airblade/vim-gitgutter/blob/f4bdaa4e9cf07f62ce1161a3d0ff70c8aad25bc5/autoload/gitgutter/hunk.vim#L442).

When I have my cursor somewhere in `print("hello")` and do `:GitGutterPreviewHunk`, then `<C-w><C-w>` to move the cursor to the floating window, then `:echom synIDattr( ... )`, I get `DiffDelete` as expected.

**Comment by kevinhwang91** [comment]
Look like you can't reproduce it, feel free to close this issue.

**Comment by airblade** [comment]
GitGutter sets the [filetype of hunk previews to `diff`](https://github.com/airblade/vim-gitgutter/blob/f4bdaa4e9cf07f62ce1161a3d0ff70c8aad25bc5/autoload/gitgutter/hunk.vim#L442) and shows the hunk (minus its header) verbatim from git-diff, i.e. with the leading `-` or `+` on each line.  These leading characters tell Neovim / your colourscheme which highlight groups, e.g. `DiffAdd` / `DiffDelete` to use.  I can't think where this could be going wrong for you.

What colorscheme do you use?

**Comment by kevinhwang91** [comment]
I use the one dark theme tuned by myself, but I can reproduce it with nvim default theme.

You can delete the total of two lines and see the colors for the lines.

**Comment by airblade** [comment]
Please could you post a screenshot with Neovim's default colorscheme?

**Comment by airblade** [comment]
Thanks.

I tried it with the default colorscheme and with [code-dark](https://github.com/tomasiser/vim-code-dark).

Default:

<img width="205" alt="Screenshot 2021-05-19 at 2 00 58 pm" src="https://user-images.githubusercontent.com/7265/118818513-5121fe00-b8ac-11eb-94be-9eb5b8f8acf9.png">

Code-dark:

<img width="227" alt="Screenshot 2021-05-19 at 2 05 29 pm" src="https://user-images.githubusercontent.com/7265/118818546-597a3900-b8ac-11eb-905c-015b9482123b.png">

The results for `:echom synIDattr(synIDtrans(synID(line("."), col("."), 1)), 'name')` depend on the colorscheme:

Cursor position in preview window | Default colorscheme | Code-dark
--|--|--
Anywhere in lines 1 or 2 | diffRemoved | DiffDelete
Anywhere in line 3 | Identifier | DiffAdd

The default diff syntax includes [these lines](https://github.com/neovim/neovim/blob/4ad30f775e5564c539324b4818886f067d2ecd99/runtime/syntax/diff.vim#L333):

```vim
syn match diffRemoved	"^-.*"
syn match diffAdded	"^+.*"
```

And [also](https://github.com/neovim/neovim/blob/4ad30f775e5564c539324b4818886f067d2ecd99/runtime/syntax/diff.vim#L380-L382):

```vim
hi def link diffRemoved		Special
hi def link diffAdded		Identifier
```

In comparison code-dark includes [these lines](https://github.com/tomasiser/vim-code-dark/blob/670fed53a2ae67542a78ef7b642f4aca6b6326dc/colors/codedark.vim#L172-L175):

```vim
" Legacy groups for official git.vim and diff.vim syntax
hi! link diffAdded DiffAdd
hi! link diffChanged DiffChange
hi! link diffRemoved DiffDelete
```

Having said all that, I can't explain why the two deleted lines in your preview are treated differently from each other.  However I think it's a syntax or colorscheme problem, not anything gitgutter is doing wrong.

**Comment by kevinhwang91** [comment]
Thank you for the detailed explanation, I'm understanding now :)
