### ISSUE TITLE
Writing "act" in a macro after a ct [char] or cf [char] inserts "call gitgutter#hunk#text_object(0)"

### ISSUE THREAD

**Issue by rombrom** [airblade/vim-gitgutter#788]
> What is the latest commit SHA in your installed vim-gitgutter?
0f98634b92da9a35580b618c11a6d2adc42d9f90

> What vim/nvim version are you on?
8.2.2320

## Steps to reproduce

1. I spun up a clean alpine container:
```
docker run -it alpine sh
```
2. And in the container:
```
apk update && apk add curl git vim
```
3. Then I added this `.vimrc`:
```
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/bundle')
  Plug 'airblade/vim-gitgutter'
call plug#end()
```
4. initialized a git repo in `~` (e.g. `/root`) and added everything
```
git config --global user.email "foo@example.com"
git config --global user.name "Foo"
git init
git add .
git commit -m 'foo'
```
5. Quit and reopen .vimrc (now under vcs). Plugins should be installed. If needed, quit and reopen again and do the following:
```
gg // top of file
qq // record q macro
ct( // or cf( // change until or until including (
act // type "act" in insert mode
<Esc> // back to normal mode
q // stop recording macro
u // undo changes
@q // execute q macro
```
6. Result
```
call gitgutter#hunk#text_object(0)
t(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.  vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/bundle')
  Plug 'airblade/vim-gitgutter'
call plug#end()
```

**Comment by airblade** [comment]
The macro is triggering the [`ac` operator-pending mode map](https://github.com/airblade/vim-gitgutter/blob/0f98634b92da9a35580b618c11a6d2adc42d9f90/autoload/gitgutter.vim#L144):




which in turn [is mapped to the function](https://github.com/airblade/vim-gitgutter/blob/0f98634b92da9a35580b618c11a6d2adc42d9f90/plugin/gitgutter.vim#L158) 

```vim
onoremap <silent> <Plug>(GitGutterTextObjectOuterPending) :<C-U>call gitgutter#hunk#text_object(0)<CR>
which you see inserted.

**Comment by airblade** [comment]
I think this is a Vim bug: vim/vim#6350.

**Comment by rombrom** [comment]
Oh that’s pretty sick. Thanks for the quick replies. I guess the only way to deal with this behavior until a patch lands is to unmap ca?

**Comment by airblade** [comment]
Yes, or you could set up your own mapping for `<Plug>(GitGutterTextObjectOuterPending)` and then gitgutter won't map `ac`.

Alternatively you could add a no-op to your macro after the `ct(`, as suggested [here](https://github.com/vim/vim/issues/3678#issuecomment-639992731), but that's less convenient.
