### ISSUE TITLE
Bogged Down With Large Files

### ISSUE THREAD

**Issue by herter4171** [airblade/vim-gitgutter#793]
> What is the latest commit SHA in your installed vim-gitgutter?
7d9b7125ff2533f6c520573f54e91db2f13a44b0
> What vim/nvim version are you on?
Vim v8.2.3173

This is a feature request.  We host some large input files on the order of 1E4 lines in version control, and when they are manipulated (long story), virtually every line changes.  For files this large, the plugin burns a single core for around 10-20 seconds and also freezes up Vim until all of the hunks are identified.

Could we have a parameter that defines the largest line count to have the plugin on for?  I'd just like it on by default for dealing with regular code and off for obnoxiously large files.

**Comment by airblade** [comment]
There’s a setting which deactivates gitgutter when the number of signs exceeds a threshold: g:gitgutter_max_signs.  See the help docs or the Activation section in the readme.

However there isn’t a threshold for file size or line count.

Does the max signs setting solve your problem?  If not I’ll add a line count equivalent.

**Comment by herter4171** [comment]
That works for me.  Thanks for the guidance.
