### ISSUE TITLE
Gitgutter is automatically re-enabled after running a `:vim /.../` command

### ISSUE THREAD

**Issue by yolenoyer** [airblade/vim-gitgutter#801]
#### What is the latest commit SHA in your installed vim-gitgutter?

549fb96d5890d5225afda070ca041468c2c770e5

#### What vim/nvim version are you on?

NVIM v0.5.0

#### How to reproduce:

 * Open a modified, tracked file in a versionned project;
 * Run `:GitGutterDisable` to ensure that gitgutter is disabled;
 * Run a command like `:vim /abcdefg/ *`;
 * Then gitgutter is automatically re-enabled.

#### Some big suspicions about the cause

Since `:vim` triggers the events `QuickFixCmdPre` and `QuickFixCmdPost`, I guess the problem comes from here:

https://github.com/airblade/vim-gitgutter/blob/832f7c62261930517453fec96d78f79d5289b75d/plugin/gitgutter.vim#L299-L300

#### Possible workaround proposal

If the auto-commands above are useful, why not adding an overloading internal variable (something like `g:gitgutter_enabled_overload`), which would bypass the public variable `g:gitgutter_enabled` everywhere it is needed, and replace the above code by something like:

```vim
autocmd QuickFixCmdPre  *vimgrep* let g:gitgutter_enabled_overload = 0 
autocmd QuickFixCmdPost *vimgrep* let g:gitgutter_enabled_overload = 1
 ```

**Comment by airblade** [comment]
Thanks for letting me know about this.
