### ISSUE TITLE
GitGutterBufferToggle when GitGutterDisable.

### ISSUE THREAD

**Issue by karamellpelle** [airblade/vim-gitgutter#803]
How can I turn on gitgutter per buffer with default mode _off_ (I use the mapping `nmap <leader>g :GitGutterBufferToggle<CR>`)?. Everything is _on_ by default.  If I use `GitGutterDisable`, `GitGutterBufferToggle` does not work.

> What is the latest commit SHA in your installed vim-gitgutter?
256702dd1432894b3607d3de6cd660863b331818

> What vim/nvim version are you on? 
`VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 10 2020 20:32:49)` / `NVIM v0.4.3`

**Comment by karamellpelle** [comment]
I see that GitGutter will not show if the file is up-to-date. So maybe my issue is not that important; default _on_ can be a nice reminder to show GitGutter if the file has any changes.

**Comment by airblade** [comment]
> How can I turn on gitgutter per buffer with default mode _off_...? If I use `GitGutterDisable`, `GitGutterBufferToggle` does not work.

That sounds an oversight by me, or perhaps a bug.  I'll look into it (though it might take a few days as I have less time available than usual at the moment).

> I see that GitGutter will not show if the file is up-to-date.

It sounds like you want the sign column to be displayed even when there are no signs – is that right?  You can achieve this with `set signcolumn=yes`.

**Comment by karamellpelle** [comment]
`GitGutterDisable` seems to turn off gitgutter (which makes sense - it's not a bug, it's a feature 😄 ). But it doesn't make it possible to turn on gitgutter per buffer.

**Comment by airblade** [comment]
This should work now – please let me know how you get on.
