### ISSUE TITLE
Gutter doesn't update unless I focus to another vim window and then go back

### ISSUE THREAD

**Issue by exapsy** [airblade/vim-gitgutter#808]
> Description

When I change a line, then stage the changed hunk, the gutter doesn't update. I noticed that it updates though when I focus on another vim window OR if I alt-tab to another window and then go back to vim/terminal.

> Disclaimer

I recognize this is likely not an issue of the plugin directly, but I thought this was the most appropriate place to address the issue since it affects the experience with this plugin directly and finding a solution here would probably be a good place for future visitors, even if that requires making an issue to another conflicting repository.

> What terminal emulator are you running vim/nvim from?

- kitty - 0.23.1 created by Kovid Goyal
- gnome-terminal - 3.40.3 for GNOME 40
- konsole - 21.08.2

I'm not actually running all of them, I use kitty for my daily use.

But the fact that the same issue occurs on all of them is an indication that the terminal is most likely not the cause here.

> Are you using tmux?

Yes, I am using tmux.

> If so does it happen only in tmux?

No, it happens outside of tmux too.

> What is your vim configuration?

https://gist.github.com/exapsy/516a7f52fc1134f3546f443e7af43661

> What are your vim plugins
<details>
<summary>Plugin list</summary>

```
" My Plugins
Plugin 'liuchengxu/vista.vim'
Plugin 'VundleVim/Vundle.vim'
Plugin 'szw/vim-maximizer'
Plugin 'xolox/vim-session'
Plugin 'xolox/vim-misc'
Plugin 'neoclide/coc.nvim'
Plugin 'rhysd/vim-clang-format'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'leafgarland/typescript-vim'
Plugin 'tomasiser/vim-code-dark'
Plugin 'airblade/vim-gitgutter'
Plugin 'mattn/vim-gist'
Plugin 'mattn/webapi-vim'
Plugin 'liuchengxu/vim-clap'
Plugin 'tpope/vim-fugitive'
Plugin 'google/vim-maktaba'
Plugin 'google/vim-codefmt'
Plugin 'google/vim-glaive'
Plugin 'majutsushi/tagbar'
Plugin 'ternjs/tern_for_vim'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/nerdcommenter'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'fatih/vim-go'
Plugin 'hexdigest/gounit-vim'
Plugin 'mdempsky/gocode'
Plugin 'rust-lang/rust.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'ryanoasis/vim-devicons'
```
</details>

> What is the latest commit SHA in your installed vim-gitgutter?

```
commit 256702dd1432894b3607d3de6cd660863b331818 (HEAD -> master, origin/master, origin/HEAD)
Author: Andy Stewart <boss@airbladesoftware.com>
Date:   Tue Sep 7 15:10:00 2021 +0100

    Fix restoration of g:gitgutter_enabled after :vimgrep

    Fixes #801.
```

> What vim/nvim version are you on?

```
$ nvim -v  

NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by airblade** [comment]
> When I change a line, then stage the changed hunk, the gutter doesn't update.

How are you staging the hunk?  Using the plugin or from the command line?

From the readme:

> Relies on the FocusGained event. If your terminal doesn't report focus events, either use something like [Terminus](https://github.com/wincent/terminus) or set `let g:gitgutter_terminal_reports_focus=0`. For tmux, `set -g focus-events on` in your tmux.conf.

Does that help?

**Comment by exapsy** [comment]
> How are you staging the hunk? Using the plugin or from the command line?

I use `<leader>hs` which in my .vimrc config is this

```
nmap <leader>hs <Plug>(GitGutterStageHunk)
```

> Relies on the FocusGained event. If your terminal doesn't report focus events, either use something like Terminus or set let g:gitgutter_terminal_reports_focus=0. For tmux, set -g focus-events on in your tmux.conf.

I tried that fix, it didnt fix :P I have `let g:gitgutter_terminal_reports_focus=0` in my `.vimrc`, and I also have set `set -g focus-events` in my `.tmux.conf` as well.

Regardless, this happens outside of tmux as I state, so I'm not confident that this is a tmux issue.

**Comment by airblade** [comment]
Since you're staging hunks with the plugin, the terminal / focus thing is irrelevant.

The code [updates the signs straight after staging a hunk](https://github.com/airblade/vim-gitgutter/blob/256702dd1432894b3607d3de6cd660863b331818/autoload/gitgutter/hunk.vim#L311).

What is your `'updatetime'`?

**Comment by airblade** [comment]
Does commenting our your [`checktime` autocommand](https://gist.github.com/exapsy/516a7f52fc1134f3546f443e7af43661#file-vimrc-L394) solve the problem?  I don't think it will but perhaps it's worth a try.

**Comment by airblade** [comment]
After staging, does `:redraw!` help?

Could you make a one-line change to a file, stage it, do `:echo sign_getplaced('', {'group': 'gitgutter'})`, and paste the result below?  This will tell us whether the signs are correct (in which case the terminal is not drawing them properly).

Regarding your screenshots, are you using a red background for modified lines?  The second screenshot definitely looks odd with the signs in the sign column highlighted but not the lines of code.

**Comment by exapsy** [comment]
> After staging, does :redraw! help?

No, did nothing.

> Could you make a one-line change to a file, stage it, do :echo sign_getplaced('', {'group': 'gitgutter'}), and paste the result below? This will tell us whether the signs are correct (in which case the terminal is not drawing them properly).

**Before**
```vim
:echo sign_getplaced('', {'group': 'gitgutter'})

[{'signs': [{'lnum': 55, 'id': 1, 'name': 'GitGutterLineModified', 'priority': 10, 'group': 'gitgutter'}, {'lnum': 59, 'id': 2, 'name': 'GitGutterLineModified', 'priority': 10, 'group': 'gitgutter'}], 'bufnr': 1}]
```

**After**
```vim
[{'signs': [{'lnum': 56, 'id': 1, 'name': 'GitGutterLineModified', 'priority': 10, 'group': 'gitgutter'}, {'lnum': 60, 'id': 2, 'name': 'GitGutterLineModified', 'priority': 10, 'group': 'gitgutter'}], 'bufnr': 1}]
```

> Regarding your screenshots, are you using a red background for modified lines?
These are my configurations for gitgutter colors

```vim
" GitGutter #signs #colors
highlight GitGutterAdd    guifg=#009900 ctermfg=2 " 2 = Green
highlight GitGutterChange guifg=#bbbb00 ctermfg=3 " 3 = Olive (Desaturated dark green)
highlight GitGutterDelete guifg=#ff2222 ctermfg=1 " 1 = Maroon (Dark red)
```

> The second screenshot definitely looks odd with the signs in the sign column highlighted but not the lines of code.

It is indeed. Can't really figure out why would that happen.

**Comment by airblade** [comment]
With your `:echo sign_getplaced()`, the only difference between _before_ and _after_ is the line numbers of the two modified lines have increased by 1.  That doesn't make sense to me.

Thanks for the screencast but unfortunately I can't see what's going on.  I can see the cursor moving between two windows on the same buffer, but not the keys you are pressing nor at what point you stage anything.  I couldn't find a way to slow down the playback.

Please could you turn on logging with `let g:gitgutter_log=1`, make a change to a file and stage it, then post the `gitgutter.log`?

**Comment by L2AsHdz** [comment]
I've been using this plugin recently and noticed this behavior when adding a hunk to the stage. (Very good plugin by the way)

>Please could you turn on logging with let g:gitgutter_log=1, make a change to a file and stage it, then post the gitgutter.log?

This is the file at the moment of adding the hunk, that's when it gives the error
[gitgutter.log](https://github.com/airblade/vim-gitgutter/files/7867891/gitgutter.log)


And this other one is after having switched to another window and returned, here the signs are already updated.
[gitgutter2.log](https://github.com/airblade/vim-gitgutter/files/7867892/gitgutter2.log)

**Comment by airblade** [comment]
Aha, thanks for the explanation :)
