### ISSUE TITLE
How to Setup on Windows using Neovim?

### ISSUE THREAD

**Issue by homie-desktop** [airblade/vim-gitgutter#815]
Hi, I've tried installing gitgutter and  aware of the possible `path` issue  `let g:gitgutter_git_executable='C:\Program Files\Git\bin\git.exe'
`. It doesn't output any errors and the `gitgutter commands` are available like `GitGutterEnable`, but there's no hunks or any signs showing even in the status line of airline. 

I have my git installed in `C:\Program Files\Git\bin\git.exe`

> Neovim version 0.6.1

Thanks.

**Comment by airblade** [comment]
It should work without setting `g:gitgutter_git_executable` – the only reason it's mentioned in the readme is because of the tiny chance of some other program called `git` being on the path.

If it's still not working, try `let g:gitgutter_log=1` and then looking at the log file `gitgutter.log` in the directory where gitgutter is installed.

**Comment by homie-desktop** [comment]
Hi, thanks for the quick response and your time. Still doesn't work even when `git executable` wasn't specified. 

Is this the correct log?

==== start log session ====

  0.000028 function <SNR>30_on_bufenter[22]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  0.000028 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

  1.735066 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  1.735066 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

  5.896082 function gitgutter#enable[1]..<SNR>112_toggle_each_buffer[6]..gitgutter#buffer_enable[3]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  5.896082 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

  6.315083 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
  6.315083 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

 12.253172 function gitgutter#all[8]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 12.253172 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

 12.297984 function <SNR>30_on_bufenter[22]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 12.297984 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

 15.428165 function <SNR>30_on_bufenter[22]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 15.428165 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

 19.350168 function gitgutter#all[8]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 19.350168 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

 19.393109 function <SNR>30_on_bufenter[22]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 19.393109 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

 19.532429 function <SNR>30_on_bufenter[20]..gitgutter#all[8]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 19.532429 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 20.148711 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 20.148711 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 22.946200 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 22.946200 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 26.862910 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 26.862910 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 30.566783 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 30.566783 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 40.334333 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 40.334333 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 64.957471 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 64.957471 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 65.505117 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 65.505117 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 66.702238 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 66.702238 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 68.300456 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 68.300456 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 70.608369 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 70.608369 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 72.195593 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 72.195593 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 74.237912 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 74.237912 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 78.708004 function <SNR>30_on_bufenter[20]..gitgutter#all[8]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 78.708004 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

 79.619393 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 79.619393 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

 84.043907 function gitgutter#all[8]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 84.043907 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

 84.088772 function <SNR>30_on_bufenter[22]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 84.088772 [async] cd /d "C:\Users\user123\.dotfiles" && git  ls-files --error-unmatch --full-name -z -- .vimrc

 90.922282 function <SNR>30_on_bufenter[20]..gitgutter#all[8]..gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 90.922282 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 91.539704 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 91.539704 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

 92.602109 function gitgutter#process_buffer[14]..<SNR>112_setup_path[3]..gitgutter#utility#set_repo_path[12]..gitgutter#async#execute[1]:
 92.602109 [async] cd /d "C:\Users\user123\.dotfiles\.vim\plugged\vim-gitgutter" && git  ls-files --error-unmatch --full-name -z -- gitgutter.log

**Comment by airblade** [comment]
Thanks for the log file.

The first thing gitgutter does is try to establish the path to the file from the repo root.  It looks like this command is not producing a result and is therefore being executed over and over again.

What do you get if you run it by hand on the command line?

```
cd /d "C:\Users\user123.dotfiles" && git ls-files --error-unmatch --full-name -z -- .vimrc
```

**Comment by airblade** [comment]
The `fatal` error is what git produces when the file is not in a git repo.  Are you sure your `.dotfiles` folder is a git repo?

**Comment by homie-desktop** [comment]
@airblade , No. My `git repo` folder is in my  `~/OneDrive/Desktop/GitHub`. How do I point it to my desktop directory? Thanks

**Comment by airblade** [comment]
Normally you have one git repository per project or "thing".  `~/OneDrive/Desktop/GitHub` sounds like a folder which would contain git repositories instead of being one itself.

If your `.dotfiles` folder isn't in git, then you could make it a git repository with:

```
git init
git add .
git commit -m "Initial import"
```

You can read more about this in [Getting a Git Repository](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository).

Anyway, it sounds like gitgutter is working correctly.

**Comment by airblade** [comment]
Great to hear you got it working!
