### ISSUE TITLE
undo hunk produces extra ^M on Windows10

### ISSUE THREAD

**Issue by xubury** [airblade/vim-gitgutter#823]
> What is the latest commit SHA in your installed vim-gitgutter?

commit 2df360de757c39c04076cb04bcbbd361dec3c8c2
> What vim/nvim version are you on?

NVIM v0.7.0-dev+920-g7e2ce35e3

See gif below, when I undo a modified hunk, it adds an extra ^M character. 
Same neovim and git config on Linux doesn't have this bug.
The only difference in my `.gitconfig` is that I have `autocrlf=true` on my windows system and `autocrlf =input` on my linux system.
![gitbug](https://user-images.githubusercontent.com/46261364/158972236-ead655ec-955a-4fc3-81a7-8cf9696fb099.gif)

**Comment by airblade** [comment]
The commit SHA you gave isn't from this repo.

Are you using vim-gitgutter or perhaps [gitsigns](https://github.com/xubury/myvimconfig/blob/master/lua/plugins/gitsigns.lua)?

**Comment by xubury** [comment]
> The commit SHA you gave isn't from this repo.
> 
> Are you using vim-gitgutter or perhaps [gitsigns](https://github.com/xubury/myvimconfig/blob/master/lua/plugins/gitsigns.lua)?

oh my bad, I was meant to post on gitsign. Got confused by brower tab.

**Comment by airblade** [comment]
No worries.

For what it's worth, I think vim-gitgutter doesn't have this problem ;)

**Comment by xubury** [comment]
> No worries.
> 
> For what it's worth, I think vim-gitgutter doesn't have this problem ;)

yeah I was browsing through the issues and saw this was fixed while ago.
