### ISSUE TITLE
Can we set the background color of the preview window?

### ISSUE THREAD

**Issue by Alex-duzhichao** [airblade/vim-gitgutter#824]
> What is the latest commit SHA in your installed vim-gitgutter?
18d12985ea6cb7ede59755ff4fd0a9fa1e6bf835

> What vim/nvim version are you on?
I'm using nvim v0.6.1

Hi, as the question says, I can't found how to set the background color of the preview window.
I am also using [git-messenger](https://github.com/rhysd/git-messenger.vim), users can define a highlight `gitmessengerPopupNormal` for git-messenger, and git-messenger will [set the `winhighlight` of preview window using `gitmessengerPopupNormal`](https://github.com/rhysd/git-messenger.vim/blob/2e67899355f3f631aad6845925e4c2c13546444d/autoload/gitmessenger/popup.vim#L195) .

Could vim-gitgutter provide a similiar way for users to set the background color of preview window? Thanks

**Comment by airblade** [comment]
Please could you show me a screenshot?  I want to make sure I understand :)

**Comment by Alex-duzhichao** [comment]
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/9667107/160139641-776826c7-db06-456b-8ad4-42571f63b6d6.png">

In the first sceenshot, I haven't defined `gitmessengerPopupNormal`. The popup window's background is ugly.

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/9667107/160139754-bc32fc15-4938-4bd5-a7a2-018a240dddbd.png">

In the second sceenshot, I define `gitmessengerPopupNormal` and the popup window looks more beautiful.

**Comment by airblade** [comment]
Thanks for the screenshots.

GitGutter sets the (floating) preview window's [filetype to `diff`](https://github.com/airblade/vim-gitgutter/blob/18d12985ea6cb7ede59755ff4fd0a9fa1e6bf835/autoload/gitgutter/hunk.vim#L435) so you can set the background colour via the `diff*` highlight groups, as the [readme explains](https://github.com/airblade/vim-gitgutter#the-diff-syntax-colours-used-in-the-preview-window).

The `diff*` groups' defaults are [here](https://github.com/neovim/neovim/blob/b81c310d49f77c8f92ba2fdd99c7e0e9cb49d498/runtime/syntax/diff.vim#L380-L382).
