### ISSUE TITLE
git update-index --assume-unchanged is ignored

### ISSUE THREAD

**Issue by Phosphenius** [airblade/vim-gitgutter#826]
> What is the latest commit SHA in your installed vim-gitgutter?

18d12985ea6cb7ede59755ff4fd0a9fa1e6bf835

> What vim/nvim version are you on?

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 13 2022 09:09:01)
Included patches: 1-4743

When ignoring the changes in a file via  `git update-index --assume-unchanged`, they are still visible in the gutter in vim. On one hand, that is quite nice because one can still see changes even though they are being ignored by git and would otherwise not be visible, on the other hand, when changes are being ignored, they should not be shown at all. 

So maybe a new status could be introduced to mark ignored changes?

**Comment by airblade** [comment]
This is an interesting edge case.  Should gitgutter show the differences between the buffer and the index or should it show the differences that git-diff reports?

I think we need to pick one or the other.  Being able to show ignored changes with their own signs would require doing both and then diffing the diffs.  It's feasible but would double the amount of work vim does each time, slowing things down.  It would also complicate the code.  I don't think it's worth it.

So which one to pick?  Maybe it's possible to make it configurable – I'm not sure yet, I'll have to do some research.  The current approach lets you diff against the index or the working tree; and handles line endings correctly.  Any new approach would have to do so too.

**Comment by Phosphenius** [comment]
IMO it should not show the diff since the changes are explicitly being ignored. Of course it would be nice to know that there are ignored changes, but that is not how `git update-index --assume-unchanged` works. Interestingly, I can undo the ignored changes via the gitgutter, but I cannot stage them. Undoing ignored changes should not be possible as they're ignored for a reason (I don't want to commit them, but I need them anyways).

I also don't think a configurable option is worth the effort or makes sense, really. Like you said, this is an edge case.

**Comment by Phosphenius** [comment]
Thanks, works like a charm!
