### ISSUE TITLE
Feature Request: Add :GitGutterDiffOrig

### ISSUE THREAD

**Issue by balki** [airblade/vim-gitgutter#827]
> What is the latest commit SHA in your installed vim-gitgutter?
latest

> What vim/nvim version are you on?
latest

Sometimes I prefer the `vimdiff` style view when reviewing changes instead of using  `:GitGutterPreviewHunk` on each hunk. It would be good to quickly go to that view and come back without having to quit vim and run `git difftool /path/to/file`. 

It would be similar to to the builtin `:DiffOrig` command, except it uses whatever diff gitgutter shows and respect variables like `gitgutter_diff_base`

**Comment by airblade** [comment]
Thanks for the suggestion!

I've never used `:DiffOrig` or `vimdiff` so let me know if there are any problems.

**Comment by balki** [comment]
Awesome Thank you for quick response. Tested and works good!
