### ISSUE TITLE
Error: Can't open temp file without sudo

### ISSUE THREAD

**Issue by shqln** [airblade/vim-gitgutter#828]
First run
`sudo -s`
then vim into a file (tracked by git), gives this error:
`Error detected while processing BufEnter Autocommands for "*"..function gitgutter#process_buffer[20]..BufEnter Autocommands for "*"..function gitgutter#process_buffer[8]..diff#run_diff:
line   30:
E484: Can't open file /tmp/vMxhVGZ/0
Press ENTER or type command to continue`

If I just `vim` normally it gives the same error.
However, I noticed that `sudo vim` seems to work fine.

> What is the latest commit SHA in your installed vim-gitgutter?
f7ea5f40a680797b0ad8d78ec972e32cf17e63c7

> What vim/nvim version are you on?
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 28 2021 11:18:09)
Included patches: 1-3458

Ubuntu version 18.04

Other plugins installed
vim airline 
nerd tree
youcompleteme

**Comment by airblade** [comment]
I don't think there's anything the plugin can do about that.  It's an OS-level file permissions issue.

**Comment by shqln** [comment]
Ah I thought so, do you know any workarounds?

**Comment by airblade** [comment]
I just use `sudo vim` if necessary.  You could try searching vi.stackexchange.com.
