### ISSUE TITLE
Less targets than List items

### ISSUE THREAD

**Issue by sak96** [airblade/vim-gitgutter#829]
*What is the latest commit SHA in your installed vim-gitgutter?*
> `2f359076bcef92cb886807dc3c6d312eb41ac428` 

*What vim/nvim version are you on?*
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 30 2022 23:54:07)

*What are the logs?*
```log
Error detected while processing function <SNR>163_on_exit_vim[15]..1:
line    1:
E687: Less targets than List items
```
*What are the `scriptnames` ?*
> 163: ~/.vim/plugged/vim-gitgutter/autoload/gitgutter/async.vim

*How to reproduce?*
```
cd /tmp
mkdir repo
cd repo
touch git\ fail.md
git add .
vim git\ fail.md
```
*What do I understand*?
```vim
  if !exit_code
    call self.handler.out(self.buffer, join(self.stdoutbuffer, "\n"))
  endif
```
The call to self.handler.out is failing. 
I could not follow the flow of code from here (still learning vim script).
`printf debugging` did not give much information.
my understanding is that file/folder name containing `git ` is causing the issue.
your help would be appreciated.

**Comment by sak96** [comment]
temporary work around disabling git gutter for file having `git ` in name

```vim
autocmd BufNewFile,BufRead */*git\ * GitGutterBufferDisable
```

**Comment by airblade** [comment]
The problem was the space, not `git`.

Thanks for reporting this!

**Comment by sak96** [comment]
That was quick. Thanks for the fix.
