### ISSUE TITLE
Doesn't show anything

### ISSUE THREAD

**Issue by xlebushek13** [airblade/vim-gitgutter#831]
Git gutter dont shown anything but if i execute :sing place group=gitgutter its show diff

<img width="640" alt="image" src="https://user-images.githubusercontent.com/73338982/165600667-37a38e7a-d5dd-456a-abb9-965450f6b3c0.png">

why gutter don show changes in number line

<img width="357" alt="image" src="https://user-images.githubusercontent.com/73338982/165600624-9379da58-b7d5-4672-8a69-e3c65967c1c1.png">

**Comment by xlebushek13** [comment]
im using nvim 0.7.0
and lunar vim 1.1.3

**Comment by airblade** [comment]
Thanks for the details.

Either the sign column isn't showing or the signs have the same foreground (and background) colour as the sign column.

What do these produce?

```viml
:echo &signcolumn
:sign list GitGutterLineAdded
:highlight GitGutterAdd
```

**Comment by xlebushek13** [comment]
1. command output no
2. command output 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/73338982/165752581-95ba6ea8-7b62-426e-9a24-81cfd7a7567c.png">
3. command output 
<img width="384" alt="image" src="https://user-images.githubusercontent.com/73338982/165752671-c850ff33-b907-4fb3-8e29-5dd1310f0cee.png">

**Comment by airblade** [comment]
Try `set signcolumn=yes` in your init.vim.

**Comment by xlebushek13** [comment]
Yep this work, thanks a lot, im so inattentive
