### ISSUE TITLE
GitGutterDiffOrig filetype/syntax-highlighting

### ISSUE THREAD

**Issue by ds2606** [airblade/vim-gitgutter#833]
> What is the latest commit SHA in your installed vim-gitgutter?
2f359076bcef92cb886807dc3c6d312eb41ac428
> What vim/nvim version are you on?
8.2

When `GitGutterDiffOrig` opens a diff in a scratch-buffer split, the filetype is unset, so no syntax highlighting is shown. GitGutter should automatically set the scratch-buffer filetype to the same as the original buffer so that syntax highlighting is shown.

Hopefully this should be an easy win?

Example:
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/2286295/166524259-d4d2effc-4e7d-4eb4-96b1-f376b88dcb5b.png">

After a manual `:set ft=javascript` in the scratch buffer:
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/2286295/166524320-ca8ac247-051d-498c-b562-41cd09ff8c47.png">

**Comment by airblade** [comment]
In general I like to stay consistent with Vim's behaviour, and [Vim's `:DiffOrig` command](https://github.com/vim/vim/blob/05cf63e9bdca1ac070df3e7d9c6dfc45e68ac916/runtime/defaults.vim#L145-L146) does not set the filetype.

However I think it's a reasonable thing to do.

Thanks for the suggestion.

**Comment by ds2606** [comment]
Cool I understand, for now I have my `:GitGutterDiffOrig` mapped to

```vim
function! GitGutterDiffWithSyntax()
    let l:ft_syntax = &ft
    call GitGutterDiffOrigToggle()
    +windo let &ft = l:ft_syntax
endfunction
```

**Comment by airblade** [comment]
You don't need that, it's in 719d4ec above.

**Comment by ds2606** [comment]
Oh I misunderstood and thought you weren't implementing it - great, thank you!
