### ISSUE TITLE
Hardcoded key binds should be removed?

### ISSUE THREAD

**Issue by smalinux** [airblade/vim-gitgutter#835]
First of all, thank you for this project.
I apologize if this question is too simple.

I want to unbind(or remove them completely) all these binds because cause conflicts with my older binds:
`<leader>hp`, `<leader>hs`, and `<leader>hu`
Are there any plans to not hardcode them inside the plugin?

Thanks

**Comment by bew** [comment]
From the readme:
> If you don't want vim-gitgutter to set up any mappings at all, use this:
>
> `let g:gitgutter_map_keys = 0`

**Comment by airblade** [comment]
It's also worth knowing that GitGutter won't map `<leader>hp`, `<leader>hs`, and `<leader>hu` if they have already been mapped, nor if you have already mapped what they map to, i.e. `<Plug>(GitGutterStageHunk)` etc:

https://github.com/airblade/vim-gitgutter/blob/719d4ec06a0fb0aa9f1dfaebcf4f9691e8dc3f73/autoload/gitgutter.vim#L140-L151

**Comment by smalinux** [comment]
Thank you for the response. 
I mapped `<leader>h` for another plugin, so this bind was a little slow because nvim was waiting to see if it would be added another key after leader+h

Thanks
