### ISSUE TITLE
About the windows rearrangement triggered by preview

### ISSUE THREAD

**Issue by Aster89** [airblade/vim-gitgutter#837]
> What is the latest commit SHA in your installed vim-gitgutter?

I've just pulled in the change you made for #836, and you haven't pushed anything else.

> What vim/nvim version are you on?

Same as #836 

---

I could reproduce this only with git-gutter in my vimrc (plus vim-plug boilerplate).

Do <kbd>Ctrl-w</kbd><kbd>s</kbd><kbd>Ctrl-w</kbd><kbd>j</kbd><kbd>Ctrl-w</kbd><kbd>1</kbd><kbd>0</kbd><kbd>_</kbd><kbd>Ctrl-w</kbd><kbd>k</kbd><kbd>leader</kbd><kbd>h</kbd><kbd>p</kbd>, where <kbd>leader</kbd><kbd>h</kbd><kbd>p</kbd> is for getting your hunk preview. You'll see that,

  - if the there's space enough for the horizontal split for the preview window, the preexisting horizontal split doesn't move
  - otherwise, the horizontal split moves toward the top by _a lot_ more than necessary.

Clearly you must push it up if there's no space, but you could push it only as little as needed, especilly if the window is not the one on which you're inspecting the hunks.

Not sure if this could be mitigate with an option :/

[![asciicast](https://asciinema.org/a/gBI7WWABbwmwRBiCToyeHWsyh.svg)](https://asciinema.org/a/gBI7WWABbwmwRBiCToyeHWsyh)

**Comment by airblade** [comment]
Thanks for the asciicast.  It makes it much easier to understand the issue!

GitGutter is supposed to set the height of the hunk preview window to the lesser of the hunk height in screen lines and `'previewheight'`.

https://github.com/airblade/vim-gitgutter/blob/ded11946c04aeab5526f869174044019ae9e3c32/autoload/gitgutter/hunk.vim#L552-L554

As far as I can see in your video, this is what happens, regardless of the height of the other windows.  The way the other windows behave is up to vim and vim's window resizing algorithm is, I believe, somewhat mysterious.

Having said that, I think `set noequalalways` will do what you want.

**Comment by Aster89** [comment]
Oh, I see. It's obvious now that your plugin is unrelated. Thanks for explaining.

I'll give `noequalalways` a try.
