### ISSUE TITLE
Mapping to jump to next/previous file with git status change

### ISSUE THREAD

**Issue by brendanator** [airblade/vim-gitgutter#844]
Vim unimpaired has a maaping `]f` that takes me to the next alphabetical file and vim-gitgutter has `]h` which takes me to the next hunk in the current file.

It'd be great if there was a mapping that took me to the first hunk in the next file with changes - e.g. `]H`
And `[H` to go to the last(?) hunk in the previous file with changes

**Comment by airblade** [comment]
This section of the readme explains how to do exactly that.

https://github.com/airblade/vim-gitgutter#cycle-through-hunks-in-all-buffers
