### ISSUE TITLE
Don't change shell option

### ISSUE THREAD

**Issue by tracyone** [airblade/vim-gitgutter#847]
hi, 

first, I would like to thank you for your work on this plugin.

second, I found `shell` option was changed by vim-gitgutter. 

My default setting of `shell` is zsh， I use built-in terminal feature of vim, I want to open terminal using `shell` option.

https://github.com/airblade/vim-gitgutter/blob/f19b6203191d69de955d91467a5707959572119b/autoload/gitgutter/utility.vim#L195-L197

**Comment by airblade** [comment]
The plugin only changes `'shell'` for some of the commands it runs and even then only when running synchronously, which is not the default.  It always changes the value back again afterwards.

https://github.com/airblade/vim-gitgutter/blob/f19b6203191d69de955d91467a5707959572119b/autoload/gitgutter/utility.vim#L94-L96

So it should not affect your use of the built-in terminal.  If it does, it's a bug – and please give me further details such as how to reproduce the problem.

**Comment by airblade** [comment]
> So it should not affect your use of the built-in terminal. If it does, it's a bug – in which case please give me further details such as how to reproduce the problem.

Closing this because I haven't heard any more details.  Let me know if it's still a problem!
