### ISSUE TITLE
Feature Request: Blame

### ISSUE THREAD

**Issue by coffeebe4code** [airblade/vim-gitgutter#849]
> What is the latest commit SHA in your installed vim-gitgutter?
latest
> What vim/nvim version are you on?
I am on version 9 of vim.

I'm just curious if there is any plan for being able to support blames. Like a BlamesHunk or something similar?

Awesome tool btw. I'm loving the quick fix list of all hunks, and being able to go to next hunks

**Comment by airblade** [comment]
Thanks for the kind words – I'm glad the plugin's helpful!

I can't quite see the benefit here of `blame`.  The code only knows about unstaged hunks, so if you `blame`d them wouldn't it just tell you that you made the modifications?

**Comment by coffeebe4code** [comment]
I was looking for blame of other sections of the code. I found another plugin that works. Thanks for the followup, I wasn't aware that this project was only focused on hunks, makes sense for the specialization!
