### ISSUE TITLE
vim-gitgutter clobbers v:shell_error via autocmd ShellCmdPost

### ISSUE THREAD

**Issue by nkouevda** [airblade/vim-gitgutter#869]
> What is the latest commit SHA in your installed vim-gitgutter?

5f525476f3ade40e60aa295a8a2a01c0935b0d61

> What vim/nvim version are you on?

    $ vim --version
    VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 27 2023 17:04:14)
    macOS version - arm64
    Included patches: 1-1800
    Compiled by Homebrew
    [...]

### Setup

1. Open any file tracked by git that did not exist in `g:gitgutter_diff_base`, e.g. `let g:gitgutter_diff_base = 'HEAD^'` and open a file that was added in `HEAD`
2. `:!echo foobar`
3. `:echo v:shell_error`

### Expected result

`:echo v:shell_error` should print `0`

### Actual result

`:echo v:shell_error` prints `128`

## Problem

Due to `autocmd ShellCmdPost * call gitgutter#all(1)` in [`plugin/gitgutter.vim`](https://github.com/airblade/vim-gitgutter/blob/5f525476f3ade40e60aa295a8a2a01c0935b0d61/plugin/gitgutter.vim#L323), `gitgutter#diff#run_diff` is called immediately after `:!echo foobar`, which [calls `gitgutter#utility#system(cmd)`](https://github.com/airblade/vim-gitgutter/blob/5f525476f3ade40e60aa295a8a2a01c0935b0d61/autoload/gitgutter/diff.vim#L92) in order to determine `"file unknown in base"`. This sets `v:shell_error` to `128`, and we lose `v:shell_error` from the `:!echo foobar` that we just ran.

The opposite is similarly problematic: if we're editing a file that _does_ exist in `g:gitgutter_diff_base`, and we run something like `:!exit 1`, then `:echo v:shell_error` after that prints `0`, not `1`.

I stumbled across #841 while figuring this out, but the issue here is different; I confirmed that `:echo gitgutter#async#available()` and `:echo g:gitgutter_async` both print `1`.

## Workarounds (outside of vim-gitgutter)

1. From [vifm/vifm.vim#80](https://github.com/vifm/vifm.vim/issues/80) I see that one workaround is to use `:noautocmd` for any individual `:!cmd`, and I've confirmed that works for simple cases like this, but 1) it might not be desirable to temporarily disable all autocmds like that, and 2) this places the burden on other plugins and user code to handle this case.

2. It's possible to entirely disable this autocmd via `autocmd! gitgutter ShellCmdPost *`, though this doesn't work in vimrc, and must be in e.g. a `~/.vim/after/plugin/disable-gitgutter-ShellCmdPost.vim`. Same downsides as the other workaround.

## Possible solutions (in vim-gitgutter)

1. Assuming `g:gitgutter_async && gitgutter#async#available()`, then similar to how the actual diff is run via [`gitgutter#async#execute`](https://github.com/airblade/vim-gitgutter/blob/5f525476f3ade40e60aa295a8a2a01c0935b0d61/autoload/gitgutter/diff.vim#L172), would it be possible to check for `"file unknown in base"` async too? (I'm not super familiar with the code here so this might be nonsensical or impossible, but I figure it's worth asking)

2. Conceptually similar to how `winsaveview()` + `winrestview()` works, can we manually restore the previous `v:shell_error`?

**Comment by nkouevda** [comment]
Proposed implementation of the second solution: #870. This seems to work, but not sure if there are edge cases I haven't considered, or any downsides / side effects.

**Comment by airblade** [comment]
Thanks for reporting this in such detail.

I had to remind myself why gitgutter watches for `ShellCmdPost`: it's a hacky way of making gitgutter run after a shell command executed from vim which updates the index (#418).  Unfortunately it runs for all shell commands, not just `git` ones.  Ideally there would be a way to watch the index instead.

As for the related `FileChangedShellPost`, I'm not sure whether it's needed.  It must have been at the time in 2013 (1511325).

Anyway, with solution (1) I'm not sure whether there's a guarantee that async jobs are completed in the order they are started.  Plus it would make the code a little more complicated.  And it doesn't solve the problem for anyone using the plugin synchronously.  (These days I assume noone would choose to run it synchronously, but it's there for backward-compatibility.)

Solution (2) sounds good.  I'll look at your PR.

**Comment by airblade** [comment]
Ah, I just looked at the code in detail and perhaps (1) would be best.  When I wrote the code to handle the case of a file not existing in `g:gitgutter_diff_base`, I made it synchronous simply because that was simpler and quicker than making it asychronous.  But perhaps it would be better asynchronous.

**Comment by airblade** [comment]
Hmm, the more I think about it, the more I remember why handling files not in the diff base was not entirely straightforward.

The current approach is to run the check synchronously so we can stop there if the file does not exist in the diff base; and if it does exist, carry on with the diff command as before (either synchronously or asynchronously).

I always want the diff to be a single command.  Checking the existence of a file in the diff base is hard to combine with the diff command.  Although I suppose it could be combined with `&&`.  The diff shouldn't fail, i.e. shouldn't exit with a non-zero exit code.  So if the combined command failed we could probably assume it was because the file didn't exist (if `g: gitgutter_diff_base` is set), or even check whether the exit code was `128`, and then proceed as before for non-existent files.

Solution (2) is looking more and more appealing :)

**Comment by airblade** [comment]
The difficulty with the shell commands is that they need to run on Windows too, including powershell, pwsh, cygwin, bash installed by the git installer, etc.  You can see some of the configuration here:

https://github.com/airblade/vim-gitgutter/blob/5f525476f3ade40e60aa295a8a2a01c0935b0d61/autoload/gitgutter/utility.vim#L209-L218

Something as simple as making the command finish successfully took two attempts to get right (a1a29b8).  I got so fed up with Windows being unable to do the simplest shell thing.  Arriving at an overall shell command that worked cross-platform was painful and it has made me risk-averse when it comes to tinkering with it.  Of course it's possible to do so but I don't want to spend any more time dealing with vim-to-shell compatibility issues.

Anyway, output on stderr triggers the job's error handler ([here's vim's](https://github.com/airblade/vim-gitgutter/blob/5f525476f3ade40e60aa295a8a2a01c0935b0d61/autoload/gitgutter/async.vim#L35)), which [resets all the signs](https://github.com/airblade/vim-gitgutter/blob/5f525476f3ade40e60aa295a8a2a01c0935b0d61/autoload/gitgutter/diff.vim#L174).  Redirecting stderr should be trivial...but Windows.  `2>/dev/null` wouldn't work, for example.

I want to keep the sync version for backward compatibility, which means we need the `v:shell_error`-restoring mechanism anyway.

**Comment by nkouevda** [comment]
Oh, that is unfortunate; thank you for explaining. I'll update #871.
