### ISSUE TITLE
g:gitgutter_diff_base () is invalid

### ISSUE THREAD

**Issue by ta3pks** [airblade/vim-gitgutter#874]
> What is the latest commit SHA in your installed vim-gitgutter?
`6efb835`
> What vim/nvim version are you on?
`0.9.4`

Everything was fine after doing an update to gitgutter  started receiving this error message on startup

**Comment by dimonomid** [comment]
Yeah I just tested it too, and indeed, the last commit (6efb835aa2de69daaf164e1605decf4987609889) breaks it. It's supposed to fix another issue from 2h ago: https://github.com/airblade/vim-gitgutter/issues/873, but apparently it broke others.

**Comment by airblade** [comment]
Please could you apply this patch?

```diff
diff --git i/autoload/gitgutter/utility.vim w/autoload/gitgutter/utility.vim
index 9c196fc..ba50d3c 100644
--- i/autoload/gitgutter/utility.vim
+++ w/autoload/gitgutter/utility.vim
@@ -291,7 +291,7 @@ function! s:obtain_file_renames(bufnr, base)
   let [out, error_code] = gitgutter#utility#system(gitgutter#utility#cd_cmd(a:bufnr, cmd))
   if error_code
     " Assume the problem is the diff base.
-    call gitgutter#utility#warn('g:gitgutter_diff_base ('.a:base.') is invalid')
+    echom error_code ' :: ' out
     return {}
   endif
   for line in split(out, '\n')

```

And let me know what message it prints?

**Comment by airblade** [comment]
Never mind, I've seen the problem.  The `-c` flag applies to `git`, not the `diff` subcommand.

**Comment by ta3pks** [comment]
thanks for the swift action :)
