### ISSUE TITLE
Neovim Nightly Issue

### ISSUE THREAD

**Issue by 1995parham** [airblade/vim-gitgutter#875]
I am using Neovim Nightly and have the following error:

```
Error detected while processing /home/parham/.local/share/nvim/site/pack/packer/start/vim-gitgutter/plugin/gitgutter.vim[109]..function gitgutter#highlight#define_signs:
line    1:
E475: Invalid argument:
```

This happens to me after the following commit on the neovim.

https://github.com/neovim/neovim/pull/25724

**Comment by luukvbaal** [comment]
I guess defining an empty now incorrectly causes an error.
Will be fixed in Neovim.

**Comment by airblade** [comment]
Thanks for flagging this.  I've opened #876 here to use extmarks instead of legacy signs where available.
