### ISSUE TITLE
errors when file path includes colons

### ISSUE THREAD

**Issue by vais** [airblade/vim-gitgutter#877]
> What is the latest commit SHA in your installed vim-gitgutter?
4b49965897b8264cd6f90fa47ddb917f4296c469
> What vim/nvim version are you on?
9.0.1897

I believe this commit introduced a regression whereby paths containing `:` result in errors being displayed every time a buffer is loaded/activated https://github.com/airblade/vim-gitgutter/commit/952dbc34f78341ce4c4e68a11a1b472c270a369b

Specifically I think this line's the culprit: https://github.com/airblade/vim-gitgutter/commit/952dbc34f78341ce4c4e68a11a1b472c270a369b#diff-8ca6e89485ffd459c09d6c5d99568d0784d6792b50f317daea59cb1ad7accebbR246

**Comment by vais** [comment]
To repro, simply make a directory in your repo that has a colon somewhere in its name.

**Comment by airblade** [comment]
I'm sure you're right.  I'll fix this up in the next few days when I get a chance.

**Comment by vais** [comment]
> I'm sure you're right. I'll fix this up in the next few days when I get a chance.

You're awesome, thank you!
