### ISSUE TITLE
Performance issues after base_path fix

### ISSUE THREAD

**Issue by azuenko** [airblade/vim-gitgutter#878]
I'm experiencing performance issues after the latest git-gutter update https://github.com/airblade/vim-gitgutter/commit/84bc2d68c0b32440bd1b12f245607a563a9421e4

Notice how the cursor starts blinking annoyingly.

### Before

![Kapture 2024-01-04 at 16 51 15](https://github.com/airblade/vim-gitgutter/assets/7202664/81e6af21-f851-4c18-bee3-b0f4dac6eda9)

### After 

![Kapture 2024-01-04 at 16 53 29](https://github.com/airblade/vim-gitgutter/assets/7202664/4635d09f-089d-4a35-97c0-ba2f5cc7b493)

> What is the latest commit SHA in your installed vim-gitgutter?

84bc2d6

> What vim/nvim version are you on?

```
> brew info neovim
==> neovim: stable 0.9.4 (bottled), HEAD
> brew info kitty
==> kitty: 0.31.0
```

**Comment by airblade** [comment]
There's no performance problem for me which makes it difficult for me to determine when it is fixed.

Please could you [profile gitgutter](https://github.com/airblade/vim-gitgutter/wiki/How-to-profile-vim-gitgutter)?  This will show exactly where the slowdown is occurring.

I'm surprised, though, because 84bc2d6 simply replaced one built-in function – `split()` – with another – `strridx()` – and two array slices.

**Comment by azuenko** [comment]
Hello Andy,

Here are two profile logs, for the normal & slow versions. In both cases I opened nvim, then run 4x `O<ESC>u` on a file in git repo, and closed it. Hope that it helps!

[gitgutter_profile_normal.log](https://github.com/airblade/vim-gitgutter/files/13833806/gitgutter_profile_normal.log)
[gitgutter_profile_slow.log](https://github.com/airblade/vim-gitgutter/files/13833807/gitgutter_profile_slow.log)

**Comment by azuenko** [comment]
Some more updates that could help you to debug the issue. 

I put some debug statements
```
    call gitgutter#debug#log(base)
    call gitgutter#debug#log(bpath)
```

and here is what I get in the log:

### Old version (before the fix)
```
  0.956426 function <SNR>74_on_exit_nvim[2]..gitgutter#diff#handler[1]:
  0.956426 @@ -255,0 +256,2 @@ function! gitgutter#utility#base_path(bufnr)^@@@ -256,0 +259 @@ function! gitgutter#utility#base_path(bufnr)

  1.484144 CursorHold Autocommands for "*"..function gitgutter#process_buffer[23]..gitgutter#diff#run_diff[55]..gitgutter#utility#base_path[7]:
  1.484144 

  1.485144 CursorHold Autocommands for "*"..function gitgutter#process_buffer[23]..gitgutter#diff#run_diff[55]..gitgutter#utility#base_path[8]:
  1.485144 autoload/gitgutter/utility.vim
```

### New version (slow)

```
  0.959054 function <SNR>74_on_exit_nvim[2]..gitgutter#diff#handler[1]:
  0.959054 @@ -256,0 +257,3 @@ function! gitgutter#utility#base_path(bufnr)

  1.207955 CursorHold Autocommands for "*"..function gitgutter#process_buffer[23]..gitgutter#diff#run_diff[55]..gitgutter#utility#base_path[8]:
  1.207955 :autoload/gitgutter/utility.vim

  1.208686 CursorHold Autocommands for "*"..function gitgutter#process_buffer[23]..gitgutter#diff#run_diff[55]..gitgutter#utility#base_path[9]:
  1.208686 autoload/gitgutter/utility.vim
```

The notable difference is in `base` var, which is set to `:autoload/gitgutter/utility.vim` in the new (slow) version. I suspect the non-empty `base` triggers some additional code that causes slow down.

**Comment by airblade** [comment]
Thanks for digging into that.

You're right: I was using substring indexes incorrectly which meant that `base` wasn't empty when it should have been, which was triggering additional code including a `system()` call.

I think I've got it right now...!

**Comment by azuenko** [comment]
Thank you Andy for fixing the issue. And generally thanks for developing and supporting this small yet quite useful plugin! 

I can confirm the fix do its job, I've no more performance issues with the plugin.
