### ISSUE TITLE
Branch rename breaking installations?

### ISSUE THREAD

**Issue by jasonkarns** [airblade/vim-gitgutter#879]
> What is the latest commit SHA in your installed vim-gitgutter?

e2056e5

> What vim/nvim version are you on?

9.1

Was the master branch renamed to main a few months ago? I still use Vundle for managing plugins and vundle's update has been failing to update this plugin for a while. At first, I didn't notice it, then i noticed but ignored it for a while. Now looking in the cloned repo is starting to show the signs about why vundle is failing. The repo has no upstream for the master branch.

I recognize this is a trivial fix; but at the same time, wonder how many folks have an installation that is no longer getting updates because of the branch rename (if that is indeed the cause). In a normal repository that is being developed on, the branch names only need to be communicated amongst the developers on that project. But with vim plugins where git repositories are also the _distribution_ and installation mechanism, the impact is much broader.

I would propose that the old name be preserved _as an alias_. The better `main` would still remain the active name, and the default branch on github. But a simple github action can force push to master any time main is updated, thus keeping _installations_ in sync and unbroken.

**Comment by airblade** [comment]
Yes, I renamed the `master` branch to `main` a few months ago.

I appreciate the suggestion to keep a `master` branch going.  However git will error if you try to pull from a non-existent branch, so I feel this is an issue with the plugin manager not reporting that error to you.

**Comment by jasonkarns** [comment]
FWIW, this is the github workflow I use to keep master in sync with main (for some deprecation window) https://github.com/nodenv/.github/blob/main/.github/workflows/sync-default-branch.yml

It's a reusable workflow which can be called directly by:

```
name: Sync Default Branch
on:
  push: { branches: main }
  workflow_dispatch:

jobs:
  sync:
    uses: nodenv/.github/.github/workflows/sync-default-branch.yml@v3
```
