### ISSUE TITLE
Performance issues with big files in the repository

### ISSUE THREAD

**Issue by dominx99** [airblade/vim-gitgutter#881]
> What is the latest commit SHA in your installed vim-gitgutter?

67ef116

> What vim/nvim version are you on? 

Neovim v0.9.5

I am experiencing performance issues.
Every time I open a file I have to wait couple of seconds (10-15)

I found that this process causes this:
```
git -c core.safecrlf=false diff --diff-filter=R --name-status
```

which is called by this plugin and it lasts so long because I have one big file in the repo (database) and I use git-lfs.

**Comment by airblade** [comment]
I've never used git-lfs but isn't it supposed to make normal git operations not be slowed down by a big file?

I think the right answer will be a way to exclude lfs-managed (or binary) files from git-diff, but I'm not sure how to do that.

**Comment by dominx99** [comment]
Thank you for hint

```
git update-index assume-unchanged <filename>
```

worked for me

**Comment by airblade** [comment]
Thanks for posting your solution!
