### ISSUE TITLE
cursorline highlighting doesn't work with gitgutter

### ISSUE THREAD

**Issue by m-deg** [airblade/vim-gitgutter#882]
I have cursorline hightlight like below. Unfortunately, this highlighting breaks when i move cursor to lines that are changed.

```local AutoCmdEnterLeaveNormalMode = function(opt)
  local enterNormal = function()
    vim.opt.cursorline = true
    vim.cmd("highlight CursorLine guibg=#7d352f guifg=fg") --
  end
  local enterInsert = function()
    vim.opt.cursorline = false
  end
```

**Comment by airblade** [comment]
I'm not sure what you mean by "this highlighting breaks" – please could you give some more details?

As an aside, I would move `highlight CursorLine guibg=#7d352f guifg=fg` out of your function and into your general config, after you set your colorscheme.

**Comment by airblade** [comment]
Any updates?

**Comment by airblade** [comment]
Closing because it's gone quiet.
