### ISSUE TITLE
GG doesn't show file changes when in a worktree

### ISSUE THREAD

**Issue by az-z** [airblade/vim-gitgutter#888]
> What is the latest commit SHA in your installed vim-gitgutter?
gitgutter was installed with the plug earlier today (04/12/2024)

> What vim/nvim version are you on?
```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Feb 16 2024 00:00:00)
Included patches: 1-113
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.
```

Hello,
 the changes to the files in the branch are visible. The changes to the file in a worktree are not.
To reproduce:
1. git checkout 
2. git worktree add ../wt <put your branch here>
3. cd ../wt
4. vim
5. change a file -> no indications that it was updated is visible.
6. cd ../master
7. change a file -> i can see the change indicators.

Maybe similar to issue 447 .

**Comment by airblade** [comment]
I can't reproduce this.  At step 5 I get the signs straightaway.

I suggest you switch on logging (`let g:gitgutter_log=1`), reproduce the problem, then look at the log file to see which commands are not working.  Or you can post it here and I'll take a look.

**Comment by az-z** [comment]
Andy,
 Thank you for your reply.

It is difficult to show diffs on a file that was not added to git.
//me been sarcastic here

All markings are working as expected. Thank you so much!

A quick question,  is there a way to have a small pop-up window to see what
the chage was at current cursor location? As I'm merging a ton of code and
rewriting parts of the code base, it will be very handy to be able to
glance at the previous version..

**Comment by airblade** [comment]
Glad it's working :)

You can view any change either in the preview window or a floating window.  See the readme [here](https://github.com/airblade/vim-gitgutter#hunks) and [here](https://github.com/airblade/vim-gitgutter#to-use-floatingpopup-windows-for-hunk-previews) or `:help GitGutterPreviewHunk` inside vim.
