### ISSUE TITLE
feature request: GitGutterNextStagedHunk

### ISSUE THREAD

**Issue by jiangyinzuo** [airblade/vim-gitgutter#895]
Can we jump to the next **staged** hunk just like jumping to the next unstaged hunk?

**Comment by airblade** [comment]
Yes, if you pass '—staged' to git diff:

```
let g:gitgutter_diff_args = '--staged'
```

**Comment by jiangyinzuo** [comment]
> Yes, if you pass '—staged' to git diff:
> 
> ```
> let g:gitgutter_diff_args = '--staged'
> ```

Thanks. Actually, I want **both** unstaged hunk and staged hunk, instead of either unstaged or staged.

**Comment by airblade** [comment]
In that case you want:

```vim
let g:gitgutter_diff_base = 'HEAD^'
```
