### ISSUE TITLE
cann't work on PC

### ISSUE THREAD

**Issue by lookforit** [airblade/vim-gitgutter#92]
I installed it as instructions ,but there are no any response when i was editting .vimrc file(versioned).
I excute `:GitGutterEnable`, no effects either.

btw, `:echo has('signs')` returns 1

**Comment by etiennebatise** [comment]
Hi,

Sorry to re-open this issue. I've just tried to install this plugin on a Windows machine and I've got the exact same problem. By the way I run *gvim*.

I use pathogen, so I dumped the folder into `bundles/`, checked with `:Helptags` with no errors.

The command `:h gitgutter` is working and displaying the *Readme* file.

Yet, your first reply maybe the clue of what my problem is. As I've installed *Git* from the wizard, I can only use it threw  "*Git Bash*" which in fact runs *Cygwin*. So the command `:echo system('git --version')` is returning an error.

You do not deeply need this plugin for the moment so I won't go much further.
